# Set up

In [1]:
# load libraries
import pandas as pd
from census import Census
from us import states
import requests
import time
import numpy as np 

# load functions
from analysis_functions import (
    fetch_census_data,
    fetch_census_data_msa_acs5,
    fetch_acs5_counties_tx,
    create_pivot_tables,
    print_rankings,
)

From Jess: 
I'd like an idea of 3 things and I'm not sure how they should be represented (I'll leave that to you)
- Population growth over the last 10, 15, and 20 years
- Migration to and from the city over that timeframe
- Median age of the population over that time frame

In [2]:
# set census api key 
c = Census("8149a6071641f66c9a2eaa2a679734a3d2a148e1")
# want data from the past 5, 10, 15 and 20 years
years = list(range(2004, 2025))

years_acs5 = [2009, 2014, 2019, 2024]  # Non-overlapping 5-year periods

# define the variables we need from the census api
census_variables = (
    'NAME', 
    'B01003_001E',  # total population
    'B11001_002E',  # total families
    # 'B11003_004E',  # families with only children under 6
    # 'B11003_005E',  # families with children under 6 AND children 6-17
    'B11005_003E',  # family households with one or more people under 18
    'B01002_001E',  # median age
    'B09001_001E',  # population under 18
    'B07003_004E',  # lived in the same house 1 year ago
    'B07003_007E',  # moved within same county
    'B07003_010E',  # moved from a different county in the same state
    'B07003_013E',  # moved from a different state
    'B07003_016E',  # moved from abroad
)

## Get ACS1 data

In [3]:
# get msa data 
df_msa = fetch_census_data(
    census_obj=c,
    geography='msa',
    years=years,
    variables=census_variables,
    include_moe=True,
)

Error for year 2004: <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1></body></html>
Retrieved msa data for 2005: 500 records
Retrieved msa data for 2006: 507 records
Retrieved msa data for 2007: 510 records
Retrieved msa data for 2008: 512 records
Retrieved msa data for 2009: 517 records
Retrieved msa data for 2010: 525 records
Retrieved msa data for 2011: 529 records
Retrieved msa data for 2012: 530 records
Retrieved msa data for 2013: 515 records
Retrieved msa data for 2014: 515 records
Retrieved msa data for 2015: 516 records
Retrieved msa data for 2016: 518 records
Retrieved msa data for 2017: 518 records
Retrieved msa data for 2018: 519 records
Retrieved msa data for 2019: 518 records
Error for year 2020: <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1></body></html>
Retrieved msa data for 2021: 513 records
Retrieved msa data for 2022: 516 records
Retrieved msa data for 2023: 530 records
Retrieved msa data for 2024: 535 records

In [4]:
# get county data 
tx_counties = fetch_census_data(
    census_obj=c,
    geography='county',
    years=years,
    variables=census_variables,
    include_moe=True,
)

Error for year 2004: Geography is not available in 2004. Available years include (2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005)
Retrieved county data for 2005: 49 records
Retrieved county data for 2006: 50 records
Retrieved county data for 2007: 50 records
Retrieved county data for 2008: 50 records
Retrieved county data for 2009: 50 records
Retrieved county data for 2010: 52 records
Retrieved county data for 2011: 53 records
Retrieved county data for 2012: 53 records
Retrieved county data for 2013: 53 records
Retrieved county data for 2014: 53 records
Retrieved county data for 2015: 53 records
Retrieved county data for 2016: 53 records
Retrieved county data for 2017: 54 records
Retrieved county data for 2018: 54 records
Retrieved county data for 2019: 54 records
Error for year 2020: Geography is not available in 2020. Available years include (2024, 2023, 2022, 2021, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005)
Retrieved county data for 2021: 54 records
Retrieved county data for 2022: 55 records
Retrieved county data for 2023: 56 records
Retrieved county data for 2024: 58 records

In [5]:
df_msa.head(10)

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,family_households_with_child_moe,median_age_moe,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,msa_code,year
0,"Decatur, AL Metro Area",146379.0,40614.0,19783.0,38.7,34840.0,121425.0,15794.0,4548.0,2837.0,...,1719.0,0.8,267.0,4185.0,3430.0,2042.0,1423.0,143.0,19460,2005
1,"Decatur, IL Metro Area",106433.0,29734.0,14431.0,39.3,26353.0,87475.0,12612.0,2093.0,2159.0,...,1399.0,0.7,0.0,2799.0,2498.0,897.0,1199.0,247.0,19500,2005
2,"Deltona-Daytona Beach-Ormond Beach, FL Metro Area",475189.0,127674.0,55714.0,42.7,98163.0,389550.0,45685.0,12061.0,21096.0,...,3331.0,0.3,278.0,8572.0,6136.0,3346.0,4083.0,807.0,19660,2005
3,"Denver-Aurora, CO Metro Area",2327901.0,585045.0,310967.0,34.6,614480.0,1837272.0,214141.0,152498.0,66123.0,...,6891.0,0.2,1241.0,16847.0,12462.0,11601.0,7801.0,3212.0,19740,2005
4,"Des Moines, IA Metro Area",511565.0,140049.0,74182.0,36.0,126951.0,414264.0,55379.0,15509.0,17388.0,...,3208.0,0.3,1250.0,7625.0,6868.0,2699.0,4132.0,549.0,19780,2005
5,"Detroit-Warren-Livonia, MI Metro Area",4428941.0,1136763.0,593643.0,36.9,1156653.0,3779007.0,423897.0,104597.0,41373.0,...,9569.0,0.2,340.0,23014.0,17958.0,9599.0,4642.0,3215.0,19820,2005
6,"Dothan, AL Metro Area",134993.0,38194.0,18616.0,39.3,32693.0,113087.0,12421.0,3043.0,4447.0,...,1376.0,0.8,216.0,3110.0,2483.0,1043.0,1209.0,327.0,20020,2005
7,"Dover, DE Metro Area",140205.0,38719.0,21289.0,35.7,35980.0,117523.0,14838.0,2341.0,3766.0,...,1412.0,0.4,329.0,3436.0,3048.0,1176.0,1129.0,473.0,20100,2005
8,"DuBois, PA Micro Area",79001.0,21874.0,9636.0,41.4,16883.0,69391.0,4192.0,3327.0,1193.0,...,898.0,0.5,146.0,1890.0,1299.0,1555.0,574.0,84.0,20180,2005
9,"Dubuque, IA Metro Area",86626.0,24048.0,11760.0,39.2,NaN,75426.0,6895.0,984.0,1800.0,...,1212.0,0.6,NaN,2139.0,1963.0,396.0,939.0,119.0,20220,2005

In [6]:
tx_counties.head(10)

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,median_age_moe,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,state,county_code,year
0,"Angelina County, Texas",78839.0,21098.0,11364.0,34.7,22099.0,61109.0,11790.0,3747.0,1329.0,...,0.6,0.0,3730.0,3268.0,2253.0,811.0,151.0,48,005,2005
1,"Bastrop County, Texas",61724.0,14862.0,6777.0,37.9,NaN,54507.0,2852.0,1933.0,623.0,...,3.9,NaN,4896.0,1444.0,945.0,624.0,519.0,48,021,2005
2,"Bell County, Texas",246592.0,66060.0,38428.0,30.2,80298.0,174071.0,30530.0,7468.0,15354.0,...,0.3,569.0,6457.0,5680.0,2384.0,3484.0,4452.0,48,027,2005
3,"Bexar County, Texas",1482598.0,357432.0,204070.0,33.0,422116.0,1172655.0,195524.0,36315.0,38089.0,...,0.2,239.0,16432.0,14916.0,5590.0,7042.0,5176.0,48,029,2005
4,"Bowie County, Texas",83813.0,24008.0,12827.0,36.9,21682.0,67032.0,9319.0,2425.0,4339.0,...,0.8,34.0,2892.0,2590.0,1051.0,1534.0,190.0,48,037,2005
5,"Brazoria County, Texas",267376.0,71863.0,41549.0,33.4,76373.0,210248.0,32282.0,15294.0,4140.0,...,0.3,100.0,8033.0,7166.0,3538.0,1962.0,1047.0,48,039,2005
6,"Brazos County, Texas",143502.0,30397.0,16378.0,25.0,32505.0,105835.0,18150.0,11982.0,2812.0,...,0.3,0.0,4153.0,2902.0,2794.0,1363.0,1165.0,48,041,2005
7,"Cameron County, Texas",374081.0,89799.0,55828.0,28.5,128146.0,312733.0,39556.0,5340.0,6930.0,...,0.3,231.0,8703.0,8441.0,2024.0,2784.0,770.0,48,061,2005
8,"Collin County, Texas",655994.0,165649.0,96710.0,33.6,181559.0,525074.0,48553.0,43116.0,19709.0,...,0.3,0.0,9200.0,7360.0,6801.0,4559.0,2578.0,48,085,2005
9,"Comal County, Texas",94794.0,25606.0,11687.0,36.7,NaN,79775.0,5169.0,7275.0,874.0,...,1.1,NaN,3482.0,2316.0,2526.0,624.0,786.0,48,091,2005

## Get ACS5 data
Data only available from 2009-2023 at the county level, and 2009-2024 at the MSA level.

In [7]:
# get msa data using ACS 5-year estimates
df_msa_acs5 = fetch_census_data_msa_acs5(
    census_obj=c,
    geography='msa',
    years=years_acs5,  # Use non-overlapping years only
    variables=census_variables,
    include_moe=True,
)

Retrieved msa data for 2009 (ACS5): 953 records
Retrieved msa data for 2014 (ACS5): 929 records
Retrieved msa data for 2019 (ACS5): 938 records
Retrieved msa data for 2024 (ACS5): 935 records

In [8]:
# get county data using ACS 5-year 
# for the counties data, the census package hasn't updated for the new five-year estimates yet.
# instead, we'll pull straight from the api using the requests package

frames = []

for y in years_acs5:
    df_year = fetch_acs5_counties_tx(y, include_moe=True)
    frames.append(df_year)
    
    time.sleep(1)  # be polite to Census API

tx_counties_acs5 = pd.concat(frames, ignore_index=True)

cols = [
    'B01003_001E',
    'B11001_002E',
    'B11005_003E',
    'B01002_001E',
    'B09001_001E',
    'B07003_004E',
    'B07003_007E',
    'B07003_010E',
    'B07003_013E',
    'B07003_016E',
    'B01003_001M',
    'B11001_002M',
    'B11005_003M',
    'B01002_001M',
    'B09001_001M',
    'B07003_004M',
    'B07003_007M',
    'B07003_010M',
    'B07003_013M',
    'B07003_016M'
]

tx_counties_acs5[cols] = tx_counties_acs5[cols].apply(
    pd.to_numeric, errors="coerce"
)

In [9]:
# rename colums for clarity
county_mapping = {
        'NAME': 'name',
        'B01003_001E': 'population',
        'B11001_002E': 'total_families',
        'B11005_003E': 'family_households_with_child',
        'B01002_001E': 'median_age',
        'B09001_001E': 'population_under_18',
        'B07003_004E': 'lived_in_same_house',
        'B07003_007E': 'moved_within_county',
        'B07003_010E': 'moved_from_diff_county_same_state',
        'B07003_013E': 'moved_from_diff_state',
        'B07003_016E': 'moved_from_abroad',
        'B01003_001M': 'population_moe',
        'B11001_002M': 'total_families_moe',
        'B11005_003M': 'family_households_with_child_moe',
        'B01002_001M': 'median_age_moe',
        'B09001_001M': 'population_under_18_moe',
        'B07003_004M': 'lived_in_same_house_moe',
        'B07003_007M': 'moved_within_county_moe',
        'B07003_010M': 'moved_from_diff_county_same_state_moe',
        'B07003_013M': 'moved_from_diff_state_moe',
        'B07003_016M': 'moved_from_abroad_moe',
        'county': 'county_code'
    }

tx_counties_acs5 = tx_counties_acs5.rename(columns=county_mapping)

In [10]:
# check out the data
tx_counties_acs5.head(10)

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,median_age_moe,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,state,county_code,year
0,"Burnet County, Texas",43402,11242,4708,44.7,9835,37013,2884,2496,610,...,0.2,139,845,697,616,282,30,48,053,2009
1,"Caldwell County, Texas",36895,8280,4437,35.8,9917,29714,2333,3995,469,...,0.5,64,1243,499,1080,247,37,48,055,2009
2,"Calhoun County, Texas",20384,5479,2896,38.1,5476,16744,1989,946,345,...,0.7,38,585,519,258,237,136,48,057,2009
3,"Callahan County, Texas",13300,3686,1645,41.0,3185,11494,578,1000,90,...,0.8,100,455,262,354,60,127,48,059,2009
4,"Cameron County, Texas",383171,93322,58790,29.1,133416,329375,32918,4970,4355,...,0.1,97,3032,2732,757,693,616,48,061,2009
5,"Camp County, Texas",12489,3301,1635,36.5,3482,10887,631,570,129,...,1.5,0,500,348,252,110,72,48,063,2009
6,"Carson County, Texas",6246,1863,724,41.7,1589,5221,360,494,76,...,1.5,21,223,112,200,64,127,48,065,2009
7,"Cass County, Texas",29315,8772,4023,43.2,6715,25308,2235,941,466,...,0.5,5,577,482,246,149,26,48,067,2009
8,"Castro County, Texas",7233,2228,1259,35.7,2216,6095,576,322,46,...,0.6,0,264,205,151,51,46,48,069,2009
9,"Chambers County, Texas",29198,9158,5235,37.1,8113,24862,1463,2088,312,...,0.5,31,636,384,622,171,6,48,071,2009

# Texas MSA analysis

## ACS 1-year

In [11]:
# filter for metro areas in texas only 
msa_tx = df_msa[df_msa['name'].str.contains('TX', case=False, na=False)].copy()

# some msa_codes have multiple names
# fix that by aggregating instances where there are multiple rows for the same metro area for the same year
# pick just the most common name
msa_tx['name'] = msa_tx.groupby('msa_code')['name'].transform(lambda x: x.mode()[0])

# create column for all people who moved to the area from a different location
msa_tx['total_in_migration'] = (
    msa_tx['moved_from_diff_county_same_state'] + 
    msa_tx['moved_from_diff_state'] + 
    msa_tx['moved_from_abroad']
)

# aggregate to ensure one row per msa_code per year
msa_tx_agg = msa_tx.groupby(['msa_code', 'name', 'year']).agg({
    'population': 'sum',
    'total_families': 'sum',
    'median_age': 'median',
    'population_under_18': 'sum',
    'family_households_with_child': 'sum'
}).reset_index()

print(msa_tx['msa_code'].nunique())

33

In [12]:
# use function to create multiple dfs at once, pivoting from original so each column is a year
msa_pivots = create_pivot_tables(
    df=msa_tx_agg,
    index_cols=['msa_code','name'],
    variable_names=['population', 
                    'median_age', 
                    'total_families', 
                    'population_under_18', 
                    'family_households_with_child'])

# extract individual pivot tables
msa_tx_pop = msa_pivots['population']
msa_tx_age = msa_pivots['median_age']
msa_tx_families = msa_pivots['total_families']
msa_tx_under18 = msa_pivots['population_under_18']
msa_tx_family_households_with_child = msa_pivots['family_households_with_child']

# create df specifically for migration
# this one is a little different because there are multiple values 
msa_tx_migration = msa_tx.pivot(
    index=['msa_code','name'],
    columns='year',
    values=['lived_in_same_house', 
            'moved_within_county', 
            'moved_from_diff_county_same_state',
            'moved_from_diff_state',
            'moved_from_abroad',
            'total_in_migration']
).reset_index()

# flatten cols so theyre not stacked
msa_tx_migration.columns = [
    f"{var}_{year}" for var, year in msa_tx_migration.columns
]

# reset index
msa_tx_migration = msa_tx_migration.reset_index();

### Population change

In [13]:
# create columns for population change in the past 5, 10, 15 and 19 years (2005–2024)
msa_tx_pop['pct_change_19_24'] = ((msa_tx_pop[2024] - msa_tx_pop[2019]) / msa_tx_pop[2019]) * 100 # 5 years
msa_tx_pop['pct_change_14_24'] = ((msa_tx_pop[2024] - msa_tx_pop[2014]) / msa_tx_pop[2014]) * 100 # 10 years
msa_tx_pop['pct_change_09_24'] = ((msa_tx_pop[2024] - msa_tx_pop[2009]) / msa_tx_pop[2009]) * 100 # 15 years
msa_tx_pop['pct_change_05_24'] = ((msa_tx_pop[2024] - msa_tx_pop[2005]) / msa_tx_pop[2005]) * 100 # 19 years

In [14]:
# print ranked results
print_rankings(
    df=msa_tx_pop,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_05_24
0                    Austin-Round Rock, TX Metro Area         81.363929
1                College Station-Bryan, TX Metro Area         58.756102
2                              Midland, TX Metro Area         57.092382
3                       Killeen-Temple, TX Metro Area         54.193287
4     Houston-The Woodlands-Sugar Land, TX Metro Area         50.115723
5            San Antonio-New Braunfels, TX Metro Area         49.836173
6                             Longview, TX Metro Area         48.176936
7                              Lubbock, TX Metro Area         46.643631
8          Dallas-Fort Worth-Arlington, TX Metro Area         45.686439
9                                 Waco, TX Metro Area         42.516148
10                              Odessa, TX Metro Area         37.858284
11            McAllen-Edinburg-Mission, TX Metro Area         36.140614
12                               Tyler, TX Metro Area         34.306203
13                     Sherman-Denison, TX Metro Area         32.162706
14                             Abilene, TX Metro Area         24.272846
15                             El Paso, TX Metro Area         23.932861
16                              Laredo, TX Metro Area         23.182889
17                            Amarillo, TX Metro Area         22.182275
18                          San Angelo, TX Metro Area         20.332230
19                        Texarkana, TX-AR Metro Area         16.144766
20               Brownsville-Harlingen, TX Metro Area         15.449328
21                              Lufkin, TX Micro Area         11.739114
22                              Athens, TX Micro Area         11.077669
23                      Corpus Christi, TX Metro Area         10.714180
24                       Wichita Falls, TX Metro Area          9.311248
25                Beaumont-Port Arthur, TX Metro Area          8.689537
26                            Victoria, TX Metro Area        -16.025351
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_09_24
0                    Austin-Round Rock, TX Metro Area         49.590898
1                             Longview, TX Metro Area         42.835736
2                              Midland, TX Metro Area         42.137761
3                College Station-Bryan, TX Metro Area         35.191783
4                       Killeen-Temple, TX Metro Area         34.347403
5            San Antonio-New Braunfels, TX Metro Area         33.279469
6     Houston-The Woodlands-Sugar Land, TX Metro Area         32.925280
7                              Lubbock, TX Metro Area         32.304502
8                                 Waco, TX Metro Area         31.038058
9          Dallas-Fort Worth-Arlington, TX Metro Area         29.420458
10                              Odessa, TX Metro Area         26.293036
11                     Sherman-Denison, TX Metro Area         25.411980
12            McAllen-Edinburg-Mission, TX Metro Area         23.432170
13                               Tyler, TX Metro Area         21.706691
14                             El Paso, TX Metro Area         16.843428
15                             Abilene, TX Metro Area         13.541862
16                            Amarillo, TX Metro Area         13.274891
17                              Laredo, TX Metro Area         12.999196
18                              Athens, TX Micro Area         10.828550
19                          San Angelo, TX Metro Area          9.962050
20               Brownsville-Harlingen, TX Metro Area          8.957012
21                      Corpus Christi, TX Metro Area          7.872721
22                        Texarkana, TX-AR Metro Area          6.345373
23                Beaumont-Port Arthur, TX Metro Area          5.351976
24                              Lufkin, TX Micro Area          5.281147
25                       Wichita Falls, TX Metro Area          0.586597
26                            Victoria, TX Metro Area        -14.389572
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                             Longview, TX Metro Area         35.869340
1                    Austin-Round Rock, TX Metro Area         31.252936
2                      Sherman-Denison, TX Metro Area         21.854712
3                              Lubbock, TX Metro Area         20.398215
4                College Station-Bryan, TX Metro Area         20.344818
5     Houston-The Woodlands-Sugar Land, TX Metro Area         20.122739
6          Dallas-Fort Worth-Arlington, TX Metro Area         19.988904
7                       Killeen-Temple, TX Metro Area         19.811918
8            San Antonio-New Braunfels, TX Metro Area         18.753925
9                                 Waco, TX Metro Area         16.741615
10                             Midland, TX Metro Area         15.049245
11                               Tyler, TX Metro Area         13.822301
12                              Odessa, TX Metro Area         10.472762
13                              Athens, TX Micro Area         10.312776
14            McAllen-Edinburg-Mission, TX Metro Area         10.076973
15                             Abilene, TX Metro Area          9.028760
16                            Amarillo, TX Metro Area          6.333476
17                             El Paso, TX Metro Area          4.949046
18               Brownsville-Harlingen, TX Metro Area          2.731260
19                          San Angelo, TX Metro Area          2.630689
20                              Laredo, TX Metro Area          2.306195
21                      Corpus Christi, TX Metro Area          1.211554
22                         Nacogdoches, TX Micro Area          0.653895
23                              Lufkin, TX Micro Area          0.392023
24                          Huntsville, TX Micro Area         -0.672686
25                        Texarkana, TX-AR Metro Area         -1.035603
26                            Victoria, TX Metro Area         -1.095081
27                       Wichita Falls, TX Metro Area         -1.100069
28                Beaumont-Port Arthur, TX Metro Area         -1.293451
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                           Huntsville, TX Micro Area         14.733250
1                    Austin-Round Rock, TX Metro Area         14.528152
2                              Lubbock, TX Metro Area         14.146132
3                                 Waco, TX Metro Area         12.901487
4                       Killeen-Temple, TX Metro Area         10.519466
5                      Sherman-Denison, TX Metro Area         10.513024
6     Houston-The Woodlands-Sugar Land, TX Metro Area         10.331553
7          Dallas-Fort Worth-Arlington, TX Metro Area         10.179350
8            San Antonio-New Braunfels, TX Metro Area          8.312400
9                College Station-Bryan, TX Metro Area          7.709781
10                               Tyler, TX Metro Area          7.020378
11                             Abilene, TX Metro Area          5.922175
12                              Athens, TX Micro Area          5.716910
13            McAllen-Edinburg-Mission, TX Metro Area          5.308234
14                      Corpus Christi, TX Metro Area          4.621886
15                             El Paso, TX Metro Area          4.043379
16                            Amarillo, TX Metro Area          3.296752
17                            Longview, TX Metro Area          3.081383
18                             Midland, TX Metro Area          2.893611
19                              Odessa, TX Metro Area          2.285484
20               Brownsville-Harlingen, TX Metro Area          2.058545
21                              Lufkin, TX Micro Area          1.590267
22                Beaumont-Port Arthur, TX Metro Area          1.571722
23                         Nacogdoches, TX Micro Area          0.803632
24                          San Angelo, TX Metro Area          0.026364
25                            Victoria, TX Metro Area         -0.649914
26                       Wichita Falls, TX Metro Area         -0.915678
27                              Laredo, TX Metro Area         -1.384049
28                        Texarkana, TX-AR Metro Area         -2.074906
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN

{'pct_change_05_24': year                                             name  pct_change_05_24
 0                    Austin-Round Rock, TX Metro Area         81.363929
 1                College Station-Bryan, TX Metro Area         58.756102
 2                              Midland, TX Metro Area         57.092382
 3                       Killeen-Temple, TX Metro Area         54.193287
 4     Houston-The Woodlands-Sugar Land, TX Metro Area         50.115723
 5            San Antonio-New Braunfels, TX Metro Area         49.836173
 6                             Longview, TX Metro Area         48.176936
 7                              Lubbock, TX Metro Area         46.643631
 8          Dallas-Fort Worth-Arlington, TX Metro Area         45.686439
 9                                 Waco, TX Metro Area         42.516148
 10                              Odessa, TX Metro Area         37.858284
 11            McAllen-Edinburg-Mission, TX Metro Area         36.140614
 12                               Tyler, TX Metro Area         34.306203
 13                     Sherman-Denison, TX Metro Area         32.162706
 14                             Abilene, TX Metro Area         24.272846
 15                             El Paso, TX Metro Area         23.932861
 16                              Laredo, TX Metro Area         23.182889
 17                            Amarillo, TX Metro Area         22.182275
 18                          San Angelo, TX Metro Area         20.332230
 19                        Texarkana, TX-AR Metro Area         16.144766
 20               Brownsville-Harlingen, TX Metro Area         15.449328
 21                              Lufkin, TX Micro Area         11.739114
 22                              Athens, TX Micro Area         11.077669
 23                      Corpus Christi, TX Metro Area         10.714180
 24                       Wichita Falls, TX Metro Area          9.311248
 25                Beaumont-Port Arthur, TX Metro Area          8.689537
 26                            Victoria, TX Metro Area        -16.025351
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_09_24': year                                             name  pct_change_09_24
 0                    Austin-Round Rock, TX Metro Area         49.590898
 1                             Longview, TX Metro Area         42.835736
 2                              Midland, TX Metro Area         42.137761
 3                College Station-Bryan, TX Metro Area         35.191783
 4                       Killeen-Temple, TX Metro Area         34.347403
 5            San Antonio-New Braunfels, TX Metro Area         33.279469
 6     Houston-The Woodlands-Sugar Land, TX Metro Area         32.925280
 7                              Lubbock, TX Metro Area         32.304502
 8                                 Waco, TX Metro Area         31.038058
 9          Dallas-Fort Worth-Arlington, TX Metro Area         29.420458
 10                              Odessa, TX Metro Area         26.293036
 11                     Sherman-Denison, TX Metro Area         25.411980
 12            McAllen-Edinburg-Mission, TX Metro Area         23.432170
 13                               Tyler, TX Metro Area         21.706691
 14                             El Paso, TX Metro Area         16.843428
 15                             Abilene, TX Metro Area         13.541862
 16                            Amarillo, TX Metro Area         13.274891
 17                              Laredo, TX Metro Area         12.999196
 18                              Athens, TX Micro Area         10.828550
 19                          San Angelo, TX Metro Area          9.962050
 20               Brownsville-Harlingen, TX Metro Area          8.957012
 21                      Corpus Christi, TX Metro Area          7.872721
 22                        Texarkana, TX-AR Metro Area          6.345373
 23                Beaumont-Port Arthur, TX Metro Area          5.351976
 24                              Lufkin, TX Micro Area          5.281147
 25                       Wichita Falls, TX Metro Area          0.586597
 26                            Victoria, TX Metro Area        -14.389572
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_14_24': year                                             name  pct_change_14_24
 0                             Longview, TX Metro Area         35.869340
 1                    Austin-Round Rock, TX Metro Area         31.252936
 2                      Sherman-Denison, TX Metro Area         21.854712
 3                              Lubbock, TX Metro Area         20.398215
 4                College Station-Bryan, TX Metro Area         20.344818
 5     Houston-The Woodlands-Sugar Land, TX Metro Area         20.122739
 6          Dallas-Fort Worth-Arlington, TX Metro Area         19.988904
 7                       Killeen-Temple, TX Metro Area         19.811918
 8            San Antonio-New Braunfels, TX Metro Area         18.753925
 9                                 Waco, TX Metro Area         16.741615
 10                             Midland, TX Metro Area         15.049245
 11                               Tyler, TX Metro Area         13.822301
 12                              Odessa, TX Metro Area         10.472762
 13                              Athens, TX Micro Area         10.312776
 14            McAllen-Edinburg-Mission, TX Metro Area         10.076973
 15                             Abilene, TX Metro Area          9.028760
 16                            Amarillo, TX Metro Area          6.333476
 17                             El Paso, TX Metro Area          4.949046
 18               Brownsville-Harlingen, TX Metro Area          2.731260
 19                          San Angelo, TX Metro Area          2.630689
 20                              Laredo, TX Metro Area          2.306195
 21                      Corpus Christi, TX Metro Area          1.211554
 22                         Nacogdoches, TX Micro Area          0.653895
 23                              Lufkin, TX Micro Area          0.392023
 24                          Huntsville, TX Micro Area         -0.672686
 25                        Texarkana, TX-AR Metro Area         -1.035603
 26                            Victoria, TX Metro Area         -1.095081
 27                       Wichita Falls, TX Metro Area         -1.100069
 28                Beaumont-Port Arthur, TX Metro Area         -1.293451
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_19_24': year                                             name  pct_change_19_24
 0                           Huntsville, TX Micro Area         14.733250
 1                    Austin-Round Rock, TX Metro Area         14.528152
 2                              Lubbock, TX Metro Area         14.146132
 3                                 Waco, TX Metro Area         12.901487
 4                       Killeen-Temple, TX Metro Area         10.519466
 5                      Sherman-Denison, TX Metro Area         10.513024
 6     Houston-The Woodlands-Sugar Land, TX Metro Area         10.331553
 7          Dallas-Fort Worth-Arlington, TX Metro Area         10.179350
 8            San Antonio-New Braunfels, TX Metro Area          8.312400
 9                College Station-Bryan, TX Metro Area          7.709781
 10                               Tyler, TX Metro Area          7.020378
 11                             Abilene, TX Metro Area          5.922175
 12                              Athens, TX Micro Area          5.716910
 13            McAllen-Edinburg-Mission, TX Metro Area          5.308234
 14                      Corpus Christi, TX Metro Area          4.621886
 15                             El Paso, TX Metro Area          4.043379
 16                            Amarillo, TX Metro Area          3.296752
 17                            Longview, TX Metro Area          3.081383
 18                             Midland, TX Metro Area          2.893611
 19                              Odessa, TX Metro Area          2.285484
 20               Brownsville-Harlingen, TX Metro Area          2.058545
 21                              Lufkin, TX Micro Area          1.590267
 22                Beaumont-Port Arthur, TX Metro Area          1.571722
 23                         Nacogdoches, TX Micro Area          0.803632
 24                          San Angelo, TX Metro Area          0.026364
 25                            Victoria, TX Metro Area         -0.649914
 26                       Wichita Falls, TX Metro Area         -0.915678
 27                              Laredo, TX Metro Area         -1.384049
 28                        Texarkana, TX-AR Metro Area         -2.074906
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN}

### Total number of families

In [15]:
# create columns for percentage change in the number of families
msa_tx_families['pct_change_19_24'] = ((msa_tx_families[2024] - msa_tx_families[2019]) / msa_tx_families[2019]) * 100 # 5 years
msa_tx_families['pct_change_14_24'] = ((msa_tx_families[2024] - msa_tx_families[2014]) / msa_tx_families[2014]) * 100 # 10 years
msa_tx_families['pct_change_09_24'] = ((msa_tx_families[2024] - msa_tx_families[2009]) / msa_tx_families[2009]) * 100 # 15 years
msa_tx_families['pct_change_05_24'] = ((msa_tx_families[2024] - msa_tx_families[2005]) / msa_tx_families[2005]) * 100 # 19 years

In [16]:
# print ranked results
print_rankings(
    df=msa_tx_families,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_05_24
0                    Austin-Round Rock, TX Metro Area         90.551594
1                              Midland, TX Metro Area         64.682253
2                College Station-Bryan, TX Metro Area         56.355436
3                             Longview, TX Metro Area         52.803703
4            San Antonio-New Braunfels, TX Metro Area         48.742176
5     Houston-The Woodlands-Sugar Land, TX Metro Area         48.538529
6                                 Waco, TX Metro Area         47.164852
7                       Killeen-Temple, TX Metro Area         45.392262
8                               Odessa, TX Metro Area         45.382840
9          Dallas-Fort Worth-Arlington, TX Metro Area         43.841879
10                               Tyler, TX Metro Area         32.100432
11            McAllen-Edinburg-Mission, TX Metro Area         31.659117
12                     Sherman-Denison, TX Metro Area         31.413051
13                              Laredo, TX Metro Area         31.302993
14                             Lubbock, TX Metro Area         31.298628
15                             El Paso, TX Metro Area         24.379297
16               Brownsville-Harlingen, TX Metro Area         24.123877
17                          San Angelo, TX Metro Area         15.254361
18                              Lufkin, TX Micro Area         13.825955
19                      Corpus Christi, TX Metro Area         13.047469
20                            Amarillo, TX Metro Area         11.129005
21                              Athens, TX Micro Area          4.742914
22                        Texarkana, TX-AR Metro Area          2.499712
23                Beaumont-Port Arthur, TX Metro Area          2.048873
24                       Wichita Falls, TX Metro Area         -1.051608
25                             Abilene, TX Metro Area         -2.039195
26                            Victoria, TX Metro Area        -23.345048
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_09_24
0                    Austin-Round Rock, TX Metro Area         64.643963
1                             Longview, TX Metro Area         48.151307
2                              Midland, TX Metro Area         47.778091
3                College Station-Bryan, TX Metro Area         44.251271
4                                 Waco, TX Metro Area         43.106178
5                       Killeen-Temple, TX Metro Area         42.693031
6            San Antonio-New Braunfels, TX Metro Area         42.329626
7                               Odessa, TX Metro Area         37.612674
8     Houston-The Woodlands-Sugar Land, TX Metro Area         34.140260
9                                Tyler, TX Metro Area         33.865774
10         Dallas-Fort Worth-Arlington, TX Metro Area         33.141943
11                             Lubbock, TX Metro Area         30.665960
12            McAllen-Edinburg-Mission, TX Metro Area         22.650166
13                     Sherman-Denison, TX Metro Area         21.904043
14                             El Paso, TX Metro Area         20.177113
15               Brownsville-Harlingen, TX Metro Area         18.711725
16                              Laredo, TX Metro Area         18.480782
17                              Lufkin, TX Micro Area         17.026461
18                      Corpus Christi, TX Metro Area         16.380620
19                            Amarillo, TX Metro Area         10.719071
20                              Athens, TX Micro Area          8.550731
21                          San Angelo, TX Metro Area          8.302184
22                             Abilene, TX Metro Area          5.671991
23                Beaumont-Port Arthur, TX Metro Area         -1.380223
24                       Wichita Falls, TX Metro Area         -1.669453
25                        Texarkana, TX-AR Metro Area         -1.972490
26                            Victoria, TX Metro Area        -20.065965
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                             Longview, TX Metro Area         46.833535
1                    Austin-Round Rock, TX Metro Area         46.436562
2                              Midland, TX Metro Area         34.402213
3                College Station-Bryan, TX Metro Area         30.766408
4                               Odessa, TX Metro Area         26.884007
5            San Antonio-New Braunfels, TX Metro Area         25.736957
6     Houston-The Woodlands-Sugar Land, TX Metro Area         23.689022
7                      Sherman-Denison, TX Metro Area         22.912864
8                       Killeen-Temple, TX Metro Area         22.318070
9                                 Waco, TX Metro Area         21.462104
10                          San Angelo, TX Metro Area         21.031655
11         Dallas-Fort Worth-Arlington, TX Metro Area         20.006239
12                               Tyler, TX Metro Area         19.478202
13                             Lubbock, TX Metro Area         17.317425
14               Brownsville-Harlingen, TX Metro Area         15.919089
15            McAllen-Edinburg-Mission, TX Metro Area         15.303163
16                             El Paso, TX Metro Area         13.958794
17                              Laredo, TX Metro Area         12.207100
18                       Wichita Falls, TX Metro Area         11.131780
19                              Lufkin, TX Micro Area         11.052023
20                         Nacogdoches, TX Micro Area         10.027767
21                              Athens, TX Micro Area          9.377099
22                      Corpus Christi, TX Metro Area          8.126623
23                          Huntsville, TX Micro Area          2.793528
24                            Amarillo, TX Metro Area          2.694202
25                Beaumont-Port Arthur, TX Metro Area          0.312417
26                             Abilene, TX Metro Area         -1.805150
27                        Texarkana, TX-AR Metro Area         -2.399408
28                            Victoria, TX Metro Area         -5.338120
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                              Midland, TX Metro Area         29.200315
1                      Sherman-Denison, TX Metro Area         26.996951
2                    Austin-Round Rock, TX Metro Area         25.048898
3                               Odessa, TX Metro Area         22.841429
4            San Antonio-New Braunfels, TX Metro Area         20.087796
5                           Huntsville, TX Micro Area         19.482398
6                                Tyler, TX Metro Area         18.175231
7                       Killeen-Temple, TX Metro Area         17.305476
8                              Lubbock, TX Metro Area         17.259995
9                               Athens, TX Micro Area         16.949964
10                                Waco, TX Metro Area         14.789260
11                      Corpus Christi, TX Metro Area         14.090236
12                             El Paso, TX Metro Area         13.540137
13                            Longview, TX Metro Area         13.480194
14                         Nacogdoches, TX Micro Area         12.556488
15         Dallas-Fort Worth-Arlington, TX Metro Area         12.194206
16               College Station-Bryan, TX Metro Area         12.137425
17    Houston-The Woodlands-Sugar Land, TX Metro Area         11.640274
18               Brownsville-Harlingen, TX Metro Area         10.502835
19            McAllen-Edinburg-Mission, TX Metro Area         10.221556
20                          San Angelo, TX Metro Area          9.095306
21                            Victoria, TX Metro Area          7.509970
22                       Wichita Falls, TX Metro Area          6.868647
23                Beaumont-Port Arthur, TX Metro Area          6.183509
24                            Amarillo, TX Metro Area          4.335017
25                              Laredo, TX Metro Area          2.840207
26                             Abilene, TX Metro Area          0.687932
27                              Lufkin, TX Micro Area         -3.573580
28                        Texarkana, TX-AR Metro Area         -6.041029
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN

{'pct_change_05_24': year                                             name  pct_change_05_24
 0                    Austin-Round Rock, TX Metro Area         90.551594
 1                              Midland, TX Metro Area         64.682253
 2                College Station-Bryan, TX Metro Area         56.355436
 3                             Longview, TX Metro Area         52.803703
 4            San Antonio-New Braunfels, TX Metro Area         48.742176
 5     Houston-The Woodlands-Sugar Land, TX Metro Area         48.538529
 6                                 Waco, TX Metro Area         47.164852
 7                       Killeen-Temple, TX Metro Area         45.392262
 8                               Odessa, TX Metro Area         45.382840
 9          Dallas-Fort Worth-Arlington, TX Metro Area         43.841879
 10                               Tyler, TX Metro Area         32.100432
 11            McAllen-Edinburg-Mission, TX Metro Area         31.659117
 12                     Sherman-Denison, TX Metro Area         31.413051
 13                              Laredo, TX Metro Area         31.302993
 14                             Lubbock, TX Metro Area         31.298628
 15                             El Paso, TX Metro Area         24.379297
 16               Brownsville-Harlingen, TX Metro Area         24.123877
 17                          San Angelo, TX Metro Area         15.254361
 18                              Lufkin, TX Micro Area         13.825955
 19                      Corpus Christi, TX Metro Area         13.047469
 20                            Amarillo, TX Metro Area         11.129005
 21                              Athens, TX Micro Area          4.742914
 22                        Texarkana, TX-AR Metro Area          2.499712
 23                Beaumont-Port Arthur, TX Metro Area          2.048873
 24                       Wichita Falls, TX Metro Area         -1.051608
 25                             Abilene, TX Metro Area         -2.039195
 26                            Victoria, TX Metro Area        -23.345048
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_09_24': year                                             name  pct_change_09_24
 0                    Austin-Round Rock, TX Metro Area         64.643963
 1                             Longview, TX Metro Area         48.151307
 2                              Midland, TX Metro Area         47.778091
 3                College Station-Bryan, TX Metro Area         44.251271
 4                                 Waco, TX Metro Area         43.106178
 5                       Killeen-Temple, TX Metro Area         42.693031
 6            San Antonio-New Braunfels, TX Metro Area         42.329626
 7                               Odessa, TX Metro Area         37.612674
 8     Houston-The Woodlands-Sugar Land, TX Metro Area         34.140260
 9                                Tyler, TX Metro Area         33.865774
 10         Dallas-Fort Worth-Arlington, TX Metro Area         33.141943
 11                             Lubbock, TX Metro Area         30.665960
 12            McAllen-Edinburg-Mission, TX Metro Area         22.650166
 13                     Sherman-Denison, TX Metro Area         21.904043
 14                             El Paso, TX Metro Area         20.177113
 15               Brownsville-Harlingen, TX Metro Area         18.711725
 16                              Laredo, TX Metro Area         18.480782
 17                              Lufkin, TX Micro Area         17.026461
 18                      Corpus Christi, TX Metro Area         16.380620
 19                            Amarillo, TX Metro Area         10.719071
 20                              Athens, TX Micro Area          8.550731
 21                          San Angelo, TX Metro Area          8.302184
 22                             Abilene, TX Metro Area          5.671991
 23                Beaumont-Port Arthur, TX Metro Area         -1.380223
 24                       Wichita Falls, TX Metro Area         -1.669453
 25                        Texarkana, TX-AR Metro Area         -1.972490
 26                            Victoria, TX Metro Area        -20.065965
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_14_24': year                                             name  pct_change_14_24
 0                             Longview, TX Metro Area         46.833535
 1                    Austin-Round Rock, TX Metro Area         46.436562
 2                              Midland, TX Metro Area         34.402213
 3                College Station-Bryan, TX Metro Area         30.766408
 4                               Odessa, TX Metro Area         26.884007
 5            San Antonio-New Braunfels, TX Metro Area         25.736957
 6     Houston-The Woodlands-Sugar Land, TX Metro Area         23.689022
 7                      Sherman-Denison, TX Metro Area         22.912864
 8                       Killeen-Temple, TX Metro Area         22.318070
 9                                 Waco, TX Metro Area         21.462104
 10                          San Angelo, TX Metro Area         21.031655
 11         Dallas-Fort Worth-Arlington, TX Metro Area         20.006239
 12                               Tyler, TX Metro Area         19.478202
 13                             Lubbock, TX Metro Area         17.317425
 14               Brownsville-Harlingen, TX Metro Area         15.919089
 15            McAllen-Edinburg-Mission, TX Metro Area         15.303163
 16                             El Paso, TX Metro Area         13.958794
 17                              Laredo, TX Metro Area         12.207100
 18                       Wichita Falls, TX Metro Area         11.131780
 19                              Lufkin, TX Micro Area         11.052023
 20                         Nacogdoches, TX Micro Area         10.027767
 21                              Athens, TX Micro Area          9.377099
 22                      Corpus Christi, TX Metro Area          8.126623
 23                          Huntsville, TX Micro Area          2.793528
 24                            Amarillo, TX Metro Area          2.694202
 25                Beaumont-Port Arthur, TX Metro Area          0.312417
 26                             Abilene, TX Metro Area         -1.805150
 27                        Texarkana, TX-AR Metro Area         -2.399408
 28                            Victoria, TX Metro Area         -5.338120
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_19_24': year                                             name  pct_change_19_24
 0                              Midland, TX Metro Area         29.200315
 1                      Sherman-Denison, TX Metro Area         26.996951
 2                    Austin-Round Rock, TX Metro Area         25.048898
 3                               Odessa, TX Metro Area         22.841429
 4            San Antonio-New Braunfels, TX Metro Area         20.087796
 5                           Huntsville, TX Micro Area         19.482398
 6                                Tyler, TX Metro Area         18.175231
 7                       Killeen-Temple, TX Metro Area         17.305476
 8                              Lubbock, TX Metro Area         17.259995
 9                               Athens, TX Micro Area         16.949964
 10                                Waco, TX Metro Area         14.789260
 11                      Corpus Christi, TX Metro Area         14.090236
 12                             El Paso, TX Metro Area         13.540137
 13                            Longview, TX Metro Area         13.480194
 14                         Nacogdoches, TX Micro Area         12.556488
 15         Dallas-Fort Worth-Arlington, TX Metro Area         12.194206
 16               College Station-Bryan, TX Metro Area         12.137425
 17    Houston-The Woodlands-Sugar Land, TX Metro Area         11.640274
 18               Brownsville-Harlingen, TX Metro Area         10.502835
 19            McAllen-Edinburg-Mission, TX Metro Area         10.221556
 20                          San Angelo, TX Metro Area          9.095306
 21                            Victoria, TX Metro Area          7.509970
 22                       Wichita Falls, TX Metro Area          6.868647
 23                Beaumont-Port Arthur, TX Metro Area          6.183509
 24                            Amarillo, TX Metro Area          4.335017
 25                              Laredo, TX Metro Area          2.840207
 26                             Abilene, TX Metro Area          0.687932
 27                              Lufkin, TX Micro Area         -3.573580
 28                        Texarkana, TX-AR Metro Area         -6.041029
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN}

### Median age

In [17]:
# for median age, calculate absolute change 
msa_tx_age['change_19_24'] = (msa_tx_age[2024] - msa_tx_age[2019])  # 5 years
msa_tx_age['change_14_24'] = (msa_tx_age[2024] - msa_tx_age[2014])  # 10 years
msa_tx_age['change_09_24'] = (msa_tx_age[2024] - msa_tx_age[2009])  # 15 years
msa_tx_age['change_05_24'] = (msa_tx_age[2024] - msa_tx_age[2005])  # 19 years

In [18]:
# rank by cities that got the youngest
print("Metros by median age change (2005-2024):")
print(msa_tx_age[msa_tx_age['change_05_24'].notna()]
      .sort_values(by='change_05_24', ascending=True)
      .reset_index(drop=True)[['name', 'change_05_24', 2005, 2024]])

Metros by median age change (2005-2024):
year                                             name  change_05_24  2005  \
0                              Midland, TX Metro Area          -1.6  34.7
1                              Abilene, TX Metro Area          -0.2  34.9
2                               Odessa, TX Metro Area          -0.1  31.8
3                        Wichita Falls, TX Metro Area          -0.1  36.4
4                             Longview, TX Metro Area           1.2  37.2
5                           San Angelo, TX Metro Area           1.2  34.8
6                 Beaumont-Port Arthur, TX Metro Area           1.2  36.9
7                              Lubbock, TX Metro Area           1.7  30.9
8                      Sherman-Denison, TX Metro Area           1.8  37.5
9                College Station-Bryan, TX Metro Area           1.9  26.8
10                               Tyler, TX Metro Area           2.1  35.4
11                            Amarillo, TX Metro Area           2.4  34.1
12           San Antonio-New Braunfels, TX Metro Area           2.4  33.8
13    Houston-The Woodlands-Sugar Land, TX Metro Area           2.8  32.9
14         Dallas-Fort Worth-Arlington, TX Metro Area           2.9  32.9
15                                Waco, TX Metro Area           2.9  32.4
16                            Victoria, TX Metro Area           3.1  35.7
17                      Killeen-Temple, TX Metro Area           3.1  30.2
18                              Athens, TX Micro Area           3.1  40.1
19                        Texarkana, TX-AR Metro Area           3.2  37.2
20                             El Paso, TX Metro Area           3.3  30.9
21                              Lufkin, TX Micro Area           3.4  34.7
22                      Corpus Christi, TX Metro Area           3.7  34.7
23                   Austin-Round Rock, TX Metro Area           3.7  32.5
24                              Laredo, TX Metro Area           3.9  26.5
25            McAllen-Edinburg-Mission, TX Metro Area           4.4  26.9
26               Brownsville-Harlingen, TX Metro Area           4.9  28.5

year  2024
0     33.1
1     34.7
2     31.7
3     36.3
4     38.4
5     36.0
6     38.1
7     32.6
8     39.3
9     28.7
10    37.5
11    36.5
12    36.2
13    35.7
14    35.8
15    35.3
16    38.8
17    33.3
18    43.2
19    40.4
20    34.2
21    38.1
22    38.4
23    36.2
24    30.4
25    31.3
26    33.4

### Total population under 18

In [19]:
# percentage change
msa_tx_under18['pct_change_19_24'] = ((msa_tx_under18[2024] - msa_tx_under18[2019]) / msa_tx_under18[2019]) * 100 # 5 years
msa_tx_under18['pct_change_14_24'] = ((msa_tx_under18[2024] - msa_tx_under18[2014]) / msa_tx_under18[2014]) * 100 # 10 years
msa_tx_under18['pct_change_09_24'] = ((msa_tx_under18[2024] - msa_tx_under18[2009]) / msa_tx_under18[2009]) * 100 # 15 years
msa_tx_under18['pct_change_05_24'] = ((msa_tx_under18[2024] - msa_tx_under18[2005]) / msa_tx_under18[2005]) * 100 # 19 years

In [20]:
# print ranked results
print_rankings(
    df=msa_tx_under18,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_05_24
0                           San Angelo, TX Metro Area               inf
1                              Midland, TX Metro Area         61.562085
2                    Austin-Round Rock, TX Metro Area         50.022222
3                College Station-Bryan, TX Metro Area         38.554790
4                               Odessa, TX Metro Area         38.516101
5                             Longview, TX Metro Area         36.361208
6     Houston-The Woodlands-Sugar Land, TX Metro Area         33.021494
7                              Lubbock, TX Metro Area         32.308208
8            San Antonio-New Braunfels, TX Metro Area         27.295813
9                      Sherman-Denison, TX Metro Area         26.759213
10         Dallas-Fort Worth-Arlington, TX Metro Area         26.216238
11                      Killeen-Temple, TX Metro Area         24.621258
12                                Waco, TX Metro Area         23.220889
13                               Tyler, TX Metro Area         20.767435
14            McAllen-Edinburg-Mission, TX Metro Area         15.278925
15                            Amarillo, TX Metro Area          9.797127
16                             Abilene, TX Metro Area          7.557564
17                        Texarkana, TX-AR Metro Area          5.447230
18                Beaumont-Port Arthur, TX Metro Area          1.137674
19                              Laredo, TX Metro Area          0.703160
20                              Athens, TX Micro Area          0.503940
21                              Lufkin, TX Micro Area         -1.769311
22                             El Paso, TX Metro Area         -2.372613
23               Brownsville-Harlingen, TX Metro Area         -6.520687
24                       Wichita Falls, TX Metro Area         -7.526674
25                      Corpus Christi, TX Metro Area         -9.859441
26                            Victoria, TX Metro Area        -28.099706
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_09_24
0                              Midland, TX Metro Area         48.806027
1                             Longview, TX Metro Area         33.192322
2                               Odessa, TX Metro Area         26.709101
3                    Austin-Round Rock, TX Metro Area         25.943057
4                              Lubbock, TX Metro Area         24.175180
5                       Killeen-Temple, TX Metro Area         23.726519
6                College Station-Bryan, TX Metro Area         21.772374
7                      Sherman-Denison, TX Metro Area         21.249066
8                                 Waco, TX Metro Area         18.353158
9     Houston-The Woodlands-Sugar Land, TX Metro Area         18.275666
10           San Antonio-New Braunfels, TX Metro Area         15.972231
11         Dallas-Fort Worth-Arlington, TX Metro Area         12.799110
12                               Tyler, TX Metro Area         12.716730
13                             Abilene, TX Metro Area         10.184126
14                          San Angelo, TX Metro Area          7.052483
15                            Amarillo, TX Metro Area          6.556199
16                              Athens, TX Micro Area          2.442623
17                Beaumont-Port Arthur, TX Metro Area          2.309059
18            McAllen-Edinburg-Mission, TX Metro Area          1.795106
19                        Texarkana, TX-AR Metro Area          1.737936
20                       Wichita Falls, TX Metro Area         -3.420772
21                              Lufkin, TX Micro Area         -4.273052
22                             El Paso, TX Metro Area         -6.599790
23                      Corpus Christi, TX Metro Area         -7.547580
24                              Laredo, TX Metro Area         -8.572684
25               Brownsville-Harlingen, TX Metro Area        -13.526507
26                            Victoria, TX Metro Area        -25.150809
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                             Longview, TX Metro Area         31.957830
1                              Midland, TX Metro Area         21.333688
2                      Sherman-Denison, TX Metro Area         20.949219
3                College Station-Bryan, TX Metro Area         18.401007
4                              Lubbock, TX Metro Area         17.014057
5                       Killeen-Temple, TX Metro Area         15.721683
6                    Austin-Round Rock, TX Metro Area         15.364792
7                               Odessa, TX Metro Area         12.904219
8     Houston-The Woodlands-Sugar Land, TX Metro Area         12.849319
9                              Abilene, TX Metro Area          9.827099
10         Dallas-Fort Worth-Arlington, TX Metro Area          9.676873
11                                Waco, TX Metro Area          9.384677
12           San Antonio-New Braunfels, TX Metro Area          9.314021
13                               Tyler, TX Metro Area          8.971000
14                              Athens, TX Micro Area          7.537429
15                            Amarillo, TX Metro Area          2.045059
16                Beaumont-Port Arthur, TX Metro Area          2.038805
17                          San Angelo, TX Metro Area          0.940710
18                       Wichita Falls, TX Metro Area         -1.187250
19            McAllen-Edinburg-Mission, TX Metro Area         -1.318249
20                         Nacogdoches, TX Micro Area         -1.657821
21                        Texarkana, TX-AR Metro Area         -2.726624
22                              Lufkin, TX Micro Area         -5.230071
23                             El Paso, TX Metro Area         -6.368441
24                          Huntsville, TX Micro Area         -7.207960
25                            Victoria, TX Metro Area         -8.168540
26                              Laredo, TX Metro Area         -8.186302
27                      Corpus Christi, TX Metro Area         -8.260745
28               Brownsville-Harlingen, TX Metro Area         -9.811628
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                              Lubbock, TX Metro Area         13.894787
1                           Huntsville, TX Micro Area         13.858341
2                      Sherman-Denison, TX Metro Area         11.645142
3                               Athens, TX Micro Area         11.509636
4                       Killeen-Temple, TX Metro Area          9.100414
5                                 Waco, TX Metro Area          8.351227
6                    Austin-Round Rock, TX Metro Area          7.666614
7     Houston-The Woodlands-Sugar Land, TX Metro Area          6.234988
8                                Tyler, TX Metro Area          5.113978
9          Dallas-Fort Worth-Arlington, TX Metro Area          4.850580
10               College Station-Bryan, TX Metro Area          3.757632
11           San Antonio-New Braunfels, TX Metro Area          3.290569
12                             Midland, TX Metro Area          3.101739
13                             Abilene, TX Metro Area          2.461911
14                Beaumont-Port Arthur, TX Metro Area          2.345631
15                              Odessa, TX Metro Area          2.032343
16                            Longview, TX Metro Area          1.607904
17                       Wichita Falls, TX Metro Area          0.296035
18                            Amarillo, TX Metro Area          0.260331
19                         Nacogdoches, TX Micro Area          0.053333
20                        Texarkana, TX-AR Metro Area         -1.082949
21            McAllen-Edinburg-Mission, TX Metro Area         -1.277159
22                              Lufkin, TX Micro Area         -1.582264
23                          San Angelo, TX Metro Area         -1.963804
24                             El Paso, TX Metro Area         -1.982924
25                      Corpus Christi, TX Metro Area         -3.284167
26                            Victoria, TX Metro Area         -4.007368
27               Brownsville-Harlingen, TX Metro Area         -5.394840
28                              Laredo, TX Metro Area         -6.587633
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN

{'pct_change_05_24': year                                             name  pct_change_05_24
 0                           San Angelo, TX Metro Area               inf
 1                              Midland, TX Metro Area         61.562085
 2                    Austin-Round Rock, TX Metro Area         50.022222
 3                College Station-Bryan, TX Metro Area         38.554790
 4                               Odessa, TX Metro Area         38.516101
 5                             Longview, TX Metro Area         36.361208
 6     Houston-The Woodlands-Sugar Land, TX Metro Area         33.021494
 7                              Lubbock, TX Metro Area         32.308208
 8            San Antonio-New Braunfels, TX Metro Area         27.295813
 9                      Sherman-Denison, TX Metro Area         26.759213
 10         Dallas-Fort Worth-Arlington, TX Metro Area         26.216238
 11                      Killeen-Temple, TX Metro Area         24.621258
 12                                Waco, TX Metro Area         23.220889
 13                               Tyler, TX Metro Area         20.767435
 14            McAllen-Edinburg-Mission, TX Metro Area         15.278925
 15                            Amarillo, TX Metro Area          9.797127
 16                             Abilene, TX Metro Area          7.557564
 17                        Texarkana, TX-AR Metro Area          5.447230
 18                Beaumont-Port Arthur, TX Metro Area          1.137674
 19                              Laredo, TX Metro Area          0.703160
 20                              Athens, TX Micro Area          0.503940
 21                              Lufkin, TX Micro Area         -1.769311
 22                             El Paso, TX Metro Area         -2.372613
 23               Brownsville-Harlingen, TX Metro Area         -6.520687
 24                       Wichita Falls, TX Metro Area         -7.526674
 25                      Corpus Christi, TX Metro Area         -9.859441
 26                            Victoria, TX Metro Area        -28.099706
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_09_24': year                                             name  pct_change_09_24
 0                              Midland, TX Metro Area         48.806027
 1                             Longview, TX Metro Area         33.192322
 2                               Odessa, TX Metro Area         26.709101
 3                    Austin-Round Rock, TX Metro Area         25.943057
 4                              Lubbock, TX Metro Area         24.175180
 5                       Killeen-Temple, TX Metro Area         23.726519
 6                College Station-Bryan, TX Metro Area         21.772374
 7                      Sherman-Denison, TX Metro Area         21.249066
 8                                 Waco, TX Metro Area         18.353158
 9     Houston-The Woodlands-Sugar Land, TX Metro Area         18.275666
 10           San Antonio-New Braunfels, TX Metro Area         15.972231
 11         Dallas-Fort Worth-Arlington, TX Metro Area         12.799110
 12                               Tyler, TX Metro Area         12.716730
 13                             Abilene, TX Metro Area         10.184126
 14                          San Angelo, TX Metro Area          7.052483
 15                            Amarillo, TX Metro Area          6.556199
 16                              Athens, TX Micro Area          2.442623
 17                Beaumont-Port Arthur, TX Metro Area          2.309059
 18            McAllen-Edinburg-Mission, TX Metro Area          1.795106
 19                        Texarkana, TX-AR Metro Area          1.737936
 20                       Wichita Falls, TX Metro Area         -3.420772
 21                              Lufkin, TX Micro Area         -4.273052
 22                             El Paso, TX Metro Area         -6.599790
 23                      Corpus Christi, TX Metro Area         -7.547580
 24                              Laredo, TX Metro Area         -8.572684
 25               Brownsville-Harlingen, TX Metro Area        -13.526507
 26                            Victoria, TX Metro Area        -25.150809
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_14_24': year                                             name  pct_change_14_24
 0                             Longview, TX Metro Area         31.957830
 1                              Midland, TX Metro Area         21.333688
 2                      Sherman-Denison, TX Metro Area         20.949219
 3                College Station-Bryan, TX Metro Area         18.401007
 4                              Lubbock, TX Metro Area         17.014057
 5                       Killeen-Temple, TX Metro Area         15.721683
 6                    Austin-Round Rock, TX Metro Area         15.364792
 7                               Odessa, TX Metro Area         12.904219
 8     Houston-The Woodlands-Sugar Land, TX Metro Area         12.849319
 9                              Abilene, TX Metro Area          9.827099
 10         Dallas-Fort Worth-Arlington, TX Metro Area          9.676873
 11                                Waco, TX Metro Area          9.384677
 12           San Antonio-New Braunfels, TX Metro Area          9.314021
 13                               Tyler, TX Metro Area          8.971000
 14                              Athens, TX Micro Area          7.537429
 15                            Amarillo, TX Metro Area          2.045059
 16                Beaumont-Port Arthur, TX Metro Area          2.038805
 17                          San Angelo, TX Metro Area          0.940710
 18                       Wichita Falls, TX Metro Area         -1.187250
 19            McAllen-Edinburg-Mission, TX Metro Area         -1.318249
 20                         Nacogdoches, TX Micro Area         -1.657821
 21                        Texarkana, TX-AR Metro Area         -2.726624
 22                              Lufkin, TX Micro Area         -5.230071
 23                             El Paso, TX Metro Area         -6.368441
 24                          Huntsville, TX Micro Area         -7.207960
 25                            Victoria, TX Metro Area         -8.168540
 26                              Laredo, TX Metro Area         -8.186302
 27                      Corpus Christi, TX Metro Area         -8.260745
 28               Brownsville-Harlingen, TX Metro Area         -9.811628
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_19_24': year                                             name  pct_change_19_24
 0                              Lubbock, TX Metro Area         13.894787
 1                           Huntsville, TX Micro Area         13.858341
 2                      Sherman-Denison, TX Metro Area         11.645142
 3                               Athens, TX Micro Area         11.509636
 4                       Killeen-Temple, TX Metro Area          9.100414
 5                                 Waco, TX Metro Area          8.351227
 6                    Austin-Round Rock, TX Metro Area          7.666614
 7     Houston-The Woodlands-Sugar Land, TX Metro Area          6.234988
 8                                Tyler, TX Metro Area          5.113978
 9          Dallas-Fort Worth-Arlington, TX Metro Area          4.850580
 10               College Station-Bryan, TX Metro Area          3.757632
 11           San Antonio-New Braunfels, TX Metro Area          3.290569
 12                             Midland, TX Metro Area          3.101739
 13                             Abilene, TX Metro Area          2.461911
 14                Beaumont-Port Arthur, TX Metro Area          2.345631
 15                              Odessa, TX Metro Area          2.032343
 16                            Longview, TX Metro Area          1.607904
 17                       Wichita Falls, TX Metro Area          0.296035
 18                            Amarillo, TX Metro Area          0.260331
 19                         Nacogdoches, TX Micro Area          0.053333
 20                        Texarkana, TX-AR Metro Area         -1.082949
 21            McAllen-Edinburg-Mission, TX Metro Area         -1.277159
 22                              Lufkin, TX Micro Area         -1.582264
 23                          San Angelo, TX Metro Area         -1.963804
 24                             El Paso, TX Metro Area         -1.982924
 25                      Corpus Christi, TX Metro Area         -3.284167
 26                            Victoria, TX Metro Area         -4.007368
 27               Brownsville-Harlingen, TX Metro Area         -5.394840
 28                              Laredo, TX Metro Area         -6.587633
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN}

### Number of family households with children under 18

In [21]:
# calculate percentage changes for family households with at least one kid under 18
msa_tx_family_households_with_child['pct_change_19_24'] = ((msa_tx_family_households_with_child[2024] - msa_tx_family_households_with_child[2019]) / msa_tx_family_households_with_child[2019]) * 100 # 5 years
msa_tx_family_households_with_child['pct_change_14_24'] = ((msa_tx_family_households_with_child[2024] - msa_tx_family_households_with_child[2014]) / msa_tx_family_households_with_child[2014]) * 100 # 10 years
msa_tx_family_households_with_child['pct_change_09_24'] = ((msa_tx_family_households_with_child[2024] - msa_tx_family_households_with_child[2009]) / msa_tx_family_households_with_child[2009]) * 100 # 15 years
msa_tx_family_households_with_child['pct_change_05_24'] = ((msa_tx_family_households_with_child[2024] - msa_tx_family_households_with_child[2005]) / msa_tx_family_households_with_child[2005]) * 100 # 19 years

In [22]:
# print ranked results
print_rankings(
    df=msa_tx_family_households_with_child,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_05_24
0                    Austin-Round Rock, TX Metro Area         64.811644
1                              Midland, TX Metro Area         56.950524
2                College Station-Bryan, TX Metro Area         41.657448
3                             Longview, TX Metro Area         39.013238
4                               Odessa, TX Metro Area         36.717834
5                       Killeen-Temple, TX Metro Area         33.666276
6            San Antonio-New Braunfels, TX Metro Area         30.291777
7     Houston-The Woodlands-Sugar Land, TX Metro Area         30.273362
8          Dallas-Fort Worth-Arlington, TX Metro Area         23.619685
9                      Sherman-Denison, TX Metro Area         16.031056
10                               Tyler, TX Metro Area         14.977330
11                                Waco, TX Metro Area         14.476040
12                              Athens, TX Micro Area          9.784379
13                             Lubbock, TX Metro Area          8.192805
14                          San Angelo, TX Metro Area          7.547836
15            McAllen-Edinburg-Mission, TX Metro Area          7.132118
16                              Lufkin, TX Micro Area          6.054206
17                              Laredo, TX Metro Area          5.834744
18                            Amarillo, TX Metro Area          1.769111
19               Brownsville-Harlingen, TX Metro Area         -0.648420
20                             El Paso, TX Metro Area         -1.029088
21                       Wichita Falls, TX Metro Area         -4.644740
22                Beaumont-Port Arthur, TX Metro Area         -5.441369
23                      Corpus Christi, TX Metro Area         -7.730896
24                        Texarkana, TX-AR Metro Area         -9.419648
25                             Abilene, TX Metro Area        -14.321991
26                            Victoria, TX Metro Area        -39.312161
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_09_24
0                              Midland, TX Metro Area         47.104949
1                    Austin-Round Rock, TX Metro Area         46.951654
2                             Longview, TX Metro Area         44.712295
3                                Tyler, TX Metro Area         36.645509
4                       Killeen-Temple, TX Metro Area         29.241787
5                               Odessa, TX Metro Area         28.558682
6            San Antonio-New Braunfels, TX Metro Area         26.864687
7                College Station-Bryan, TX Metro Area         25.214911
8     Houston-The Woodlands-Sugar Land, TX Metro Area         20.822883
9                      Sherman-Denison, TX Metro Area         18.760331
10                                Waco, TX Metro Area         18.192575
11         Dallas-Fort Worth-Arlington, TX Metro Area         14.756589
12                              Athens, TX Micro Area         12.457053
13                             Lubbock, TX Metro Area          8.442595
14                              Lufkin, TX Micro Area          7.655203
15                          San Angelo, TX Metro Area          4.946948
16                              Laredo, TX Metro Area          4.193038
17                            Amarillo, TX Metro Area          3.385210
18                      Corpus Christi, TX Metro Area          3.215144
19            McAllen-Edinburg-Mission, TX Metro Area          1.772822
20                       Wichita Falls, TX Metro Area          1.361089
21                             El Paso, TX Metro Area          1.179662
22                             Abilene, TX Metro Area         -2.269855
23                        Texarkana, TX-AR Metro Area         -5.848155
24               Brownsville-Harlingen, TX Metro Area         -7.422429
25                Beaumont-Port Arthur, TX Metro Area        -15.883596
26                            Victoria, TX Metro Area        -26.176019
27                          Eagle Pass, TX Metro Area               NaN
28                            Granbury, TX Micro Area               NaN
29                          Huntsville, TX Micro Area               NaN
30                            Marshall, TX Micro Area               NaN
31                         Nacogdoches, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                             Longview, TX Metro Area         41.015187
1                    Austin-Round Rock, TX Metro Area         33.525335
2                              Midland, TX Metro Area         30.381553
3                               Odessa, TX Metro Area         23.914803
4                      Sherman-Denison, TX Metro Area         23.453608
5                           San Angelo, TX Metro Area         21.953563
6                       Killeen-Temple, TX Metro Area         20.888258
7                College Station-Bryan, TX Metro Area         20.369718
8                               Athens, TX Micro Area         19.744957
9                                Tyler, TX Metro Area         19.696000
10                       Wichita Falls, TX Metro Area         18.339877
11                          Huntsville, TX Micro Area         17.093822
12           San Antonio-New Braunfels, TX Metro Area         15.927837
13    Houston-The Woodlands-Sugar Land, TX Metro Area         15.039456
14                                Waco, TX Metro Area          9.834376
15         Dallas-Fort Worth-Arlington, TX Metro Area          6.530068
16                              Lufkin, TX Micro Area          5.497199
17            McAllen-Edinburg-Mission, TX Metro Area          4.295295
18                         Nacogdoches, TX Micro Area          3.708489
19                             El Paso, TX Metro Area         -0.430682
20                             Lubbock, TX Metro Area         -0.929615
21                             Abilene, TX Metro Area         -1.455048
22                      Corpus Christi, TX Metro Area         -3.041901
23                              Laredo, TX Metro Area         -4.369700
24               Brownsville-Harlingen, TX Metro Area         -4.810448
25                            Amarillo, TX Metro Area         -5.499058
26                        Texarkana, TX-AR Metro Area         -5.527319
27                            Victoria, TX Metro Area         -9.132720
28                Beaumont-Port Arthur, TX Metro Area        -11.881415
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                               Athens, TX Micro Area         42.275211
1                             Victoria, TX Metro Area         20.918033
2                               Odessa, TX Metro Area         20.655172
3                    Austin-Round Rock, TX Metro Area         19.678309
4                        Wichita Falls, TX Metro Area         18.962601
5                      Sherman-Denison, TX Metro Area         17.203087
6                       Killeen-Temple, TX Metro Area         17.139426
7            San Antonio-New Braunfels, TX Metro Area         17.056383
8                              Midland, TX Metro Area         14.092392
9                             Longview, TX Metro Area         13.537526
10                               Tyler, TX Metro Area         10.637039
11    Houston-The Woodlands-Sugar Land, TX Metro Area          7.561235
12         Dallas-Fort Worth-Arlington, TX Metro Area          5.444406
13                             El Paso, TX Metro Area          5.019377
14                            Amarillo, TX Metro Area          3.352451
15                      Corpus Christi, TX Metro Area          2.983586
16                                Waco, TX Metro Area          2.557192
17               College Station-Bryan, TX Metro Area          2.272803
18                Beaumont-Port Arthur, TX Metro Area         -0.006494
19                              Lufkin, TX Micro Area         -0.273066
20                         Nacogdoches, TX Micro Area         -0.754297
21               Brownsville-Harlingen, TX Metro Area         -0.925264
22                          Huntsville, TX Micro Area         -1.197142
23                        Texarkana, TX-AR Metro Area         -1.291413
24            McAllen-Edinburg-Mission, TX Metro Area         -1.369932
25                             Lubbock, TX Metro Area         -1.544911
26                          San Angelo, TX Metro Area         -2.527676
27                              Laredo, TX Metro Area         -4.458896
28                             Abilene, TX Metro Area         -5.437220
29                          Eagle Pass, TX Metro Area               NaN
30                            Granbury, TX Micro Area               NaN
31                            Marshall, TX Micro Area               NaN
32                Rio Grande City-Roma, TX Micro Area               NaN

{'pct_change_05_24': year                                             name  pct_change_05_24
 0                    Austin-Round Rock, TX Metro Area         64.811644
 1                              Midland, TX Metro Area         56.950524
 2                College Station-Bryan, TX Metro Area         41.657448
 3                             Longview, TX Metro Area         39.013238
 4                               Odessa, TX Metro Area         36.717834
 5                       Killeen-Temple, TX Metro Area         33.666276
 6            San Antonio-New Braunfels, TX Metro Area         30.291777
 7     Houston-The Woodlands-Sugar Land, TX Metro Area         30.273362
 8          Dallas-Fort Worth-Arlington, TX Metro Area         23.619685
 9                      Sherman-Denison, TX Metro Area         16.031056
 10                               Tyler, TX Metro Area         14.977330
 11                                Waco, TX Metro Area         14.476040
 12                              Athens, TX Micro Area          9.784379
 13                             Lubbock, TX Metro Area          8.192805
 14                          San Angelo, TX Metro Area          7.547836
 15            McAllen-Edinburg-Mission, TX Metro Area          7.132118
 16                              Lufkin, TX Micro Area          6.054206
 17                              Laredo, TX Metro Area          5.834744
 18                            Amarillo, TX Metro Area          1.769111
 19               Brownsville-Harlingen, TX Metro Area         -0.648420
 20                             El Paso, TX Metro Area         -1.029088
 21                       Wichita Falls, TX Metro Area         -4.644740
 22                Beaumont-Port Arthur, TX Metro Area         -5.441369
 23                      Corpus Christi, TX Metro Area         -7.730896
 24                        Texarkana, TX-AR Metro Area         -9.419648
 25                             Abilene, TX Metro Area        -14.321991
 26                            Victoria, TX Metro Area        -39.312161
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_09_24': year                                             name  pct_change_09_24
 0                              Midland, TX Metro Area         47.104949
 1                    Austin-Round Rock, TX Metro Area         46.951654
 2                             Longview, TX Metro Area         44.712295
 3                                Tyler, TX Metro Area         36.645509
 4                       Killeen-Temple, TX Metro Area         29.241787
 5                               Odessa, TX Metro Area         28.558682
 6            San Antonio-New Braunfels, TX Metro Area         26.864687
 7                College Station-Bryan, TX Metro Area         25.214911
 8     Houston-The Woodlands-Sugar Land, TX Metro Area         20.822883
 9                      Sherman-Denison, TX Metro Area         18.760331
 10                                Waco, TX Metro Area         18.192575
 11         Dallas-Fort Worth-Arlington, TX Metro Area         14.756589
 12                              Athens, TX Micro Area         12.457053
 13                             Lubbock, TX Metro Area          8.442595
 14                              Lufkin, TX Micro Area          7.655203
 15                          San Angelo, TX Metro Area          4.946948
 16                              Laredo, TX Metro Area          4.193038
 17                            Amarillo, TX Metro Area          3.385210
 18                      Corpus Christi, TX Metro Area          3.215144
 19            McAllen-Edinburg-Mission, TX Metro Area          1.772822
 20                       Wichita Falls, TX Metro Area          1.361089
 21                             El Paso, TX Metro Area          1.179662
 22                             Abilene, TX Metro Area         -2.269855
 23                        Texarkana, TX-AR Metro Area         -5.848155
 24               Brownsville-Harlingen, TX Metro Area         -7.422429
 25                Beaumont-Port Arthur, TX Metro Area        -15.883596
 26                            Victoria, TX Metro Area        -26.176019
 27                          Eagle Pass, TX Metro Area               NaN
 28                            Granbury, TX Micro Area               NaN
 29                          Huntsville, TX Micro Area               NaN
 30                            Marshall, TX Micro Area               NaN
 31                         Nacogdoches, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_14_24': year                                             name  pct_change_14_24
 0                             Longview, TX Metro Area         41.015187
 1                    Austin-Round Rock, TX Metro Area         33.525335
 2                              Midland, TX Metro Area         30.381553
 3                               Odessa, TX Metro Area         23.914803
 4                      Sherman-Denison, TX Metro Area         23.453608
 5                           San Angelo, TX Metro Area         21.953563
 6                       Killeen-Temple, TX Metro Area         20.888258
 7                College Station-Bryan, TX Metro Area         20.369718
 8                               Athens, TX Micro Area         19.744957
 9                                Tyler, TX Metro Area         19.696000
 10                       Wichita Falls, TX Metro Area         18.339877
 11                          Huntsville, TX Micro Area         17.093822
 12           San Antonio-New Braunfels, TX Metro Area         15.927837
 13    Houston-The Woodlands-Sugar Land, TX Metro Area         15.039456
 14                                Waco, TX Metro Area          9.834376
 15         Dallas-Fort Worth-Arlington, TX Metro Area          6.530068
 16                              Lufkin, TX Micro Area          5.497199
 17            McAllen-Edinburg-Mission, TX Metro Area          4.295295
 18                         Nacogdoches, TX Micro Area          3.708489
 19                             El Paso, TX Metro Area         -0.430682
 20                             Lubbock, TX Metro Area         -0.929615
 21                             Abilene, TX Metro Area         -1.455048
 22                      Corpus Christi, TX Metro Area         -3.041901
 23                              Laredo, TX Metro Area         -4.369700
 24               Brownsville-Harlingen, TX Metro Area         -4.810448
 25                            Amarillo, TX Metro Area         -5.499058
 26                        Texarkana, TX-AR Metro Area         -5.527319
 27                            Victoria, TX Metro Area         -9.132720
 28                Beaumont-Port Arthur, TX Metro Area        -11.881415
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN,
 'pct_change_19_24': year                                             name  pct_change_19_24
 0                               Athens, TX Micro Area         42.275211
 1                             Victoria, TX Metro Area         20.918033
 2                               Odessa, TX Metro Area         20.655172
 3                    Austin-Round Rock, TX Metro Area         19.678309
 4                        Wichita Falls, TX Metro Area         18.962601
 5                      Sherman-Denison, TX Metro Area         17.203087
 6                       Killeen-Temple, TX Metro Area         17.139426
 7            San Antonio-New Braunfels, TX Metro Area         17.056383
 8                              Midland, TX Metro Area         14.092392
 9                             Longview, TX Metro Area         13.537526
 10                               Tyler, TX Metro Area         10.637039
 11    Houston-The Woodlands-Sugar Land, TX Metro Area          7.561235
 12         Dallas-Fort Worth-Arlington, TX Metro Area          5.444406
 13                             El Paso, TX Metro Area          5.019377
 14                            Amarillo, TX Metro Area          3.352451
 15                      Corpus Christi, TX Metro Area          2.983586
 16                                Waco, TX Metro Area          2.557192
 17               College Station-Bryan, TX Metro Area          2.272803
 18                Beaumont-Port Arthur, TX Metro Area         -0.006494
 19                              Lufkin, TX Micro Area         -0.273066
 20                         Nacogdoches, TX Micro Area         -0.754297
 21               Brownsville-Harlingen, TX Metro Area         -0.925264
 22                          Huntsville, TX Micro Area         -1.197142
 23                        Texarkana, TX-AR Metro Area         -1.291413
 24            McAllen-Edinburg-Mission, TX Metro Area         -1.369932
 25                             Lubbock, TX Metro Area         -1.544911
 26                          San Angelo, TX Metro Area         -2.527676
 27                              Laredo, TX Metro Area         -4.458896
 28                             Abilene, TX Metro Area         -5.437220
 29                          Eagle Pass, TX Metro Area               NaN
 30                            Granbury, TX Micro Area               NaN
 31                            Marshall, TX Micro Area               NaN
 32                Rio Grande City-Roma, TX Micro Area               NaN}

### Migration to Texas MSAs

In [23]:
# Calculate migration percentage changes
msa_tx_migration['pct_chg_migration_05_24'] = ((msa_tx_migration['total_in_migration_2024'] - msa_tx_migration['total_in_migration_2005']) / msa_tx_migration['total_in_migration_2005'] * 100)
msa_tx_migration['pct_chg_migration_09_24'] = ((msa_tx_migration['total_in_migration_2024'] - msa_tx_migration['total_in_migration_2009']) / msa_tx_migration['total_in_migration_2009'] * 100)
msa_tx_migration['pct_chg_migration_14_24'] = ((msa_tx_migration['total_in_migration_2024'] - msa_tx_migration['total_in_migration_2014']) / msa_tx_migration['total_in_migration_2014'] * 100)
msa_tx_migration['pct_chg_migration_19_24'] = ((msa_tx_migration['total_in_migration_2024'] - msa_tx_migration['total_in_migration_2019']) / msa_tx_migration['total_in_migration_2019'] * 100)

In [24]:
# Print ranked results
print_rankings(
    df=msa_tx_migration,
    name_col='name_',
    variable_names=['pct_chg_migration_05_24', 'pct_chg_migration_09_24',
                 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

                                              name_  pct_chg_migration_05_24
0                            Midland, TX Metro Area               248.428661
1                             Odessa, TX Metro Area               199.605263
2                            Lubbock, TX Metro Area                96.150691
3              College Station-Bryan, TX Metro Area                79.185659
4                  Austin-Round Rock, TX Metro Area                65.322141
5                           Amarillo, TX Metro Area                53.519363
6                            El Paso, TX Metro Area                51.352402
7          San Antonio-New Braunfels, TX Metro Area                48.938003
8        Dallas-Fort Worth-Arlington, TX Metro Area                43.363235
9                    Sherman-Denison, TX Metro Area                40.719446
10                              Waco, TX Metro Area                32.143328
11                        San Angelo, TX Metro Area                31.882936
12  Houston-The Woodlands-Sugar Land, TX Metro Area                23.600799
13                            Lufkin, TX Micro Area                22.362052
14                          Longview, TX Metro Area                20.921128
15                     Wichita Falls, TX Metro Area                18.967401
16                    Killeen-Temple, TX Metro Area                 5.612408
17                             Tyler, TX Metro Area                 5.376472
18                            Athens, TX Micro Area                 2.106136
19                           Abilene, TX Metro Area                 1.991311
20              Beaumont-Port Arthur, TX Metro Area               -12.045336
21             Brownsville-Harlingen, TX Metro Area               -16.388929
22          McAllen-Edinburg-Mission, TX Metro Area               -22.724248
23                    Corpus Christi, TX Metro Area               -28.388915
24                          Victoria, TX Metro Area               -38.349276
25                      Texarkana, TX-AR Metro Area               -44.737976
26                            Laredo, TX Metro Area               -49.005236
27                        Eagle Pass, TX Metro Area                      NaN
28                          Granbury, TX Micro Area                      NaN
29                        Huntsville, TX Micro Area                      NaN
30                          Marshall, TX Micro Area                      NaN
31                       Nacogdoches, TX Micro Area                      NaN
32              Rio Grande City-Roma, TX Micro Area                      NaN
                                              name_  pct_chg_migration_09_24
0                            Midland, TX Metro Area               149.062114
1                             Lufkin, TX Micro Area                73.435785
2                             Odessa, TX Metro Area                55.867397
3          San Antonio-New Braunfels, TX Metro Area                50.104001
4        Dallas-Fort Worth-Arlington, TX Metro Area                37.571458
5                  Austin-Round Rock, TX Metro Area                34.415425
6   Houston-The Woodlands-Sugar Land, TX Metro Area                28.914305
7              College Station-Bryan, TX Metro Area                20.908211
8                             Athens, TX Micro Area                13.305116
9                              Tyler, TX Metro Area                11.042868
10                   Sherman-Denison, TX Metro Area                 9.448458
11                              Waco, TX Metro Area                 6.707090
12                          Amarillo, TX Metro Area                 5.767439
13                           Lubbock, TX Metro Area                 4.964876
14                           El Paso, TX Metro Area                 1.245223
15          McAllen-Edinburg-Mission, TX Metro Area                -2.747428
16                    Killeen-Temple, TX Metro Area                -4.063328
17                     Wichita Falls, TX Metro Area                -7.373272
18             Brownsville-Harlingen, TX Metro Area                -7.768542
19                          Longview, TX Metro Area                -8.985212
20              Beaumont-Port Arthur, TX Metro Area                -9.529125
21                          Victoria, TX Metro Area               -17.644168
22                      Texarkana, TX-AR Metro Area               -30.548538
23                    Corpus Christi, TX Metro Area               -33.762232
24                        San Angelo, TX Metro Area               -34.114644
25                           Abilene, TX Metro Area               -37.274549
26                            Laredo, TX Metro Area               -51.628923
27                        Eagle Pass, TX Metro Area                      NaN
28                          Granbury, TX Micro Area                      NaN
29                        Huntsville, TX Micro Area                      NaN
30                          Marshall, TX Micro Area                      NaN
31                       Nacogdoches, TX Micro Area                      NaN
32              Rio Grande City-Roma, TX Micro Area                      NaN
                                              name_  pct_chg_migration_14_24
0                            Midland, TX Metro Area                56.408267
1                              Tyler, TX Metro Area                44.956230
2           McAllen-Edinburg-Mission, TX Metro Area                41.107383
3                             Athens, TX Micro Area                33.095547
4                           Amarillo, TX Metro Area                32.188767
5          San Antonio-New Braunfels, TX Metro Area                27.120783
6        Dallas-Fort Worth-Arlington, TX Metro Area                26.425448
7                             Odessa, TX Metro Area                20.869038
8              Brownsville-Harlingen, TX Metro Area                20.233382
9                             Lufkin, TX Micro Area                16.885519
10                 Austin-Round Rock, TX Metro Area                16.267693
11                              Waco, TX Metro Area                11.208426
12                   Sherman-Denison, TX Metro Area                 9.098183
13  Houston-The Woodlands-Sugar Land, TX Metro Area                 8.237165
14                    Killeen-Temple, TX Metro Area                 4.332030
15                        Huntsville, TX Micro Area                 3.605687
16                           Lubbock, TX Metro Area                 1.697979
17                          Victoria, TX Metro Area                -0.455446
18                           El Paso, TX Metro Area                -5.012073
19             College Station-Bryan, TX Metro Area                -8.197324
20                        San Angelo, TX Metro Area                -8.310905
21                     Wichita Falls, TX Metro Area               -14.311012
22                          Longview, TX Metro Area               -16.229411
23              Beaumont-Port Arthur, TX Metro Area               -21.907005
24                      Texarkana, TX-AR Metro Area               -30.754700
25                    Corpus Christi, TX Metro Area               -31.567900
26                       Nacogdoches, TX Micro Area               -39.221469
27                           Abilene, TX Metro Area               -41.977343
28                            Laredo, TX Metro Area               -45.033860
29                        Eagle Pass, TX Metro Area                      NaN
30                          Granbury, TX Micro Area                      NaN
31                          Marshall, TX Micro Area                      NaN
32              Rio Grande City-Roma, TX Micro Area                      NaN
                                              name_  pct_chg_migration_19_24
0                         Huntsville, TX Micro Area                81.228464
1                              Tyler, TX Metro Area                38.303021
2                           Amarillo, TX Metro Area                37.924206
3              Brownsville-Harlingen, TX Metro Area                36.616550
4                             Odessa, TX Metro Area                26.872562
5          San Antonio-New Braunfels, TX Metro Area                23.897717
6        Dallas-Fort Worth-Arlington, TX Metro Area                21.032612
7                             Lufkin, TX Micro Area                20.495710
8                            Midland, TX Metro Area                16.417284
9                       Texarkana, TX-AR Metro Area                12.248469
10                            Athens, TX Micro Area                11.479269
11                 Austin-Round Rock, TX Metro Area                10.758004
12  Houston-The Woodlands-Sugar Land, TX Metro Area                 9.678654
13             College Station-Bryan, TX Metro Area                 2.415035
14                     Wichita Falls, TX Metro Area                 1.594090
15                              Waco, TX Metro Area                 1.364188
16                    Killeen-Temple, TX Metro Area                 1.241570
17                          Victoria, TX Metro Area                -0.238142
18          McAllen-Edinburg-Mission, TX Metro Area                -1.787943
19                   Sherman-Denison, TX Metro Area                -6.905296
20              Beaumont-Port Arthur, TX Metro Area                -8.691117
21                       Nacogdoches, TX Micro Area               -11.734475
22                           El Paso, TX Metro Area               -12.202710
23                    Corpus Christi, TX Metro Area               -13.880696
24                        San Angelo, TX Metro Area               -14.419212
25                           Lubbock, TX Metro Area               -17.524795
26                           Abilene, TX Metro Area               -39.200345
27                          Longview, TX Metro Area               -44.705576
28                            Laredo, TX Metro Area               -45.256295
29                        Eagle Pass, TX Metro Area                      NaN
30                          Granbury, TX Micro Area                      NaN
31                          Marshall, TX Micro Area                      NaN
32              Rio Grande City-Roma, TX Micro Area                      NaN

{'pct_chg_migration_05_24':                                               name_  pct_chg_migration_05_24
 0                            Midland, TX Metro Area               248.428661
 1                             Odessa, TX Metro Area               199.605263
 2                            Lubbock, TX Metro Area                96.150691
 3              College Station-Bryan, TX Metro Area                79.185659
 4                  Austin-Round Rock, TX Metro Area                65.322141
 5                           Amarillo, TX Metro Area                53.519363
 6                            El Paso, TX Metro Area                51.352402
 7          San Antonio-New Braunfels, TX Metro Area                48.938003
 8        Dallas-Fort Worth-Arlington, TX Metro Area                43.363235
 9                    Sherman-Denison, TX Metro Area                40.719446
 10                              Waco, TX Metro Area                32.143328
 11                        San Angelo, TX Metro Area                31.882936
 12  Houston-The Woodlands-Sugar Land, TX Metro Area                23.600799
 13                            Lufkin, TX Micro Area                22.362052
 14                          Longview, TX Metro Area                20.921128
 15                     Wichita Falls, TX Metro Area                18.967401
 16                    Killeen-Temple, TX Metro Area                 5.612408
 17                             Tyler, TX Metro Area                 5.376472
 18                            Athens, TX Micro Area                 2.106136
 19                           Abilene, TX Metro Area                 1.991311
 20              Beaumont-Port Arthur, TX Metro Area               -12.045336
 21             Brownsville-Harlingen, TX Metro Area               -16.388929
 22          McAllen-Edinburg-Mission, TX Metro Area               -22.724248
 23                    Corpus Christi, TX Metro Area               -28.388915
 24                          Victoria, TX Metro Area               -38.349276
 25                      Texarkana, TX-AR Metro Area               -44.737976
 26                            Laredo, TX Metro Area               -49.005236
 27                        Eagle Pass, TX Metro Area                      NaN
 28                          Granbury, TX Micro Area                      NaN
 29                        Huntsville, TX Micro Area                      NaN
 30                          Marshall, TX Micro Area                      NaN
 31                       Nacogdoches, TX Micro Area                      NaN
 32              Rio Grande City-Roma, TX Micro Area                      NaN,
 'pct_chg_migration_09_24':                                               name_  pct_chg_migration_09_24
 0                            Midland, TX Metro Area               149.062114
 1                             Lufkin, TX Micro Area                73.435785
 2                             Odessa, TX Metro Area                55.867397
 3          San Antonio-New Braunfels, TX Metro Area                50.104001
 4        Dallas-Fort Worth-Arlington, TX Metro Area                37.571458
 5                  Austin-Round Rock, TX Metro Area                34.415425
 6   Houston-The Woodlands-Sugar Land, TX Metro Area                28.914305
 7              College Station-Bryan, TX Metro Area                20.908211
 8                             Athens, TX Micro Area                13.305116
 9                              Tyler, TX Metro Area                11.042868
 10                   Sherman-Denison, TX Metro Area                 9.448458
 11                              Waco, TX Metro Area                 6.707090
 12                          Amarillo, TX Metro Area                 5.767439
 13                           Lubbock, TX Metro Area                 4.964876
 14                           El Paso, TX Metro Area                 1.245223
 15          McAllen-Edinburg-Mission, TX Metro Area                -2.747428
 16                    Killeen-Temple, TX Metro Area                -4.063328
 17                     Wichita Falls, TX Metro Area                -7.373272
 18             Brownsville-Harlingen, TX Metro Area                -7.768542
 19                          Longview, TX Metro Area                -8.985212
 20              Beaumont-Port Arthur, TX Metro Area                -9.529125
 21                          Victoria, TX Metro Area               -17.644168
 22                      Texarkana, TX-AR Metro Area               -30.548538
 23                    Corpus Christi, TX Metro Area               -33.762232
 24                        San Angelo, TX Metro Area               -34.114644
 25                           Abilene, TX Metro Area               -37.274549
 26                            Laredo, TX Metro Area               -51.628923
 27                        Eagle Pass, TX Metro Area                      NaN
 28                          Granbury, TX Micro Area                      NaN
 29                        Huntsville, TX Micro Area                      NaN
 30                          Marshall, TX Micro Area                      NaN
 31                       Nacogdoches, TX Micro Area                      NaN
 32              Rio Grande City-Roma, TX Micro Area                      NaN,
 'pct_chg_migration_14_24':                                               name_  pct_chg_migration_14_24
 0                            Midland, TX Metro Area                56.408267
 1                              Tyler, TX Metro Area                44.956230
 2           McAllen-Edinburg-Mission, TX Metro Area                41.107383
 3                             Athens, TX Micro Area                33.095547
 4                           Amarillo, TX Metro Area                32.188767
 5          San Antonio-New Braunfels, TX Metro Area                27.120783
 6        Dallas-Fort Worth-Arlington, TX Metro Area                26.425448
 7                             Odessa, TX Metro Area                20.869038
 8              Brownsville-Harlingen, TX Metro Area                20.233382
 9                             Lufkin, TX Micro Area                16.885519
 10                 Austin-Round Rock, TX Metro Area                16.267693
 11                              Waco, TX Metro Area                11.208426
 12                   Sherman-Denison, TX Metro Area                 9.098183
 13  Houston-The Woodlands-Sugar Land, TX Metro Area                 8.237165
 14                    Killeen-Temple, TX Metro Area                 4.332030
 15                        Huntsville, TX Micro Area                 3.605687
 16                           Lubbock, TX Metro Area                 1.697979
 17                          Victoria, TX Metro Area                -0.455446
 18                           El Paso, TX Metro Area                -5.012073
 19             College Station-Bryan, TX Metro Area                -8.197324
 20                        San Angelo, TX Metro Area                -8.310905
 21                     Wichita Falls, TX Metro Area               -14.311012
 22                          Longview, TX Metro Area               -16.229411
 23              Beaumont-Port Arthur, TX Metro Area               -21.907005
 24                      Texarkana, TX-AR Metro Area               -30.754700
 25                    Corpus Christi, TX Metro Area               -31.567900
 26                       Nacogdoches, TX Micro Area               -39.221469
 27                           Abilene, TX Metro Area               -41.977343
 28                            Laredo, TX Metro Area               -45.033860
 29                        Eagle Pass, TX Metro Area                      NaN
 30                          Granbury, TX Micro Area                      NaN
 31                          Marshall, TX Micro Area                      NaN
 32              Rio Grande City-Roma, TX Micro Area                      NaN,
 'pct_chg_migration_19_24':                                               name_  pct_chg_migration_19_24
 0                         Huntsville, TX Micro Area                81.228464
 1                              Tyler, TX Metro Area                38.303021
 2                           Amarillo, TX Metro Area                37.924206
 3              Brownsville-Harlingen, TX Metro Area                36.616550
 4                             Odessa, TX Metro Area                26.872562
 5          San Antonio-New Braunfels, TX Metro Area                23.897717
 6        Dallas-Fort Worth-Arlington, TX Metro Area                21.032612
 7                             Lufkin, TX Micro Area                20.495710
 8                            Midland, TX Metro Area                16.417284
 9                       Texarkana, TX-AR Metro Area                12.248469
 10                            Athens, TX Micro Area                11.479269
 11                 Austin-Round Rock, TX Metro Area                10.758004
 12  Houston-The Woodlands-Sugar Land, TX Metro Area                 9.678654
 13             College Station-Bryan, TX Metro Area                 2.415035
 14                     Wichita Falls, TX Metro Area                 1.594090
 15                              Waco, TX Metro Area                 1.364188
 16                    Killeen-Temple, TX Metro Area                 1.241570
 17                          Victoria, TX Metro Area                -0.238142
 18          McAllen-Edinburg-Mission, TX Metro Area                -1.787943
 19                   Sherman-Denison, TX Metro Area                -6.905296
 20              Beaumont-Port Arthur, TX Metro Area                -8.691117
 21                       Nacogdoches, TX Micro Area               -11.734475
 22                           El Paso, TX Metro Area               -12.202710
 23                    Corpus Christi, TX Metro Area               -13.880696
 24                        San Angelo, TX Metro Area               -14.419212
 25                           Lubbock, TX Metro Area               -17.524795
 26                           Abilene, TX Metro Area               -39.200345
 27                          Longview, TX Metro Area               -44.705576
 28                            Laredo, TX Metro Area               -45.256295
 29                        Eagle Pass, TX Metro Area                      NaN
 30                          Granbury, TX Micro Area                      NaN
 31                          Marshall, TX Micro Area                      NaN
 32              Rio Grande City-Roma, TX Micro Area                      NaN}

## ACS1 margins of error

In [25]:
# Filter just for Tyler, TX
tyler_estimates_acs1 = msa_tx[msa_tx['name'] == 'Tyler, TX Metro Area'].copy()

tyler_estimates_acs1

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,median_age_moe,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,msa_code,year,total_in_migration
346,"Tyler, TX Metro Area",185465.0,48152.0,26026.0,35.4,49255.0,144741.0,20038.0,12408.0,3638.0,...,0.2,177.0,4081.0,3858.0,2456.0,1629.0,540.0,46340,2005,16814.0
969,"Tyler, TX Metro Area",194635.0,48471.0,24303.0,35.2,49980.0,152096.0,24363.0,7647.0,4786.0,...,0.2,279.0,5212.0,4351.0,1975.0,1536.0,1034.0,46340,2006,13726.0
1025,"Tyler, TX Metro Area",198705.0,48396.0,24532.0,35.3,50624.0,154608.0,25920.0,10017.0,4053.0,...,0.3,251.0,5101.0,4337.0,2316.0,1380.0,432.0,46340,2007,14573.0
1971,"Tyler, TX Metro Area",201277.0,48756.0,24358.0,35.8,50898.0,161619.0,23302.0,10093.0,3134.0,...,0.5,329.0,5316.0,4955.0,2644.0,1990.0,703.0,46340,2008,14059.0
2514,"Tyler, TX Metro Area",204665.0,47517.0,21899.0,36.1,52773.0,165461.0,20022.0,11575.0,3633.0,...,0.6,0.0,4666.0,4029.0,3036.0,1409.0,627.0,46340,2009,15956.0
2739,"Tyler, TX Metro Area",210512.0,53601.0,26382.0,35.5,54236.0,166384.0,26636.0,10171.0,2857.0,...,0.3,524.0,5540.0,5242.0,2945.0,1916.0,1016.0,46340,2010,14361.0
3414,"Tyler, TX Metro Area",213381.0,53407.0,25992.0,35.6,54404.0,165910.0,25906.0,12872.0,6230.0,...,0.3,292.0,6348.0,4968.0,3165.0,2931.0,252.0,46340,2011,19403.0
3971,"Tyler, TX Metro Area",214821.0,54091.0,26429.0,36.0,54602.0,170460.0,21024.0,14251.0,5551.0,...,0.4,293.0,6012.0,4227.0,4031.0,2173.0,553.0,46340,2012,20525.0
4606,"Tyler, TX Metro Area",216080.0,53610.0,27734.0,36.2,54209.0,174730.0,22026.0,9675.0,5403.0,...,0.5,<NA>,6449.0,4986.0,2275.0,2022.0,313.0,46340,2013,15526.0
4972,"Tyler, TX Metro Area",218842.0,53239.0,25000.0,36.3,54587.0,178721.0,24562.0,8009.0,3510.0,...,0.6,57.0,5087.0,4560.0,2168.0,1540.0,519.0,46340,2014,12223.0
5460,"Tyler, TX Metro Area",222936.0,53257.0,25684.0,36.4,55292.0,190221.0,15197.0,11106.0,2564.0,...,0.4,275.0,4706.0,3331.0,2335.0,1203.0,503.0,46340,2015,14372.0
6155,"Tyler, TX Metro Area",225290.0,52685.0,22597.0,36.5,55690.0,187591.0,17535.0,12218.0,4018.0,...,0.3,819.0,5157.0,3074.0,4144.0,1929.0,720.0,46340,2016,17338.0
6673,"Tyler, TX Metro Area",227727.0,54767.0,25085.0,37.5,56044.0,198458.0,13748.0,8445.0,4121.0,...,0.5,232.0,4798.0,3389.0,2225.0,1915.0,421.0,46340,2017,13253.0
7192,"Tyler, TX Metro Area",230221.0,54682.0,25784.0,36.7,56559.0,205283.0,10558.0,9005.0,2870.0,...,0.8,164.0,4212.0,2900.0,2638.0,1135.0,442.0,46340,2018,12447.0
7709,"Tyler, TX Metro Area",232751.0,53826.0,27047.0,36.6,56590.0,206124.0,11381.0,8304.0,2578.0,...,0.5,176.0,4213.0,3341.0,2022.0,1299.0,1464.0,46340,2019,12811.0
8222,"Tyler, TX Metro Area",237186.0,56562.0,25715.0,37.4,57702.0,208772.0,14370.0,7613.0,2400.0,...,0.7,<NA>,4190.0,3406.0,2139.0,1407.0,661.0,46340,2021,10981.0
8738,"Tyler, TX Metro Area",241922.0,55528.0,25542.0,37.3,58091.0,215732.0,10347.0,9226.0,3504.0,...,0.5,<NA>,4373.0,2400.0,2599.0,1939.0,458.0,46340,2022,13154.0
9267,"Tyler, TX Metro Area",245209.0,57735.0,26556.0,38.2,58876.0,215472.0,13291.0,8231.0,3498.0,...,0.6,258.0,3949.0,3067.0,2261.0,2084.0,563.0,46340,2023,12421.0
9802,"Tyler, TX Metro Area",249091.0,63609.0,29924.0,37.5,59484.0,212063.0,16864.0,12795.0,4018.0,...,0.4,174.0,5081.0,3688.0,2587.0,1610.0,655.0,46340,2024,17718.0

In [26]:
# Create migration confidence intervals dataframe for Smith County
migration_data_tyler_acs1 = []

for year in tyler_estimates_acs1['year'].unique():
    row = tyler_estimates_acs1[tyler_estimates_acs1['year'] == year].iloc[0]
    
    # have to use this formula to calculate total MOE 
    total_moe = np.sqrt(
        row["moved_from_diff_county_same_state_moe"]**2 +
        row["moved_from_diff_state_moe"]**2 +
        row["moved_from_abroad_moe"]**2
    )
    
    migration_data_tyler_acs1.append({
        'year': year,
        'total_in_migration': row['total_in_migration'],
        'moe': total_moe,
        'lower_bound': row['total_in_migration'] - total_moe,
        'upper_bound': row['total_in_migration'] + total_moe
    })

tyler_migration_moes_acs1 = pd.DataFrame(migration_data_tyler_acs1)
tyler_migration_moes_acs1

    year  total_in_migration          moe   lower_bound   upper_bound
0   2005             16814.0  2996.193752  13817.806248  19810.193752
1   2006             13726.0  2707.226810  11018.773190  16433.226810
2   2007             14573.0  2730.362613  11842.637387  17303.362613
3   2008             14059.0  3383.052616  10675.947384  17442.052616
4   2009             15956.0  3405.246834  12550.753166  19361.246834
5   2010             14361.0  3657.367496  10703.632504  18018.367496
6   2011             19403.0  4321.051955  15081.948045  23724.051955
7   2012             20525.0  4612.667233  15912.332767  25137.667233
8   2013             15526.0  3059.751297  12466.248703  18585.751297
9   2014             12223.0  2709.462124   9513.537876  14932.462124
10  2015             14372.0  2674.405168  11697.594832  17046.405168
11  2016             17338.0  4627.329359  12710.670641  21965.329359
12  2017             13253.0  2965.651868  10287.348132  16218.651868
13  2018             12447.0  2905.620932   9541.379068  15352.620932
14  2019             12811.0  2814.103943   9996.896057  15625.103943
15  2021             10981.0  2644.218410   8336.781590  13625.218410
16  2022             13154.0  3274.795566   9879.204434  16428.795566
17  2023             12421.0  3126.043186   9294.956814  15547.043186
18  2024             17718.0  3116.679964  14601.320036  20834.679964

## ACS 5-year

In [27]:
# filter for metro areas in texas only 
msa_tx_acs5 = df_msa_acs5[df_msa_acs5['name'].str.contains('TX', case=False, na=False)].copy()

# some msa_codes have multiple names
# fix that by aggregating instances where there are multiple rows for the same metro area for the same year
# pick just the most common name
msa_tx_acs5['name'] = msa_tx_acs5.groupby('msa_code')['name'].transform(lambda x: x.mode()[0])

# create column for all people who moved to the area from a different location
msa_tx_acs5['total_in_migration'] = (
    msa_tx_acs5['moved_from_diff_county_same_state'] + 
    msa_tx_acs5['moved_from_diff_state'] + 
    msa_tx_acs5['moved_from_abroad']
)

# aggregate to ensure one row per msa_code per year
msa_tx_agg_acs5 = msa_tx_acs5.groupby(['msa_code', 'name', 'year']).agg({
    'population': 'sum',
    'total_families': 'sum',
    'median_age': 'median',
    'population_under_18': 'sum',
    'family_households_with_child': 'sum'
}).reset_index()

print(msa_tx_acs5['msa_code'].nunique())

73

In [28]:
# use function to create multiple dfs at once, pivoting from original so each column is a year
msa_pivots_acs5 = create_pivot_tables(
    df=msa_tx_agg_acs5,
    index_cols=['msa_code','name'],
    variable_names=['population', 
                    'median_age', 
                    'total_families', 
                    'population_under_18', 
                    'family_households_with_child'])

# extract individual pivot tables
msa_tx_pop_acs5 = msa_pivots_acs5['population']
msa_tx_age_acs5 = msa_pivots_acs5['median_age']
msa_tx_families_acs5 = msa_pivots_acs5['total_families']
msa_tx_under18_acs5 = msa_pivots_acs5['population_under_18']
msa_tx_family_households_with_child_acs5 = msa_pivots_acs5['family_households_with_child']

# create df specifically for migration
# this one is a little different because there are multiple values 
msa_tx_migration_acs5 = msa_tx_acs5.pivot(
    index=['msa_code','name'],
    columns='year',
    values=['lived_in_same_house', 
            'moved_within_county', 
            'moved_from_diff_county_same_state',
            'moved_from_diff_state',
            'moved_from_abroad',
            'total_in_migration']
).reset_index()

# flatten cols so theyre not stacked
msa_tx_migration_acs5.columns = [
    f"{var}_{year}" for var, year in msa_tx_migration_acs5.columns
]

# reset index
msa_tx_migration_acs5 = msa_tx_migration_acs5.reset_index();

In [29]:
msa_tx_acs5['year'].unique()

array([2009, 2014, 2019, 2024])

### Population change (ACS5)

In [30]:
# ACS 5-year population change - only non-overlapping periods are valid
msa_tx_pop_acs5['pct_change_19_24'] = ((msa_tx_pop_acs5[2024] - msa_tx_pop_acs5[2019]) / msa_tx_pop_acs5[2019]) * 100 # 5 years
msa_tx_pop_acs5['pct_change_14_24'] = ((msa_tx_pop_acs5[2024] - msa_tx_pop_acs5[2014]) / msa_tx_pop_acs5[2014]) * 100 # 10 years
msa_tx_pop_acs5['pct_change_09_24'] = ((msa_tx_pop_acs5[2024] - msa_tx_pop_acs5[2009]) / msa_tx_pop_acs5[2009]) * 100 # 15 years

# print ranked results
print_rankings(
    df=msa_tx_pop_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_09_24
0                       Mount Pleasant, TX Micro Area         93.181272
1                    Austin-Round Rock, TX Metro Area         52.674134
2                             Longview, TX Metro Area         43.385555
3                              Midland, TX Metro Area         42.547531
4                              Andrews, TX Micro Area         39.977435
5                College Station-Bryan, TX Metro Area         36.541801
6            San Antonio-New Braunfels, TX Metro Area         34.502795
7                       Killeen-Temple, TX Metro Area         34.088456
8                              Lubbock, TX Metro Area         33.201632
9     Houston-The Woodlands-Sugar Land, TX Metro Area         33.019473
10                                Waco, TX Metro Area         32.261822
11         Dallas-Fort Worth-Arlington, TX Metro Area         29.968846
12                              Odessa, TX Metro Area         27.650634
13                               Paris, TX Micro Area         27.120201
14            McAllen-Edinburg-Mission, TX Metro Area         26.936219
15                          Huntsville, TX Micro Area         25.467714
16                        Stephenville, TX Micro Area         23.523439
17                               Tyler, TX Metro Area         22.318867
18                     Sherman-Denison, TX Metro Area         21.561660
19                             El Paso, TX Metro Area         19.850123
20                      Fredericksburg, TX Micro Area         17.183243
21                              Laredo, TX Metro Area         16.559829
22                            Granbury, TX Micro Area         15.421265
23                             Brenham, TX Micro Area         13.980468
24                              Bonham, TX Micro Area         13.508089
25                             Abilene, TX Metro Area         13.385708
26                          Eagle Pass, TX Micro Area         13.220273
27                           Kerrville, TX Micro Area         12.822189
28                            Amarillo, TX Metro Area         12.427902
29                               Alice, TX Micro Area         12.029064
30                         Gainesville, TX Micro Area         12.028940
31                           Corsicana, TX Micro Area         12.004831
32                          San Angelo, TX Metro Area         11.692100
33                     Sulphur Springs, TX Micro Area         11.575715
34               Brownsville-Harlingen, TX Metro Area         11.208834
35                      Corpus Christi, TX Metro Area          8.584226
36                        Texarkana, TX-AR Metro Area          8.518530
37                Rio Grande City-Roma, TX Micro Area          8.420310
38                        Jacksonville, TX Micro Area          8.003580
39                              Athens, TX Micro Area          7.727071
40                       Mineral Wells, TX Micro Area          6.717424
41                               Dumas, TX Micro Area          6.301602
42                              Lufkin, TX Micro Area          5.832778
43                Beaumont-Port Arthur, TX Metro Area          5.258872
44                           Plainview, TX Micro Area          5.099198
45                         Nacogdoches, TX Micro Area          4.079351
46                           Palestine, TX Micro Area          3.294741
47                              Snyder, TX Micro Area          3.088658
48                            El Campo, TX Micro Area          2.138371
49                            Hereford, TX Micro Area          0.698233
50                       Wichita Falls, TX Metro Area          0.576423
51                             Del Rio, TX Micro Area          0.437591
52                           Brownwood, TX Micro Area          0.319163
53                          Big Spring, TX Micro Area         -0.105185
54                        Raymondville, TX Micro Area         -1.104891
55                          Kingsville, TX Micro Area         -1.272076
56                          Sweetwater, TX Micro Area         -1.800394
57                            Bay City, TX Micro Area         -1.834738
58                               Pampa, TX Micro Area         -3.642530
59                            Beeville, TX Micro Area         -4.103292
60                              Uvalde, TX Micro Area         -6.543215
61                              Borger, TX Micro Area         -6.904663
62                              Vernon, TX Micro Area         -8.080146
63                            Victoria, TX Metro Area        -13.241663
64                              Lamesa, TX Micro Area               NaN
65                           Levelland, TX Micro Area               NaN
66                            Marshall, TX Micro Area               NaN
67                            Pearsall, TX Micro Area               NaN
68                               Pecos, TX Micro Area               NaN
69                         Port Lavaca, TX Micro Area               NaN
70                            Rockport, TX Micro Area               NaN
71                       Town of Pecos, TX Micro Area               NaN
72                              Zapata, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                       Mount Pleasant, TX Micro Area         72.824216
1                             Longview, TX Metro Area         34.278833
2                    Austin-Round Rock, TX Metro Area         32.238193
3                                Paris, TX Micro Area         25.301787
4                              Lubbock, TX Metro Area         20.138791
5     Houston-The Woodlands-Sugar Land, TX Metro Area         19.964843
6          Dallas-Fort Worth-Arlington, TX Metro Area         19.134211
7            San Antonio-New Braunfels, TX Metro Area         18.913310
8                              Midland, TX Metro Area         18.837757
9                       Killeen-Temple, TX Metro Area         18.299923
10               College Station-Bryan, TX Metro Area         18.281375
11                     Sherman-Denison, TX Metro Area         17.513425
12                                Waco, TX Metro Area         17.417130
13                             Andrews, TX Micro Area         15.403696
14                           Corsicana, TX Micro Area         13.808167
15                              Odessa, TX Metro Area         13.607761
16                               Tyler, TX Metro Area         12.575966
17                         Gainesville, TX Micro Area         11.639608
18                        Stephenville, TX Micro Area         11.460640
19                               Alice, TX Micro Area         10.750218
20            McAllen-Edinburg-Mission, TX Metro Area         10.605781
21                      Fredericksburg, TX Micro Area          9.313317
22                             Abilene, TX Metro Area          7.918239
23                             Brenham, TX Micro Area          7.661800
24                              Athens, TX Micro Area          7.643716
25                           Kerrville, TX Micro Area          7.162319
26                     Sulphur Springs, TX Micro Area          6.499803
27                Rio Grande City-Roma, TX Micro Area          6.490974
28                            Amarillo, TX Metro Area          5.788638
29                             El Paso, TX Metro Area          5.678876
30                          San Angelo, TX Metro Area          5.075472
31                       Mineral Wells, TX Micro Area          4.520480
32                          Eagle Pass, TX Micro Area          4.050447
33                           Plainview, TX Micro Area          3.958246
34                              Laredo, TX Metro Area          3.785780
35               Brownsville-Harlingen, TX Metro Area          2.654040
36                      Corpus Christi, TX Metro Area          2.396190
37                            Victoria, TX Metro Area          2.327851
38                        Jacksonville, TX Micro Area          1.795138
39                            El Campo, TX Micro Area          1.394988
40                           Brownwood, TX Micro Area          1.171411
41                           Palestine, TX Micro Area          0.611184
42                              Lufkin, TX Micro Area         -0.180710
43                         Nacogdoches, TX Micro Area         -0.244940
44                            Bay City, TX Micro Area         -0.770260
45                       Wichita Falls, TX Metro Area         -1.219561
46                Beaumont-Port Arthur, TX Metro Area         -1.955325
47                        Texarkana, TX-AR Metro Area         -2.114990
48                             Del Rio, TX Micro Area         -2.567399
49                              Zapata, TX Micro Area         -2.740496
50                               Dumas, TX Micro Area         -3.603644
51                              Snyder, TX Micro Area         -3.624036
52                          Huntsville, TX Micro Area         -3.749970
53                               Pampa, TX Micro Area         -3.926046
54                          Sweetwater, TX Micro Area         -4.163904
55                            Beeville, TX Micro Area         -4.248044
56                            Hereford, TX Micro Area         -4.505716
57                              Vernon, TX Micro Area         -4.892574
58                          Kingsville, TX Micro Area         -6.400367
59                              Uvalde, TX Micro Area         -7.032097
60                         Port Lavaca, TX Micro Area         -7.886318
61                              Borger, TX Micro Area         -8.032989
62                        Raymondville, TX Micro Area         -8.691513
63                          Big Spring, TX Micro Area        -12.474249
64                              Bonham, TX Micro Area               NaN
65                            Granbury, TX Micro Area               NaN
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                                Paris, TX Micro Area         25.536675
1                       Mount Pleasant, TX Micro Area         23.548926
2                    Austin-Round Rock, TX Metro Area         14.762814
3                              Lubbock, TX Metro Area         13.345172
4                             Granbury, TX Micro Area         12.990843
5                                 Waco, TX Metro Area         12.551749
6                            Corsicana, TX Micro Area         11.666497
7                       Killeen-Temple, TX Metro Area         11.163079
8                           Huntsville, TX Micro Area         10.906929
9                            Plainview, TX Micro Area         10.409153
10                     Sherman-Denison, TX Metro Area          9.405865
11         Dallas-Fort Worth-Arlington, TX Metro Area          9.082880
12    Houston-The Woodlands-Sugar Land, TX Metro Area          8.115032
13                              Bonham, TX Micro Area          8.075397
14           San Antonio-New Braunfels, TX Metro Area          7.881880
15               College Station-Bryan, TX Metro Area          7.869658
16                         Gainesville, TX Micro Area          7.504808
17                               Tyler, TX Metro Area          6.283167
18                             Abilene, TX Metro Area          5.706367
19                              Athens, TX Micro Area          4.677439
20                        Stephenville, TX Micro Area          4.667670
21                      Corpus Christi, TX Metro Area          4.541848
22            McAllen-Edinburg-Mission, TX Metro Area          4.303325
23                             Brenham, TX Micro Area          4.220345
24                      Fredericksburg, TX Micro Area          4.025095
25                             El Paso, TX Metro Area          4.010223
26                             Midland, TX Metro Area          3.568716
27                     Sulphur Springs, TX Micro Area          3.557529
28                             Andrews, TX Micro Area          3.182524
29                           Kerrville, TX Micro Area          3.174971
30                Rio Grande City-Roma, TX Micro Area          3.104029
31                            Amarillo, TX Metro Area          3.086331
32                       Mineral Wells, TX Micro Area          2.645410
33                              Odessa, TX Metro Area          2.537692
34                            Longview, TX Metro Area          2.193851
35                           Brownwood, TX Micro Area          1.299696
36                           Palestine, TX Micro Area          1.088047
37               Brownsville-Harlingen, TX Metro Area          1.056286
38                            El Campo, TX Micro Area          0.521923
39                Beaumont-Port Arthur, TX Metro Area          0.418297
40                          San Angelo, TX Metro Area          0.123307
41                              Lufkin, TX Micro Area         -0.053824
42                               Dumas, TX Micro Area         -0.121501
43                          Eagle Pass, TX Micro Area         -0.158146
44                         Nacogdoches, TX Micro Area         -0.270895
45                        Jacksonville, TX Micro Area         -0.445144
46                       Wichita Falls, TX Metro Area         -0.900375
47                            Victoria, TX Metro Area         -1.123663
48                            Bay City, TX Micro Area         -1.210094
49                            Hereford, TX Micro Area         -1.473100
50                              Laredo, TX Metro Area         -1.547202
51                              Vernon, TX Micro Area         -1.690953
52                        Texarkana, TX-AR Metro Area         -2.006805
53                             Del Rio, TX Micro Area         -2.507709
54                          Sweetwater, TX Micro Area         -3.019324
55                          Kingsville, TX Micro Area         -3.053072
56                              Zapata, TX Micro Area         -3.236857
57                              Snyder, TX Micro Area         -3.556387
58                            Beeville, TX Micro Area         -4.685536
59                              Borger, TX Micro Area         -5.434783
60                               Pampa, TX Micro Area         -5.763515
61                        Raymondville, TX Micro Area         -6.712062
62                              Uvalde, TX Micro Area         -7.574294
63                         Port Lavaca, TX Micro Area         -8.307181
64                          Big Spring, TX Micro Area        -11.166745
65                               Alice, TX Micro Area        -12.341118
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN

{'pct_change_09_24': year                              name  pct_change_09_24
 0        Mount Pleasant, TX Micro Area         93.181272
 1     Austin-Round Rock, TX Metro Area         52.674134
 2              Longview, TX Metro Area         43.385555
 3               Midland, TX Metro Area         42.547531
 4               Andrews, TX Micro Area         39.977435
 ..                                 ...               ...
 68                Pecos, TX Micro Area               NaN
 69          Port Lavaca, TX Micro Area               NaN
 70             Rockport, TX Micro Area               NaN
 71        Town of Pecos, TX Micro Area               NaN
 72               Zapata, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_14_24': year                              name  pct_change_14_24
 0        Mount Pleasant, TX Micro Area         72.824216
 1              Longview, TX Metro Area         34.278833
 2     Austin-Round Rock, TX Metro Area         32.238193
 3                 Paris, TX Micro Area         25.301787
 4               Lubbock, TX Metro Area         20.138791
 ..                                 ...               ...
 68             Marshall, TX Micro Area               NaN
 69             Pearsall, TX Micro Area               NaN
 70                Pecos, TX Micro Area               NaN
 71             Rockport, TX Micro Area               NaN
 72        Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_19_24': year                              name  pct_change_19_24
 0                 Paris, TX Micro Area         25.536675
 1        Mount Pleasant, TX Micro Area         23.548926
 2     Austin-Round Rock, TX Metro Area         14.762814
 3               Lubbock, TX Metro Area         13.345172
 4              Granbury, TX Micro Area         12.990843
 ..                                 ...               ...
 68             Marshall, TX Micro Area               NaN
 69             Pearsall, TX Micro Area               NaN
 70                Pecos, TX Micro Area               NaN
 71             Rockport, TX Micro Area               NaN
 72        Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns]}

### Total number of families (ACS5)

In [31]:
# ACS 5-year families change - only non-overlapping periods are valid
msa_tx_families_acs5['pct_change_19_24'] = ((msa_tx_families_acs5[2024] - msa_tx_families_acs5[2019]) / msa_tx_families_acs5[2019]) * 100 # 5 years
msa_tx_families_acs5['pct_change_14_24'] = ((msa_tx_families_acs5[2024] - msa_tx_families_acs5[2014]) / msa_tx_families_acs5[2014]) * 100 # 10 years
msa_tx_families_acs5['pct_change_09_24'] = ((msa_tx_families_acs5[2024] - msa_tx_families_acs5[2009]) / msa_tx_families_acs5[2009]) * 100 # 15 years

# print ranked results
print_rankings(
    df=msa_tx_families_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_09_24
0                       Mount Pleasant, TX Micro Area         89.136381
1                    Austin-Round Rock, TX Metro Area         63.304302
2                             Longview, TX Metro Area         40.776027
3                              Midland, TX Metro Area         40.494172
4            San Antonio-New Braunfels, TX Metro Area         38.397394
5                College Station-Bryan, TX Metro Area         37.811315
6                       Killeen-Temple, TX Metro Area         36.497293
7     Houston-The Woodlands-Sugar Land, TX Metro Area         36.489430
8                         Stephenville, TX Micro Area         36.475153
9                                 Waco, TX Metro Area         35.767456
10         Dallas-Fort Worth-Arlington, TX Metro Area         33.645912
11                              Odessa, TX Metro Area         32.289718
12                             Lubbock, TX Metro Area         28.858173
13                            Granbury, TX Micro Area         27.179026
14                             Andrews, TX Micro Area         25.953417
15                               Paris, TX Micro Area         23.743691
16                              Laredo, TX Metro Area         23.705895
17                          Eagle Pass, TX Micro Area         22.080275
18            McAllen-Edinburg-Mission, TX Metro Area         21.477242
19                     Sherman-Denison, TX Metro Area         21.441164
20                Rio Grande City-Roma, TX Micro Area         20.107518
21                          Huntsville, TX Micro Area         20.080805
22                             El Paso, TX Metro Area         19.704162
23                               Tyler, TX Metro Area         19.648057
24                               Alice, TX Micro Area         19.526920
25                             Brenham, TX Micro Area         18.910832
26                      Fredericksburg, TX Micro Area         18.440893
27                           Corsicana, TX Micro Area         17.729448
28                           Palestine, TX Micro Area         17.181485
29                         Nacogdoches, TX Micro Area         13.538702
30                        Jacksonville, TX Micro Area         13.141026
31               Brownsville-Harlingen, TX Metro Area         11.954309
32                         Gainesville, TX Micro Area         11.845036
33                            Amarillo, TX Metro Area         11.325042
34                              Bonham, TX Micro Area          9.929935
35                     Sulphur Springs, TX Micro Area          9.618304
36                      Corpus Christi, TX Metro Area          8.891754
37                            El Campo, TX Micro Area          8.558985
38                             Del Rio, TX Micro Area          8.409050
39                           Kerrville, TX Micro Area          8.205318
40                             Abilene, TX Metro Area          7.832043
41                              Athens, TX Micro Area          7.058662
42                       Mineral Wells, TX Micro Area          7.043991
43                          San Angelo, TX Metro Area          6.423295
44                              Lufkin, TX Micro Area          5.372536
45                          Kingsville, TX Micro Area          2.164323
46                        Texarkana, TX-AR Metro Area          1.846805
47                           Plainview, TX Micro Area          1.470424
48                Beaumont-Port Arthur, TX Metro Area          0.770277
49                            Hereford, TX Micro Area         -2.223676
50                           Brownwood, TX Micro Area         -2.552889
51                          Big Spring, TX Micro Area         -2.555430
52                        Raymondville, TX Micro Area         -4.105901
53                            Bay City, TX Micro Area         -4.488051
54                               Dumas, TX Micro Area         -4.968203
55                          Sweetwater, TX Micro Area         -6.441948
56                       Wichita Falls, TX Metro Area         -6.876157
57                               Pampa, TX Micro Area         -8.936438
58                              Snyder, TX Micro Area        -10.175358
59                            Beeville, TX Micro Area        -11.811268
60                              Uvalde, TX Micro Area        -15.856970
61                            Victoria, TX Metro Area        -17.130791
62                              Vernon, TX Micro Area        -23.255172
63                              Borger, TX Micro Area        -29.396703
64                              Lamesa, TX Micro Area               NaN
65                           Levelland, TX Micro Area               NaN
66                            Marshall, TX Micro Area               NaN
67                            Pearsall, TX Micro Area               NaN
68                               Pecos, TX Micro Area               NaN
69                         Port Lavaca, TX Micro Area               NaN
70                            Rockport, TX Micro Area               NaN
71                       Town of Pecos, TX Micro Area               NaN
72                              Zapata, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                       Mount Pleasant, TX Micro Area         84.451220
1                    Austin-Round Rock, TX Metro Area         41.080515
2                             Longview, TX Metro Area         40.154296
3                                Paris, TX Micro Area         28.129970
4                              Midland, TX Metro Area         25.530671
5     Houston-The Woodlands-Sugar Land, TX Metro Area         24.038958
6                College Station-Bryan, TX Metro Area         22.474580
7                              Lubbock, TX Metro Area         22.260235
8                       Killeen-Temple, TX Metro Area         22.110084
9                         Stephenville, TX Micro Area         21.090626
10                              Odessa, TX Metro Area         20.910874
11                             Andrews, TX Micro Area         20.701496
12           San Antonio-New Braunfels, TX Metro Area         20.686581
13                                Waco, TX Metro Area         19.757058
14         Dallas-Fort Worth-Arlington, TX Metro Area         19.454948
15                               Alice, TX Micro Area         18.054741
16                             Brenham, TX Micro Area         17.908854
17                     Sherman-Denison, TX Metro Area         17.098350
18                            El Campo, TX Micro Area         16.666667
19            McAllen-Edinburg-Mission, TX Metro Area         15.316338
20                              Laredo, TX Metro Area         14.404221
21                              Athens, TX Micro Area         13.486970
22                Rio Grande City-Roma, TX Micro Area         12.102149
23                           Kerrville, TX Micro Area         11.405977
24                         Port Lavaca, TX Micro Area         10.791616
25                       Mineral Wells, TX Micro Area         10.731500
26                             El Paso, TX Metro Area         10.448167
27               Brownsville-Harlingen, TX Metro Area          9.467530
28                         Gainesville, TX Micro Area          9.304307
29                             Abilene, TX Metro Area          9.145713
30                      Fredericksburg, TX Micro Area          8.840238
31                           Plainview, TX Micro Area          8.337298
32                            Bay City, TX Micro Area          8.293865
33                           Palestine, TX Micro Area          6.739075
34                               Tyler, TX Metro Area          6.666419
35                             Del Rio, TX Micro Area          6.520788
36                          San Angelo, TX Metro Area          6.495501
37                           Corsicana, TX Micro Area          5.693533
38                         Nacogdoches, TX Micro Area          5.562905
39                          Sweetwater, TX Micro Area          5.223252
40                               Pampa, TX Micro Area          4.931109
41                      Corpus Christi, TX Metro Area          4.712810
42                        Jacksonville, TX Micro Area          3.879811
43                            Amarillo, TX Metro Area          3.813799
44                          Eagle Pass, TX Micro Area          3.447217
45                           Brownwood, TX Micro Area          2.756328
46                     Sulphur Springs, TX Micro Area          1.455239
47                          Big Spring, TX Micro Area          1.104757
48                Beaumont-Port Arthur, TX Metro Area          0.589152
49                            Victoria, TX Metro Area         -0.099439
50                       Wichita Falls, TX Metro Area         -0.198424
51                              Lufkin, TX Micro Area         -0.654571
52                          Kingsville, TX Micro Area         -0.948944
53                            Hereford, TX Micro Area         -2.266289
54                        Raymondville, TX Micro Area         -3.346902
55                              Snyder, TX Micro Area         -7.441750
56                        Texarkana, TX-AR Metro Area         -7.509018
57                              Zapata, TX Micro Area         -9.070796
58                          Huntsville, TX Micro Area         -9.403982
59                               Dumas, TX Micro Area         -9.431818
60                              Uvalde, TX Micro Area        -10.091891
61                            Beeville, TX Micro Area        -10.236967
62                              Vernon, TX Micro Area        -17.497034
63                              Borger, TX Micro Area        -20.260257
64                              Bonham, TX Micro Area               NaN
65                            Granbury, TX Micro Area               NaN
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                                Paris, TX Micro Area         28.149383
1                         Stephenville, TX Micro Area         25.466053
2                          Port Lavaca, TX Micro Area         24.556962
3                    Austin-Round Rock, TX Metro Area         24.535135
4                       Mount Pleasant, TX Micro Area         23.563952
5                               Odessa, TX Metro Area         18.790098
6                              Lubbock, TX Metro Area         17.512948
7                              Midland, TX Metro Area         17.396706
8            San Antonio-New Braunfels, TX Metro Area         16.868155
9                      Sherman-Denison, TX Metro Area         16.161275
10                            Granbury, TX Micro Area         15.774559
11                           Plainview, TX Micro Area         15.640472
12                             Brenham, TX Micro Area         15.536690
13                                Waco, TX Metro Area         15.491531
14                Rio Grande City-Roma, TX Micro Area         15.421389
15                             Andrews, TX Micro Area         15.164989
16                       Mineral Wells, TX Micro Area         13.268561
17                      Killeen-Temple, TX Metro Area         12.920848
18    Houston-The Woodlands-Sugar Land, TX Metro Area         10.950988
19         Dallas-Fort Worth-Arlington, TX Metro Area         10.933954
20                      Corpus Christi, TX Metro Area         10.039180
21                             El Paso, TX Metro Area          9.827972
22                           Corsicana, TX Micro Area          9.605572
23               College Station-Bryan, TX Metro Area          9.507003
24                      Fredericksburg, TX Micro Area          9.142698
25                              Athens, TX Micro Area          8.653354
26                            El Campo, TX Micro Area          8.630981
27            McAllen-Edinburg-Mission, TX Metro Area          8.425459
28                             Abilene, TX Metro Area          8.178355
29                          Big Spring, TX Micro Area          8.176888
30                            Longview, TX Metro Area          7.749062
31                           Palestine, TX Micro Area          7.576280
32                              Laredo, TX Metro Area          7.456287
33                               Pampa, TX Micro Area          7.185185
34               Brownsville-Harlingen, TX Metro Area          6.885051
35                         Gainesville, TX Micro Area          6.728281
36                               Tyler, TX Metro Area          6.682246
37                          Huntsville, TX Micro Area          6.430476
38                            Bay City, TX Micro Area          6.154178
39                         Nacogdoches, TX Micro Area          5.367754
40                              Bonham, TX Micro Area          5.105105
41                          San Angelo, TX Metro Area          4.748692
42                             Del Rio, TX Micro Area          3.981545
43                          Kingsville, TX Micro Area          3.911946
44                Beaumont-Port Arthur, TX Metro Area          3.858050
45                     Sulphur Springs, TX Micro Area          3.650159
46                            Victoria, TX Metro Area          3.213611
47                               Alice, TX Micro Area          3.160502
48                          Sweetwater, TX Micro Area          2.545156
49                            Amarillo, TX Metro Area          1.935583
50                       Wichita Falls, TX Metro Area          1.380141
51                        Jacksonville, TX Micro Area          1.237736
52                           Kerrville, TX Micro Area          0.687238
53                          Eagle Pass, TX Micro Area          0.208240
54                              Zapata, TX Micro Area          0.121803
55                           Brownwood, TX Micro Area          0.094024
56                              Lufkin, TX Micro Area         -0.378855
57                            Hereford, TX Micro Area         -0.818222
58                            Beeville, TX Micro Area         -1.216968
59                              Snyder, TX Micro Area         -2.772228
60                        Raymondville, TX Micro Area         -5.526083
61                               Dumas, TX Micro Area         -5.643252
62                        Texarkana, TX-AR Metro Area         -6.733041
63                              Borger, TX Micro Area         -8.025849
64                              Uvalde, TX Micro Area         -9.508356
65                              Vernon, TX Micro Area        -14.452645
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN

{'pct_change_09_24': year                                      name  pct_change_09_24
 0                Mount Pleasant, TX Micro Area         89.136381
 1             Austin-Round Rock, TX Metro Area         63.304302
 2                      Longview, TX Metro Area         40.776027
 3                       Midland, TX Metro Area         40.494172
 4     San Antonio-New Braunfels, TX Metro Area         38.397394
 ..                                         ...               ...
 68                        Pecos, TX Micro Area               NaN
 69                  Port Lavaca, TX Micro Area               NaN
 70                     Rockport, TX Micro Area               NaN
 71                Town of Pecos, TX Micro Area               NaN
 72                       Zapata, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_14_24': year                              name  pct_change_14_24
 0        Mount Pleasant, TX Micro Area         84.451220
 1     Austin-Round Rock, TX Metro Area         41.080515
 2              Longview, TX Metro Area         40.154296
 3                 Paris, TX Micro Area         28.129970
 4               Midland, TX Metro Area         25.530671
 ..                                 ...               ...
 68             Marshall, TX Micro Area               NaN
 69             Pearsall, TX Micro Area               NaN
 70                Pecos, TX Micro Area               NaN
 71             Rockport, TX Micro Area               NaN
 72        Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_19_24': year                              name  pct_change_19_24
 0                 Paris, TX Micro Area         28.149383
 1          Stephenville, TX Micro Area         25.466053
 2           Port Lavaca, TX Micro Area         24.556962
 3     Austin-Round Rock, TX Metro Area         24.535135
 4        Mount Pleasant, TX Micro Area         23.563952
 ..                                 ...               ...
 68             Marshall, TX Micro Area               NaN
 69             Pearsall, TX Micro Area               NaN
 70                Pecos, TX Micro Area               NaN
 71             Rockport, TX Micro Area               NaN
 72        Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns]}

### Median age (ACS5)

In [32]:
# ACS 5-year median age change - only non-overlapping periods are valid
msa_tx_age_acs5['change_19_24'] = (msa_tx_age_acs5[2024] - msa_tx_age_acs5[2019])  # 5 years
msa_tx_age_acs5['change_14_24'] = (msa_tx_age_acs5[2024] - msa_tx_age_acs5[2014])  # 10 years
msa_tx_age_acs5['change_09_24'] = (msa_tx_age_acs5[2024] - msa_tx_age_acs5[2009])  # 15 years

# rank by cities that got the youngest
print("\nMetros by median age change (2009-2024) - ACS5:")
print(msa_tx_age_acs5[msa_tx_age_acs5['change_09_24'].notna()]
      .sort_values(by='change_09_24', ascending=True)
      .reset_index(drop=True)[['name', 'change_09_24', 2009, 2024]])

Metros by median age change (2009-2024) - ACS5:
year                                  name  change_09_24  2009  2024
0                     Pampa, TX Micro Area          -2.1  39.1  37.0
1                   Andrews, TX Micro Area          -1.1  34.1  33.0
2                   Midland, TX Metro Area          -0.5  33.4  32.9
3                   Del Rio, TX Micro Area          -0.1  32.4  32.3
4                Big Spring, TX Micro Area          -0.1  36.8  36.7
..                                     ...           ...   ...   ...
59        Austin-Round Rock, TX Metro Area           4.0  32.0  36.0
60              Nacogdoches, TX Micro Area           4.2  27.7  31.9
61    College Station-Bryan, TX Metro Area           4.6  24.0  28.6
62                   Vernon, TX Micro Area           4.6  35.9  40.5
63           Mount Pleasant, TX Micro Area           5.3  32.1  37.4

[64 rows x 4 columns]

### Total population under 18 (ACS5)

In [33]:
# ACS 5-year population under 18 change - only non-overlapping periods are valid
msa_tx_under18_acs5['pct_change_19_24'] = ((msa_tx_under18_acs5[2024] - msa_tx_under18_acs5[2019]) / msa_tx_under18_acs5[2019]) * 100 # 5 years
msa_tx_under18_acs5['pct_change_14_24'] = ((msa_tx_under18_acs5[2024] - msa_tx_under18_acs5[2014]) / msa_tx_under18_acs5[2014]) * 100 # 10 years
msa_tx_under18_acs5['pct_change_09_24'] = ((msa_tx_under18_acs5[2024] - msa_tx_under18_acs5[2009]) / msa_tx_under18_acs5[2009]) * 100 # 15 years

# print ranked results
print_rankings(
    df=msa_tx_under18_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_09_24
0                       Mount Pleasant, TX Micro Area         64.973557
1                              Midland, TX Metro Area         47.429775
2                              Andrews, TX Micro Area         43.889028
3                             Longview, TX Metro Area         36.023005
4                    Austin-Round Rock, TX Metro Area         32.180747
5                               Odessa, TX Metro Area         29.677737
6                              Lubbock, TX Metro Area         27.487562
7                College Station-Bryan, TX Metro Area         25.731858
8                       Killeen-Temple, TX Metro Area         25.264708
9                                 Waco, TX Metro Area         20.957199
10    Houston-The Woodlands-Sugar Land, TX Metro Area         20.275111
11                               Paris, TX Micro Area         19.073726
12                     Sherman-Denison, TX Metro Area         18.506415
13           San Antonio-New Braunfels, TX Metro Area         18.369015
14         Dallas-Fort Worth-Arlington, TX Metro Area         15.995643
15                               Tyler, TX Metro Area         14.461015
16                          Huntsville, TX Micro Area         12.059191
17                        Stephenville, TX Micro Area         11.011868
18                      Fredericksburg, TX Micro Area         10.560033
19                           Corsicana, TX Micro Area         10.345610
20                          San Angelo, TX Metro Area          9.474085
21                             Abilene, TX Metro Area          9.183568
22            McAllen-Edinburg-Mission, TX Metro Area          8.265988
23                            Amarillo, TX Metro Area          6.610823
24                              Bonham, TX Micro Area          6.281237
25                     Sulphur Springs, TX Micro Area          5.473781
26                        Jacksonville, TX Micro Area          4.970643
27                        Texarkana, TX-AR Metro Area          4.662487
28                             Brenham, TX Micro Area          4.009118
29                Beaumont-Port Arthur, TX Metro Area          3.870641
30                              Snyder, TX Micro Area          3.668580
31                         Nacogdoches, TX Micro Area          2.105051
32                            Granbury, TX Micro Area          1.270868
33                         Gainesville, TX Micro Area         -0.468407
34                             El Paso, TX Metro Area         -1.055823
35                              Athens, TX Micro Area         -1.153679
36                              Lufkin, TX Micro Area         -1.164353
37                               Alice, TX Micro Area         -1.510697
38                               Dumas, TX Micro Area         -1.819258
39                           Palestine, TX Micro Area         -2.175813
40                          Eagle Pass, TX Micro Area         -2.749402
41                              Laredo, TX Metro Area         -2.785187
42                       Mineral Wells, TX Micro Area         -2.853474
43                               Pampa, TX Micro Area         -2.961641
44                            Hereford, TX Micro Area         -3.175134
45                          Sweetwater, TX Micro Area         -4.005236
46                          Big Spring, TX Micro Area         -5.085848
47                      Corpus Christi, TX Metro Area         -5.391745
48                           Kerrville, TX Micro Area         -5.766047
49                           Plainview, TX Micro Area         -5.766635
50                          Kingsville, TX Micro Area         -5.843990
51                            El Campo, TX Micro Area         -5.916740
52                Rio Grande City-Roma, TX Micro Area         -6.096388
53                       Wichita Falls, TX Metro Area         -6.748330
54                             Del Rio, TX Micro Area         -6.998880
55                            Beeville, TX Micro Area         -7.599643
56               Brownsville-Harlingen, TX Metro Area         -8.439767
57                            Bay City, TX Micro Area         -9.521489
58                              Borger, TX Micro Area        -12.275501
59                           Brownwood, TX Micro Area        -15.442846
60                              Uvalde, TX Micro Area        -17.085743
61                            Victoria, TX Metro Area        -21.301297
62                        Raymondville, TX Micro Area        -23.017158
63                              Vernon, TX Micro Area        -27.086699
64                              Lamesa, TX Micro Area               NaN
65                           Levelland, TX Micro Area               NaN
66                            Marshall, TX Micro Area               NaN
67                            Pearsall, TX Micro Area               NaN
68                               Pecos, TX Micro Area               NaN
69                         Port Lavaca, TX Micro Area               NaN
70                            Rockport, TX Micro Area               NaN
71                       Town of Pecos, TX Micro Area               NaN
72                              Zapata, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                       Mount Pleasant, TX Micro Area         55.128471
1                             Longview, TX Metro Area         33.016312
2                              Midland, TX Metro Area         25.830117
3                                Paris, TX Micro Area         23.342939
4                              Andrews, TX Micro Area         21.404471
5                      Sherman-Denison, TX Metro Area         18.197413
6                               Odessa, TX Metro Area         17.678336
7                              Lubbock, TX Metro Area         16.927116
8                    Austin-Round Rock, TX Metro Area         16.533566
9                College Station-Bryan, TX Metro Area         15.265849
10                           Corsicana, TX Micro Area         14.242092
11    Houston-The Woodlands-Sugar Land, TX Metro Area         13.260946
12                      Killeen-Temple, TX Metro Area         12.803821
13                                Waco, TX Metro Area         11.676281
14           San Antonio-New Braunfels, TX Metro Area         10.017217
15         Dallas-Fort Worth-Arlington, TX Metro Area          9.646930
16                      Fredericksburg, TX Micro Area          8.651503
17                               Tyler, TX Metro Area          7.715117
18                             Abilene, TX Metro Area          7.157184
19                        Stephenville, TX Micro Area          7.093957
20                          San Angelo, TX Metro Area          6.704803
21                             Brenham, TX Micro Area          5.122645
22                         Gainesville, TX Micro Area          4.795383
23                Rio Grande City-Roma, TX Micro Area          4.056215
24                              Athens, TX Micro Area          2.888864
25                               Alice, TX Micro Area          2.664283
26                     Sulphur Springs, TX Micro Area          1.730257
27                            Amarillo, TX Metro Area          1.632787
28                Beaumont-Port Arthur, TX Metro Area          0.713540
29            McAllen-Edinburg-Mission, TX Metro Area          0.525837
30                       Mineral Wells, TX Micro Area         -0.190560
31                        Jacksonville, TX Micro Area         -0.419655
32                           Palestine, TX Micro Area         -0.665484
33                         Nacogdoches, TX Micro Area         -0.699850
34                            Bay City, TX Micro Area         -0.727117
35                           Kerrville, TX Micro Area         -1.526718
36                          Eagle Pass, TX Micro Area         -1.788850
37                            El Campo, TX Micro Area         -1.983944
38                            Victoria, TX Metro Area         -2.111741
39                       Wichita Falls, TX Metro Area         -2.495001
40                          Sweetwater, TX Micro Area         -3.423756
41                        Texarkana, TX-AR Metro Area         -4.136701
42                           Plainview, TX Micro Area         -4.186685
43                              Snyder, TX Micro Area         -4.285714
44                              Lufkin, TX Micro Area         -4.363652
45                      Corpus Christi, TX Metro Area         -5.115023
46                               Pampa, TX Micro Area         -5.161290
47                               Dumas, TX Micro Area         -5.481988
48                             El Paso, TX Metro Area         -5.559915
49                              Laredo, TX Metro Area         -6.088324
50                            Hereford, TX Micro Area         -7.162314
51                             Del Rio, TX Micro Area         -7.400697
52               Brownsville-Harlingen, TX Metro Area         -8.757096
53                              Zapata, TX Micro Area         -8.998337
54                          Kingsville, TX Micro Area         -9.188456
55                            Beeville, TX Micro Area         -9.734128
56                           Brownwood, TX Micro Area        -11.997749
57                          Big Spring, TX Micro Area        -12.200698
58                              Uvalde, TX Micro Area        -12.856765
59                              Borger, TX Micro Area        -13.033708
60                          Huntsville, TX Micro Area        -16.533066
61                        Raymondville, TX Micro Area        -16.634531
62                              Vernon, TX Micro Area        -16.651277
63                         Port Lavaca, TX Micro Area        -18.660892
64                              Bonham, TX Micro Area               NaN
65                            Granbury, TX Micro Area               NaN
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                                Paris, TX Micro Area         23.061311
1                       Mount Pleasant, TX Micro Area         16.703040
2                            Corsicana, TX Micro Area         13.504473
3                              Lubbock, TX Metro Area         11.636726
4                      Sherman-Denison, TX Metro Area         10.774920
5                             Granbury, TX Micro Area          9.576892
6                       Killeen-Temple, TX Metro Area          9.523729
7                                 Waco, TX Metro Area          8.288242
8                           Huntsville, TX Micro Area          7.971484
9                               Bonham, TX Micro Area          7.515715
10                   Austin-Round Rock, TX Metro Area          7.271460
11                           Plainview, TX Micro Area          6.125109
12                             Midland, TX Metro Area          6.109617
13               College Station-Bryan, TX Metro Area          5.818074
14    Houston-The Woodlands-Sugar Land, TX Metro Area          4.742141
15                         Gainesville, TX Micro Area          4.575916
16                               Tyler, TX Metro Area          4.415125
17                             Abilene, TX Metro Area          4.299906
18         Dallas-Fort Worth-Arlington, TX Metro Area          4.207934
19                              Athens, TX Micro Area          4.008246
20                        Stephenville, TX Micro Area          3.679579
21           San Antonio-New Braunfels, TX Metro Area          3.354036
22                              Odessa, TX Metro Area          3.225673
23                Beaumont-Port Arthur, TX Metro Area          2.690995
24                       Mineral Wells, TX Micro Area          1.839665
25                Rio Grande City-Roma, TX Micro Area          1.503262
26                             Andrews, TX Micro Area          1.213080
27                     Sulphur Springs, TX Micro Area          0.902090
28                            Amarillo, TX Metro Area          0.796401
29                             Brenham, TX Micro Area          0.727178
30                       Wichita Falls, TX Metro Area          0.588921
31                            Longview, TX Metro Area          0.552275
32                      Fredericksburg, TX Micro Area          0.375235
33                         Nacogdoches, TX Micro Area          0.046129
34                           Palestine, TX Micro Area         -0.471195
35                          San Angelo, TX Metro Area         -0.550459
36                            Hereford, TX Micro Area         -1.227412
37                             El Paso, TX Metro Area         -1.363489
38                               Dumas, TX Micro Area         -1.571767
39                            El Campo, TX Micro Area         -1.666358
40                              Lufkin, TX Micro Area         -1.683892
41                      Corpus Christi, TX Metro Area         -1.751208
42            McAllen-Edinburg-Mission, TX Metro Area         -1.949684
43                        Jacksonville, TX Micro Area         -2.026875
44                            Bay City, TX Micro Area         -2.201622
45                          Eagle Pass, TX Micro Area         -2.335480
46                        Texarkana, TX-AR Metro Area         -2.450786
47                            Victoria, TX Metro Area         -3.128732
48                           Kerrville, TX Micro Area         -3.269346
49                              Snyder, TX Micro Area         -3.372877
50                          Kingsville, TX Micro Area         -4.264725
51                             Del Rio, TX Micro Area         -4.704532
52                          Sweetwater, TX Micro Area         -5.294421
53               Brownsville-Harlingen, TX Metro Area         -5.841183
54                              Vernon, TX Micro Area         -5.841446
55                           Brownwood, TX Micro Area         -6.772386
56                              Laredo, TX Metro Area         -7.396082
57                              Borger, TX Micro Area         -8.293839
58                        Raymondville, TX Micro Area         -8.432807
59                               Pampa, TX Micro Area         -8.618952
60                              Zapata, TX Micro Area         -8.694746
61                          Big Spring, TX Micro Area         -9.196117
62                              Uvalde, TX Micro Area         -9.620392
63                            Beeville, TX Micro Area         -9.982614
64                         Port Lavaca, TX Micro Area        -15.835668
65                               Alice, TX Micro Area        -16.027292
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN

{'pct_change_09_24': year                              name  pct_change_09_24
 0        Mount Pleasant, TX Micro Area         64.973557
 1               Midland, TX Metro Area         47.429775
 2               Andrews, TX Micro Area         43.889028
 3              Longview, TX Metro Area         36.023005
 4     Austin-Round Rock, TX Metro Area         32.180747
 ..                                 ...               ...
 68                Pecos, TX Micro Area               NaN
 69          Port Lavaca, TX Micro Area               NaN
 70             Rockport, TX Micro Area               NaN
 71        Town of Pecos, TX Micro Area               NaN
 72               Zapata, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_14_24': year                           name  pct_change_14_24
 0     Mount Pleasant, TX Micro Area         55.128471
 1           Longview, TX Metro Area         33.016312
 2            Midland, TX Metro Area         25.830117
 3              Paris, TX Micro Area         23.342939
 4            Andrews, TX Micro Area         21.404471
 ..                              ...               ...
 68          Marshall, TX Micro Area               NaN
 69          Pearsall, TX Micro Area               NaN
 70             Pecos, TX Micro Area               NaN
 71          Rockport, TX Micro Area               NaN
 72     Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_19_24': year                            name  pct_change_19_24
 0               Paris, TX Micro Area         23.061311
 1      Mount Pleasant, TX Micro Area         16.703040
 2           Corsicana, TX Micro Area         13.504473
 3             Lubbock, TX Metro Area         11.636726
 4     Sherman-Denison, TX Metro Area         10.774920
 ..                               ...               ...
 68           Marshall, TX Micro Area               NaN
 69           Pearsall, TX Micro Area               NaN
 70              Pecos, TX Micro Area               NaN
 71           Rockport, TX Micro Area               NaN
 72      Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns]}

### Number of family households with children under 18 (ACS5)

In [34]:
# ACS 5-year family households with children change - only non-overlapping periods are valid
msa_tx_family_households_with_child_acs5['pct_change_19_24'] = ((msa_tx_family_households_with_child_acs5[2024] - msa_tx_family_households_with_child_acs5[2019]) / msa_tx_family_households_with_child_acs5[2019]) * 100 # 5 years
msa_tx_family_households_with_child_acs5['pct_change_14_24'] = ((msa_tx_family_households_with_child_acs5[2024] - msa_tx_family_households_with_child_acs5[2014]) / msa_tx_family_households_with_child_acs5[2014]) * 100 # 10 years
msa_tx_family_households_with_child_acs5['pct_change_09_24'] = ((msa_tx_family_households_with_child_acs5[2024] - msa_tx_family_households_with_child_acs5[2009]) / msa_tx_family_households_with_child_acs5[2009]) * 100 # 15 years

# print ranked results
print_rankings(
    df=msa_tx_family_households_with_child_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                                             name  pct_change_09_24
0                       Mount Pleasant, TX Micro Area         64.870932
1                              Midland, TX Metro Area         50.217085
2                    Austin-Round Rock, TX Metro Area         45.012852
3                              Andrews, TX Micro Area         44.867886
4                               Odessa, TX Metro Area         38.185095
5                             Longview, TX Metro Area         36.012646
6                         Stephenville, TX Micro Area         33.699835
7                College Station-Bryan, TX Metro Area         27.649065
8            San Antonio-New Braunfels, TX Metro Area         26.907925
9                       Fredericksburg, TX Micro Area         25.190840
10                      Killeen-Temple, TX Metro Area         24.316198
11    Houston-The Woodlands-Sugar Land, TX Metro Area         23.299162
12                                Waco, TX Metro Area         22.829994
13                             Lubbock, TX Metro Area         21.649574
14         Dallas-Fort Worth-Arlington, TX Metro Area         18.867347
15                Rio Grande City-Roma, TX Micro Area         18.457584
16                            Granbury, TX Micro Area         17.991996
17                               Paris, TX Micro Area         17.568380
18                     Sherman-Denison, TX Metro Area         14.325489
19                               Tyler, TX Metro Area         13.319672
20                               Alice, TX Micro Area         13.150061
21                             Brenham, TX Micro Area         12.464907
22                           Corsicana, TX Micro Area         11.587763
23                           Palestine, TX Micro Area         11.529700
24                          Huntsville, TX Micro Area         11.248261
25                             Del Rio, TX Micro Area         10.605570
26                          Eagle Pass, TX Micro Area         10.120413
27                              Laredo, TX Metro Area          9.736029
28                              Bonham, TX Micro Area          8.829415
29                         Gainesville, TX Micro Area          8.338114
30                              Lufkin, TX Micro Area          6.781694
31                         Nacogdoches, TX Micro Area          5.991823
32            McAllen-Edinburg-Mission, TX Metro Area          5.560617
33                             El Paso, TX Metro Area          4.531120
34                     Sulphur Springs, TX Micro Area          4.207274
35                            Amarillo, TX Metro Area          2.772389
36                              Athens, TX Micro Area          2.535774
37                             Abilene, TX Metro Area          2.035153
38                        Jacksonville, TX Micro Area          0.191174
39                            Hereford, TX Micro Area         -0.781250
40                          Big Spring, TX Micro Area         -0.923361
41                              Snyder, TX Micro Area         -1.002865
42                          San Angelo, TX Metro Area         -1.459400
43                        Texarkana, TX-AR Metro Area         -3.858393
44                Beaumont-Port Arthur, TX Metro Area         -4.185001
45                      Corpus Christi, TX Metro Area         -4.763266
46               Brownsville-Harlingen, TX Metro Area         -7.417928
47                           Plainview, TX Micro Area         -7.512553
48                            El Campo, TX Micro Area         -9.832134
49                          Kingsville, TX Micro Area        -10.536681
50                          Sweetwater, TX Micro Area        -11.360239
51                              Uvalde, TX Micro Area        -12.420470
52                            Beeville, TX Micro Area        -12.768362
53                               Pampa, TX Micro Area        -13.079629
54                       Mineral Wells, TX Micro Area        -13.129399
55                           Kerrville, TX Micro Area        -13.572459
56                            Bay City, TX Micro Area        -15.067709
57                        Raymondville, TX Micro Area        -15.372610
58                       Wichita Falls, TX Metro Area        -17.712993
59                               Dumas, TX Micro Area        -18.024156
60                           Brownwood, TX Micro Area        -19.613948
61                            Victoria, TX Metro Area        -25.989203
62                              Vernon, TX Micro Area        -27.128713
63                              Borger, TX Micro Area        -40.826709
64                              Lamesa, TX Micro Area               NaN
65                           Levelland, TX Micro Area               NaN
66                            Marshall, TX Micro Area               NaN
67                            Pearsall, TX Micro Area               NaN
68                               Pecos, TX Micro Area               NaN
69                         Port Lavaca, TX Micro Area               NaN
70                            Rockport, TX Micro Area               NaN
71                       Town of Pecos, TX Micro Area               NaN
72                              Zapata, TX Micro Area               NaN
year                                             name  pct_change_14_24
0                       Mount Pleasant, TX Micro Area         84.269945
1                             Longview, TX Metro Area         38.118980
2                              Midland, TX Metro Area         36.524613
3                              Andrews, TX Micro Area         29.826958
4                    Austin-Round Rock, TX Metro Area         28.671796
5                                Paris, TX Micro Area         27.368935
6                               Odessa, TX Metro Area         26.910720
7                          Gainesville, TX Micro Area         21.358183
8                                Alice, TX Micro Area         18.721293
9                College Station-Bryan, TX Metro Area         17.736473
10                          Sweetwater, TX Micro Area         16.808930
11                             Lubbock, TX Metro Area         16.644381
12                             Brenham, TX Micro Area         16.318235
13    Houston-The Woodlands-Sugar Land, TX Metro Area         15.749204
14                        Stephenville, TX Micro Area         15.287983
15                      Fredericksburg, TX Micro Area         15.267474
16                     Sherman-Denison, TX Metro Area         15.157585
17                      Killeen-Temple, TX Metro Area         14.194509
18           San Antonio-New Braunfels, TX Metro Area         12.923095
19                                Waco, TX Metro Area         12.695096
20                             Abilene, TX Metro Area         12.105488
21                              Athens, TX Micro Area         12.075906
22                          Big Spring, TX Micro Area         10.249165
23                           Palestine, TX Micro Area         10.083016
24         Dallas-Fort Worth-Arlington, TX Metro Area          9.568275
25                             Del Rio, TX Micro Area          9.471154
26                Rio Grande City-Roma, TX Micro Area          8.666431
27                              Uvalde, TX Micro Area          5.322688
28                          San Angelo, TX Metro Area          5.167196
29                              Snyder, TX Micro Area          4.485887
30            McAllen-Edinburg-Mission, TX Metro Area          4.469210
31                        Jacksonville, TX Micro Area          4.208782
32                              Laredo, TX Metro Area          3.969669
33                               Tyler, TX Metro Area          1.883742
34                       Mineral Wells, TX Micro Area          1.840685
35                            Amarillo, TX Metro Area          1.279719
36                             El Paso, TX Metro Area          0.729175
37                               Pampa, TX Micro Area          0.332226
38                              Lufkin, TX Micro Area         -0.025916
39                           Corsicana, TX Micro Area         -0.305390
40                Beaumont-Port Arthur, TX Metro Area         -0.306563
41                            El Campo, TX Micro Area         -0.346585
42                         Port Lavaca, TX Micro Area         -0.371609
43                           Plainview, TX Micro Area         -1.298434
44                         Nacogdoches, TX Micro Area         -1.364471
45                            Bay City, TX Micro Area         -1.916300
46                            Beeville, TX Micro Area         -2.123613
47                           Kerrville, TX Micro Area         -2.182783
48                          Eagle Pass, TX Micro Area         -3.054013
49                          Huntsville, TX Micro Area         -3.629518
50                            Hereford, TX Micro Area         -5.011219
51                           Brownwood, TX Micro Area         -5.073529
52                      Corpus Christi, TX Metro Area         -5.704686
53               Brownsville-Harlingen, TX Metro Area         -5.762072
54                     Sulphur Springs, TX Micro Area         -6.980692
55                       Wichita Falls, TX Metro Area         -7.529971
56                            Victoria, TX Metro Area         -7.903264
57                        Texarkana, TX-AR Metro Area         -9.971798
58                          Kingsville, TX Micro Area         -9.982660
59                              Vernon, TX Micro Area        -10.516717
60                               Dumas, TX Micro Area        -11.382658
61                        Raymondville, TX Micro Area        -13.894403
62                              Zapata, TX Micro Area        -17.505198
63                              Borger, TX Micro Area        -32.548025
64                              Bonham, TX Micro Area               NaN
65                            Granbury, TX Micro Area               NaN
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN
year                                             name  pct_change_19_24
0                                Paris, TX Micro Area         29.928583
1                              Midland, TX Metro Area         25.802200
2                              Brenham, TX Micro Area         25.422668
3                               Odessa, TX Metro Area         24.344176
4                         Stephenville, TX Micro Area         23.892002
5                       Fredericksburg, TX Micro Area         22.591362
6                       Mount Pleasant, TX Micro Area         22.111388
7                    Austin-Round Rock, TX Metro Area         18.788698
8                 Rio Grande City-Roma, TX Micro Area         18.442360
9                            Palestine, TX Micro Area         17.435424
10                              Bonham, TX Micro Area         17.372538
11                             Andrews, TX Micro Area         17.132293
12                         Gainesville, TX Micro Area         15.612245
13                           Plainview, TX Micro Area         14.459847
14                            Bay City, TX Micro Area         14.443588
15                       Mineral Wells, TX Micro Area         14.321340
16           San Antonio-New Braunfels, TX Metro Area         14.133625
17                          Big Spring, TX Micro Area         13.906582
18                           Corsicana, TX Micro Area         11.283450
19                              Athens, TX Micro Area         10.952977
20                            Granbury, TX Micro Area         10.836875
21                               Alice, TX Micro Area         10.537119
22                             Lubbock, TX Metro Area         10.465362
23                      Killeen-Temple, TX Metro Area          9.701094
24                     Sherman-Denison, TX Metro Area          9.456715
25                                Waco, TX Metro Area          9.377278
26                            Longview, TX Metro Area          8.820641
27                             El Paso, TX Metro Area          7.945123
28                             Abilene, TX Metro Area          7.076436
29                               Tyler, TX Metro Area          6.744140
30    Houston-The Woodlands-Sugar Land, TX Metro Area          6.355973
31                         Port Lavaca, TX Micro Area          6.304520
32               College Station-Bryan, TX Metro Area          5.919692
33         Dallas-Fort Worth-Arlington, TX Metro Area          5.738794
34                          Huntsville, TX Micro Area          5.402734
35                             Del Rio, TX Micro Area          5.238022
36                              Uvalde, TX Micro Area          4.869162
37                Beaumont-Port Arthur, TX Metro Area          4.019360
38                               Pampa, TX Micro Area          3.938815
39                            Beeville, TX Micro Area          3.589400
40                              Snyder, TX Micro Area          3.443114
41                              Vernon, TX Micro Area          3.225806
42                          San Angelo, TX Metro Area          3.179316
43                            Hereford, TX Micro Area          2.584814
44                            Victoria, TX Metro Area          2.516055
45                              Laredo, TX Metro Area          2.132720
46            McAllen-Edinburg-Mission, TX Metro Area          2.014978
47                      Corpus Christi, TX Metro Area          1.409201
48                        Jacksonville, TX Micro Area          0.898444
49                          Sweetwater, TX Micro Area          0.281849
50                       Wichita Falls, TX Metro Area         -0.083572
51                            Amarillo, TX Metro Area         -0.342871
52                              Zapata, TX Micro Area         -1.342616
53                         Nacogdoches, TX Micro Area         -1.712642
54                               Dumas, TX Micro Area         -2.719588
55                              Lufkin, TX Micro Area         -3.542257
56               Brownsville-Harlingen, TX Metro Area         -4.277097
57                     Sulphur Springs, TX Micro Area         -4.529617
58                          Eagle Pass, TX Micro Area         -5.101915
59                        Texarkana, TX-AR Metro Area         -6.005556
60                          Kingsville, TX Micro Area         -6.388460
61                        Raymondville, TX Micro Area         -7.544757
62                            El Campo, TX Micro Area         -8.873975
63                              Borger, TX Micro Area         -9.528439
64                           Brownwood, TX Micro Area        -11.595526
65                           Kerrville, TX Micro Area        -18.076200
66                              Lamesa, TX Micro Area               NaN
67                           Levelland, TX Micro Area               NaN
68                            Marshall, TX Micro Area               NaN
69                            Pearsall, TX Micro Area               NaN
70                               Pecos, TX Micro Area               NaN
71                            Rockport, TX Micro Area               NaN
72                       Town of Pecos, TX Micro Area               NaN

{'pct_change_09_24': year                              name  pct_change_09_24
 0        Mount Pleasant, TX Micro Area         64.870932
 1               Midland, TX Metro Area         50.217085
 2     Austin-Round Rock, TX Metro Area         45.012852
 3               Andrews, TX Micro Area         44.867886
 4                Odessa, TX Metro Area         38.185095
 ..                                 ...               ...
 68                Pecos, TX Micro Area               NaN
 69          Port Lavaca, TX Micro Area               NaN
 70             Rockport, TX Micro Area               NaN
 71        Town of Pecos, TX Micro Area               NaN
 72               Zapata, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_14_24': year                              name  pct_change_14_24
 0        Mount Pleasant, TX Micro Area         84.269945
 1              Longview, TX Metro Area         38.118980
 2               Midland, TX Metro Area         36.524613
 3               Andrews, TX Micro Area         29.826958
 4     Austin-Round Rock, TX Metro Area         28.671796
 ..                                 ...               ...
 68             Marshall, TX Micro Area               NaN
 69             Pearsall, TX Micro Area               NaN
 70                Pecos, TX Micro Area               NaN
 71             Rockport, TX Micro Area               NaN
 72        Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns],
 'pct_change_19_24': year                          name  pct_change_19_24
 0             Paris, TX Micro Area         29.928583
 1           Midland, TX Metro Area         25.802200
 2           Brenham, TX Micro Area         25.422668
 3            Odessa, TX Metro Area         24.344176
 4      Stephenville, TX Micro Area         23.892002
 ..                             ...               ...
 68         Marshall, TX Micro Area               NaN
 69         Pearsall, TX Micro Area               NaN
 70            Pecos, TX Micro Area               NaN
 71         Rockport, TX Micro Area               NaN
 72    Town of Pecos, TX Micro Area               NaN

 [73 rows x 2 columns]}

### Migration to Texas MSAs (ACS5)

In [35]:
# ACS 5-year migration change - only non-overlapping periods are valid
msa_tx_migration_acs5['pct_chg_migration_09_24'] = ((msa_tx_migration_acs5['total_in_migration_2024'] - msa_tx_migration_acs5['total_in_migration_2009']) / msa_tx_migration_acs5['total_in_migration_2009'] * 100)
msa_tx_migration_acs5['pct_chg_migration_14_24'] = ((msa_tx_migration_acs5['total_in_migration_2024'] - msa_tx_migration_acs5['total_in_migration_2014']) / msa_tx_migration_acs5['total_in_migration_2014'] * 100)
msa_tx_migration_acs5['pct_chg_migration_19_24'] = ((msa_tx_migration_acs5['total_in_migration_2024'] - msa_tx_migration_acs5['total_in_migration_2019']) / msa_tx_migration_acs5['total_in_migration_2019'] * 100)

# Print ranked results
print_rankings(
    df=msa_tx_migration_acs5,
    name_col='name_',
    variable_names=['pct_chg_migration_09_24', 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

                                              name_  pct_chg_migration_09_24
0                            Andrews, TX Micro Area                80.529595
1                       Jacksonville, TX Micro Area                76.741071
2                            Midland, TX Metro Area                65.308151
3                    Sherman-Denison, TX Metro Area                58.253558
4                       Stephenville, TX Micro Area                53.927987
5                             Odessa, TX Metro Area                47.248085
6                            Brenham, TX Micro Area                46.729958
7                           El Campo, TX Micro Area                36.303030
8                  Austin-Round Rock, TX Metro Area                35.685288
9                            Lubbock, TX Metro Area                35.356608
10                    Mount Pleasant, TX Micro Area                29.406221
11                             Paris, TX Micro Area                29.366736
12         San Antonio-New Braunfels, TX Metro Area                28.881521
13                         Brownwood, TX Micro Area                28.429818
14                           Del Rio, TX Micro Area                23.654749
15             College Station-Bryan, TX Metro Area                20.642996
16                              Waco, TX Metro Area                20.137503
17                           El Paso, TX Metro Area                16.115277
18       Dallas-Fort Worth-Arlington, TX Metro Area                15.548170
19  Houston-The Woodlands-Sugar Land, TX Metro Area                13.832953
20              Rio Grande City-Roma, TX Micro Area                11.310905
21                     Mineral Wells, TX Micro Area                10.825295
22                        Eagle Pass, TX Micro Area                 8.752475
23                          Bay City, TX Micro Area                 8.143608
24                            Bonham, TX Micro Area                 6.729356
25                          Longview, TX Metro Area                 4.792725
26                      Raymondville, TX Micro Area                 2.362869
27                         Kerrville, TX Micro Area                 1.853123
28                            Lufkin, TX Micro Area                 1.601557
29                    Killeen-Temple, TX Metro Area                 1.006211
30                        Huntsville, TX Micro Area                -4.000310
31                    Fredericksburg, TX Micro Area                -4.195323
32                             Alice, TX Micro Area                -4.491816
33             Brownsville-Harlingen, TX Metro Area                -4.858693
34              Beaumont-Port Arthur, TX Metro Area                -4.898740
35                     Wichita Falls, TX Metro Area                -6.423815
36                          Granbury, TX Micro Area                -7.016161
37                            Athens, TX Micro Area                -8.485026
38                         Plainview, TX Micro Area                -8.919844
39                            Snyder, TX Micro Area               -10.058542
40                             Tyler, TX Metro Area               -10.179132
41                             Pampa, TX Micro Area               -10.676835
42                         Palestine, TX Micro Area               -12.395437
43                   Sulphur Springs, TX Micro Area               -13.330530
44                        Kingsville, TX Micro Area               -15.584804
45          McAllen-Edinburg-Mission, TX Metro Area               -18.093505
46                       Nacogdoches, TX Micro Area               -18.723404
47                           Abilene, TX Metro Area               -19.637056
48                          Amarillo, TX Metro Area               -19.750394
49                        San Angelo, TX Metro Area               -19.875891
50                          Beeville, TX Micro Area               -20.410407
51                         Corsicana, TX Micro Area               -23.807339
52                        Sweetwater, TX Micro Area               -23.954704
53                    Corpus Christi, TX Metro Area               -24.735566
54                      Texarkana, TX-AR Metro Area               -26.684974
55                            Borger, TX Micro Area               -29.453441
56                            Uvalde, TX Micro Area               -29.904441
57                          Victoria, TX Metro Area               -32.952236
58                       Gainesville, TX Micro Area               -36.324664
59                        Big Spring, TX Micro Area               -43.367474
60                            Laredo, TX Metro Area               -45.106875
61                             Dumas, TX Micro Area               -51.355579
62                            Vernon, TX Micro Area               -57.344633
63                          Hereford, TX Micro Area               -74.340021
64                            Lamesa, TX Micro Area                      NaN
65                         Levelland, TX Micro Area                      NaN
66                          Marshall, TX Micro Area                      NaN
67                          Pearsall, TX Micro Area                      NaN
68                             Pecos, TX Micro Area                      NaN
69                       Port Lavaca, TX Micro Area                      NaN
70                          Rockport, TX Micro Area                      NaN
71                     Town of Pecos, TX Micro Area                      NaN
72                            Zapata, TX Micro Area                      NaN
                                              name_  pct_chg_migration_14_24
0                           El Campo, TX Micro Area               111.372180
1                            Brenham, TX Micro Area               108.754377
2                          Brownwood, TX Micro Area                77.382256
3                           Bay City, TX Micro Area                75.550817
4                    Sherman-Denison, TX Metro Area                65.713899
5                       Stephenville, TX Micro Area                50.319659
6                             Lufkin, TX Micro Area                38.728796
7                     Mount Pleasant, TX Micro Area                36.007925
8                          Corsicana, TX Micro Area                28.163580
9                  Austin-Round Rock, TX Metro Area                25.892466
10                      Jacksonville, TX Micro Area                25.722452
11                             Paris, TX Micro Area                25.016812
12                              Waco, TX Metro Area                24.715092
13         San Antonio-New Braunfels, TX Metro Area                24.680870
14                           Midland, TX Metro Area                23.714664
15       Dallas-Fort Worth-Arlington, TX Metro Area                23.616986
16                             Alice, TX Micro Area                22.270955
17  Houston-The Woodlands-Sugar Land, TX Metro Area                19.277837
18                        Huntsville, TX Micro Area                19.193378
19                         Kerrville, TX Micro Area                17.343173
20                        Kingsville, TX Micro Area                16.659777
21                            Odessa, TX Metro Area                15.322134
22                            Athens, TX Micro Area                15.316315
23                            Zapata, TX Micro Area                12.614679
24                        Eagle Pass, TX Micro Area                12.494879
25                    Killeen-Temple, TX Metro Area                11.534166
26                     Mineral Wells, TX Micro Area                11.422414
27                           Del Rio, TX Micro Area                10.988655
28             Brownsville-Harlingen, TX Metro Area                10.474847
29                            Snyder, TX Micro Area                10.313316
30             College Station-Bryan, TX Metro Area                10.096640
31                           Lubbock, TX Metro Area                 8.681957
32                            Borger, TX Micro Area                 6.331045
33                    Fredericksburg, TX Micro Area                -1.275691
34          McAllen-Edinburg-Mission, TX Metro Area                -1.539160
35                          Longview, TX Metro Area                -1.902759
36                         Palestine, TX Micro Area                -1.924059
37                     Wichita Falls, TX Metro Area                -2.556084
38                           Andrews, TX Micro Area                -5.464927
39                           El Paso, TX Metro Area                -7.333729
40                           Abilene, TX Metro Area                -9.333333
41                       Nacogdoches, TX Micro Area               -10.124469
42              Beaumont-Port Arthur, TX Metro Area               -10.197911
43                   Sulphur Springs, TX Micro Area               -11.048770
44                      Texarkana, TX-AR Metro Area               -11.807456
45                          Victoria, TX Metro Area               -13.219336
46                             Tyler, TX Metro Area               -13.258413
47              Rio Grande City-Roma, TX Micro Area               -14.100269
48                          Amarillo, TX Metro Area               -14.276469
49                         Plainview, TX Micro Area               -16.359964
50                          Beeville, TX Micro Area               -22.150538
51                       Port Lavaca, TX Micro Area               -22.910217
52                        Sweetwater, TX Micro Area               -24.415584
53                        Big Spring, TX Micro Area               -25.890814
54                       Gainesville, TX Micro Area               -26.127321
55                    Corpus Christi, TX Metro Area               -29.825057
56                             Pampa, TX Micro Area               -30.360461
57                            Uvalde, TX Micro Area               -31.746032
58                        San Angelo, TX Metro Area               -35.498061
59                      Raymondville, TX Micro Area               -35.547290
60                            Laredo, TX Metro Area               -45.484796
61                             Dumas, TX Micro Area               -47.078843
62                            Vernon, TX Micro Area               -59.335727
63                          Hereford, TX Micro Area               -79.716194
64                            Bonham, TX Micro Area                      NaN
65                          Granbury, TX Micro Area                      NaN
66                            Lamesa, TX Micro Area                      NaN
67                         Levelland, TX Micro Area                      NaN
68                          Marshall, TX Micro Area                      NaN
69                          Pearsall, TX Micro Area                      NaN
70                             Pecos, TX Micro Area                      NaN
71                          Rockport, TX Micro Area                      NaN
72                     Town of Pecos, TX Micro Area                      NaN
                                              name_  pct_chg_migration_19_24
0                              Dumas, TX Micro Area                84.752475
1                           Bay City, TX Micro Area                61.649215
2                             Snyder, TX Micro Area                57.943925
3                          Brownwood, TX Micro Area                48.373798
4                            Brenham, TX Micro Area                47.612310
5                         Huntsville, TX Micro Area                42.759972
6                              Paris, TX Micro Area                41.154138
7                           Beeville, TX Micro Area                39.364774
8                          Kerrville, TX Micro Area                39.299124
9               Rio Grande City-Roma, TX Micro Area                38.057554
10                      Stephenville, TX Micro Area                34.389140
11                          El Campo, TX Micro Area                32.998226
12             Brownsville-Harlingen, TX Metro Area                30.486450
13                         Plainview, TX Micro Area                29.185442
14                      Jacksonville, TX Micro Area                28.957655
15                   Sherman-Denison, TX Metro Area                24.369662
16                 Austin-Round Rock, TX Metro Area                21.976262
17                            Borger, TX Micro Area                19.349315
18                    Mount Pleasant, TX Micro Area                17.955326
19         San Antonio-New Braunfels, TX Metro Area                17.596817
20                            Athens, TX Micro Area                16.807195
21                            Lufkin, TX Micro Area                14.933965
22                        Eagle Pass, TX Micro Area                13.050638
23                         Corsicana, TX Micro Area                11.738984
24                            Odessa, TX Metro Area                10.205522
25                             Alice, TX Micro Area                 9.707040
26       Dallas-Fort Worth-Arlington, TX Metro Area                 8.386520
27  Houston-The Woodlands-Sugar Land, TX Metro Area                 8.126305
28                              Waco, TX Metro Area                 8.042882
29                    Killeen-Temple, TX Metro Area                 7.579337
30          McAllen-Edinburg-Mission, TX Metro Area                 6.689023
31                          Victoria, TX Metro Area                 6.111781
32             College Station-Bryan, TX Metro Area                 5.234401
33                          Granbury, TX Micro Area                 4.611973
34                      Texarkana, TX-AR Metro Area                 4.053452
35                         Palestine, TX Micro Area                 3.709039
36                             Pampa, TX Micro Area                 3.250689
37                   Sulphur Springs, TX Micro Area                 1.078960
38              Beaumont-Port Arthur, TX Metro Area                 0.118203
39                     Wichita Falls, TX Metro Area                -0.891931
40                           Lubbock, TX Metro Area                -1.627423
41                           Andrews, TX Micro Area                -4.687500
42                       Nacogdoches, TX Micro Area                -5.460642
43                             Tyler, TX Metro Area                -6.212028
44                           Del Rio, TX Micro Area                -6.345733
45                           Midland, TX Metro Area                -6.817333
46                      Raymondville, TX Micro Area                -7.192043
47                           El Paso, TX Metro Area                -8.590547
48                     Mineral Wells, TX Micro Area                -8.858528
49                          Amarillo, TX Metro Area               -11.180152
50                        San Angelo, TX Metro Area               -14.261645
51                            Uvalde, TX Micro Area               -14.764183
52                        Kingsville, TX Micro Area               -15.153337
53                    Corpus Christi, TX Metro Area               -16.107836
54                          Longview, TX Metro Area               -16.334985
55                           Abilene, TX Metro Area               -16.967593
56                            Bonham, TX Micro Area               -17.191062
57                    Fredericksburg, TX Micro Area               -23.671233
58                            Laredo, TX Metro Area               -25.286995
59                            Zapata, TX Micro Area               -27.900147
60                       Gainesville, TX Micro Area               -31.593491
61                        Sweetwater, TX Micro Area               -33.052147
62                        Big Spring, TX Micro Area               -39.368815
63                       Port Lavaca, TX Micro Area               -43.537415
64                            Vernon, TX Micro Area               -50.814332
65                          Hereford, TX Micro Area               -65.035971
66                            Lamesa, TX Micro Area                      NaN
67                         Levelland, TX Micro Area                      NaN
68                          Marshall, TX Micro Area                      NaN
69                          Pearsall, TX Micro Area                      NaN
70                             Pecos, TX Micro Area                      NaN
71                          Rockport, TX Micro Area                      NaN
72                     Town of Pecos, TX Micro Area                      NaN

{'pct_chg_migration_09_24':                              name_  pct_chg_migration_09_24
 0           Andrews, TX Micro Area                80.529595
 1      Jacksonville, TX Micro Area                76.741071
 2           Midland, TX Metro Area                65.308151
 3   Sherman-Denison, TX Metro Area                58.253558
 4      Stephenville, TX Micro Area                53.927987
 ..                             ...                      ...
 68            Pecos, TX Micro Area                      NaN
 69      Port Lavaca, TX Micro Area                      NaN
 70         Rockport, TX Micro Area                      NaN
 71    Town of Pecos, TX Micro Area                      NaN
 72           Zapata, TX Micro Area                      NaN

 [73 rows x 2 columns],
 'pct_chg_migration_14_24':                              name_  pct_chg_migration_14_24
 0          El Campo, TX Micro Area               111.372180
 1           Brenham, TX Micro Area               108.754377
 2         Brownwood, TX Micro Area                77.382256
 3          Bay City, TX Micro Area                75.550817
 4   Sherman-Denison, TX Metro Area                65.713899
 ..                             ...                      ...
 68         Marshall, TX Micro Area                      NaN
 69         Pearsall, TX Micro Area                      NaN
 70            Pecos, TX Micro Area                      NaN
 71         Rockport, TX Micro Area                      NaN
 72    Town of Pecos, TX Micro Area                      NaN

 [73 rows x 2 columns],
 'pct_chg_migration_19_24':                            name_  pct_chg_migration_19_24
 0           Dumas, TX Micro Area                84.752475
 1        Bay City, TX Micro Area                61.649215
 2          Snyder, TX Micro Area                57.943925
 3       Brownwood, TX Micro Area                48.373798
 4         Brenham, TX Micro Area                47.612310
 ..                           ...                      ...
 68       Marshall, TX Micro Area                      NaN
 69       Pearsall, TX Micro Area                      NaN
 70          Pecos, TX Micro Area                      NaN
 71       Rockport, TX Micro Area                      NaN
 72  Town of Pecos, TX Micro Area                      NaN

 [73 rows x 2 columns]}

## ACS5 margins of error

In [36]:
tyler_estimates_acs5 = msa_tx_acs5[msa_tx_acs5['name'] == 'Tyler, TX Metro Area'].copy()
tyler_estimates_acs5

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,median_age_moe,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,msa_code,year,total_in_migration
444,"Tyler, TX Metro Area",197631.0,48076.0,23912.0,35.7,51096.0,155721.0,23260.0,10612.0,3891.0,...,0.1,0.0,2186.0,1915.0,1195.0,848.0,322.0,46340,2009,15296.0
1607,"Tyler, TX Metro Area",214735.0,53927.0,26596.0,36.0,54296.0,172408.0,23577.0,10885.0,4206.0,...,0.2,<NA>,1791.0,1568.0,1188.0,762.0,304.0,46340,2014,15839.0
2549,"Tyler, TX Metro Area",227449.0,53919.0,25385.0,36.6,56012.0,195995.0,14368.0,10144.0,3540.0,...,0.2,<NA>,2119.0,1645.0,1281.0,809.0,352.0,46340,2019,14649.0
3679,"Tyler, TX Metro Area",241740.0,57522.0,27097.0,37.5,58485.0,210107.0,14964.0,9982.0,3187.0,...,0.3,<NA>,2237.0,1753.0,1160.0,737.0,222.0,46340,2024,13739.0

In [37]:
# Create migration confidence intervals dataframe for Smith County
migration_data_tyler_acs5 = []

for year in tyler_estimates_acs5['year'].unique():
    row = tyler_estimates_acs5[tyler_estimates_acs5['year'] == year].iloc[0]
    
    # Calculate total MOE
    total_moe = np.sqrt(
        row["moved_from_diff_county_same_state_moe"]**2 +
        row["moved_from_diff_state_moe"]**2 +
        row["moved_from_abroad_moe"]**2
    )
    
    migration_data_tyler_acs5.append({
        'year': year,
        'total_in_migration': row['total_in_migration'],
        'moe': total_moe,
        'lower_bound': row['total_in_migration'] - total_moe,
        'upper_bound': row['total_in_migration'] + total_moe
    })

tyler_migration_moes_acs5 = pd.DataFrame(migration_data_tyler_acs5)
tyler_migration_moes_acs5

   year  total_in_migration          moe   lower_bound   upper_bound
0  2009             15296.0  1500.270976  13795.729024  16796.270976
1  2014             15839.0  1443.746515  14395.253485  17282.746515
2  2019             14649.0  1555.424701  13093.575299  16204.424701
3  2024             13739.0  1392.139720  12346.860280  15131.139720

# County-level analysis

## ACS 1-year

In [38]:
# We already created tx_counties
# Use helper function to create multiple pivot tables at once
county_pivots = create_pivot_tables(
    df=tx_counties,
    index_cols=['county_code','name'],
    variable_names=['population', 'median_age', 'total_families', 'population_under_18', 'family_households_with_child']
)

tx_counties['total_in_migration'] = (
    tx_counties['moved_from_diff_county_same_state'] + 
    tx_counties['moved_from_diff_state'] + 
    tx_counties['moved_from_abroad']
)

county_tx_pop = county_pivots['population']
county_tx_age = county_pivots['median_age']
county_tx_families = county_pivots['total_families']
county_tx_under18 = county_pivots['population_under_18']
county_tx_family_households_with_child = county_pivots['family_households_with_child']

tx_counties_migration = tx_counties.pivot(
    index=['county_code','name'],
    columns='year',
    values=['lived_in_same_house', 
            'moved_within_county', 
            'moved_from_diff_county_same_state',
            'moved_from_diff_state',
            'moved_from_abroad',
            'total_in_migration']
) 

# flatten cols so theyre not stacked
tx_counties_migration.columns = [
    f"{var}_{year}" for var, year in tx_counties_migration.columns
]

# reset index
tx_counties_migration = tx_counties_migration.reset_index();

### County Population Change Analysis

In [39]:
# create columns for population change in the past 5, 10, 15 and 19 years (2005–2024)
county_tx_pop['pct_change_19_24'] = ((county_tx_pop[2024] - county_tx_pop[2019]) / county_tx_pop[2019]) * 100 # 5 years
county_tx_pop['pct_change_14_24'] = ((county_tx_pop[2024] - county_tx_pop[2014]) / county_tx_pop[2014]) * 100 # 10 years
county_tx_pop['pct_change_09_24'] = ((county_tx_pop[2024] - county_tx_pop[2009]) / county_tx_pop[2009]) * 100 # 15 years
county_tx_pop['pct_change_05_24'] = ((county_tx_pop[2024] - county_tx_pop[2005]) / county_tx_pop[2005]) * 100 # 19 years

# Print ranked results
print_rankings(
    df=county_tx_pop,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                        name  pct_change_05_24
0             Hays County, Texas        153.872033
1          Kaufman County, Texas        125.690491
2       Williamson County, Texas        121.508369
3            Comal County, Texas        112.701226
4        Fort Bend County, Texas        109.619771
5       Montgomery County, Texas         99.338122
6        Guadalupe County, Texas         92.783200
7           Denton County, Texas         91.937353
8           Collin County, Texas         91.260591
9          Bastrop County, Texas         86.201478
10          Parker County, Texas         79.984176
11           Ellis County, Texas         76.747034
12          Brazos County, Texas         73.951583
13         Liberty County, Texas         64.073821
14            Bell County, Texas         62.040131
15          Travis County, Texas         57.415430
16        Brazoria County, Texas         54.547903
17         Midland County, Texas         53.346976
18            Hunt County, Texas         48.314845
19         Coryell County, Texas         46.563720
20         Johnson County, Texas         46.460346
21           Bexar County, Texas         43.514088
22         Tarrant County, Texas         39.793635
23         Randall County, Texas         38.902780
24           Ector County, Texas         37.858284
25          Harris County, Texas         37.329342
26         Hidalgo County, Texas         36.140614
27         Lubbock County, Texas         35.316412
28       Galveston County, Texas         34.501505
29           Smith County, Texas         34.306203
30         Grayson County, Texas         32.162706
31        McLennan County, Texas         25.992861
32          Taylor County, Texas         25.322543
33         El Paso County, Texas         23.642596
34            Webb County, Texas         23.182889
35       Tom Green County, Texas         21.098429
36          Dallas County, Texas         17.156342
37         Cameron County, Texas         15.449328
38         Wichita County, Texas         13.373630
39           Gregg County, Texas         12.746869
40          Nueces County, Texas         12.652130
41        Angelina County, Texas         11.739114
42       Henderson County, Texas         11.077669
43       Jefferson County, Texas          9.786391
44           Bowie County, Texas          9.758629
45        Victoria County, Texas          9.405787
46    San Patricio County, Texas          4.979655
47          Orange County, Texas          2.522739
48          Potter County, Texas          2.473141
49        Harrison County, Texas               NaN
50            Hood County, Texas               NaN
51     Nacogdoches County, Texas               NaN
52        Rockwall County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_09_24
0          Kaufman County, Texas         91.996157
1             Hays County, Texas         87.745668
2       Williamson County, Texas         77.137765
3            Comal County, Texas         76.055883
4        Fort Bend County, Texas         72.110906
5         Rockwall County, Texas         68.377339
6       Montgomery County, Texas         67.429721
7        Guadalupe County, Texas         60.720403
8           Denton County, Texas         58.684271
9           Collin County, Texas         58.490256
10          Parker County, Texas         56.377100
11         Bastrop County, Texas         53.495112
12           Ellis County, Texas         53.151176
13         Liberty County, Texas         51.812507
14            Hunt County, Texas         43.338847
15            Bell County, Texas         39.816717
16         Midland County, Texas         38.748904
17          Brazos County, Texas         38.686164
18         Johnson County, Texas         34.108932
19        Brazoria County, Texas         33.639492
20          Travis County, Texas         32.900294
21         Randall County, Texas         29.243752
22           Bexar County, Texas         28.840690
23       Galveston County, Texas         28.099395
24           Ector County, Texas         26.293036
25         Grayson County, Texas         25.411980
26         Tarrant County, Texas         24.627521
27         Hidalgo County, Texas         23.432170
28          Harris County, Texas         23.048773
29           Smith County, Texas         21.706691
30         Lubbock County, Texas         21.010534
31         Coryell County, Texas         19.083401
32         El Paso County, Texas         16.569767
33          Taylor County, Texas         16.548797
34        McLennan County, Texas         15.845538
35            Webb County, Texas         12.999196
36       Henderson County, Texas         10.828550
37       Tom Green County, Texas         10.818616
38          Nueces County, Texas          9.311058
39         Cameron County, Texas          8.957012
40          Dallas County, Texas          8.332810
41           Gregg County, Texas          5.886139
42        Angelina County, Texas          5.281147
43          Orange County, Texas          5.254473
44    San Patricio County, Texas          4.754995
45        Victoria County, Texas          4.737442
46       Jefferson County, Texas          4.403524
47         Wichita County, Texas          1.855567
48           Bowie County, Texas         -2.098676
49          Potter County, Texas         -5.883464
50        Harrison County, Texas               NaN
51            Hood County, Texas               NaN
52     Nacogdoches County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_14_24
0          Kaufman County, Texas         77.846201
1            Comal County, Texas         63.005481
2             Hays County, Texas         57.832185
3         Rockwall County, Texas         56.070562
4       Williamson County, Texas         48.692897
5          Liberty County, Texas         47.268840
6          Bastrop County, Texas         47.217205
7           Parker County, Texas         45.908707
8            Ellis County, Texas         45.864534
9       Montgomery County, Texas         44.448855
10          Collin County, Texas         41.730670
11       Fort Bend County, Texas         39.846938
12          Denton County, Texas         38.727280
13            Hunt County, Texas         34.167674
14         Johnson County, Texas         33.717991
15       Guadalupe County, Texas         32.540577
16        Brazoria County, Texas         22.210787
17         Grayson County, Texas         21.854712
18            Bell County, Texas         21.400620
19          Walker County, Texas         19.964464
20          Brazos County, Texas         19.350520
21          Travis County, Texas         18.470479
22         Midland County, Texas         17.812360
23         Randall County, Texas         17.413040
24       Galveston County, Texas         16.934863
25         Tarrant County, Texas         14.668133
26           Bexar County, Texas         14.649280
27         Coryell County, Texas         14.303486
28           Smith County, Texas         13.822301
29          Harris County, Texas         12.787316
30         Lubbock County, Texas         11.368352
31        McLennan County, Texas         11.056889
32           Ector County, Texas         10.472762
33       Henderson County, Texas         10.312776
34          Taylor County, Texas         10.115211
35         Hidalgo County, Texas         10.076973
36    San Patricio County, Texas          6.802660
37        Harrison County, Texas          5.990852
38          Dallas County, Texas          5.454932
39         El Paso County, Texas          5.074704
40          Orange County, Texas          3.214555
41       Tom Green County, Texas          2.997221
42           Gregg County, Texas          2.820525
43         Cameron County, Texas          2.731260
44            Webb County, Texas          2.306195
45        Victoria County, Texas          0.952998
46       Jefferson County, Texas          0.679129
47     Nacogdoches County, Texas          0.653895
48        Angelina County, Texas          0.392023
49          Nueces County, Texas         -0.869123
50           Bowie County, Texas         -1.375503
51         Wichita County, Texas         -1.791394
52          Potter County, Texas         -5.737213
53            Hood County, Texas               NaN
54           Starr County, Texas               NaN
55       Van Zandt County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_19_24
0          Kaufman County, Texas         45.297971
1         Rockwall County, Texas         30.623838
2          Liberty County, Texas         30.405015
3          Bastrop County, Texas         29.539127
4            Comal County, Texas         29.075789
5             Hays County, Texas         26.863778
6           Parker County, Texas         25.776537
7            Ellis County, Texas         25.732851
8       Montgomery County, Texas         23.415230
9       Williamson County, Texas         23.186651
10          Collin County, Texas         21.254627
11            Hunt County, Texas         20.422135
12         Johnson County, Texas         19.753494
13       Fort Bend County, Texas         18.079114
14          Denton County, Texas         17.798890
15       Guadalupe County, Texas         16.973035
16            Wise County, Texas         16.133688
17          Walker County, Texas         14.733250
18         Coryell County, Texas         13.718055
19         Grayson County, Texas         10.513024
20        Brazoria County, Texas         10.409764
21            Bell County, Texas         10.099635
22         Randall County, Texas          9.319382
23          Brazos County, Texas          8.905768
24          Taylor County, Texas          7.808946
25       Galveston County, Texas          7.385302
26        Harrison County, Texas          7.237841
27    San Patricio County, Texas          7.098756
28          Travis County, Texas          7.049941
29           Smith County, Texas          7.020378
30          Harris County, Texas          6.279580
31           Bexar County, Texas          6.198136
32         Tarrant County, Texas          6.097127
33       Henderson County, Texas          5.716910
34         Lubbock County, Texas          5.417476
35        McLennan County, Texas          5.352209
36         Hidalgo County, Texas          5.308234
37         El Paso County, Texas          4.354665
38         Midland County, Texas          3.820010
39          Orange County, Texas          3.260348
40           Ector County, Texas          2.285484
41           Gregg County, Texas          2.205817
42         Cameron County, Texas          2.058545
43        Angelina County, Texas          1.590267
44       Jefferson County, Texas          0.947270
45     Nacogdoches County, Texas          0.803632
46          Dallas County, Texas          0.778292
47       Tom Green County, Texas          0.757550
48        Victoria County, Texas         -0.146605
49           Bowie County, Texas         -1.343772
50            Webb County, Texas         -1.384049
51         Wichita County, Texas         -1.698556
52          Potter County, Texas         -2.355747
53          Nueces County, Texas         -2.530818
54            Hood County, Texas               NaN
55           Starr County, Texas               NaN
56       Van Zandt County, Texas               NaN
57          Waller County, Texas               NaN

{'pct_change_05_24': year                        name  pct_change_05_24
 0             Hays County, Texas        153.872033
 1          Kaufman County, Texas        125.690491
 2       Williamson County, Texas        121.508369
 3            Comal County, Texas        112.701226
 4        Fort Bend County, Texas        109.619771
 5       Montgomery County, Texas         99.338122
 6        Guadalupe County, Texas         92.783200
 7           Denton County, Texas         91.937353
 8           Collin County, Texas         91.260591
 9          Bastrop County, Texas         86.201478
 10          Parker County, Texas         79.984176
 11           Ellis County, Texas         76.747034
 12          Brazos County, Texas         73.951583
 13         Liberty County, Texas         64.073821
 14            Bell County, Texas         62.040131
 15          Travis County, Texas         57.415430
 16        Brazoria County, Texas         54.547903
 17         Midland County, Texas         53.346976
 18            Hunt County, Texas         48.314845
 19         Coryell County, Texas         46.563720
 20         Johnson County, Texas         46.460346
 21           Bexar County, Texas         43.514088
 22         Tarrant County, Texas         39.793635
 23         Randall County, Texas         38.902780
 24           Ector County, Texas         37.858284
 25          Harris County, Texas         37.329342
 26         Hidalgo County, Texas         36.140614
 27         Lubbock County, Texas         35.316412
 28       Galveston County, Texas         34.501505
 29           Smith County, Texas         34.306203
 30         Grayson County, Texas         32.162706
 31        McLennan County, Texas         25.992861
 32          Taylor County, Texas         25.322543
 33         El Paso County, Texas         23.642596
 34            Webb County, Texas         23.182889
 35       Tom Green County, Texas         21.098429
 36          Dallas County, Texas         17.156342
 37         Cameron County, Texas         15.449328
 38         Wichita County, Texas         13.373630
 39           Gregg County, Texas         12.746869
 40          Nueces County, Texas         12.652130
 41        Angelina County, Texas         11.739114
 42       Henderson County, Texas         11.077669
 43       Jefferson County, Texas          9.786391
 44           Bowie County, Texas          9.758629
 45        Victoria County, Texas          9.405787
 46    San Patricio County, Texas          4.979655
 47          Orange County, Texas          2.522739
 48          Potter County, Texas          2.473141
 49        Harrison County, Texas               NaN
 50            Hood County, Texas               NaN
 51     Nacogdoches County, Texas               NaN
 52        Rockwall County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_09_24': year                        name  pct_change_09_24
 0          Kaufman County, Texas         91.996157
 1             Hays County, Texas         87.745668
 2       Williamson County, Texas         77.137765
 3            Comal County, Texas         76.055883
 4        Fort Bend County, Texas         72.110906
 5         Rockwall County, Texas         68.377339
 6       Montgomery County, Texas         67.429721
 7        Guadalupe County, Texas         60.720403
 8           Denton County, Texas         58.684271
 9           Collin County, Texas         58.490256
 10          Parker County, Texas         56.377100
 11         Bastrop County, Texas         53.495112
 12           Ellis County, Texas         53.151176
 13         Liberty County, Texas         51.812507
 14            Hunt County, Texas         43.338847
 15            Bell County, Texas         39.816717
 16         Midland County, Texas         38.748904
 17          Brazos County, Texas         38.686164
 18         Johnson County, Texas         34.108932
 19        Brazoria County, Texas         33.639492
 20          Travis County, Texas         32.900294
 21         Randall County, Texas         29.243752
 22           Bexar County, Texas         28.840690
 23       Galveston County, Texas         28.099395
 24           Ector County, Texas         26.293036
 25         Grayson County, Texas         25.411980
 26         Tarrant County, Texas         24.627521
 27         Hidalgo County, Texas         23.432170
 28          Harris County, Texas         23.048773
 29           Smith County, Texas         21.706691
 30         Lubbock County, Texas         21.010534
 31         Coryell County, Texas         19.083401
 32         El Paso County, Texas         16.569767
 33          Taylor County, Texas         16.548797
 34        McLennan County, Texas         15.845538
 35            Webb County, Texas         12.999196
 36       Henderson County, Texas         10.828550
 37       Tom Green County, Texas         10.818616
 38          Nueces County, Texas          9.311058
 39         Cameron County, Texas          8.957012
 40          Dallas County, Texas          8.332810
 41           Gregg County, Texas          5.886139
 42        Angelina County, Texas          5.281147
 43          Orange County, Texas          5.254473
 44    San Patricio County, Texas          4.754995
 45        Victoria County, Texas          4.737442
 46       Jefferson County, Texas          4.403524
 47         Wichita County, Texas          1.855567
 48           Bowie County, Texas         -2.098676
 49          Potter County, Texas         -5.883464
 50        Harrison County, Texas               NaN
 51            Hood County, Texas               NaN
 52     Nacogdoches County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_14_24': year                        name  pct_change_14_24
 0          Kaufman County, Texas         77.846201
 1            Comal County, Texas         63.005481
 2             Hays County, Texas         57.832185
 3         Rockwall County, Texas         56.070562
 4       Williamson County, Texas         48.692897
 5          Liberty County, Texas         47.268840
 6          Bastrop County, Texas         47.217205
 7           Parker County, Texas         45.908707
 8            Ellis County, Texas         45.864534
 9       Montgomery County, Texas         44.448855
 10          Collin County, Texas         41.730670
 11       Fort Bend County, Texas         39.846938
 12          Denton County, Texas         38.727280
 13            Hunt County, Texas         34.167674
 14         Johnson County, Texas         33.717991
 15       Guadalupe County, Texas         32.540577
 16        Brazoria County, Texas         22.210787
 17         Grayson County, Texas         21.854712
 18            Bell County, Texas         21.400620
 19          Walker County, Texas         19.964464
 20          Brazos County, Texas         19.350520
 21          Travis County, Texas         18.470479
 22         Midland County, Texas         17.812360
 23         Randall County, Texas         17.413040
 24       Galveston County, Texas         16.934863
 25         Tarrant County, Texas         14.668133
 26           Bexar County, Texas         14.649280
 27         Coryell County, Texas         14.303486
 28           Smith County, Texas         13.822301
 29          Harris County, Texas         12.787316
 30         Lubbock County, Texas         11.368352
 31        McLennan County, Texas         11.056889
 32           Ector County, Texas         10.472762
 33       Henderson County, Texas         10.312776
 34          Taylor County, Texas         10.115211
 35         Hidalgo County, Texas         10.076973
 36    San Patricio County, Texas          6.802660
 37        Harrison County, Texas          5.990852
 38          Dallas County, Texas          5.454932
 39         El Paso County, Texas          5.074704
 40          Orange County, Texas          3.214555
 41       Tom Green County, Texas          2.997221
 42           Gregg County, Texas          2.820525
 43         Cameron County, Texas          2.731260
 44            Webb County, Texas          2.306195
 45        Victoria County, Texas          0.952998
 46       Jefferson County, Texas          0.679129
 47     Nacogdoches County, Texas          0.653895
 48        Angelina County, Texas          0.392023
 49          Nueces County, Texas         -0.869123
 50           Bowie County, Texas         -1.375503
 51         Wichita County, Texas         -1.791394
 52          Potter County, Texas         -5.737213
 53            Hood County, Texas               NaN
 54           Starr County, Texas               NaN
 55       Van Zandt County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_19_24': year                        name  pct_change_19_24
 0          Kaufman County, Texas         45.297971
 1         Rockwall County, Texas         30.623838
 2          Liberty County, Texas         30.405015
 3          Bastrop County, Texas         29.539127
 4            Comal County, Texas         29.075789
 5             Hays County, Texas         26.863778
 6           Parker County, Texas         25.776537
 7            Ellis County, Texas         25.732851
 8       Montgomery County, Texas         23.415230
 9       Williamson County, Texas         23.186651
 10          Collin County, Texas         21.254627
 11            Hunt County, Texas         20.422135
 12         Johnson County, Texas         19.753494
 13       Fort Bend County, Texas         18.079114
 14          Denton County, Texas         17.798890
 15       Guadalupe County, Texas         16.973035
 16            Wise County, Texas         16.133688
 17          Walker County, Texas         14.733250
 18         Coryell County, Texas         13.718055
 19         Grayson County, Texas         10.513024
 20        Brazoria County, Texas         10.409764
 21            Bell County, Texas         10.099635
 22         Randall County, Texas          9.319382
 23          Brazos County, Texas          8.905768
 24          Taylor County, Texas          7.808946
 25       Galveston County, Texas          7.385302
 26        Harrison County, Texas          7.237841
 27    San Patricio County, Texas          7.098756
 28          Travis County, Texas          7.049941
 29           Smith County, Texas          7.020378
 30          Harris County, Texas          6.279580
 31           Bexar County, Texas          6.198136
 32         Tarrant County, Texas          6.097127
 33       Henderson County, Texas          5.716910
 34         Lubbock County, Texas          5.417476
 35        McLennan County, Texas          5.352209
 36         Hidalgo County, Texas          5.308234
 37         El Paso County, Texas          4.354665
 38         Midland County, Texas          3.820010
 39          Orange County, Texas          3.260348
 40           Ector County, Texas          2.285484
 41           Gregg County, Texas          2.205817
 42         Cameron County, Texas          2.058545
 43        Angelina County, Texas          1.590267
 44       Jefferson County, Texas          0.947270
 45     Nacogdoches County, Texas          0.803632
 46          Dallas County, Texas          0.778292
 47       Tom Green County, Texas          0.757550
 48        Victoria County, Texas         -0.146605
 49           Bowie County, Texas         -1.343772
 50            Webb County, Texas         -1.384049
 51         Wichita County, Texas         -1.698556
 52          Potter County, Texas         -2.355747
 53          Nueces County, Texas         -2.530818
 54            Hood County, Texas               NaN
 55           Starr County, Texas               NaN
 56       Van Zandt County, Texas               NaN
 57          Waller County, Texas               NaN}

### Number of families

In [40]:
# create columns for percentage change in the number of families
county_tx_families['pct_change_19_24'] = ((county_tx_families[2024] - county_tx_families[2019]) / county_tx_families[2019]) * 100 # 5 years
county_tx_families['pct_change_14_24'] = ((county_tx_families[2024] - county_tx_families[2014]) / county_tx_families[2014]) * 100 # 10 years
county_tx_families['pct_change_09_24'] = ((county_tx_families[2024] - county_tx_families[2009]) / county_tx_families[2009]) * 100 # 15 years
county_tx_families['pct_change_05_24'] = ((county_tx_families[2024] - county_tx_families[2005]) / county_tx_families[2005]) * 100 # 19 years

# Print ranked results
print_rankings(
    df=county_tx_families,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                        name  pct_change_05_24
0             Hays County, Texas        159.685109
1       Williamson County, Texas        132.381552
2        Fort Bend County, Texas        131.091559
3            Comal County, Texas        115.406545
4           Denton County, Texas        110.410813
5       Montgomery County, Texas        104.294636
6           Collin County, Texas         96.455155
7          Bastrop County, Texas         94.159602
8        Guadalupe County, Texas         87.060608
9            Ellis County, Texas         81.301542
10         Kaufman County, Texas         75.400483
11          Brazos County, Texas         73.852683
12          Travis County, Texas         65.761376
13          Parker County, Texas         59.610080
14         Midland County, Texas         58.895340
15            Bell County, Texas         52.034514
16            Hunt County, Texas         50.854432
17         Liberty County, Texas         50.777810
18         Johnson County, Texas         49.156446
19        Brazoria County, Texas         46.112742
20           Ector County, Texas         45.382840
21       Galveston County, Texas         41.737175
22           Bexar County, Texas         41.005562
23         Coryell County, Texas         36.430678
24         Randall County, Texas         34.058274
25         Tarrant County, Texas         33.335234
26          Harris County, Texas         32.734430
27           Smith County, Texas         32.100432
28         Hidalgo County, Texas         31.659117
29         Grayson County, Texas         31.413051
30            Webb County, Texas         31.302993
31        McLennan County, Texas         27.839561
32         Cameron County, Texas         24.123877
33         El Paso County, Texas         24.052988
34         Lubbock County, Texas         19.686158
35           Gregg County, Texas         19.151684
36       Tom Green County, Texas         16.055729
37          Nueces County, Texas         14.149966
38        Angelina County, Texas         13.825955
39          Dallas County, Texas         12.305047
40    San Patricio County, Texas         10.801776
41       Henderson County, Texas          4.742914
42          Orange County, Texas          2.287230
43          Taylor County, Texas          1.269334
44         Wichita County, Texas          0.355940
45       Jefferson County, Texas          0.117878
46        Victoria County, Texas         -4.438238
47           Bowie County, Texas         -8.430523
48          Potter County, Texas        -13.379803
49        Harrison County, Texas               NaN
50            Hood County, Texas               NaN
51     Nacogdoches County, Texas               NaN
52        Rockwall County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_09_24
0             Hays County, Texas        135.861027
1        Fort Bend County, Texas         94.471838
2       Williamson County, Texas         93.061823
3           Denton County, Texas         84.710658
4       Montgomery County, Texas         74.819809
5            Comal County, Texas         73.804947
6          Kaufman County, Texas         73.121074
7         Rockwall County, Texas         72.750978
8          Bastrop County, Texas         68.040997
9           Parker County, Texas         67.857143
10       Guadalupe County, Texas         67.739474
11          Collin County, Texas         64.147650
12           Ellis County, Texas         59.889759
13            Hunt County, Texas         51.081160
14            Bell County, Texas         49.861231
15          Brazos County, Texas         43.693069
16          Travis County, Texas         43.140861
17         Midland County, Texas         42.585187
18         Liberty County, Texas         39.161294
19           Ector County, Texas         37.612674
20           Bexar County, Texas         37.466520
21         Johnson County, Texas         36.304559
22         Randall County, Texas         34.800589
23           Smith County, Texas         33.865774
24        Brazoria County, Texas         30.814656
25       Galveston County, Texas         26.773329
26        McLennan County, Texas         24.313860
27         Hidalgo County, Texas         22.650166
28         Tarrant County, Texas         21.970432
29         Grayson County, Texas         21.904043
30          Harris County, Texas         21.543652
31         El Paso County, Texas         19.861828
32         Cameron County, Texas         18.711725
33           Gregg County, Texas         18.523277
34            Webb County, Texas         18.480782
35         Coryell County, Texas         18.453067
36         Lubbock County, Texas         18.248744
37        Angelina County, Texas         17.026461
38          Nueces County, Texas         16.268156
39    San Patricio County, Texas         16.235484
40          Dallas County, Texas          9.469790
41       Tom Green County, Texas          8.607286
42       Henderson County, Texas          8.550731
43          Taylor County, Texas          7.540102
44          Orange County, Texas          1.617750
45        Victoria County, Texas         -1.805660
46         Wichita County, Texas         -2.944431
47       Jefferson County, Texas         -4.763183
48           Bowie County, Texas         -9.709216
49          Potter County, Texas        -13.368020
50        Harrison County, Texas               NaN
51            Hood County, Texas               NaN
52     Nacogdoches County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_14_24
0             Hays County, Texas         72.708502
1            Comal County, Texas         72.597553
2       Williamson County, Texas         57.529478
3            Ellis County, Texas         53.478346
4       Montgomery County, Texas         49.903526
5          Bastrop County, Texas         48.980329
6          Liberty County, Texas         48.640046
7             Hunt County, Texas         47.428680
8          Kaufman County, Texas         46.268711
9         Rockwall County, Texas         46.115831
10          Denton County, Texas         45.123446
11       Fort Bend County, Texas         45.094990
12          Collin County, Texas         40.951498
13          Parker County, Texas         39.007207
14          Travis County, Texas         36.624392
15         Midland County, Texas         36.016118
16          Walker County, Texas         31.151301
17          Brazos County, Texas         28.968176
18       Guadalupe County, Texas         28.039206
19           Ector County, Texas         26.884007
20            Bell County, Texas         24.751885
21       Galveston County, Texas         23.831052
22         Grayson County, Texas         22.912864
23       Tom Green County, Texas         21.533900
24    San Patricio County, Texas         21.247376
25         Johnson County, Texas         21.123138
26           Bexar County, Texas         20.865388
27        Brazoria County, Texas         20.171443
28           Smith County, Texas         19.478202
29        Harrison County, Texas         16.784295
30         Cameron County, Texas         15.919089
31         Coryell County, Texas         15.437414
32         Hidalgo County, Texas         15.303163
33          Harris County, Texas         15.245833
34         Tarrant County, Texas         14.824503
35         El Paso County, Texas         14.066662
36        McLennan County, Texas         13.130489
37            Webb County, Texas         12.207100
38           Gregg County, Texas         12.153300
39        Angelina County, Texas         11.052023
40         Wichita County, Texas         11.014238
41         Randall County, Texas         10.392331
42     Nacogdoches County, Texas         10.027767
43       Henderson County, Texas          9.377099
44         Lubbock County, Texas          7.822055
45          Orange County, Texas          5.284258
46          Dallas County, Texas          3.914703
47          Nueces County, Texas          2.899562
48       Jefferson County, Texas          0.242698
49        Victoria County, Texas         -2.618214
50          Taylor County, Texas         -3.441138
51           Bowie County, Texas         -3.844640
52          Potter County, Texas         -6.739640
53            Hood County, Texas               NaN
54           Starr County, Texas               NaN
55       Van Zandt County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_19_24
0          Bastrop County, Texas         47.555737
1       Williamson County, Texas         36.748852
2     San Patricio County, Texas         36.120649
3             Hays County, Texas         34.484937
4          Liberty County, Texas         32.369615
5             Hunt County, Texas         30.505067
6          Midland County, Texas         29.895585
7            Ellis County, Texas         29.366341
8           Denton County, Texas         29.221657
9          Grayson County, Texas         26.996951
10           Comal County, Texas         26.434384
11         Kaufman County, Texas         25.191868
12      Montgomery County, Texas         25.061465
13          Parker County, Texas         23.945578
14           Ector County, Texas         22.841429
15       Fort Bend County, Texas         21.818350
16          Collin County, Texas         21.788433
17           Gregg County, Texas         21.215684
18         Coryell County, Texas         21.017858
19           Bexar County, Texas         20.004333
20          Walker County, Texas         19.482398
21            Wise County, Texas         19.340433
22        Rockwall County, Texas         18.617374
23           Smith County, Texas         18.175231
24       Guadalupe County, Texas         18.008870
25            Bell County, Texas         17.421346
26       Henderson County, Texas         16.949964
27         Johnson County, Texas         15.976808
28          Travis County, Texas         15.850974
29         Randall County, Texas         14.129725
30         El Paso County, Texas         13.805472
31          Brazos County, Texas         13.574038
32     Nacogdoches County, Texas         12.556488
33        Brazoria County, Texas         12.173365
34       Galveston County, Texas         10.646893
35         Cameron County, Texas         10.502835
36         Hidalgo County, Texas         10.221556
37        Harrison County, Texas         10.060924
38       Tom Green County, Texas          9.573720
39         Wichita County, Texas          7.426433
40         Lubbock County, Texas          7.260689
41        Victoria County, Texas          7.190361
42          Orange County, Texas          7.148748
43         Tarrant County, Texas          6.977628
44          Harris County, Texas          6.575807
45        McLennan County, Texas          5.310864
46       Jefferson County, Texas          4.525757
47            Webb County, Texas          2.840207
48          Dallas County, Texas          1.827127
49          Nueces County, Texas          1.719112
50          Taylor County, Texas          1.486584
51        Angelina County, Texas         -3.573580
52          Potter County, Texas         -6.328136
53           Bowie County, Texas         -8.178097
54            Hood County, Texas               NaN
55           Starr County, Texas               NaN
56       Van Zandt County, Texas               NaN
57          Waller County, Texas               NaN

{'pct_change_05_24': year                        name  pct_change_05_24
 0             Hays County, Texas        159.685109
 1       Williamson County, Texas        132.381552
 2        Fort Bend County, Texas        131.091559
 3            Comal County, Texas        115.406545
 4           Denton County, Texas        110.410813
 5       Montgomery County, Texas        104.294636
 6           Collin County, Texas         96.455155
 7          Bastrop County, Texas         94.159602
 8        Guadalupe County, Texas         87.060608
 9            Ellis County, Texas         81.301542
 10         Kaufman County, Texas         75.400483
 11          Brazos County, Texas         73.852683
 12          Travis County, Texas         65.761376
 13          Parker County, Texas         59.610080
 14         Midland County, Texas         58.895340
 15            Bell County, Texas         52.034514
 16            Hunt County, Texas         50.854432
 17         Liberty County, Texas         50.777810
 18         Johnson County, Texas         49.156446
 19        Brazoria County, Texas         46.112742
 20           Ector County, Texas         45.382840
 21       Galveston County, Texas         41.737175
 22           Bexar County, Texas         41.005562
 23         Coryell County, Texas         36.430678
 24         Randall County, Texas         34.058274
 25         Tarrant County, Texas         33.335234
 26          Harris County, Texas         32.734430
 27           Smith County, Texas         32.100432
 28         Hidalgo County, Texas         31.659117
 29         Grayson County, Texas         31.413051
 30            Webb County, Texas         31.302993
 31        McLennan County, Texas         27.839561
 32         Cameron County, Texas         24.123877
 33         El Paso County, Texas         24.052988
 34         Lubbock County, Texas         19.686158
 35           Gregg County, Texas         19.151684
 36       Tom Green County, Texas         16.055729
 37          Nueces County, Texas         14.149966
 38        Angelina County, Texas         13.825955
 39          Dallas County, Texas         12.305047
 40    San Patricio County, Texas         10.801776
 41       Henderson County, Texas          4.742914
 42          Orange County, Texas          2.287230
 43          Taylor County, Texas          1.269334
 44         Wichita County, Texas          0.355940
 45       Jefferson County, Texas          0.117878
 46        Victoria County, Texas         -4.438238
 47           Bowie County, Texas         -8.430523
 48          Potter County, Texas        -13.379803
 49        Harrison County, Texas               NaN
 50            Hood County, Texas               NaN
 51     Nacogdoches County, Texas               NaN
 52        Rockwall County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_09_24': year                        name  pct_change_09_24
 0             Hays County, Texas        135.861027
 1        Fort Bend County, Texas         94.471838
 2       Williamson County, Texas         93.061823
 3           Denton County, Texas         84.710658
 4       Montgomery County, Texas         74.819809
 5            Comal County, Texas         73.804947
 6          Kaufman County, Texas         73.121074
 7         Rockwall County, Texas         72.750978
 8          Bastrop County, Texas         68.040997
 9           Parker County, Texas         67.857143
 10       Guadalupe County, Texas         67.739474
 11          Collin County, Texas         64.147650
 12           Ellis County, Texas         59.889759
 13            Hunt County, Texas         51.081160
 14            Bell County, Texas         49.861231
 15          Brazos County, Texas         43.693069
 16          Travis County, Texas         43.140861
 17         Midland County, Texas         42.585187
 18         Liberty County, Texas         39.161294
 19           Ector County, Texas         37.612674
 20           Bexar County, Texas         37.466520
 21         Johnson County, Texas         36.304559
 22         Randall County, Texas         34.800589
 23           Smith County, Texas         33.865774
 24        Brazoria County, Texas         30.814656
 25       Galveston County, Texas         26.773329
 26        McLennan County, Texas         24.313860
 27         Hidalgo County, Texas         22.650166
 28         Tarrant County, Texas         21.970432
 29         Grayson County, Texas         21.904043
 30          Harris County, Texas         21.543652
 31         El Paso County, Texas         19.861828
 32         Cameron County, Texas         18.711725
 33           Gregg County, Texas         18.523277
 34            Webb County, Texas         18.480782
 35         Coryell County, Texas         18.453067
 36         Lubbock County, Texas         18.248744
 37        Angelina County, Texas         17.026461
 38          Nueces County, Texas         16.268156
 39    San Patricio County, Texas         16.235484
 40          Dallas County, Texas          9.469790
 41       Tom Green County, Texas          8.607286
 42       Henderson County, Texas          8.550731
 43          Taylor County, Texas          7.540102
 44          Orange County, Texas          1.617750
 45        Victoria County, Texas         -1.805660
 46         Wichita County, Texas         -2.944431
 47       Jefferson County, Texas         -4.763183
 48           Bowie County, Texas         -9.709216
 49          Potter County, Texas        -13.368020
 50        Harrison County, Texas               NaN
 51            Hood County, Texas               NaN
 52     Nacogdoches County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_14_24': year                        name  pct_change_14_24
 0             Hays County, Texas         72.708502
 1            Comal County, Texas         72.597553
 2       Williamson County, Texas         57.529478
 3            Ellis County, Texas         53.478346
 4       Montgomery County, Texas         49.903526
 5          Bastrop County, Texas         48.980329
 6          Liberty County, Texas         48.640046
 7             Hunt County, Texas         47.428680
 8          Kaufman County, Texas         46.268711
 9         Rockwall County, Texas         46.115831
 10          Denton County, Texas         45.123446
 11       Fort Bend County, Texas         45.094990
 12          Collin County, Texas         40.951498
 13          Parker County, Texas         39.007207
 14          Travis County, Texas         36.624392
 15         Midland County, Texas         36.016118
 16          Walker County, Texas         31.151301
 17          Brazos County, Texas         28.968176
 18       Guadalupe County, Texas         28.039206
 19           Ector County, Texas         26.884007
 20            Bell County, Texas         24.751885
 21       Galveston County, Texas         23.831052
 22         Grayson County, Texas         22.912864
 23       Tom Green County, Texas         21.533900
 24    San Patricio County, Texas         21.247376
 25         Johnson County, Texas         21.123138
 26           Bexar County, Texas         20.865388
 27        Brazoria County, Texas         20.171443
 28           Smith County, Texas         19.478202
 29        Harrison County, Texas         16.784295
 30         Cameron County, Texas         15.919089
 31         Coryell County, Texas         15.437414
 32         Hidalgo County, Texas         15.303163
 33          Harris County, Texas         15.245833
 34         Tarrant County, Texas         14.824503
 35         El Paso County, Texas         14.066662
 36        McLennan County, Texas         13.130489
 37            Webb County, Texas         12.207100
 38           Gregg County, Texas         12.153300
 39        Angelina County, Texas         11.052023
 40         Wichita County, Texas         11.014238
 41         Randall County, Texas         10.392331
 42     Nacogdoches County, Texas         10.027767
 43       Henderson County, Texas          9.377099
 44         Lubbock County, Texas          7.822055
 45          Orange County, Texas          5.284258
 46          Dallas County, Texas          3.914703
 47          Nueces County, Texas          2.899562
 48       Jefferson County, Texas          0.242698
 49        Victoria County, Texas         -2.618214
 50          Taylor County, Texas         -3.441138
 51           Bowie County, Texas         -3.844640
 52          Potter County, Texas         -6.739640
 53            Hood County, Texas               NaN
 54           Starr County, Texas               NaN
 55       Van Zandt County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_19_24': year                        name  pct_change_19_24
 0          Bastrop County, Texas         47.555737
 1       Williamson County, Texas         36.748852
 2     San Patricio County, Texas         36.120649
 3             Hays County, Texas         34.484937
 4          Liberty County, Texas         32.369615
 5             Hunt County, Texas         30.505067
 6          Midland County, Texas         29.895585
 7            Ellis County, Texas         29.366341
 8           Denton County, Texas         29.221657
 9          Grayson County, Texas         26.996951
 10           Comal County, Texas         26.434384
 11         Kaufman County, Texas         25.191868
 12      Montgomery County, Texas         25.061465
 13          Parker County, Texas         23.945578
 14           Ector County, Texas         22.841429
 15       Fort Bend County, Texas         21.818350
 16          Collin County, Texas         21.788433
 17           Gregg County, Texas         21.215684
 18         Coryell County, Texas         21.017858
 19           Bexar County, Texas         20.004333
 20          Walker County, Texas         19.482398
 21            Wise County, Texas         19.340433
 22        Rockwall County, Texas         18.617374
 23           Smith County, Texas         18.175231
 24       Guadalupe County, Texas         18.008870
 25            Bell County, Texas         17.421346
 26       Henderson County, Texas         16.949964
 27         Johnson County, Texas         15.976808
 28          Travis County, Texas         15.850974
 29         Randall County, Texas         14.129725
 30         El Paso County, Texas         13.805472
 31          Brazos County, Texas         13.574038
 32     Nacogdoches County, Texas         12.556488
 33        Brazoria County, Texas         12.173365
 34       Galveston County, Texas         10.646893
 35         Cameron County, Texas         10.502835
 36         Hidalgo County, Texas         10.221556
 37        Harrison County, Texas         10.060924
 38       Tom Green County, Texas          9.573720
 39         Wichita County, Texas          7.426433
 40         Lubbock County, Texas          7.260689
 41        Victoria County, Texas          7.190361
 42          Orange County, Texas          7.148748
 43         Tarrant County, Texas          6.977628
 44          Harris County, Texas          6.575807
 45        McLennan County, Texas          5.310864
 46       Jefferson County, Texas          4.525757
 47            Webb County, Texas          2.840207
 48          Dallas County, Texas          1.827127
 49          Nueces County, Texas          1.719112
 50          Taylor County, Texas          1.486584
 51        Angelina County, Texas         -3.573580
 52          Potter County, Texas         -6.328136
 53           Bowie County, Texas         -8.178097
 54            Hood County, Texas               NaN
 55           Starr County, Texas               NaN
 56       Van Zandt County, Texas               NaN
 57          Waller County, Texas               NaN}

In [41]:
# Export county families data with percentage changes to CSV
county_families_export = county_tx_families[['county_code', 'name', 'pct_change_05_24', 'pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']].copy()
county_families_export['name'] = county_families_export['name'].str.replace(' County, Texas', '', regex=False)
county_families_export.to_csv('county_families_pct_changes.csv', index=False)
print("Exported to county_families_pct_changes.csv")

Exported to county_families_pct_changes.csv

### Family households with children under 18

In [42]:
# cols for percentage change in the number of families with at least one kid
county_tx_family_households_with_child['pct_change_19_24'] = ((county_tx_family_households_with_child[2024] - county_tx_family_households_with_child[2019]) / county_tx_family_households_with_child[2019]) * 100 # 5 years
county_tx_family_households_with_child['pct_change_14_24'] = ((county_tx_family_households_with_child[2024] - county_tx_family_households_with_child[2014]) / county_tx_family_households_with_child[2014]) * 100 # 10 years
county_tx_family_households_with_child['pct_change_09_24'] = ((county_tx_family_households_with_child[2024] - county_tx_family_households_with_child[2009]) / county_tx_family_households_with_child[2009]) * 100 # 15 years
county_tx_family_households_with_child['pct_change_05_24'] = ((county_tx_family_households_with_child[2024] - county_tx_family_households_with_child[2005]) / county_tx_family_households_with_child[2005]) * 100 # 19 years

# Print ranked results
print_rankings(
    df=county_tx_family_households_with_child,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                        name  pct_change_05_24
0             Hays County, Texas        151.499036
1       Williamson County, Texas        108.450401
2            Comal County, Texas        103.687858
3        Fort Bend County, Texas        100.633578
4        Guadalupe County, Texas         96.395672
5       Montgomery County, Texas         90.183548
6          Bastrop County, Texas         83.163642
7           Collin County, Texas         79.391997
8          Liberty County, Texas         75.860038
9           Denton County, Texas         74.477575
10         Kaufman County, Texas         70.799385
11          Brazos County, Texas         58.810600
12            Hunt County, Texas         54.573658
13         Midland County, Texas         53.415702
14           Ellis County, Texas         51.729156
15          Parker County, Texas         51.271836
16            Bell County, Texas         40.845217
17          Travis County, Texas         37.021448
18           Ector County, Texas         36.717834
19         Johnson County, Texas         32.198356
20         Coryell County, Texas         30.817296
21       Galveston County, Texas         24.614770
22         Randall County, Texas         23.820288
23        Brazoria County, Texas         22.233989
24           Bexar County, Texas         21.481844
25         Tarrant County, Texas         16.887528
26         Grayson County, Texas         16.031056
27           Smith County, Texas         14.977330
28          Harris County, Texas         14.926288
29           Gregg County, Texas         14.604789
30       Tom Green County, Texas          9.803492
31       Henderson County, Texas          9.784379
32         Hidalgo County, Texas          7.132118
33        Angelina County, Texas          6.054206
34            Webb County, Texas          5.834744
35        McLennan County, Texas          0.855956
36         Cameron County, Texas         -0.648420
37         El Paso County, Texas         -1.211236
38          Orange County, Texas         -1.526182
39         Wichita County, Texas         -3.963686
40         Lubbock County, Texas         -4.539425
41          Nueces County, Texas         -4.628014
42       Jefferson County, Texas         -5.580447
43    San Patricio County, Texas         -6.914841
44          Dallas County, Texas         -8.511190
45          Taylor County, Texas        -10.320773
46          Potter County, Texas        -19.755348
47           Bowie County, Texas        -22.257738
48        Victoria County, Texas        -22.432754
49        Harrison County, Texas               NaN
50            Hood County, Texas               NaN
51     Nacogdoches County, Texas               NaN
52        Rockwall County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_09_24
0             Hays County, Texas        148.917692
1       Williamson County, Texas         81.619494
2          Kaufman County, Texas         77.782223
3       Montgomery County, Texas         77.448589
4        Fort Bend County, Texas         74.718232
5        Guadalupe County, Texas         72.630294
6             Hunt County, Texas         69.680083
7           Parker County, Texas         67.067186
8          Liberty County, Texas         58.192031
9           Denton County, Texas         52.062060
10           Comal County, Texas         49.322544
11          Collin County, Texas         48.630125
12           Ellis County, Texas         45.599255
13         Midland County, Texas         43.791868
14         Bastrop County, Texas         39.896315
15        Rockwall County, Texas         38.564434
16           Smith County, Texas         36.645509
17            Bell County, Texas         35.693334
18           Ector County, Texas         28.558682
19         Johnson County, Texas         26.811152
20          Brazos County, Texas         24.939956
21         Randall County, Texas         23.541021
22           Gregg County, Texas         22.438454
23          Travis County, Texas         21.260234
24           Bexar County, Texas         20.260208
25    San Patricio County, Texas         19.523269
26         Grayson County, Texas         18.760331
27       Galveston County, Texas         14.124156
28        Brazoria County, Texas         12.467613
29       Henderson County, Texas         12.457053
30        Angelina County, Texas          7.655203
31          Harris County, Texas          7.506059
32         Coryell County, Texas          7.474333
33         Tarrant County, Texas          6.975900
34       Tom Green County, Texas          5.310727
35            Webb County, Texas          4.193038
36        McLennan County, Texas          4.130306
37          Nueces County, Texas          2.886031
38         Hidalgo County, Texas          1.772822
39         El Paso County, Texas          0.993449
40         Wichita County, Texas         -2.675887
41          Taylor County, Texas         -3.232971
42         Lubbock County, Texas         -4.677106
43         Cameron County, Texas         -7.422429
44        Victoria County, Texas         -8.853575
45          Dallas County, Texas        -11.065747
46          Orange County, Texas        -12.500974
47       Jefferson County, Texas        -14.484283
48          Potter County, Texas        -16.230722
49           Bowie County, Texas        -20.484810
50        Harrison County, Texas               NaN
51            Hood County, Texas               NaN
52     Nacogdoches County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_14_24
0            Comal County, Texas         77.596240
1          Liberty County, Texas         77.196106
2             Hays County, Texas         74.982656
3             Hunt County, Texas         63.309495
4       Montgomery County, Texas         50.926406
5            Ellis County, Texas         50.887517
6          Kaufman County, Texas         50.661062
7       Williamson County, Texas         47.409898
8           Parker County, Texas         42.032947
9           Walker County, Texas         39.238095
10       Fort Bend County, Texas         37.999317
11       Guadalupe County, Texas         35.459634
12         Midland County, Texas         33.580974
13          Collin County, Texas         29.278162
14         Coryell County, Texas         27.146848
15         Bastrop County, Texas         26.909314
16          Denton County, Texas         24.428514
17           Ector County, Texas         23.914803
18         Grayson County, Texas         23.453608
19       Tom Green County, Texas         21.777526
20        Rockwall County, Texas         21.003207
21          Travis County, Texas         20.383966
22            Bell County, Texas         20.168739
23        Harrison County, Texas         19.887687
24       Henderson County, Texas         19.744957
25           Smith County, Texas         19.696000
26         Wichita County, Texas         15.623661
27       Galveston County, Texas         13.835606
28          Brazos County, Texas         13.660199
29         Johnson County, Texas         12.553057
30           Gregg County, Texas         11.889650
31    San Patricio County, Texas          8.768507
32           Bexar County, Texas          8.299332
33          Harris County, Texas          6.046594
34        Angelina County, Texas          5.497199
35         Tarrant County, Texas          4.522360
36         Hidalgo County, Texas          4.295295
37     Nacogdoches County, Texas          3.708489
38        McLennan County, Texas          2.582690
39        Brazoria County, Texas          2.393145
40         El Paso County, Texas         -0.520470
41          Taylor County, Texas         -1.538075
42         Randall County, Texas         -1.660682
43            Webb County, Texas         -4.369700
44         Cameron County, Texas         -4.810448
45          Nueces County, Texas         -5.402467
46           Bowie County, Texas         -7.828820
47        Victoria County, Texas         -8.453916
48          Orange County, Texas         -8.530226
49          Potter County, Texas         -9.810043
50         Lubbock County, Texas        -11.714192
51       Jefferson County, Texas        -12.667388
52          Dallas County, Texas        -13.767853
53            Hood County, Texas               NaN
54           Starr County, Texas               NaN
55       Van Zandt County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_19_24
0             Hunt County, Texas         55.671274
1             Hays County, Texas         51.471354
2          Liberty County, Texas         46.919291
3        Henderson County, Texas         42.275211
4       Williamson County, Texas         35.398675
5           Parker County, Texas         34.974022
6        Guadalupe County, Texas         31.978972
7            Ellis County, Texas         31.591789
8       Montgomery County, Texas         30.422062
9          Bastrop County, Texas         27.929506
10         Coryell County, Texas         27.752014
11           Comal County, Texas         25.243331
12         Kaufman County, Texas         24.745972
13           Gregg County, Texas         22.860889
14        Victoria County, Texas         21.567486
15           Ector County, Texas         20.655172
16       Fort Bend County, Texas         19.134087
17         Wichita County, Texas         19.086160
18          Collin County, Texas         18.862146
19         Grayson County, Texas         17.203087
20          Denton County, Texas         17.202855
21         Midland County, Texas         16.510982
22            Bell County, Texas         15.869924
23    San Patricio County, Texas         14.789244
24           Bexar County, Texas         14.701065
25         Randall County, Texas         11.707348
26       Galveston County, Texas         11.496333
27           Smith County, Texas         10.637039
28          Travis County, Texas          5.875737
29         Johnson County, Texas          5.744103
30          Orange County, Texas          5.309070
31         El Paso County, Texas          5.155207
32        Harrison County, Texas          4.600860
33         Tarrant County, Texas          4.590467
34        Brazoria County, Texas          2.874332
35          Brazos County, Texas          2.490346
36       Jefferson County, Texas          1.433190
37          Harris County, Texas          1.228348
38        Angelina County, Texas         -0.273066
39     Nacogdoches County, Texas         -0.754297
40         Cameron County, Texas         -0.925264
41          Walker County, Texas         -1.197142
42         Hidalgo County, Texas         -1.369932
43       Tom Green County, Texas         -1.745326
44          Nueces County, Texas         -2.868143
45          Taylor County, Texas         -3.725984
46            Webb County, Texas         -4.458896
47          Potter County, Texas         -6.105656
48        McLennan County, Texas         -6.407657
49          Dallas County, Texas         -9.089896
50        Rockwall County, Texas        -10.709859
51            Wise County, Texas        -12.610002
52         Lubbock County, Texas        -12.948229
53           Bowie County, Texas        -12.984293
54            Hood County, Texas               NaN
55           Starr County, Texas               NaN
56       Van Zandt County, Texas               NaN
57          Waller County, Texas               NaN

{'pct_change_05_24': year                        name  pct_change_05_24
 0             Hays County, Texas        151.499036
 1       Williamson County, Texas        108.450401
 2            Comal County, Texas        103.687858
 3        Fort Bend County, Texas        100.633578
 4        Guadalupe County, Texas         96.395672
 5       Montgomery County, Texas         90.183548
 6          Bastrop County, Texas         83.163642
 7           Collin County, Texas         79.391997
 8          Liberty County, Texas         75.860038
 9           Denton County, Texas         74.477575
 10         Kaufman County, Texas         70.799385
 11          Brazos County, Texas         58.810600
 12            Hunt County, Texas         54.573658
 13         Midland County, Texas         53.415702
 14           Ellis County, Texas         51.729156
 15          Parker County, Texas         51.271836
 16            Bell County, Texas         40.845217
 17          Travis County, Texas         37.021448
 18           Ector County, Texas         36.717834
 19         Johnson County, Texas         32.198356
 20         Coryell County, Texas         30.817296
 21       Galveston County, Texas         24.614770
 22         Randall County, Texas         23.820288
 23        Brazoria County, Texas         22.233989
 24           Bexar County, Texas         21.481844
 25         Tarrant County, Texas         16.887528
 26         Grayson County, Texas         16.031056
 27           Smith County, Texas         14.977330
 28          Harris County, Texas         14.926288
 29           Gregg County, Texas         14.604789
 30       Tom Green County, Texas          9.803492
 31       Henderson County, Texas          9.784379
 32         Hidalgo County, Texas          7.132118
 33        Angelina County, Texas          6.054206
 34            Webb County, Texas          5.834744
 35        McLennan County, Texas          0.855956
 36         Cameron County, Texas         -0.648420
 37         El Paso County, Texas         -1.211236
 38          Orange County, Texas         -1.526182
 39         Wichita County, Texas         -3.963686
 40         Lubbock County, Texas         -4.539425
 41          Nueces County, Texas         -4.628014
 42       Jefferson County, Texas         -5.580447
 43    San Patricio County, Texas         -6.914841
 44          Dallas County, Texas         -8.511190
 45          Taylor County, Texas        -10.320773
 46          Potter County, Texas        -19.755348
 47           Bowie County, Texas        -22.257738
 48        Victoria County, Texas        -22.432754
 49        Harrison County, Texas               NaN
 50            Hood County, Texas               NaN
 51     Nacogdoches County, Texas               NaN
 52        Rockwall County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_09_24': year                        name  pct_change_09_24
 0             Hays County, Texas        148.917692
 1       Williamson County, Texas         81.619494
 2          Kaufman County, Texas         77.782223
 3       Montgomery County, Texas         77.448589
 4        Fort Bend County, Texas         74.718232
 5        Guadalupe County, Texas         72.630294
 6             Hunt County, Texas         69.680083
 7           Parker County, Texas         67.067186
 8          Liberty County, Texas         58.192031
 9           Denton County, Texas         52.062060
 10           Comal County, Texas         49.322544
 11          Collin County, Texas         48.630125
 12           Ellis County, Texas         45.599255
 13         Midland County, Texas         43.791868
 14         Bastrop County, Texas         39.896315
 15        Rockwall County, Texas         38.564434
 16           Smith County, Texas         36.645509
 17            Bell County, Texas         35.693334
 18           Ector County, Texas         28.558682
 19         Johnson County, Texas         26.811152
 20          Brazos County, Texas         24.939956
 21         Randall County, Texas         23.541021
 22           Gregg County, Texas         22.438454
 23          Travis County, Texas         21.260234
 24           Bexar County, Texas         20.260208
 25    San Patricio County, Texas         19.523269
 26         Grayson County, Texas         18.760331
 27       Galveston County, Texas         14.124156
 28        Brazoria County, Texas         12.467613
 29       Henderson County, Texas         12.457053
 30        Angelina County, Texas          7.655203
 31          Harris County, Texas          7.506059
 32         Coryell County, Texas          7.474333
 33         Tarrant County, Texas          6.975900
 34       Tom Green County, Texas          5.310727
 35            Webb County, Texas          4.193038
 36        McLennan County, Texas          4.130306
 37          Nueces County, Texas          2.886031
 38         Hidalgo County, Texas          1.772822
 39         El Paso County, Texas          0.993449
 40         Wichita County, Texas         -2.675887
 41          Taylor County, Texas         -3.232971
 42         Lubbock County, Texas         -4.677106
 43         Cameron County, Texas         -7.422429
 44        Victoria County, Texas         -8.853575
 45          Dallas County, Texas        -11.065747
 46          Orange County, Texas        -12.500974
 47       Jefferson County, Texas        -14.484283
 48          Potter County, Texas        -16.230722
 49           Bowie County, Texas        -20.484810
 50        Harrison County, Texas               NaN
 51            Hood County, Texas               NaN
 52     Nacogdoches County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_14_24': year                        name  pct_change_14_24
 0            Comal County, Texas         77.596240
 1          Liberty County, Texas         77.196106
 2             Hays County, Texas         74.982656
 3             Hunt County, Texas         63.309495
 4       Montgomery County, Texas         50.926406
 5            Ellis County, Texas         50.887517
 6          Kaufman County, Texas         50.661062
 7       Williamson County, Texas         47.409898
 8           Parker County, Texas         42.032947
 9           Walker County, Texas         39.238095
 10       Fort Bend County, Texas         37.999317
 11       Guadalupe County, Texas         35.459634
 12         Midland County, Texas         33.580974
 13          Collin County, Texas         29.278162
 14         Coryell County, Texas         27.146848
 15         Bastrop County, Texas         26.909314
 16          Denton County, Texas         24.428514
 17           Ector County, Texas         23.914803
 18         Grayson County, Texas         23.453608
 19       Tom Green County, Texas         21.777526
 20        Rockwall County, Texas         21.003207
 21          Travis County, Texas         20.383966
 22            Bell County, Texas         20.168739
 23        Harrison County, Texas         19.887687
 24       Henderson County, Texas         19.744957
 25           Smith County, Texas         19.696000
 26         Wichita County, Texas         15.623661
 27       Galveston County, Texas         13.835606
 28          Brazos County, Texas         13.660199
 29         Johnson County, Texas         12.553057
 30           Gregg County, Texas         11.889650
 31    San Patricio County, Texas          8.768507
 32           Bexar County, Texas          8.299332
 33          Harris County, Texas          6.046594
 34        Angelina County, Texas          5.497199
 35         Tarrant County, Texas          4.522360
 36         Hidalgo County, Texas          4.295295
 37     Nacogdoches County, Texas          3.708489
 38        McLennan County, Texas          2.582690
 39        Brazoria County, Texas          2.393145
 40         El Paso County, Texas         -0.520470
 41          Taylor County, Texas         -1.538075
 42         Randall County, Texas         -1.660682
 43            Webb County, Texas         -4.369700
 44         Cameron County, Texas         -4.810448
 45          Nueces County, Texas         -5.402467
 46           Bowie County, Texas         -7.828820
 47        Victoria County, Texas         -8.453916
 48          Orange County, Texas         -8.530226
 49          Potter County, Texas         -9.810043
 50         Lubbock County, Texas        -11.714192
 51       Jefferson County, Texas        -12.667388
 52          Dallas County, Texas        -13.767853
 53            Hood County, Texas               NaN
 54           Starr County, Texas               NaN
 55       Van Zandt County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_19_24': year                        name  pct_change_19_24
 0             Hunt County, Texas         55.671274
 1             Hays County, Texas         51.471354
 2          Liberty County, Texas         46.919291
 3        Henderson County, Texas         42.275211
 4       Williamson County, Texas         35.398675
 5           Parker County, Texas         34.974022
 6        Guadalupe County, Texas         31.978972
 7            Ellis County, Texas         31.591789
 8       Montgomery County, Texas         30.422062
 9          Bastrop County, Texas         27.929506
 10         Coryell County, Texas         27.752014
 11           Comal County, Texas         25.243331
 12         Kaufman County, Texas         24.745972
 13           Gregg County, Texas         22.860889
 14        Victoria County, Texas         21.567486
 15           Ector County, Texas         20.655172
 16       Fort Bend County, Texas         19.134087
 17         Wichita County, Texas         19.086160
 18          Collin County, Texas         18.862146
 19         Grayson County, Texas         17.203087
 20          Denton County, Texas         17.202855
 21         Midland County, Texas         16.510982
 22            Bell County, Texas         15.869924
 23    San Patricio County, Texas         14.789244
 24           Bexar County, Texas         14.701065
 25         Randall County, Texas         11.707348
 26       Galveston County, Texas         11.496333
 27           Smith County, Texas         10.637039
 28          Travis County, Texas          5.875737
 29         Johnson County, Texas          5.744103
 30          Orange County, Texas          5.309070
 31         El Paso County, Texas          5.155207
 32        Harrison County, Texas          4.600860
 33         Tarrant County, Texas          4.590467
 34        Brazoria County, Texas          2.874332
 35          Brazos County, Texas          2.490346
 36       Jefferson County, Texas          1.433190
 37          Harris County, Texas          1.228348
 38        Angelina County, Texas         -0.273066
 39     Nacogdoches County, Texas         -0.754297
 40         Cameron County, Texas         -0.925264
 41          Walker County, Texas         -1.197142
 42         Hidalgo County, Texas         -1.369932
 43       Tom Green County, Texas         -1.745326
 44          Nueces County, Texas         -2.868143
 45          Taylor County, Texas         -3.725984
 46            Webb County, Texas         -4.458896
 47          Potter County, Texas         -6.105656
 48        McLennan County, Texas         -6.407657
 49          Dallas County, Texas         -9.089896
 50        Rockwall County, Texas        -10.709859
 51            Wise County, Texas        -12.610002
 52         Lubbock County, Texas        -12.948229
 53           Bowie County, Texas        -12.984293
 54            Hood County, Texas               NaN
 55           Starr County, Texas               NaN
 56       Van Zandt County, Texas               NaN
 57          Waller County, Texas               NaN}

### Total people under 18

In [43]:
# create columns for population change for people under 18 
county_tx_under18['pct_change_19_24'] = ((county_tx_under18[2024] - county_tx_under18[2019]) / county_tx_under18[2019]) * 100 # 5 years
county_tx_under18['pct_change_14_24'] = ((county_tx_under18[2024] - county_tx_under18[2014]) / county_tx_under18[2014]) * 100 # 10 years
county_tx_under18['pct_change_09_24'] = ((county_tx_under18[2024] - county_tx_under18[2009]) / county_tx_under18[2009]) * 100 # 15 years
county_tx_under18['pct_change_05_24'] = ((county_tx_under18[2024] - county_tx_under18[2005]) / county_tx_under18[2005]) * 100 # 19 years

# Print ranked results
print_rankings(
    df=county_tx_under18,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

year                        name  pct_change_05_24
0          Kaufman County, Texas        139.352906
1             Hays County, Texas        130.239327
2        Fort Bend County, Texas         95.064697
3       Montgomery County, Texas         86.812906
4       Williamson County, Texas         81.817695
5        Guadalupe County, Texas         74.669728
6           Parker County, Texas         73.329630
7           Collin County, Texas         66.061170
8            Ellis County, Texas         65.072005
9          Midland County, Texas         60.094493
10          Denton County, Texas         58.946922
11          Brazos County, Texas         52.918013
12            Hunt County, Texas         43.167867
13           Ector County, Texas         38.516101
14         Johnson County, Texas         36.922998
15        Brazoria County, Texas         35.194375
16            Bell County, Texas         34.649680
17         Randall County, Texas         30.601994
18         Grayson County, Texas         26.759213
19          Travis County, Texas         23.130967
20           Bexar County, Texas         21.658501
21         Tarrant County, Texas         21.572456
22         Lubbock County, Texas         21.235380
23           Smith County, Texas         20.767435
24          Harris County, Texas         19.667652
25       Galveston County, Texas         18.904187
26         Hidalgo County, Texas         15.278925
27        McLennan County, Texas         11.102002
28          Taylor County, Texas         10.252477
29           Gregg County, Texas          5.211470
30           Bowie County, Texas          1.236048
31            Webb County, Texas          0.703160
32       Henderson County, Texas          0.503940
33       Jefferson County, Texas          0.293051
34          Dallas County, Texas         -0.640395
35        Angelina County, Texas         -1.769311
36         El Paso County, Texas         -2.506611
37         Wichita County, Texas         -4.694214
38          Nueces County, Texas         -6.137230
39        Victoria County, Texas         -6.347341
40         Cameron County, Texas         -6.520687
41          Potter County, Texas        -11.929376
42    San Patricio County, Texas        -13.745754
43         Bastrop County, Texas               NaN
44           Comal County, Texas               NaN
45         Coryell County, Texas               NaN
46        Harrison County, Texas               NaN
47            Hood County, Texas               NaN
48         Liberty County, Texas               NaN
49     Nacogdoches County, Texas               NaN
50          Orange County, Texas               NaN
51        Rockwall County, Texas               NaN
52           Starr County, Texas               NaN
53       Tom Green County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_09_24
0          Kaufman County, Texas         86.060467
1          Liberty County, Texas         75.911608
2             Hays County, Texas         67.514641
3            Comal County, Texas         59.941723
4        Fort Bend County, Texas         53.198780
5       Montgomery County, Texas         52.880768
6         Rockwall County, Texas         48.427804
7          Midland County, Texas         47.454308
8       Williamson County, Texas         46.717796
9           Parker County, Texas         44.861889
10       Guadalupe County, Texas         43.972203
11         Bastrop County, Texas         43.798450
12            Hunt County, Texas         43.438257
13           Ellis County, Texas         37.847626
14          Collin County, Texas         35.933435
15          Denton County, Texas         31.395039
16            Bell County, Texas         27.297024
17           Ector County, Texas         26.709101
18          Brazos County, Texas         25.191416
19         Johnson County, Texas         24.572216
20         Randall County, Texas         21.850522
21         Grayson County, Texas         21.249066
22        Brazoria County, Texas         20.296862
23       Galveston County, Texas         13.677085
24          Taylor County, Texas         13.547755
25         Lubbock County, Texas         13.531653
26           Smith County, Texas         12.716730
27         Coryell County, Texas         12.673704
28           Bexar County, Texas         11.007114
29         Tarrant County, Texas          8.716123
30          Travis County, Texas          8.587369
31          Harris County, Texas          8.320991
32       Tom Green County, Texas          7.526211
33        McLennan County, Texas          6.713017
34          Orange County, Texas          4.896049
35       Jefferson County, Texas          3.374330
36       Henderson County, Texas          2.442623
37         Hidalgo County, Texas          1.795106
38           Gregg County, Texas         -0.698264
39         Wichita County, Texas         -2.518009
40        Angelina County, Texas         -4.273052
41           Bowie County, Texas         -4.448894
42          Nueces County, Texas         -5.461209
43          Dallas County, Texas         -5.654117
44         El Paso County, Texas         -6.727987
45    San Patricio County, Texas         -7.714271
46        Victoria County, Texas         -7.810240
47            Webb County, Texas         -8.572684
48          Potter County, Texas        -10.494629
49         Cameron County, Texas        -13.526507
50        Harrison County, Texas               NaN
51            Hood County, Texas               NaN
52     Nacogdoches County, Texas               NaN
53           Starr County, Texas               NaN
54       Van Zandt County, Texas               NaN
55          Walker County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_14_24
0          Kaufman County, Texas         84.008951
1          Liberty County, Texas         80.024504
2            Comal County, Texas         51.253789
3          Bastrop County, Texas         48.348078
4             Hays County, Texas         47.462542
5         Rockwall County, Texas         46.656516
6           Parker County, Texas         45.508444
7            Ellis County, Texas         40.445084
8             Hunt County, Texas         39.565566
9       Montgomery County, Texas         36.984743
10       Fort Bend County, Texas         30.073696
11         Johnson County, Texas         29.295891
12      Williamson County, Texas         27.822976
13         Midland County, Texas         26.321676
14          Collin County, Texas         25.431732
15       Guadalupe County, Texas         21.217187
16         Grayson County, Texas         20.949219
17          Denton County, Texas         20.249622
18            Bell County, Texas         18.514743
19          Brazos County, Texas         15.436959
20        Brazoria County, Texas         13.699882
21         Randall County, Texas         13.510499
22           Ector County, Texas         12.904219
23          Walker County, Texas         12.505756
24       Galveston County, Texas          9.061389
25           Smith County, Texas          8.971000
26          Taylor County, Texas          7.895764
27       Henderson County, Texas          7.537429
28         Lubbock County, Texas          7.046542
29        McLennan County, Texas          5.775586
30           Bexar County, Texas          5.720832
31          Harris County, Texas          5.591289
32          Orange County, Texas          5.185257
33         Tarrant County, Texas          4.680087
34       Jefferson County, Texas          3.663230
35          Travis County, Texas          0.908717
36       Tom Green County, Texas          0.896025
37         Coryell County, Texas          0.708993
38        Harrison County, Texas          0.637816
39           Gregg County, Texas          0.531749
40         Wichita County, Texas         -0.966832
41         Hidalgo County, Texas         -1.318249
42           Bowie County, Texas         -1.485571
43     Nacogdoches County, Texas         -1.657821
44    San Patricio County, Texas         -2.857923
45          Dallas County, Texas         -3.754887
46        Victoria County, Texas         -4.662393
47        Angelina County, Texas         -5.230071
48         El Paso County, Texas         -6.421543
49            Webb County, Texas         -8.186302
50          Nueces County, Texas         -9.031548
51          Potter County, Texas         -9.167690
52         Cameron County, Texas         -9.811628
53            Hood County, Texas               NaN
54           Starr County, Texas               NaN
55       Van Zandt County, Texas               NaN
56          Waller County, Texas               NaN
57            Wise County, Texas               NaN
year                        name  pct_change_19_24
0          Kaufman County, Texas         49.294848
1          Liberty County, Texas         47.812055
2          Bastrop County, Texas         33.621466
3         Rockwall County, Texas         27.550911
4            Comal County, Texas         25.505888
5             Hunt County, Texas         24.984177
6            Ellis County, Texas         24.295572
7             Hays County, Texas         21.119492
8           Parker County, Texas         20.896638
9       Montgomery County, Texas         20.079525
10         Johnson County, Texas         17.191172
11          Walker County, Texas         13.858341
12          Collin County, Texas         13.648409
13      Williamson County, Texas         13.448553
14            Wise County, Texas         13.214631
15       Guadalupe County, Texas         12.357157
16       Fort Bend County, Texas         12.312056
17         Grayson County, Texas         11.645142
18       Henderson County, Texas         11.509636
19         Coryell County, Texas         10.647769
20          Denton County, Texas          9.690101
21            Bell County, Texas          8.396327
22         Randall County, Texas          7.563863
23        Brazoria County, Texas          5.899487
24         Midland County, Texas          5.636849
25          Orange County, Texas          5.292209
26          Brazos County, Texas          5.120017
27           Smith County, Texas          5.113978
28          Taylor County, Texas          4.934451
29         Lubbock County, Texas          4.036492
30       Galveston County, Texas          2.845894
31       Jefferson County, Texas          2.546063
32          Harris County, Texas          2.182361
33           Ector County, Texas          2.032343
34        Harrison County, Texas          1.796804
35           Bexar County, Texas          1.401743
36        McLennan County, Texas          1.263871
37           Gregg County, Texas          1.050116
38         Tarrant County, Texas          0.801304
39    San Patricio County, Texas          0.514531
40     Nacogdoches County, Texas          0.053333
41         Wichita County, Texas         -0.549506
42           Bowie County, Texas         -0.647264
43          Travis County, Texas         -0.860555
44         Hidalgo County, Texas         -1.277159
45       Tom Green County, Texas         -1.386903
46        Angelina County, Texas         -1.582264
47         El Paso County, Texas         -1.714230
48        Victoria County, Texas         -3.105455
49          Dallas County, Texas         -4.260481
50          Potter County, Texas         -5.236845
51         Cameron County, Texas         -5.394840
52            Webb County, Texas         -6.587633
53          Nueces County, Texas         -7.010302
54            Hood County, Texas               NaN
55           Starr County, Texas               NaN
56       Van Zandt County, Texas               NaN
57          Waller County, Texas               NaN

{'pct_change_05_24': year                        name  pct_change_05_24
 0          Kaufman County, Texas        139.352906
 1             Hays County, Texas        130.239327
 2        Fort Bend County, Texas         95.064697
 3       Montgomery County, Texas         86.812906
 4       Williamson County, Texas         81.817695
 5        Guadalupe County, Texas         74.669728
 6           Parker County, Texas         73.329630
 7           Collin County, Texas         66.061170
 8            Ellis County, Texas         65.072005
 9          Midland County, Texas         60.094493
 10          Denton County, Texas         58.946922
 11          Brazos County, Texas         52.918013
 12            Hunt County, Texas         43.167867
 13           Ector County, Texas         38.516101
 14         Johnson County, Texas         36.922998
 15        Brazoria County, Texas         35.194375
 16            Bell County, Texas         34.649680
 17         Randall County, Texas         30.601994
 18         Grayson County, Texas         26.759213
 19          Travis County, Texas         23.130967
 20           Bexar County, Texas         21.658501
 21         Tarrant County, Texas         21.572456
 22         Lubbock County, Texas         21.235380
 23           Smith County, Texas         20.767435
 24          Harris County, Texas         19.667652
 25       Galveston County, Texas         18.904187
 26         Hidalgo County, Texas         15.278925
 27        McLennan County, Texas         11.102002
 28          Taylor County, Texas         10.252477
 29           Gregg County, Texas          5.211470
 30           Bowie County, Texas          1.236048
 31            Webb County, Texas          0.703160
 32       Henderson County, Texas          0.503940
 33       Jefferson County, Texas          0.293051
 34          Dallas County, Texas         -0.640395
 35        Angelina County, Texas         -1.769311
 36         El Paso County, Texas         -2.506611
 37         Wichita County, Texas         -4.694214
 38          Nueces County, Texas         -6.137230
 39        Victoria County, Texas         -6.347341
 40         Cameron County, Texas         -6.520687
 41          Potter County, Texas        -11.929376
 42    San Patricio County, Texas        -13.745754
 43         Bastrop County, Texas               NaN
 44           Comal County, Texas               NaN
 45         Coryell County, Texas               NaN
 46        Harrison County, Texas               NaN
 47            Hood County, Texas               NaN
 48         Liberty County, Texas               NaN
 49     Nacogdoches County, Texas               NaN
 50          Orange County, Texas               NaN
 51        Rockwall County, Texas               NaN
 52           Starr County, Texas               NaN
 53       Tom Green County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_09_24': year                        name  pct_change_09_24
 0          Kaufman County, Texas         86.060467
 1          Liberty County, Texas         75.911608
 2             Hays County, Texas         67.514641
 3            Comal County, Texas         59.941723
 4        Fort Bend County, Texas         53.198780
 5       Montgomery County, Texas         52.880768
 6         Rockwall County, Texas         48.427804
 7          Midland County, Texas         47.454308
 8       Williamson County, Texas         46.717796
 9           Parker County, Texas         44.861889
 10       Guadalupe County, Texas         43.972203
 11         Bastrop County, Texas         43.798450
 12            Hunt County, Texas         43.438257
 13           Ellis County, Texas         37.847626
 14          Collin County, Texas         35.933435
 15          Denton County, Texas         31.395039
 16            Bell County, Texas         27.297024
 17           Ector County, Texas         26.709101
 18          Brazos County, Texas         25.191416
 19         Johnson County, Texas         24.572216
 20         Randall County, Texas         21.850522
 21         Grayson County, Texas         21.249066
 22        Brazoria County, Texas         20.296862
 23       Galveston County, Texas         13.677085
 24          Taylor County, Texas         13.547755
 25         Lubbock County, Texas         13.531653
 26           Smith County, Texas         12.716730
 27         Coryell County, Texas         12.673704
 28           Bexar County, Texas         11.007114
 29         Tarrant County, Texas          8.716123
 30          Travis County, Texas          8.587369
 31          Harris County, Texas          8.320991
 32       Tom Green County, Texas          7.526211
 33        McLennan County, Texas          6.713017
 34          Orange County, Texas          4.896049
 35       Jefferson County, Texas          3.374330
 36       Henderson County, Texas          2.442623
 37         Hidalgo County, Texas          1.795106
 38           Gregg County, Texas         -0.698264
 39         Wichita County, Texas         -2.518009
 40        Angelina County, Texas         -4.273052
 41           Bowie County, Texas         -4.448894
 42          Nueces County, Texas         -5.461209
 43          Dallas County, Texas         -5.654117
 44         El Paso County, Texas         -6.727987
 45    San Patricio County, Texas         -7.714271
 46        Victoria County, Texas         -7.810240
 47            Webb County, Texas         -8.572684
 48          Potter County, Texas        -10.494629
 49         Cameron County, Texas        -13.526507
 50        Harrison County, Texas               NaN
 51            Hood County, Texas               NaN
 52     Nacogdoches County, Texas               NaN
 53           Starr County, Texas               NaN
 54       Van Zandt County, Texas               NaN
 55          Walker County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_14_24': year                        name  pct_change_14_24
 0          Kaufman County, Texas         84.008951
 1          Liberty County, Texas         80.024504
 2            Comal County, Texas         51.253789
 3          Bastrop County, Texas         48.348078
 4             Hays County, Texas         47.462542
 5         Rockwall County, Texas         46.656516
 6           Parker County, Texas         45.508444
 7            Ellis County, Texas         40.445084
 8             Hunt County, Texas         39.565566
 9       Montgomery County, Texas         36.984743
 10       Fort Bend County, Texas         30.073696
 11         Johnson County, Texas         29.295891
 12      Williamson County, Texas         27.822976
 13         Midland County, Texas         26.321676
 14          Collin County, Texas         25.431732
 15       Guadalupe County, Texas         21.217187
 16         Grayson County, Texas         20.949219
 17          Denton County, Texas         20.249622
 18            Bell County, Texas         18.514743
 19          Brazos County, Texas         15.436959
 20        Brazoria County, Texas         13.699882
 21         Randall County, Texas         13.510499
 22           Ector County, Texas         12.904219
 23          Walker County, Texas         12.505756
 24       Galveston County, Texas          9.061389
 25           Smith County, Texas          8.971000
 26          Taylor County, Texas          7.895764
 27       Henderson County, Texas          7.537429
 28         Lubbock County, Texas          7.046542
 29        McLennan County, Texas          5.775586
 30           Bexar County, Texas          5.720832
 31          Harris County, Texas          5.591289
 32          Orange County, Texas          5.185257
 33         Tarrant County, Texas          4.680087
 34       Jefferson County, Texas          3.663230
 35          Travis County, Texas          0.908717
 36       Tom Green County, Texas          0.896025
 37         Coryell County, Texas          0.708993
 38        Harrison County, Texas          0.637816
 39           Gregg County, Texas          0.531749
 40         Wichita County, Texas         -0.966832
 41         Hidalgo County, Texas         -1.318249
 42           Bowie County, Texas         -1.485571
 43     Nacogdoches County, Texas         -1.657821
 44    San Patricio County, Texas         -2.857923
 45          Dallas County, Texas         -3.754887
 46        Victoria County, Texas         -4.662393
 47        Angelina County, Texas         -5.230071
 48         El Paso County, Texas         -6.421543
 49            Webb County, Texas         -8.186302
 50          Nueces County, Texas         -9.031548
 51          Potter County, Texas         -9.167690
 52         Cameron County, Texas         -9.811628
 53            Hood County, Texas               NaN
 54           Starr County, Texas               NaN
 55       Van Zandt County, Texas               NaN
 56          Waller County, Texas               NaN
 57            Wise County, Texas               NaN,
 'pct_change_19_24': year                        name  pct_change_19_24
 0          Kaufman County, Texas         49.294848
 1          Liberty County, Texas         47.812055
 2          Bastrop County, Texas         33.621466
 3         Rockwall County, Texas         27.550911
 4            Comal County, Texas         25.505888
 5             Hunt County, Texas         24.984177
 6            Ellis County, Texas         24.295572
 7             Hays County, Texas         21.119492
 8           Parker County, Texas         20.896638
 9       Montgomery County, Texas         20.079525
 10         Johnson County, Texas         17.191172
 11          Walker County, Texas         13.858341
 12          Collin County, Texas         13.648409
 13      Williamson County, Texas         13.448553
 14            Wise County, Texas         13.214631
 15       Guadalupe County, Texas         12.357157
 16       Fort Bend County, Texas         12.312056
 17         Grayson County, Texas         11.645142
 18       Henderson County, Texas         11.509636
 19         Coryell County, Texas         10.647769
 20          Denton County, Texas          9.690101
 21            Bell County, Texas          8.396327
 22         Randall County, Texas          7.563863
 23        Brazoria County, Texas          5.899487
 24         Midland County, Texas          5.636849
 25          Orange County, Texas          5.292209
 26          Brazos County, Texas          5.120017
 27           Smith County, Texas          5.113978
 28          Taylor County, Texas          4.934451
 29         Lubbock County, Texas          4.036492
 30       Galveston County, Texas          2.845894
 31       Jefferson County, Texas          2.546063
 32          Harris County, Texas          2.182361
 33           Ector County, Texas          2.032343
 34        Harrison County, Texas          1.796804
 35           Bexar County, Texas          1.401743
 36        McLennan County, Texas          1.263871
 37           Gregg County, Texas          1.050116
 38         Tarrant County, Texas          0.801304
 39    San Patricio County, Texas          0.514531
 40     Nacogdoches County, Texas          0.053333
 41         Wichita County, Texas         -0.549506
 42           Bowie County, Texas         -0.647264
 43          Travis County, Texas         -0.860555
 44         Hidalgo County, Texas         -1.277159
 45       Tom Green County, Texas         -1.386903
 46        Angelina County, Texas         -1.582264
 47         El Paso County, Texas         -1.714230
 48        Victoria County, Texas         -3.105455
 49          Dallas County, Texas         -4.260481
 50          Potter County, Texas         -5.236845
 51         Cameron County, Texas         -5.394840
 52            Webb County, Texas         -6.587633
 53          Nueces County, Texas         -7.010302
 54            Hood County, Texas               NaN
 55           Starr County, Texas               NaN
 56       Van Zandt County, Texas               NaN
 57          Waller County, Texas               NaN}

### County Migration Analysis

In [44]:
# migration
tx_counties_migration['pct_chg_migration_05_24'] = ((tx_counties_migration['total_in_migration_2024'] - tx_counties_migration['total_in_migration_2005']) / tx_counties_migration['total_in_migration_2005'] * 100)
tx_counties_migration['pct_chg_migration_09_24'] = ((tx_counties_migration['total_in_migration_2024'] - tx_counties_migration['total_in_migration_2009']) / tx_counties_migration['total_in_migration_2009'] * 100)
tx_counties_migration['pct_chg_migration_14_24'] = ((tx_counties_migration['total_in_migration_2024'] - tx_counties_migration['total_in_migration_2014']) / tx_counties_migration['total_in_migration_2014'] * 100)
tx_counties_migration['pct_chg_migration_19_24'] = ((tx_counties_migration['total_in_migration_2024'] - tx_counties_migration['total_in_migration_2019']) / tx_counties_migration['total_in_migration_2019'] * 100)

# Print ranked results
print_rankings(
    df=tx_counties_migration,
    variable_names=['pct_chg_migration_05_24', 'pct_chg_migration_09_24',
                 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

                          name  pct_chg_migration_05_24
0        Midland County, Texas               248.397234
1           Hunt County, Texas               232.508105
2        Bastrop County, Texas               230.826307
3        Kaufman County, Texas               226.609724
4          Ector County, Texas               199.605263
5           Hays County, Texas               124.803569
6         Brazos County, Texas                93.648208
7     Williamson County, Texas                85.874606
8        Lubbock County, Texas                80.895458
9      Guadalupe County, Texas                62.192864
10        Potter County, Texas                56.850575
11       Randall County, Texas                55.568401
12         Bexar County, Texas                52.315018
13         Comal County, Texas                51.468564
14       El Paso County, Texas                50.652884
15       Johnson County, Texas                50.633302
16        Denton County, Texas                48.540891
17         Ellis County, Texas                48.392984
18        Collin County, Texas                46.611617
19        Travis County, Texas                46.190896
20     Fort Bend County, Texas                45.299237
21       Grayson County, Texas                40.719446
22       Coryell County, Texas                37.576408
23        Dallas County, Texas                34.435864
24     Tom Green County, Texas                34.429150
25       Wichita County, Texas                34.241116
26       Tarrant County, Texas                33.683946
27        Harris County, Texas                26.980364
28        Parker County, Texas                25.641026
29      Angelina County, Texas                22.362052
30      McLennan County, Texas                21.644052
31    Montgomery County, Texas                15.398918
32      Brazoria County, Texas                 5.951510
33         Smith County, Texas                 5.376472
34     Henderson County, Texas                 2.106136
35          Bell County, Texas                -2.081550
36         Gregg County, Texas                -3.508550
37      Victoria County, Texas               -11.128860
38     Jefferson County, Texas               -12.765957
39       Cameron County, Texas               -16.388929
40     Galveston County, Texas               -17.595249
41        Orange County, Texas               -19.142478
42       Hidalgo County, Texas               -22.724248
43         Bowie County, Texas               -24.755325
44        Nueces County, Texas               -25.720763
45        Taylor County, Texas               -26.398822
46       Liberty County, Texas               -26.700037
47  San Patricio County, Texas               -35.792187
48          Webb County, Texas               -49.005236
49      Harrison County, Texas                      NaN
50          Hood County, Texas                      NaN
51   Nacogdoches County, Texas                      NaN
52      Rockwall County, Texas                      NaN
53         Starr County, Texas                      NaN
54     Van Zandt County, Texas                      NaN
55        Walker County, Texas                      NaN
56        Waller County, Texas                      NaN
57          Wise County, Texas                      NaN
                          name  pct_chg_migration_09_24
0        Midland County, Texas               149.039650
1        Bastrop County, Texas               122.224739
2        Kaufman County, Texas                86.249532
3      Guadalupe County, Texas                79.636533
4           Hunt County, Texas                78.512658
5       Angelina County, Texas                73.435785
6         Collin County, Texas                71.871329
7           Hays County, Texas                61.698357
8          Ector County, Texas                55.867397
9        Randall County, Texas                54.659515
10         Bexar County, Texas                53.371780
11       Coryell County, Texas                48.612474
12     Fort Bend County, Texas                48.094137
13        Denton County, Texas                43.226599
14         Comal County, Texas                42.401035
15        Parker County, Texas                34.809242
16    Williamson County, Texas                33.823893
17        Harris County, Texas                33.021751
18       Tarrant County, Texas                32.222840
19        Brazos County, Texas                27.029915
20        Travis County, Texas                25.607737
21        Dallas County, Texas                23.608373
22      Rockwall County, Texas                22.671290
23     Galveston County, Texas                17.130233
24       Johnson County, Texas                15.737005
25     Henderson County, Texas                13.305116
26         Smith County, Texas                11.042868
27         Ellis County, Texas                10.685926
28    Montgomery County, Texas                10.318347
29       Grayson County, Texas                 9.448458
30      Victoria County, Texas                 1.975560
31       El Paso County, Texas                 0.777290
32      McLennan County, Texas                -1.771182
33       Hidalgo County, Texas                -2.747428
34      Brazoria County, Texas                -2.975207
35       Lubbock County, Texas                -5.082491
36     Jefferson County, Texas                -5.649680
37       Cameron County, Texas                -7.768542
38       Wichita County, Texas                -9.783498
39        Orange County, Texas               -12.753327
40          Bell County, Texas               -14.995446
41        Potter County, Texas               -24.428200
42       Liberty County, Texas               -28.190408
43         Gregg County, Texas               -30.238095
44         Bowie County, Texas               -31.255753
45        Nueces County, Texas               -32.509404
46     Tom Green County, Texas               -35.785565
47  San Patricio County, Texas               -41.940111
48        Taylor County, Texas               -47.694148
49          Webb County, Texas               -51.628923
50      Harrison County, Texas                      NaN
51          Hood County, Texas                      NaN
52   Nacogdoches County, Texas                      NaN
53         Starr County, Texas                      NaN
54     Van Zandt County, Texas                      NaN
55        Walker County, Texas                      NaN
56        Waller County, Texas                      NaN
57          Wise County, Texas                      NaN
                          name  pct_chg_migration_14_24
0        Kaufman County, Texas               135.525443
1        Bastrop County, Texas                75.631155
2        Randall County, Texas                74.856524
3         Collin County, Texas                63.660285
4        Midland County, Texas                62.969497
5        Johnson County, Texas                49.113150
6           Hunt County, Texas                47.111749
7      Guadalupe County, Texas                45.526614
8          Smith County, Texas                44.956230
9        Hidalgo County, Texas                41.107383
10         Bexar County, Texas                41.018843
11     Henderson County, Texas                33.095547
12          Hays County, Texas                31.806824
13         Ellis County, Texas                30.480521
14        Denton County, Texas                26.770242
15        Walker County, Texas                24.621407
16       Tarrant County, Texas                21.528088
17         Ector County, Texas                20.869038
18       Cameron County, Texas                20.233382
19    Williamson County, Texas                17.585482
20      Angelina County, Texas                16.885519
21       Coryell County, Texas                16.574508
22         Bowie County, Texas                16.100378
23        Harris County, Texas                14.388390
24      McLennan County, Texas                12.967947
25         Comal County, Texas                10.504729
26        Dallas County, Texas                 9.948179
27       Grayson County, Texas                 9.098183
28        Parker County, Texas                 8.888889
29      Harrison County, Texas                 8.602151
30        Travis County, Texas                 7.765346
31        Potter County, Texas                 5.611021
32      Victoria County, Texas                 4.117280
33      Brazoria County, Texas                 1.075019
34    Montgomery County, Texas                 0.479452
35          Bell County, Texas                 0.362186
36        Brazos County, Texas                -1.750037
37       El Paso County, Texas                -3.276030
38     Fort Bend County, Texas                -3.733442
39      Rockwall County, Texas                -6.736364
40       Lubbock County, Texas                -7.921230
41       Wichita County, Texas                -9.141316
42     Tom Green County, Texas               -10.356371
43  San Patricio County, Texas               -17.566191
44         Gregg County, Texas               -19.496988
45        Orange County, Texas               -20.276842
46     Galveston County, Texas               -23.378789
47     Jefferson County, Texas               -25.427035
48       Liberty County, Texas               -28.224746
49        Nueces County, Texas               -33.518592
50   Nacogdoches County, Texas               -39.221469
51          Webb County, Texas               -45.033860
52        Taylor County, Texas               -52.754523
53          Hood County, Texas                      NaN
54         Starr County, Texas                      NaN
55     Van Zandt County, Texas                      NaN
56        Waller County, Texas                      NaN
57          Wise County, Texas                      NaN
                          name  pct_chg_migration_19_24
0         Potter County, Texas                97.682167
1         Walker County, Texas                81.228464
2           Hunt County, Texas                76.088653
3         Parker County, Texas                68.920011
4           Hays County, Texas                67.241294
5          Smith County, Texas                38.303021
6        Cameron County, Texas                36.616550
7      Guadalupe County, Texas                35.969244
8         Orange County, Texas                33.646911
9          Bexar County, Texas                30.177038
10       Coryell County, Texas                30.157862
11        Collin County, Texas                28.519637
12         Ector County, Texas                26.872562
13       Kaufman County, Texas                22.077603
14        Denton County, Texas                20.729798
15      Angelina County, Texas                20.495710
16       Johnson County, Texas                20.059094
17       Tarrant County, Texas                20.019103
18    Montgomery County, Texas                19.500876
19       Bastrop County, Texas                17.967529
20        Dallas County, Texas                17.677983
21       Midland County, Texas                16.940928
22        Harris County, Texas                16.703587
23         Bowie County, Texas                15.587000
24      Brazoria County, Texas                11.792259
25     Henderson County, Texas                11.479269
26       Randall County, Texas                10.580018
27      Victoria County, Texas                10.407938
28         Ellis County, Texas                10.227444
29       Wichita County, Texas                 6.771154
30          Wise County, Texas                 4.224092
31        Travis County, Texas                 4.190818
32        Brazos County, Texas                 3.568207
33         Comal County, Texas                 2.317291
34    Williamson County, Texas                 1.951855
35     Fort Bend County, Texas                -0.966104
36      McLennan County, Texas                -0.975871
37       Hidalgo County, Texas                -1.787943
38       Grayson County, Texas                -6.905296
39  San Patricio County, Texas                -7.114171
40          Bell County, Texas                -7.615972
41       El Paso County, Texas                -9.121598
42   Nacogdoches County, Texas               -11.734475
43     Jefferson County, Texas               -13.258110
44     Tom Green County, Texas               -14.387376
45      Rockwall County, Texas               -17.098990
46        Nueces County, Texas               -21.618389
47       Lubbock County, Texas               -27.076519
48     Galveston County, Texas               -29.739373
49         Gregg County, Texas               -33.681553
50          Webb County, Texas               -45.256295
51        Taylor County, Texas               -49.447374
52       Liberty County, Texas               -54.027565
53      Harrison County, Texas               -54.104817
54          Hood County, Texas                      NaN
55         Starr County, Texas                      NaN
56     Van Zandt County, Texas                      NaN
57        Waller County, Texas                      NaN

{'pct_chg_migration_05_24':                           name  pct_chg_migration_05_24
 0        Midland County, Texas               248.397234
 1           Hunt County, Texas               232.508105
 2        Bastrop County, Texas               230.826307
 3        Kaufman County, Texas               226.609724
 4          Ector County, Texas               199.605263
 5           Hays County, Texas               124.803569
 6         Brazos County, Texas                93.648208
 7     Williamson County, Texas                85.874606
 8        Lubbock County, Texas                80.895458
 9      Guadalupe County, Texas                62.192864
 10        Potter County, Texas                56.850575
 11       Randall County, Texas                55.568401
 12         Bexar County, Texas                52.315018
 13         Comal County, Texas                51.468564
 14       El Paso County, Texas                50.652884
 15       Johnson County, Texas                50.633302
 16        Denton County, Texas                48.540891
 17         Ellis County, Texas                48.392984
 18        Collin County, Texas                46.611617
 19        Travis County, Texas                46.190896
 20     Fort Bend County, Texas                45.299237
 21       Grayson County, Texas                40.719446
 22       Coryell County, Texas                37.576408
 23        Dallas County, Texas                34.435864
 24     Tom Green County, Texas                34.429150
 25       Wichita County, Texas                34.241116
 26       Tarrant County, Texas                33.683946
 27        Harris County, Texas                26.980364
 28        Parker County, Texas                25.641026
 29      Angelina County, Texas                22.362052
 30      McLennan County, Texas                21.644052
 31    Montgomery County, Texas                15.398918
 32      Brazoria County, Texas                 5.951510
 33         Smith County, Texas                 5.376472
 34     Henderson County, Texas                 2.106136
 35          Bell County, Texas                -2.081550
 36         Gregg County, Texas                -3.508550
 37      Victoria County, Texas               -11.128860
 38     Jefferson County, Texas               -12.765957
 39       Cameron County, Texas               -16.388929
 40     Galveston County, Texas               -17.595249
 41        Orange County, Texas               -19.142478
 42       Hidalgo County, Texas               -22.724248
 43         Bowie County, Texas               -24.755325
 44        Nueces County, Texas               -25.720763
 45        Taylor County, Texas               -26.398822
 46       Liberty County, Texas               -26.700037
 47  San Patricio County, Texas               -35.792187
 48          Webb County, Texas               -49.005236
 49      Harrison County, Texas                      NaN
 50          Hood County, Texas                      NaN
 51   Nacogdoches County, Texas                      NaN
 52      Rockwall County, Texas                      NaN
 53         Starr County, Texas                      NaN
 54     Van Zandt County, Texas                      NaN
 55        Walker County, Texas                      NaN
 56        Waller County, Texas                      NaN
 57          Wise County, Texas                      NaN,
 'pct_chg_migration_09_24':                           name  pct_chg_migration_09_24
 0        Midland County, Texas               149.039650
 1        Bastrop County, Texas               122.224739
 2        Kaufman County, Texas                86.249532
 3      Guadalupe County, Texas                79.636533
 4           Hunt County, Texas                78.512658
 5       Angelina County, Texas                73.435785
 6         Collin County, Texas                71.871329
 7           Hays County, Texas                61.698357
 8          Ector County, Texas                55.867397
 9        Randall County, Texas                54.659515
 10         Bexar County, Texas                53.371780
 11       Coryell County, Texas                48.612474
 12     Fort Bend County, Texas                48.094137
 13        Denton County, Texas                43.226599
 14         Comal County, Texas                42.401035
 15        Parker County, Texas                34.809242
 16    Williamson County, Texas                33.823893
 17        Harris County, Texas                33.021751
 18       Tarrant County, Texas                32.222840
 19        Brazos County, Texas                27.029915
 20        Travis County, Texas                25.607737
 21        Dallas County, Texas                23.608373
 22      Rockwall County, Texas                22.671290
 23     Galveston County, Texas                17.130233
 24       Johnson County, Texas                15.737005
 25     Henderson County, Texas                13.305116
 26         Smith County, Texas                11.042868
 27         Ellis County, Texas                10.685926
 28    Montgomery County, Texas                10.318347
 29       Grayson County, Texas                 9.448458
 30      Victoria County, Texas                 1.975560
 31       El Paso County, Texas                 0.777290
 32      McLennan County, Texas                -1.771182
 33       Hidalgo County, Texas                -2.747428
 34      Brazoria County, Texas                -2.975207
 35       Lubbock County, Texas                -5.082491
 36     Jefferson County, Texas                -5.649680
 37       Cameron County, Texas                -7.768542
 38       Wichita County, Texas                -9.783498
 39        Orange County, Texas               -12.753327
 40          Bell County, Texas               -14.995446
 41        Potter County, Texas               -24.428200
 42       Liberty County, Texas               -28.190408
 43         Gregg County, Texas               -30.238095
 44         Bowie County, Texas               -31.255753
 45        Nueces County, Texas               -32.509404
 46     Tom Green County, Texas               -35.785565
 47  San Patricio County, Texas               -41.940111
 48        Taylor County, Texas               -47.694148
 49          Webb County, Texas               -51.628923
 50      Harrison County, Texas                      NaN
 51          Hood County, Texas                      NaN
 52   Nacogdoches County, Texas                      NaN
 53         Starr County, Texas                      NaN
 54     Van Zandt County, Texas                      NaN
 55        Walker County, Texas                      NaN
 56        Waller County, Texas                      NaN
 57          Wise County, Texas                      NaN,
 'pct_chg_migration_14_24':                           name  pct_chg_migration_14_24
 0        Kaufman County, Texas               135.525443
 1        Bastrop County, Texas                75.631155
 2        Randall County, Texas                74.856524
 3         Collin County, Texas                63.660285
 4        Midland County, Texas                62.969497
 5        Johnson County, Texas                49.113150
 6           Hunt County, Texas                47.111749
 7      Guadalupe County, Texas                45.526614
 8          Smith County, Texas                44.956230
 9        Hidalgo County, Texas                41.107383
 10         Bexar County, Texas                41.018843
 11     Henderson County, Texas                33.095547
 12          Hays County, Texas                31.806824
 13         Ellis County, Texas                30.480521
 14        Denton County, Texas                26.770242
 15        Walker County, Texas                24.621407
 16       Tarrant County, Texas                21.528088
 17         Ector County, Texas                20.869038
 18       Cameron County, Texas                20.233382
 19    Williamson County, Texas                17.585482
 20      Angelina County, Texas                16.885519
 21       Coryell County, Texas                16.574508
 22         Bowie County, Texas                16.100378
 23        Harris County, Texas                14.388390
 24      McLennan County, Texas                12.967947
 25         Comal County, Texas                10.504729
 26        Dallas County, Texas                 9.948179
 27       Grayson County, Texas                 9.098183
 28        Parker County, Texas                 8.888889
 29      Harrison County, Texas                 8.602151
 30        Travis County, Texas                 7.765346
 31        Potter County, Texas                 5.611021
 32      Victoria County, Texas                 4.117280
 33      Brazoria County, Texas                 1.075019
 34    Montgomery County, Texas                 0.479452
 35          Bell County, Texas                 0.362186
 36        Brazos County, Texas                -1.750037
 37       El Paso County, Texas                -3.276030
 38     Fort Bend County, Texas                -3.733442
 39      Rockwall County, Texas                -6.736364
 40       Lubbock County, Texas                -7.921230
 41       Wichita County, Texas                -9.141316
 42     Tom Green County, Texas               -10.356371
 43  San Patricio County, Texas               -17.566191
 44         Gregg County, Texas               -19.496988
 45        Orange County, Texas               -20.276842
 46     Galveston County, Texas               -23.378789
 47     Jefferson County, Texas               -25.427035
 48       Liberty County, Texas               -28.224746
 49        Nueces County, Texas               -33.518592
 50   Nacogdoches County, Texas               -39.221469
 51          Webb County, Texas               -45.033860
 52        Taylor County, Texas               -52.754523
 53          Hood County, Texas                      NaN
 54         Starr County, Texas                      NaN
 55     Van Zandt County, Texas                      NaN
 56        Waller County, Texas                      NaN
 57          Wise County, Texas                      NaN,
 'pct_chg_migration_19_24':                           name  pct_chg_migration_19_24
 0         Potter County, Texas                97.682167
 1         Walker County, Texas                81.228464
 2           Hunt County, Texas                76.088653
 3         Parker County, Texas                68.920011
 4           Hays County, Texas                67.241294
 5          Smith County, Texas                38.303021
 6        Cameron County, Texas                36.616550
 7      Guadalupe County, Texas                35.969244
 8         Orange County, Texas                33.646911
 9          Bexar County, Texas                30.177038
 10       Coryell County, Texas                30.157862
 11        Collin County, Texas                28.519637
 12         Ector County, Texas                26.872562
 13       Kaufman County, Texas                22.077603
 14        Denton County, Texas                20.729798
 15      Angelina County, Texas                20.495710
 16       Johnson County, Texas                20.059094
 17       Tarrant County, Texas                20.019103
 18    Montgomery County, Texas                19.500876
 19       Bastrop County, Texas                17.967529
 20        Dallas County, Texas                17.677983
 21       Midland County, Texas                16.940928
 22        Harris County, Texas                16.703587
 23         Bowie County, Texas                15.587000
 24      Brazoria County, Texas                11.792259
 25     Henderson County, Texas                11.479269
 26       Randall County, Texas                10.580018
 27      Victoria County, Texas                10.407938
 28         Ellis County, Texas                10.227444
 29       Wichita County, Texas                 6.771154
 30          Wise County, Texas                 4.224092
 31        Travis County, Texas                 4.190818
 32        Brazos County, Texas                 3.568207
 33         Comal County, Texas                 2.317291
 34    Williamson County, Texas                 1.951855
 35     Fort Bend County, Texas                -0.966104
 36      McLennan County, Texas                -0.975871
 37       Hidalgo County, Texas                -1.787943
 38       Grayson County, Texas                -6.905296
 39  San Patricio County, Texas                -7.114171
 40          Bell County, Texas                -7.615972
 41       El Paso County, Texas                -9.121598
 42   Nacogdoches County, Texas               -11.734475
 43     Jefferson County, Texas               -13.258110
 44     Tom Green County, Texas               -14.387376
 45      Rockwall County, Texas               -17.098990
 46        Nueces County, Texas               -21.618389
 47       Lubbock County, Texas               -27.076519
 48     Galveston County, Texas               -29.739373
 49         Gregg County, Texas               -33.681553
 50          Webb County, Texas               -45.256295
 51        Taylor County, Texas               -49.447374
 52       Liberty County, Texas               -54.027565
 53      Harrison County, Texas               -54.104817
 54          Hood County, Texas                      NaN
 55         Starr County, Texas                      NaN
 56     Van Zandt County, Texas                      NaN
 57        Waller County, Texas                      NaN}

## ACS1 margins of error

In [45]:
smith_estimates = tx_counties[tx_counties['name'] == 'Smith County, Texas'].copy()
smith_estimates

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,state,county_code,year,total_in_migration
40,"Smith County, Texas",185465.0,48152.0,26026.0,35.4,49255.0,144741.0,20038.0,12408.0,3638.0,...,177.0,4081.0,3858.0,2456.0,1629.0,540.0,48,423,2005,16814.0
90,"Smith County, Texas",194635.0,48471.0,24303.0,35.2,49980.0,152096.0,24363.0,7647.0,4786.0,...,279.0,5212.0,4351.0,1975.0,1536.0,1034.0,48,423,2006,13726.0
122,"Smith County, Texas",198705.0,48396.0,24532.0,35.3,50624.0,154608.0,25920.0,10017.0,4053.0,...,251.0,5101.0,4337.0,2316.0,1380.0,432.0,48,423,2007,14573.0
172,"Smith County, Texas",201277.0,48756.0,24358.0,35.8,50898.0,161619.0,23302.0,10093.0,3134.0,...,329.0,5316.0,4955.0,2644.0,1990.0,703.0,48,423,2008,14059.0
225,"Smith County, Texas",204665.0,47517.0,21899.0,36.1,52773.0,165461.0,20022.0,11575.0,3633.0,...,0.0,4666.0,4029.0,3036.0,1409.0,627.0,48,423,2009,15956.0
291,"Smith County, Texas",210512.0,53601.0,26382.0,35.5,54236.0,166384.0,26636.0,10171.0,2857.0,...,524.0,5540.0,5242.0,2945.0,1916.0,1016.0,48,423,2010,14361.0
344,"Smith County, Texas",213381.0,53407.0,25992.0,35.6,54404.0,165910.0,25906.0,12872.0,6230.0,...,292.0,6348.0,4968.0,3165.0,2931.0,252.0,48,423,2011,19403.0
365,"Smith County, Texas",214821.0,54091.0,26429.0,36.0,54602.0,170460.0,21024.0,14251.0,5551.0,...,293.0,6012.0,4227.0,4031.0,2173.0,553.0,48,423,2012,20525.0
418,"Smith County, Texas",216080.0,53610.0,27734.0,36.2,54209.0,174730.0,22026.0,9675.0,5403.0,...,<NA>,6449.0,4986.0,2275.0,2022.0,313.0,48,423,2013,15526.0
470,"Smith County, Texas",218842.0,53239.0,25000.0,36.3,54587.0,178721.0,24562.0,8009.0,3510.0,...,57.0,5087.0,4560.0,2168.0,1540.0,519.0,48,423,2014,12223.0
542,"Smith County, Texas",222936.0,53257.0,25684.0,36.4,55292.0,190221.0,15197.0,11106.0,2564.0,...,275.0,4706.0,3331.0,2335.0,1203.0,503.0,48,423,2015,14372.0
587,"Smith County, Texas",225290.0,52685.0,22597.0,36.5,55690.0,187591.0,17535.0,12218.0,4018.0,...,819.0,5157.0,3074.0,4144.0,1929.0,720.0,48,423,2016,17338.0
636,"Smith County, Texas",227727.0,54767.0,25085.0,37.5,56044.0,198458.0,13748.0,8445.0,4121.0,...,232.0,4798.0,3389.0,2225.0,1915.0,421.0,48,423,2017,13253.0
717,"Smith County, Texas",230221.0,54682.0,25784.0,36.7,56559.0,205283.0,10558.0,9005.0,2870.0,...,164.0,4212.0,2900.0,2638.0,1135.0,442.0,48,423,2018,12447.0
767,"Smith County, Texas",232751.0,53826.0,27047.0,36.6,56590.0,206124.0,11381.0,8304.0,2578.0,...,176.0,4213.0,3341.0,2022.0,1299.0,1464.0,48,423,2019,12811.0
789,"Smith County, Texas",237186.0,56562.0,25715.0,37.4,57702.0,208772.0,14370.0,7613.0,2400.0,...,<NA>,4190.0,3406.0,2139.0,1407.0,661.0,48,423,2021,10981.0
878,"Smith County, Texas",241922.0,55528.0,25542.0,37.3,58091.0,215732.0,10347.0,9226.0,3504.0,...,<NA>,4373.0,2400.0,2599.0,1939.0,458.0,48,423,2022,13154.0
934,"Smith County, Texas",245209.0,57735.0,26556.0,38.2,58876.0,215472.0,13291.0,8231.0,3498.0,...,258.0,3949.0,3067.0,2261.0,2084.0,563.0,48,423,2023,12421.0
990,"Smith County, Texas",249091.0,63609.0,29924.0,37.5,59484.0,212063.0,16864.0,12795.0,4018.0,...,174.0,5081.0,3688.0,2587.0,1610.0,655.0,48,423,2024,17718.0

In [46]:
# Create migration confidence intervals dataframe
migration_data_acs1 = []

for year in smith_estimates['year'].unique():
    row = smith_estimates[smith_estimates['year'] == year].iloc[0]
    
    # Calculate total MOE by summing component MOEs
    total_moe = np.sqrt(
        row["moved_from_diff_county_same_state_moe"]**2 +
        row["moved_from_diff_state_moe"]**2 +
        row["moved_from_abroad_moe"]**2
    )
    
    migration_data_acs1.append({
        'year': year,
        'total_in_migration': row['total_in_migration'],
        'moe': total_moe,
        'lower_bound': row['total_in_migration'] - total_moe,
        'upper_bound': row['total_in_migration'] + total_moe
    })

smith_migration_acs1 = pd.DataFrame(migration_data_acs1)
smith_migration_acs1

    year  total_in_migration          moe   lower_bound   upper_bound
0   2005             16814.0  2996.193752  13817.806248  19810.193752
1   2006             13726.0  2707.226810  11018.773190  16433.226810
2   2007             14573.0  2730.362613  11842.637387  17303.362613
3   2008             14059.0  3383.052616  10675.947384  17442.052616
4   2009             15956.0  3405.246834  12550.753166  19361.246834
5   2010             14361.0  3657.367496  10703.632504  18018.367496
6   2011             19403.0  4321.051955  15081.948045  23724.051955
7   2012             20525.0  4612.667233  15912.332767  25137.667233
8   2013             15526.0  3059.751297  12466.248703  18585.751297
9   2014             12223.0  2709.462124   9513.537876  14932.462124
10  2015             14372.0  2674.405168  11697.594832  17046.405168
11  2016             17338.0  4627.329359  12710.670641  21965.329359
12  2017             13253.0  2965.651868  10287.348132  16218.651868
13  2018             12447.0  2905.620932   9541.379068  15352.620932
14  2019             12811.0  2814.103943   9996.896057  15625.103943
15  2021             10981.0  2644.218410   8336.781590  13625.218410
16  2022             13154.0  3274.795566   9879.204434  16428.795566
17  2023             12421.0  3126.043186   9294.956814  15547.043186
18  2024             17718.0  3116.679964  14601.320036  20834.679964

## ACS 5-year analysis

In [47]:
# Use helper function to create multiple pivot tables at once

# check out the data
county_pivots_acs5 = create_pivot_tables(
    df=tx_counties_acs5,
    index_cols=['county_code','name'],
    variable_names=['population', 'median_age', 'total_families', 'population_under_18', 'family_households_with_child']
)

tx_counties_acs5['total_in_migration'] = (
    tx_counties_acs5['moved_from_diff_county_same_state'] + 
    tx_counties_acs5['moved_from_diff_state'] + 
    tx_counties_acs5['moved_from_abroad']
)

county_tx_pop_acs5 = county_pivots_acs5['population']
county_tx_age_acs5 = county_pivots_acs5['median_age']
county_tx_families_acs5 = county_pivots_acs5['total_families']
county_tx_under18_acs5 = county_pivots_acs5['population_under_18']
county_tx_family_households_with_child_acs5 = county_pivots_acs5['family_households_with_child']

tx_counties_migration_acs5 = tx_counties_acs5.pivot(
    index=['county_code','name'],
    columns='year',
    values=['lived_in_same_house', 
            'moved_within_county', 
            'moved_from_diff_county_same_state',
            'moved_from_diff_state',
            'moved_from_abroad',
            'total_in_migration']
) 

# flatten cols so theyre not stacked
tx_counties_migration_acs5.columns = [
    f"{var}_{year}" for var, year in tx_counties_migration_acs5.columns
]

# reset index
tx_counties_migration_acs5 = tx_counties_migration_acs5.reset_index();

### Population change (ACS5)

In [48]:
county_tx_pop_acs5

year county_code                    name   2009   2014   2019   2024
0            001  Anderson County, Texas  56575  58084  57810  58439
1            003   Andrews County, Texas  13295  16126  18036  18610
2            005  Angelina County, Texas  82465  87433  87322  87275
3            007   Aransas County, Texas  24499  23889  24462  24876
4            009    Archer County, Texas   8936   8853   8716   8867
..           ...                     ...    ...    ...    ...    ...
249          499      Wood County, Texas  42104  42431  44366  46961
250          501    Yoakum County, Texas   7453   8054   8631   7571
251          503     Young County, Texas  17701  18374  18036  18029
252          505    Zapata County, Texas  13561  14231  14304  13841
253          507    Zavala County, Texas  11620  12013  12039   9412

[254 rows x 6 columns]

In [49]:
# ACS 5-year population change - only non-overlapping periods are valid
county_tx_pop_acs5['pct_change_19_24'] = ((county_tx_pop_acs5[2024] - county_tx_pop_acs5[2019]) / county_tx_pop_acs5[2019]) * 100 # 5 years
county_tx_pop_acs5['pct_change_14_24'] = ((county_tx_pop_acs5[2024] - county_tx_pop_acs5[2014]) / county_tx_pop_acs5[2014]) * 100 # 10 years
county_tx_pop_acs5['pct_change_09_24'] = ((county_tx_pop_acs5[2024] - county_tx_pop_acs5[2009]) / county_tx_pop_acs5[2009]) * 100 # 15 years

# Print ranked results
print_rankings(
    df=county_tx_pop_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                         name  pct_change_09_24
0              Hays County, Texas         90.023414
1        Williamson County, Texas         80.617445
2           Kaufman County, Texas         79.808944
3          Chambers County, Texas         76.375094
4         Fort Bend County, Texas         75.904105
5             Comal County, Texas         75.139101
6            Waller County, Texas         73.132313
7          Rockwall County, Texas         69.770923
8        Montgomery County, Texas         66.234826
9         Guadalupe County, Texas         63.576118
10           Denton County, Texas         60.100320
11           Collin County, Texas         59.467399
12          Kendall County, Texas         55.195884
13           Parker County, Texas         52.475906
14           Gaines County, Texas         49.811321
15            Ellis County, Texas         49.745694
16          Bastrop County, Texas         48.178734
17           Brazos County, Texas         41.386493
18             Bell County, Texas         40.386583
19          Andrews County, Texas         39.977435
20          Midland County, Texas         38.415672
21          Liberty County, Texas         37.948520
22           Blanco County, Texas         37.722696
23           Travis County, Texas         37.574333
24           Wilson County, Texas         35.221479
25         Brazoria County, Texas         33.852086
26             Hood County, Texas         33.496759
27             Hunt County, Texas         32.562892
28         Caldwell County, Texas         31.912183
29         Sterling County, Texas         31.777379
30            Bexar County, Texas         30.446670
31          Johnson County, Texas         30.331097
32             Wise County, Texas         30.183112
33          Randall County, Texas         29.492385
34            Ector County, Texas         27.650634
35          Tarrant County, Texas         27.123898
36        Galveston County, Texas         27.103102
37          Hidalgo County, Texas         26.936219
38           Walker County, Texas         25.467714
39        Somervell County, Texas         25.368693
40           Harris County, Texas         23.748411
41            Llano County, Texas         23.548209
42            Erath County, Texas         23.523439
43           Medina County, Texas         22.662299
44           Grimes County, Texas         22.321533
45            Smith County, Texas         22.318867
46           Borden County, Texas         21.880342
47          Grayson County, Texas         21.561660
48           Burnet County, Texas         21.312382
49          Lubbock County, Texas         21.255585
50        Van Zandt County, Texas         20.771485
51          El Paso County, Texas         19.383572
52           Dallam County, Texas         18.608809
53            Crane County, Texas         18.023554
54           Martin County, Texas         17.337531
55           Austin County, Texas         17.326006
56         Atascosa County, Texas         17.195111
57        Gillespie County, Texas         17.183243
58          Coryell County, Texas         16.705455
59             Webb County, Texas         16.559829
60         McLennan County, Texas         16.507494
61         La Salle County, Texas         16.092344
62      San Jacinto County, Texas         15.402719
63           Taylor County, Texas         15.227472
64             Frio County, Texas         15.158651
65            Rains County, Texas         15.048631
66           Reeves County, Texas         14.090090
67       Washington County, Texas         13.980468
68             Polk County, Texas         13.974874
69           Fannin County, Texas         13.508089
70         Burleson County, Texas         13.364194
71          Winkler County, Texas         13.231050
72         Maverick County, Texas         13.220273
73           Upshur County, Texas         13.104823
74             Kerr County, Texas         12.822189
75        Tom Green County, Texas         12.128316
76            Cooke County, Texas         12.028940
77          Navarro County, Texas         12.004831
78          Hopkins County, Texas         11.575715
79             Wood County, Texas         11.535721
80           Hardin County, Texas         11.269400
81          Cameron County, Texas         11.208834
82         Lampasas County, Texas         10.961848
83              Lee County, Texas         10.911560
84          Fayette County, Texas         10.707339
85         Harrison County, Texas         10.431621
86           Nueces County, Texas         10.400903
87           Lavaca County, Texas         10.304852
88           Dallas County, Texas          9.989107
89          Bandera County, Texas          9.355912
90             Rusk County, Texas          9.078524
91           Bailey County, Texas          8.694969
92        Robertson County, Texas          8.445989
93            Starr County, Texas          8.420310
94           Reagan County, Texas          8.383635
95             Ward County, Texas          8.225697
96         Cherokee County, Texas          8.003580
97            Garza County, Texas          7.906388
98            Titus County, Texas          7.735907
99        Henderson County, Texas          7.727071
100          Oldham County, Texas          7.659167
101        Montague County, Texas          7.613642
102        Hudspeth County, Texas          7.384033
103           Gregg County, Texas          7.338688
104         Jackson County, Texas          7.301183
105        Callahan County, Texas          7.075188
106      Palo Pinto County, Texas          6.717424
107           Moore County, Texas          6.301602
108        Victoria County, Texas          6.040183
109       Freestone County, Texas          5.877693
110        Angelina County, Texas          5.832778
111            Hill County, Texas          5.807988
112           Jones County, Texas          5.623472
113          Bosque County, Texas          5.457111
114           Upton County, Texas          4.760341
115       Jefferson County, Texas          4.616031
116         Haskell County, Texas          4.551591
117            Kent County, Texas          4.409673
118        Hamilton County, Texas          4.409390
119     Nacogdoches County, Texas          4.079351
120          Parmer County, Texas          3.543307
121       Ochiltree County, Texas          3.511741
122           Lamar County, Texas          3.420897
123         Madison County, Texas          3.378276
124          Orange County, Texas          3.376110
125        Anderson County, Texas          3.294741
126        Comanche County, Texas          3.203374
127           Milam County, Texas          3.175948
128        Brewster County, Texas          3.114149
129        Live Oak County, Texas          3.096442
130          Scurry County, Texas          3.088658
131         Terrell County, Texas          3.086420
132     Shackelford County, Texas          2.950713
133    San Patricio County, Texas          2.615803
134         Hartley County, Texas          2.475928
135            Camp County, Texas          2.474177
136        Colorado County, Texas          2.199085
137            Jack County, Texas          2.197676
138         Wharton County, Texas          2.138371
139         Wheeler County, Texas          2.078522
140          Zapata County, Texas          2.064744
141          Goliad County, Texas          1.926920
142           Young County, Texas          1.853003
143        Gonzales County, Texas          1.747822
144           Mason County, Texas          1.670951
145          Yoakum County, Texas          1.583255
146         Aransas County, Texas          1.538838
147          Castro County, Texas          1.534633
148           Falls County, Texas          1.425387
149         Wichita County, Texas          1.192552
150          DeWitt County, Texas          0.983805
151      Deaf Smith County, Texas          0.698233
152          Motley County, Texas          0.680851
153    Throckmorton County, Texas          0.552147
154       Val Verde County, Texas          0.437591
155           Brown County, Texas          0.319163
156           Bowie County, Texas          0.298342
157         Trinity County, Texas          0.292753
158           Delta County, Texas          0.073611
159          Howard County, Texas         -0.105185
160         Kleberg County, Texas         -0.189314
161       Limestone County, Texas         -0.375553
162           Tyler County, Texas         -0.501475
163          Karnes County, Texas         -0.610890
164          Archer County, Texas         -0.772158
165         Willacy County, Texas         -1.104891
166        Stephens County, Texas         -1.298290
167        Eastland County, Texas         -1.363636
168          Sabine County, Texas         -1.513216
169            Lynn County, Texas         -1.523712
170            Leon County, Texas         -1.543770
171          Panola County, Texas         -1.648851
172           Nolan County, Texas         -1.800394
173       Matagorda County, Texas         -1.834738
174          Kimble County, Texas         -2.140468
175        Hansford County, Texas         -2.420892
176         Houston County, Texas         -2.480984
177         Calhoun County, Texas         -2.531397
178        Lipscomb County, Texas         -2.538410
179            Cass County, Texas         -2.548184
180        Franklin County, Texas         -2.592762
181          Kinney County, Texas         -2.711864
182        Mitchell County, Texas         -2.770889
183            Gray County, Texas         -3.423432
184        San Saba County, Texas         -3.523035
185        Hemphill County, Texas         -3.835861
186            Coke County, Texas         -3.953022
187          Potter County, Texas         -3.991821
188             Bee County, Texas         -4.103292
189           Terry County, Texas         -4.319566
190         Hockley County, Texas         -4.454582
191            Knox County, Texas         -4.559885
192       McCulloch County, Texas         -4.801723
193         Runnels County, Texas         -4.838088
194        Jim Hogg County, Texas         -4.946712
195          Jasper County, Texas         -4.949028
196       Jim Wells County, Texas         -4.956454
197            Clay County, Texas         -5.467483
198            Real County, Texas         -5.529332
199          Morris County, Texas         -6.037971
200           Pecos County, Texas         -6.320357
201          Uvalde County, Texas         -6.543215
202            Lamb County, Texas         -6.644349
203      Hutchinson County, Texas         -6.904663
204          Brooks County, Texas         -7.117057
205          Carson County, Texas         -7.124560
206          Concho County, Texas         -7.811634
207          Marion County, Texas         -7.880795
208          Baylor County, Texas         -8.023225
209       Wilbarger County, Texas         -8.080146
210         Coleman County, Texas         -8.257203
211          Menard County, Texas         -8.302064
212          Shelby County, Texas         -8.357994
213         Swisher County, Texas         -8.831647
214         Roberts County, Texas         -8.871851
215         Refugio County, Texas         -8.921782
216          Fisher County, Texas         -9.260179
217   San Augustine County, Texas         -9.421374
218            King County, Texas         -9.442060
219       Armstrong County, Texas         -9.533267
220            Hale County, Texas         -9.579288
221           Mills County, Texas         -9.834100
222       Childress County, Texas        -10.451527
223       Stonewall County, Texas        -11.151340
224       Red River County, Texas        -11.203732
225       Culberson County, Texas        -11.348950
226          Donley County, Texas        -12.044288
227          Dawson County, Texas        -12.269539
228          Newton County, Texas        -12.540681
229   Collingsworth County, Texas        -13.531574
230          Dimmit County, Texas        -14.776772
231        Hardeman County, Texas        -14.858949
232      Jeff Davis County, Texas        -14.917883
233           Irion County, Texas        -16.030989
234      Schleicher County, Texas        -16.806429
235         Cochran County, Texas        -17.207792
236         Briscoe County, Texas        -17.814277
237            Hall County, Texas        -18.379161
238          Zavala County, Texas        -19.001721
239          Cottle County, Texas        -19.339623
240          Crosby County, Texas        -20.136248
241           Duval County, Texas        -20.140995
242         Sherman County, Texas        -20.998279
243        Presidio County, Texas        -21.311040
244           Floyd County, Texas        -21.951220
245          Sutton County, Texas        -23.255269
246       Glasscock County, Texas        -24.147727
247           Foard County, Texas        -25.151057
248        McMullen County, Texas        -25.373134
249        Crockett County, Texas        -25.422833
250         Dickens County, Texas        -29.528035
251         Edwards County, Texas        -32.389937
252          Kenedy County, Texas        -56.845238
253          Loving County, Texas        -59.259259
year                         name  pct_change_14_24
0           Kaufman County, Texas         61.132946
1             Comal County, Texas         58.733421
2              Hays County, Texas         57.642157
3          Rockwall County, Texas         48.508512
4        Williamson County, Texas         47.126316
5         Fort Bend County, Texas         41.207465
6          Chambers County, Texas         40.897401
7           Bastrop County, Texas         40.780367
8        Montgomery County, Texas         40.532372
9            Collin County, Texas         38.997690
10           Denton County, Texas         38.233655
11            Ellis County, Texas         38.014982
12           Parker County, Texas         37.888199
13           Waller County, Texas         37.316230
14          Liberty County, Texas         34.772576
15          Kendall County, Texas         34.691331
16        Guadalupe County, Texas         31.446077
17          Johnson County, Texas         27.131566
18             Hood County, Texas         25.879229
19         Caldwell County, Texas         25.209673
20             Hunt County, Texas         24.887687
21             Wise County, Texas         24.153742
22           Travis County, Texas         21.705969
23             Bell County, Texas         20.307160
24           Brazos County, Texas         20.233311
25         Brazoria County, Texas         20.209723
26           Gaines County, Texas         20.198962
27           Burnet County, Texas         19.906174
28          Midland County, Texas         19.410194
29        Van Zandt County, Texas         19.093242
30        Galveston County, Texas         18.762323
31           Wilson County, Texas         18.319173
32          Grayson County, Texas         17.513425
33           Blanco County, Texas         17.138824
34          Randall County, Texas         16.985152
35           Grimes County, Texas         16.887961
36           Walker County, Texas         16.444064
37            Llano County, Texas         16.355334
38            Rains County, Texas         16.263196
39            Bexar County, Texas         15.552784
40          Andrews County, Texas         15.403696
41             Polk County, Texas         15.392180
42          Tarrant County, Texas         15.196689
43           Medina County, Texas         14.014692
44          Navarro County, Texas         13.808167
45            Ector County, Texas         13.607761
46         Lampasas County, Texas         13.461538
47           Harris County, Texas         13.319607
48        Somervell County, Texas         13.014577
49            Smith County, Texas         12.575966
50            Cooke County, Texas         11.639608
51            Erath County, Texas         11.460640
52          Lubbock County, Texas         11.207441
53          Coryell County, Texas         11.107032
54         McLennan County, Texas         10.992128
55             Wood County, Texas         10.676157
56          Hidalgo County, Texas         10.605781
57           Fannin County, Texas         10.513694
58         Atascosa County, Texas         10.066245
59         Burleson County, Texas          9.404734
60        Gillespie County, Texas          9.313317
61           Taylor County, Texas          9.211590
62           Oldham County, Texas          8.752418
63           Austin County, Texas          8.515527
64         McMullen County, Texas          8.359133
65              Lee County, Texas          8.148282
66         Sterling County, Texas          7.941176
67       Washington County, Texas          7.661800
68        Henderson County, Texas          7.643716
69         Montague County, Texas          7.553148
70             Kerr County, Texas          7.162319
71     San Patricio County, Texas          7.131844
72           Dallas County, Texas          7.033075
73           Upshur County, Texas          6.815387
74          Bandera County, Texas          6.680554
75             Hill County, Texas          6.569218
76          Hopkins County, Texas          6.499803
77            Starr County, Texas          6.490974
78      San Jacinto County, Texas          6.000522
79           Lavaca County, Texas          5.731042
80          El Paso County, Texas          5.694764
81          Jackson County, Texas          5.691964
82           Borden County, Texas          5.473373
83         Callahan County, Texas          5.340632
84        Tom Green County, Texas          5.339335
85           Dallam County, Texas          4.901538
86            Milam County, Texas          4.834345
87         Harrison County, Texas          4.754297
88       Palo Pinto County, Texas          4.520480
89           Hardin County, Texas          4.395545
90          Aransas County, Texas          4.131609
91             Frio County, Texas          4.118339
92         Maverick County, Texas          4.050447
93            Delta County, Texas          3.798435
94             Webb County, Texas          3.785780
95        Robertson County, Texas          3.753173
96           Bosque County, Texas          3.517616
97     Throckmorton County, Texas          3.472222
98          Terrell County, Texas          3.213844
99           Orange County, Texas          3.106228
100            Coke County, Texas          2.852761
101        Victoria County, Texas          2.763195
102            Camp County, Texas          2.687956
103         Cameron County, Texas          2.654040
104        Brewster County, Texas          2.513484
105          Martin County, Texas          2.394035
106           Gregg County, Texas          2.235693
107       Freestone County, Texas          1.973450
108           Lamar County, Texas          1.941494
109        Cherokee County, Texas          1.795138
110        Hudspeth County, Texas          1.764354
111        Comanche County, Texas          1.417666
112         Wharton County, Texas          1.394988
113          Nueces County, Texas          1.385977
114         Fayette County, Texas          1.282103
115            Ward County, Texas          1.207883
116           Brown County, Texas          1.171411
117        Colorado County, Texas          1.131385
118           Jones County, Texas          1.055146
119          Motley County, Texas          0.938567
120        Hamilton County, Texas          0.912365
121         Winkler County, Texas          0.675311
122        Anderson County, Texas          0.611184
123          Karnes County, Texas          0.564364
124       Jefferson County, Texas          0.559283
125        Franklin County, Texas          0.301887
126           Crane County, Texas          0.173837
127          Archer County, Texas          0.158138

{'pct_change_09_24': year                      name  pct_change_09_24
 0           Hays County, Texas         90.023414
 1     Williamson County, Texas         80.617445
 2        Kaufman County, Texas         79.808944
 3       Chambers County, Texas         76.375094
 4      Fort Bend County, Texas         75.904105
 ..                         ...               ...
 249     Crockett County, Texas        -25.422833
 250      Dickens County, Texas        -29.528035
 251      Edwards County, Texas        -32.389937
 252       Kenedy County, Texas        -56.845238
 253       Loving County, Texas        -59.259259

 [254 rows x 2 columns],
 'pct_change_14_24': year                      name  pct_change_14_24
 0        Kaufman County, Texas         61.132946
 1          Comal County, Texas         58.733421
 2           Hays County, Texas         57.642157
 3       Rockwall County, Texas         48.508512
 4     Williamson County, Texas         47.126316
 ..                         ...               ...
 249         King County, Texas        -27.241379
 250   Schleicher County, Texas        -27.430661
 251      Edwards County, Texas        -36.671576
 252       Loving County, Texas        -62.921348
 253       Kenedy County, Texas        -72.537879

 [254 rows x 2 columns],
 'pct_change_19_24': year                     name  pct_change_19_24
 0       Kaufman County, Texas         39.417143
 1         Comal County, Texas         29.782127
 2      Rockwall County, Texas         27.210702
 3       Bastrop County, Texas         26.099714
 4          Hays County, Texas         25.904783
 ..                        ...               ...
 249     Sherman County, Texas        -24.975482
 250   Glasscock County, Texas        -29.271523
 251     Edwards County, Texas        -32.742440
 252      Loving County, Texas        -66.326531
 253      Kenedy County, Texas        -74.471831

 [254 rows x 2 columns]}

### Number of families (ACS5)

In [50]:
# ACS 5-year families change - only non-overlapping periods are valid
county_tx_families_acs5['pct_change_19_24'] = ((county_tx_families_acs5[2024] - county_tx_families_acs5[2019]) / county_tx_families_acs5[2019]) * 100 # 5 years
county_tx_families_acs5['pct_change_14_24'] = ((county_tx_families_acs5[2024] - county_tx_families_acs5[2014]) / county_tx_families_acs5[2014]) * 100 # 10 years
county_tx_families_acs5['pct_change_09_24'] = ((county_tx_families_acs5[2024] - county_tx_families_acs5[2009]) / county_tx_families_acs5[2009]) * 100 # 15 years

# Print ranked results
print_rankings(
    df=county_tx_families_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                         name  pct_change_09_24
0              Hays County, Texas        123.573773
1         Fort Bend County, Texas        103.856381
2        Williamson County, Texas         91.989684
3            Denton County, Texas         80.286680
4             Comal County, Texas         76.079218
5           Kaufman County, Texas         72.932065
6        Montgomery County, Texas         71.888188
7          Rockwall County, Texas         69.486911
8         Guadalupe County, Texas         67.092263
9           Bastrop County, Texas         64.299124
10           Collin County, Texas         62.928015
11           Parker County, Texas         60.386258
12        Somervell County, Texas         57.314974
13           Wilson County, Texas         53.593363
14            Ellis County, Texas         53.368553
15           Waller County, Texas         52.478483
16           Blanco County, Texas         52.161264
17          Kendall County, Texas         52.019804
18         Chambers County, Texas         50.338502
19           Brazos County, Texas         46.944823
20             Hood County, Texas         44.615748
21           Travis County, Texas         44.152747
22             Bell County, Texas         40.756352
23         Caldwell County, Texas         38.852657
24           Gaines County, Texas         38.809202
25             Wise County, Texas         36.712739
26            Erath County, Texas         36.475153
27          Johnson County, Texas         36.075079
28      San Jacinto County, Texas         35.960998
29          Midland County, Texas         35.763559
30           Grimes County, Texas         34.457965
31           Burnet County, Texas         34.371108
32            Bexar County, Texas         33.584983
33             Hunt County, Texas         33.088308
34         Brewster County, Texas         33.073551
35           Austin County, Texas         32.799517
36            Ector County, Texas         32.289718
37            Rains County, Texas         30.794224
38             King County, Texas         30.666667
39           Medina County, Texas         29.654640
40          Randall County, Texas         29.615358
41         Brazoria County, Texas         29.526961
42          Liberty County, Texas         29.276390
43        Galveston County, Texas         28.847440
44            Upton County, Texas         28.232190
45              Lee County, Texas         27.913085
46             Polk County, Texas         26.492470
47          Andrews County, Texas         25.953417
48          Tarrant County, Texas         25.360392
49           Harris County, Texas         25.060012
50         Lampasas County, Texas         23.785699
51             Webb County, Texas         23.705895
52            Llano County, Texas         23.484580
53          Jackson County, Texas         22.547195
54          Winkler County, Texas         22.383721
55         Maverick County, Texas         22.080275
56          Coryell County, Texas         21.915969
57          Hidalgo County, Texas         21.477242
58          Grayson County, Texas         21.441164
59            Starr County, Texas         20.107518
60           Walker County, Texas         20.080805
61            Smith County, Texas         19.648057
62          El Paso County, Texas         19.386757
63         Atascosa County, Texas         19.115370
64       Washington County, Texas         18.910832
65           Dallam County, Texas         18.745786
66         McLennan County, Texas         18.531338
67        Gillespie County, Texas         18.440893
68          Navarro County, Texas         17.729448
69         Anderson County, Texas         17.181485
70          Calhoun County, Texas         16.736631
71         Franklin County, Texas         16.386218
72          Lubbock County, Texas         16.369525
73            Garza County, Texas         16.201117
74             Wood County, Texas         16.180173
75        Van Zandt County, Texas         15.509654
76           Brooks County, Texas         14.973883
77           Hardin County, Texas         14.779025
78          Bandera County, Texas         14.436288
79           Borden County, Texas         14.204545
80            Delta County, Texas         13.798112
81      Nacogdoches County, Texas         13.538702
82         Cherokee County, Texas         13.141026
83          Madison County, Texas         12.617349
84        Freestone County, Texas         12.505664
85           Dallas County, Texas         12.437732
86             Ward County, Texas         12.409812
87           Martin County, Texas         12.121212
88      Shackelford County, Texas         12.019827
89          Cameron County, Texas         11.954309
90            Mason County, Texas         11.869436
91         Harrison County, Texas         11.851227
92            Cooke County, Texas         11.845036
93           Nueces County, Texas         10.731350
94             Coke County, Texas         10.332951
95           Taylor County, Texas         10.095561
96          Aransas County, Texas         10.092011
97           Fannin County, Texas          9.929935
98          Hopkins County, Texas          9.618304
99             Frio County, Texas          9.185143
100          Bosque County, Texas          9.064449
101         Hartley County, Texas          8.733205
102         Fayette County, Texas          8.601323
103         Wharton County, Texas          8.558985
104       Val Verde County, Texas          8.409050
105            Kerr County, Texas          8.205318
106          Upshur County, Texas          7.946568
107           Gregg County, Texas          7.431202
108           Terry County, Texas          7.174734
109       Henderson County, Texas          7.058662
110      Palo Pinto County, Texas          7.043991
111       Tom Green County, Texas          6.776337
112        Burleson County, Texas          6.748851
113        Gonzales County, Texas          6.578684
114          Motley County, Texas          6.484642
115          Lavaca County, Texas          6.397433
116            Hill County, Texas          6.069298
117        Angelina County, Texas          5.372536
118       Limestone County, Texas          5.108019
119        Montague County, Texas          5.020154
120         Terrell County, Texas          4.661017
121          Sabine County, Texas          4.024273
122        Colorado County, Texas          3.947368
123           Milam County, Texas          3.873448
124         Kleberg County, Texas          3.621365
125           Titus County, Texas          3.451869
126         Trinity County, Texas          3.031944
127        Live Oak County, Texas          2.916074
128        Eastland County, Texas          2.575016
129        Sterling County, Texas          2.416918
130        Victoria County, Texas          2.212758
131       Robertson County, Texas          2.124804
132           Falls County, Texas          1.722391
133            Jack County, Texas          1.547389
134            Leon County, Texas          1.460968
135            Camp County, Texas          1.423811
136            Rusk County, Texas          1.318122
137          Parmer County, Texas          0.801221
138           Jones County, Texas          0.599520
139          Kimble County, Texas          0.243902
140    San Patricio County, Texas          0.232468
141        Stephens County, Texas         -0.042391
142       Jim Wells County, Texas         -0.079177
143          Reeves County, Texas         -0.251708
144          Bailey County, Texas         -0.358423
145       Jefferson County, Texas         -0.466170
146          Baylor County, Texas         -0.749064
147         Wheeler County, Texas         -1.173223
148           Lamar County, Texas         -1.199620
149        Comanche County, Texas         -2.116962
150      Deaf Smith County, Texas         -2.223676
151           Mills County, Texas         -2.375479
152           Brown County, Texas         -2.552889
153          Howard County, Texas         -2.555430
154          Kinney County, Texas         -2.739726
155          Archer County, Texas         -3.622047
156          Jasper County, Texas         -3.629115
157          Panola County, Texas         -3.861789
158        Callahan County, Texas         -3.906674
159         Willacy County, Texas         -4.105901
160          Orange County, Texas         -4.238905
161         Houston County, Texas         -4.267527
162           Young County, Texas         -4.314477
163       Matagorda County, Texas         -4.488051
164       Armstrong County, Texas         -4.582651
165            Kent County, Texas         -4.687500
166        Hansford County, Texas         -4.751620
167           Bowie County, Texas         -4.773966
168           Moore County, Texas         -4.968203
169        La Salle County, Texas         -5.156250
170          Shelby County, Texas         -5.174787
171        San Saba County, Texas         -5.191257
172       Ochiltree County, Texas         -5.424811
173       Red River County, Texas         -5.982906
174          Morris County, Texas         -6.322506
175           Nolan County, Texas         -6.441948
176          Potter County, Texas         -6.528770
177         Wichita County, Texas         -6.885525
178           Crane County, Texas         -6.939799
179          Zavala County, Texas         -7.185406
180            Gray County, Texas         -7.708850
181       McCulloch County, Texas         -8.434864
182        Hamilton County, Texas         -8.454106
183         Hockley County, Texas         -8.468584
184          Fisher County, Texas         -8.865815
185          Yoakum County, Texas         -8.906526
186          Karnes County, Texas         -9.101416
187            Clay County, Texas         -9.142694
188          Zapata County, Texas         -9.246481
189            Hall County, Texas         -9.978541
190            Lynn County, Texas        -10.000000
191          Scurry County, Texas        -10.175358
192          Goliad County, Texas        -10.575049
193       Culberson County, Texas        -10.958904
194            Cass County, Texas        -10.989512
195          DeWitt County, Texas        -11.254538
196         Runnels County, Texas        -11.478261
197        Lipscomb County, Texas        -11.619718
198             Bee County, Texas        -11.811268
199       Glasscock County, Texas        -13.110540
200          Oldham County, Texas        -13.285458
201           Irion County, Texas        -13.580247
202            Real County, Texas        -14.044213
203          Newton County, Texas        -14.208971
204            Hale County, Texas        -14.849059
205          Castro County, Texas        -14.901257
206   Collingsworth County, Texas        -15.101070
207    Throckmorton County, Texas        -15.109344
208       Stonewall County, Texas        -15.113350
209            Lamb County, Texas        -15.271739
210           Tyler County, Texas        -15.332757
211          Cottle County, Texas        -15.835141
212          Uvalde County, Texas        -15.856970
213        Mitchell County, Texas        -15.913371
214   San Augustine County, Texas        -16.003153
215         Coleman County, Texas        -16.938250
216      Schleicher County, Texas        -16.964286
217          Menard County, Texas        -17.880795
218           Pecos County, Texas        -18.335862
219          Sutton County, Texas        -18.859246
220      Jeff Davis County, Texas        -18.918919
221            Knox County, Texas        -18.936567
222         Swisher County, Texas        -19.055649
223          Dawson County, Texas        -20.226092
224        Hemphill County, Texas        -20.641804
225         Haskell County, Texas        -21.237458
226          Reagan County, Texas        -21.237994
227        Crockett County, Texas        -21.264368
228        McMullen County, Texas        -21.658986
229         Refugio County, Texas        -21.702128
230          Crosby County, Texas        -21.976744
231          Carson County, Texas        -22.544283
232         Dickens County, Texas        -22.797927
233       Wilbarger County, Texas        -23.255172
234          Dimmit County, Texas        -23.762024
235         Sherman County, Texas        -27.352572
236          Marion County, Texas        -27.777778
237          Donley County, Texas        -28.026692
238        Presidio County, Texas        -28.555368
239         Briscoe County, Texas        -28.898129
240       Childress County, Texas        -29.101124
241        Hudspeth County, Texas        -29.331683
242      Hutchinson County, Texas        -29.396703
243          Concho County, Texas        -30.428954
244         Roberts County, Texas        -32.797428
245         Cochran County, Texas        -32.910053
246           Floyd County, Texas        -34.186882
247        Hardeman County, Texas        -36.485356
248           Duval County, Texas        -38.945300
249           Foard County, Texas        -39.320388
250        Jim Hogg County, Texas        -40.076336
251         Edwards County, Texas        -46.840959
252          Kenedy County, Texas        -67.647059
253          Loving County, Texas        -89.189189
year                         name  pct_change_14_24
0              Hays County, Texas         69.179150
1             Comal County, Texas         60.451639
2        Williamson County, Texas         53.354774
3        Montgomery County, Texas         47.107750
4         Fort Bend County, Texas         45.081402
5            Denton County, Texas         43.796889
6          Rockwall County, Texas         42.733686
7           Kaufman County, Texas         42.045950
8           Bastrop County, Texas         41.102811
9            Waller County, Texas         39.932014
10            Ellis County, Texas         38.702130
11         Chambers County, Texas         38.636592
12           Collin County, Texas         37.770378
13         Caldwell County, Texas         36.381969
14          Kendall County, Texas         35.086491
15           Parker County, Texas         34.928917
16        Guadalupe County, Texas         32.588891
17           Martin County, Texas         31.270627
18           Travis County, Texas         30.930798
19           Sabine County, Texas         29.606049
20             Hood County, Texas         28.990388
21             Hunt County, Texas         28.725486
22            Llano County, Texas         27.975753
23          Jackson County, Texas         27.779318
24           Burnet County, Texas         27.713899
25           Blanco County, Texas         27.694454
26              Lee County, Texas         26.225259
27          Midland County, Texas         25.339702
28           Brooks County, Texas         25.142135
29           Brazos County, Texas         24.768519
30          Liberty County, Texas         24.330321
31             Bell County, Texas         23.884140
32         Brewster County, Texas         23.508137
33          Johnson County, Texas         23.426531
34        Galveston County, Texas         23.220158
35        Van Zandt County, Texas         22.556108
36         Brazoria County, Texas         22.416014
37            Erath County, Texas         21.090626
38            Ector County, Texas         20.910874
39          Andrews County, Texas         20.701496
40            Rains County, Texas         19.927176
41             Wise County, Texas         19.744150
42             King County, Texas         19.512195
43          Coryell County, Texas         19.083016
44           Gaines County, Texas         18.947124
45       Washington County, Texas         17.908854
46            Bexar County, Texas         17.369777
47          Trinity County, Texas         17.324291
48         Gonzales County, Texas         17.271727
49          Grayson County, Texas         17.098350
50            Delta County, Texas         16.940299
51           Harris County, Texas         16.843447
52           Grimes County, Texas         16.800128
53          Wharton County, Texas         16.666667
54             Ward County, Texas         16.008935
55         Burleson County, Texas         15.457627
56          Hidalgo County, Texas         15.316338
57          Aransas County, Texas         14.926056
58           Walker County, Texas         14.735113
59             Webb County, Texas         14.404221
60            Milam County, Texas         14.299658
61           Wilson County, Texas         14.286860
62        Armstrong County, Texas         14.090020
63            Falls County, Texas         13.832200
64          Tarrant County, Texas         13.658233
65            Terry County, Texas         13.651256
66        Somervell County, Texas         13.540373
67           Austin County, Texas         13.536554
68        Henderson County, Texas         13.486970
69      San Jacinto County, Texas         13.350785
70           Medina County, Texas         13.245703
71           Reeves County, Texas         12.993890
72          Lubbock County, Texas         12.752540
73            Jones County, Texas         12.406217
74            Starr County, Texas         12.102149
75    San Augustine County, Texas         12.098895
76             Polk County, Texas         11.894061
77         Eastland County, Texas         11.884865
78          Randall County, Texas         11.740588
79             Kerr County, Texas         11.405977
80            Upton County, Texas         11.340206
81           Jasper County, Texas         11.023437
82         McLennan County, Texas         10.980624
83          Winkler County, Texas         10.906217
84          Calhoun County, Texas         10.791616
85             Wood County, Texas         10.767316
86       Palo Pinto County, Texas         10.731500
87         Comanche County, Texas         10.715355
88           Dallam County, Texas         10.615578
89          El Paso County, Texas         10.576121
90          Madison County, Texas         10.501105
91           Fannin County, Texas          9.731099
92           Bosque County, Texas          9.542702
93          Cameron County, Texas          9.467530
94            Cooke County, Texas          9.304307
95         Live Oak County, Texas          9.084056
96           Taylor County, Texas          9.053435
97         Harrison County, Texas          8.878066
98             Clay County, Texas          8.873720
99        Gillespie County, Texas          8.840238
100         Terrell County, Texas          8.810573
101       Matagorda County, Texas          8.293865
102       Robertson County, Texas          8.224698
103          Dallas County, Texas          8.022335
104          Motley County, Texas          7.958478
105          Fisher County, Texas          7.743154
106          Shelby County, Texas          7.656250
107          Upshur County, Texas          7.318728
108        San Saba County, Texas          6.933744
109          Baylor County, Texas          6.854839
110       Tom Green County, Texas          6.807367
111        Anderson County, Texas          6.739075
112    San Patricio County, Texas          6.674128
113           Smith County, Texas          6.666419
114       Val Verde County, Texas          6.520788
115        Callahan County, Texas          6.398318
116        Lampasas County, Texas          6.301468
117         Fayette County, Texas          6.023734
118          Hardin County, Texas          5.990421
119          Howard County, Texas          5.966490
120         Navarro County, Texas          5.693533
121     Nacogdoches County, Texas          5.562905
122          Parmer County, Texas          5.553336
123            Camp County, Texas          5.515285
124           Gregg County, Texas          5.310826
125        Atascosa County, Texas          5.296030
126            Hall County, Texas          5.269762
127           Nolan County, Texas          5.223252

{'pct_change_09_24': year                      name  pct_change_09_24
 0           Hays County, Texas        123.573773
 1      Fort Bend County, Texas        103.856381
 2     Williamson County, Texas         91.989684
 3         Denton County, Texas         80.286680
 4          Comal County, Texas         76.079218
 ..                         ...               ...
 249        Foard County, Texas        -39.320388
 250     Jim Hogg County, Texas        -40.076336
 251      Edwards County, Texas        -46.840959
 252       Kenedy County, Texas        -67.647059
 253       Loving County, Texas        -89.189189

 [254 rows x 2 columns],
 'pct_change_14_24': year                      name  pct_change_14_24
 0           Hays County, Texas         69.179150
 1          Comal County, Texas         60.451639
 2     Williamson County, Texas         53.354774
 3     Montgomery County, Texas         47.107750
 4      Fort Bend County, Texas         45.081402
 ..                         ...               ...
 249        Duval County, Texas        -31.090573
 250     Jim Hogg County, Texas        -38.527800
 251      Edwards County, Texas        -53.256705
 252       Kenedy County, Texas        -67.961165
 253       Loving County, Texas        -73.333333

 [254 rows x 2 columns],
 'pct_change_19_24': year                      name  pct_change_19_24
 0           King County, Texas        108.510638
 1        Bastrop County, Texas         41.110394
 2         Brooks County, Texas         38.920056
 3     Williamson County, Texas         35.757981
 4          Comal County, Texas         33.259221
 ..                         ...               ...
 249     Hardeman County, Texas        -27.988615
 250     Jim Hogg County, Texas        -33.418151
 251      Edwards County, Texas        -45.168539
 252       Kenedy County, Texas        -78.431373
 253       Loving County, Texas        -80.000000

 [254 rows x 2 columns]}

### Family households with children under 18 (ACS5)

In [51]:
# ACS 5-year family households with children change - only non-overlapping periods are valid
county_tx_family_households_with_child_acs5['pct_change_19_24'] = ((county_tx_family_households_with_child_acs5[2024] - county_tx_family_households_with_child_acs5[2019]) / county_tx_family_households_with_child_acs5[2019]) * 100 # 5 years
county_tx_family_households_with_child_acs5['pct_change_14_24'] = ((county_tx_family_households_with_child_acs5[2024] - county_tx_family_households_with_child_acs5[2014]) / county_tx_family_households_with_child_acs5[2014]) * 100 # 10 years
county_tx_family_households_with_child_acs5['pct_change_09_24'] = ((county_tx_family_households_with_child_acs5[2024] - county_tx_family_households_with_child_acs5[2009]) / county_tx_family_households_with_child_acs5[2009]) * 100 # 15 years

# Print ranked results
print_rankings(
    df=county_tx_family_households_with_child_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                         name  pct_change_09_24
0              King County, Texas        177.777778
1              Hays County, Texas        110.952226
2         Somervell County, Texas         86.573427
3           Kaufman County, Texas         84.843162
4         Fort Bend County, Texas         82.699973
5        Williamson County, Texas         77.476498
6         Guadalupe County, Texas         62.432809
7        Montgomery County, Texas         62.424296
8            Denton County, Texas         55.906206
9             Mason County, Texas         55.862069
10         Rockwall County, Texas         55.520737
11            Comal County, Texas         54.314054
12           Parker County, Texas         51.928850
13           Collin County, Texas         49.215962
14          Kendall County, Texas         48.808681
15           Waller County, Texas         47.409326
16          Midland County, Texas         45.723434
17            Rains County, Texas         45.218418
18          Andrews County, Texas         44.867886
19           Gaines County, Texas         43.166506
20          Madison County, Texas         41.890639
21          Bastrop County, Texas         41.208459
22           Wilson County, Texas         40.439607
23           Grimes County, Texas         38.985256
24            Ector County, Texas         38.185095
25          Jackson County, Texas         37.530713
26           Brazos County, Texas         37.018783
27            Ellis County, Texas         36.404689
28          Liberty County, Texas         35.388825
29             Hood County, Texas         34.757552
30         McMullen County, Texas         34.246575
31            Erath County, Texas         33.699835
32             Polk County, Texas         33.697552
33           Austin County, Texas         32.568807
34             Bell County, Texas         31.690376
35         Chambers County, Texas         31.308500
36             Wise County, Texas         29.832833
37          Johnson County, Texas         27.555395
38           Burnet County, Texas         26.699235
39           Bailey County, Texas         26.675258
40             Hunt County, Texas         26.418298
41        Freestone County, Texas         26.098465
42         Brewster County, Texas         25.529412
43        Gillespie County, Texas         25.190840
44           Martin County, Texas         24.137931
45           Travis County, Texas         23.897113
46           Borden County, Texas         23.863636
47          Winkler County, Texas         23.684211
48         Caldwell County, Texas         22.943430
49            Bexar County, Texas         22.660584
50            Mills County, Texas         21.768707
51           Dallam County, Texas         21.474774
52         Sterling County, Texas         21.379310
53      San Jacinto County, Texas         20.904779
54         Live Oak County, Texas         20.408163
55             Ward County, Texas         20.332851
56           Medina County, Texas         20.284767
57         Brazoria County, Texas         19.187265
58            Starr County, Texas         18.457584
59            Delta County, Texas         17.051510
60             Jack County, Texas         16.966292
61          Randall County, Texas         16.818575
62            Terry County, Texas         15.842294
63          Grayson County, Texas         14.325489
64              Lee County, Texas         14.240791
65             Coke County, Texas         13.880126
66            Smith County, Texas         13.319672
67            Llano County, Texas         12.608444
68       Washington County, Texas         12.464907
69           Harris County, Texas         12.212396
70        Galveston County, Texas         12.022773
71             Wood County, Texas         11.959895
72          Tarrant County, Texas         11.799868
73           Lavaca County, Texas         11.701128
74          Navarro County, Texas         11.587763
75         Anderson County, Texas         11.529700
76           Walker County, Texas         11.248261
77        Val Verde County, Texas         10.605570
78         Maverick County, Texas         10.120413
79           Kimble County, Texas          9.930716
80             Webb County, Texas          9.736029
81         McLennan County, Texas          9.655148
82          Wheeler County, Texas          9.615385
83          Lubbock County, Texas          9.267261
84           Fannin County, Texas          8.829415
85           Oldham County, Texas          8.627451
86            Cooke County, Texas          8.338114
87           Hardin County, Texas          7.403651
88         Atascosa County, Texas          7.334299
89         Angelina County, Texas          6.781694
90            Gregg County, Texas          6.633845
91           Morris County, Texas          6.161137
92           Dawson County, Texas          6.004289
93      Nacogdoches County, Texas          5.991823
94             Frio County, Texas          5.612829
95          Hidalgo County, Texas          5.560617
96           Taylor County, Texas          5.354610
97         Hansford County, Texas          5.194805
98          El Paso County, Texas          4.271033
99         Franklin County, Texas          4.247461
100         Hopkins County, Texas          4.207274
101            Rusk County, Texas          3.714144
102        Harrison County, Texas          3.379302
103            Hill County, Texas          2.677652
104       Henderson County, Texas          2.535774
105         Aransas County, Texas          2.517986
106        Lampasas County, Texas          1.857969
107          Upshur County, Texas          1.716224
108          Brooks County, Texas          1.662971
109          Fisher County, Texas          1.621622
110       Limestone County, Texas          1.390498
111         Coryell County, Texas          0.916784
112           Upton County, Texas          0.652174
113         Bandera County, Texas          0.517331
114        Cherokee County, Texas          0.191174
115         Hartley County, Texas         -0.557621
116       Van Zandt County, Texas         -0.702610
117      Deaf Smith County, Texas         -0.781250
118       Tom Green County, Texas         -0.781690
119          Howard County, Texas         -0.923361
120          Scurry County, Texas         -1.002865
121          Yoakum County, Texas         -1.228324
122            Camp County, Texas         -1.284404
123           Milam County, Texas         -1.484523
124        Montague County, Texas         -2.100494
125         Fayette County, Texas         -2.400295
126        Gonzales County, Texas         -2.578342
127     Shackelford County, Texas         -2.597403
128          Dallas County, Texas         -2.775115
129       Jim Wells County, Texas         -2.906671
130          Baylor County, Texas         -3.076923
131          Nueces County, Texas         -3.339127
132          Panola County, Texas         -3.442569
133          Sabine County, Texas         -3.700516
134           Crane County, Texas         -4.084720
135    Throckmorton County, Texas         -4.117647
136       Ochiltree County, Texas         -4.169715
137          Reeves County, Texas         -4.216444
138           Lamar County, Texas         -4.553652
139            Lynn County, Texas         -4.831461
140          Archer County, Texas         -5.157343
141           Jones County, Texas         -5.167173
142       Jefferson County, Texas         -5.810472
143        Comanche County, Texas         -6.023392
144   Collingsworth County, Texas         -6.153846
145          Orange County, Texas         -6.425165
146         Trinity County, Texas         -6.529714
147           Titus County, Texas         -6.554433
148         Swisher County, Texas         -6.731946
149        Hamilton County, Texas         -6.931964
150          Reagan County, Texas         -7.090909
151        Lipscomb County, Texas         -7.191011
152         Cameron County, Texas         -7.417928
153         Calhoun County, Texas         -7.424033
154        Eastland County, Texas         -8.390333
155        Victoria County, Texas         -8.562385
156           Young County, Texas         -8.781075
157       Robertson County, Texas         -9.055118
158         Kleberg County, Texas         -9.489415
159       Red River County, Texas         -9.526736
160          Bosque County, Texas         -9.643984
161          Parmer County, Texas         -9.712722
162        Burleson County, Texas         -9.789609
163         Wharton County, Texas         -9.832134
164          Zapata County, Texas        -10.022676
165          Zavala County, Texas        -10.193548
166          Potter County, Texas        -10.783329
167         Hockley County, Texas        -11.052956
168        La Salle County, Texas        -11.227545
169           Nolan County, Texas        -11.360239
170            Gray County, Texas        -11.533289
171          Karnes County, Texas        -11.667555
172           Bowie County, Texas        -11.706874
173           Falls County, Texas        -11.844156
174          Uvalde County, Texas        -12.420470
175             Bee County, Texas        -12.768362
176         Houston County, Texas        -12.932674
177    San Patricio County, Texas        -13.005632
178      Palo Pinto County, Texas        -13.129399
179            Kerr County, Texas        -13.572459
180           Garza County, Texas        -13.765182
181            Leon County, Texas        -13.938754
182        Stephens County, Texas        -13.979417
183       Glasscock County, Texas        -14.358974
184          Shelby County, Texas        -14.378921
185          Jasper County, Texas        -14.499901
186       Matagorda County, Texas        -15.067709
187         Willacy County, Texas        -15.372610
188      Jeff Davis County, Texas        -16.086957
189          DeWitt County, Texas        -16.199813
190            Cass County, Texas        -17.275665
191            Lamb County, Texas        -17.460317
192           Moore County, Texas        -18.024156
193      Schleicher County, Texas        -18.061674
194         Wichita County, Texas        -18.449516
195            Clay County, Texas        -18.595579
196           Tyler County, Texas        -18.837898
197          Crosby County, Texas        -19.025522
198          Blanco County, Texas        -19.086460
199       Armstrong County, Texas        -19.557196
200          Cottle County, Texas        -19.565217
201           Brown County, Texas        -19.613948
202          Goliad County, Texas        -19.928826
203          Carson County, Texas        -20.441989
204          Castro County, Texas        -20.492454
205            Hall County, Texas        -20.645161
206       Stonewall County, Texas        -21.176471
207            Hale County, Texas        -21.687910
208         Coleman County, Texas        -22.222222
209        San Saba County, Texas        -22.471910
210           Pecos County, Texas        -22.635589
211        Jim Hogg County, Texas        -23.100304
212       Childress County, Texas        -23.112128
213          Newton County, Texas        -23.213195
214            Knox County, Texas        -23.427332
215        Callahan County, Texas        -23.465046
216       McCulloch County, Texas        -24.278075
217        Mitchell County, Texas        -24.671053
218        Crockett County, Texas        -25.418060
219         Dickens County, Texas        -27.099237
220       Wilbarger County, Texas        -27.128713
221   San Augustine County, Texas        -27.360989
222        Colorado County, Texas        -27.663230
223          Motley County, Texas        -27.884615
224         Runnels County, Texas        -28.966914
225         Refugio County, Texas        -29.224230
226        Hemphill County, Texas        -31.327434
227        Hudspeth County, Texas        -31.828979
228          Menard County, Texas        -34.199134
229         Haskell County, Texas        -35.925926
230          Dimmit County, Texas        -36.308204
231           Irion County, Texas        -38.759690
232         Cochran County, Texas        -39.222615
233           Floyd County, Texas        -39.388935
234       Culberson County, Texas        -39.825581
235      Hutchinson County, Texas        -40.826709
236          Sutton County, Texas        -42.743222
237         Roberts County, Texas        -43.137255
238         Sherman County, Texas        -45.374449
239         Briscoe County, Texas        -45.454545
240          Concho County, Texas        -46.875000
241        Hardeman County, Texas        -47.191011
242         Edwards County, Texas        -48.936170
243          Kinney County, Texas        -49.285714
244        Presidio County, Texas        -49.695740
245            Real County, Texas        -49.820789
246          Donley County, Texas        -51.797040
247           Duval County, Texas        -53.559127
248          Marion County, Texas        -55.840100
249         Terrell County, Texas        -60.447761
250            Kent County, Texas        -61.538462
251           Foard County, Texas        -66.511628
252          Kenedy County, Texas        -80.851064
253          Loving County, Texas       -100.000000
year                         name  pct_change_14_24
0          McMullen County, Texas        151.282051
1              King County, Texas        117.391304
2              Hays County, Texas         56.341828
3            Waller County, Texas         49.585440
4             Comal County, Texas         49.210155
5           Kendall County, Texas         47.279944
6           Kaufman County, Texas         45.171462
7           Jackson County, Texas         44.451613
8        Williamson County, Texas         44.095244
9               Lee County, Texas         42.865169
10       Montgomery County, Texas         42.241889
11           Sabine County, Texas         39.352428
12          Midland County, Texas         37.120825
13        Fort Bend County, Texas         36.660053
14           Parker County, Texas         36.574012
15         Rockwall County, Texas         36.421699
16           Newton County, Texas         36.038961
17         Chambers County, Texas         33.996101
18           Fisher County, Texas         33.649289
19      San Jacinto County, Texas         32.613045
20          Liberty County, Texas         32.257401
21    San Augustine County, Texas         31.469649
22        Guadalupe County, Texas         31.208791
23             Hunt County, Texas         30.808185
24          Trinity County, Texas         30.532787
25            Llano County, Texas         30.408573
26           Jasper County, Texas         29.994001
27          Andrews County, Texas         29.826958
28             Wood County, Texas         29.809023
29         Caldwell County, Texas         29.480180
30          Winkler County, Texas         29.449153
31            Ellis County, Texas         29.269292
32          Bastrop County, Texas         28.987747
33           Oldham County, Texas         28.837209
34           Collin County, Texas         28.206422
35           Denton County, Texas         28.125428
36         Eastland County, Texas         27.717737
37            Ector County, Texas         26.910720
38            Delta County, Texas         24.105461
39         Comanche County, Texas         23.996914
40             Ward County, Texas         23.919523
41           Gaines County, Texas         22.933884
42             Hood County, Texas         22.356550
43         Burleson County, Texas         21.585648
44           Austin County, Texas         21.465026
45            Cooke County, Texas         21.358183
46             Jack County, Texas         20.486111
47        Van Zandt County, Texas         20.183964
48           Yoakum County, Texas         20.017559
49           Martin County, Texas         19.653179
50           Burnet County, Texas         19.443332
51           Fannin County, Texas         19.303537
52          Madison County, Texas         18.406806
53           Brazos County, Texas         18.196419
54           Borden County, Texas         17.204301
55           Brooks County, Texas         16.815287
56            Nolan County, Texas         16.808930
57           Travis County, Texas         16.565067
58         Sterling County, Texas         16.556291
59       Washington County, Texas         16.318235
60             Wise County, Texas         16.142638
61           Howard County, Texas         15.749730
62            Jones County, Texas         15.626930
63         Brewster County, Texas         15.601300
64             Bell County, Texas         15.591483
65            Erath County, Texas         15.287983
66        Gillespie County, Texas         15.267474
67          Grayson County, Texas         15.157585
68         Brazoria County, Texas         15.024455
69        Stonewall County, Texas         14.529915
70          Johnson County, Texas         14.465817
71            Falls County, Texas         14.122394
72           Wilson County, Texas         14.055459
73             Lynn County, Texas         13.997308
74           Taylor County, Texas         13.744257
75             Polk County, Texas         13.590791
76            Rains County, Texas         13.468635
77           Walker County, Texas         12.976695
78        Henderson County, Texas         12.075906
79            Terry County, Texas         12.066574
80        Galveston County, Texas         11.514297
81    Collingsworth County, Texas         11.488251
82         Lipscomb County, Texas         10.723861
83           Grimes County, Texas         10.708117
84           Reeves County, Texas         10.185934
85         Anderson County, Texas         10.083016
86           Upshur County, Texas          9.896507
87          Randall County, Texas          9.874226
88          Coryell County, Texas          9.811445
89        Val Verde County, Texas          9.471154
90            Bexar County, Texas          9.353805
91        Robertson County, Texas          9.133858
92            Starr County, Texas          8.666431
93           Harris County, Texas          8.267231
94          Aransas County, Texas          8.000000
95          Houston County, Texas          7.819124
96        Armstrong County, Texas          7.389163
97            Milam County, Texas          7.145311
98           Shelby County, Texas          6.858754
99            Mason County, Texas          6.855792
100         Lubbock County, Texas          6.726236
101            Rusk County, Texas          6.685997
102        Gonzales County, Texas          6.550976
103           Pecos County, Texas          6.411837
104          Medina County, Texas          6.181129
105            Clay County, Texas          5.922166
106           Gregg County, Texas          5.759359
107        McLennan County, Texas          5.741446
108          Kimble County, Texas          5.543237
109          Uvalde County, Texas          5.322688
110       Tom Green County, Texas          5.314696
111        Hamilton County, Texas          5.224964
112            Cass County, Texas          5.017356
113       Limestone County, Texas          4.958017
114        Lampasas County, Texas          4.889456
115          Karnes County, Texas          4.870335
116          Dallam County, Texas          4.799107
117          Panola County, Texas          4.514511
118         Tarrant County, Texas          4.497493
119          Scurry County, Texas          4.485887
120         Hidalgo County, Texas          4.469210
121           Titus County, Texas          4.440542
122          Orange County, Texas          4.337687
123        Cherokee County, Texas          4.208782
124            Webb County, Texas          3.969669
125            Hall County, Texas          3.651685
126        Harrison County, Texas          3.623910
127           Lamar County, Texas          3.402800

{'pct_change_09_24': year                     name  pct_change_09_24
 0          King County, Texas        177.777778
 1          Hays County, Texas        110.952226
 2     Somervell County, Texas         86.573427
 3       Kaufman County, Texas         84.843162
 4     Fort Bend County, Texas         82.699973
 ..                        ...               ...
 249     Terrell County, Texas        -60.447761
 250        Kent County, Texas        -61.538462
 251       Foard County, Texas        -66.511628
 252      Kenedy County, Texas        -80.851064
 253      Loving County, Texas       -100.000000

 [254 rows x 2 columns],
 'pct_change_14_24': year                    name  pct_change_14_24
 0     McMullen County, Texas        151.282051
 1         King County, Texas        117.391304
 2         Hays County, Texas         56.341828
 3       Waller County, Texas         49.585440
 4        Comal County, Texas         49.210155
 ..                       ...               ...
 249       Real County, Texas        -47.565543
 250     Kinney County, Texas        -51.202749
 251       Kent County, Texas        -70.930233
 252     Kenedy County, Texas        -80.434783
 253     Loving County, Texas       -100.000000

 [254 rows x 2 columns],
 'pct_change_19_24': year                    name  pct_change_19_24
 0         King County, Texas         92.307692
 1       Borden County, Texas         73.015873
 2     Eastland County, Texas         51.966717
 3     Live Oak County, Texas         47.149644
 4       Oldham County, Texas         45.789474
 ..                       ...               ...
 249      Foard County, Texas        -46.666667
 250     Motley County, Texas        -49.664430
 251       Kent County, Texas        -67.532468
 252     Kenedy County, Texas        -86.153846
 253     Loving County, Texas       -100.000000

 [254 rows x 2 columns]}

### Total people under 18 (ACS5)

In [52]:
# ACS 5-year population under 18 change - only non-overlapping periods are valid
county_tx_under18_acs5['pct_change_19_24'] = ((county_tx_under18_acs5[2024] - county_tx_under18_acs5[2019]) / county_tx_under18_acs5[2019]) * 100 # 5 years
county_tx_under18_acs5['pct_change_14_24'] = ((county_tx_under18_acs5[2024] - county_tx_under18_acs5[2014]) / county_tx_under18_acs5[2014]) * 100 # 10 years
county_tx_under18_acs5['pct_change_09_24'] = ((county_tx_under18_acs5[2024] - county_tx_under18_acs5[2009]) / county_tx_under18_acs5[2009]) * 100 # 15 years

# Print ranked results
print_rankings(
    df=county_tx_under18_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

year                         name  pct_change_09_24
0            Karnes County, Texas        134.894992
1            Borden County, Texas        107.438017
2          Sterling County, Texas         81.138790
3           Kaufman County, Texas         78.644934
4              Hays County, Texas         75.548041
5          Chambers County, Texas         74.115617
6            Waller County, Texas         62.604341
7            Gaines County, Texas         62.436238
8         Fort Bend County, Texas         57.813183
9             Comal County, Texas         57.232388
10          Liberty County, Texas         55.024547
11       Montgomery County, Texas         53.667005
12       Williamson County, Texas         53.030446
13         Rockwall County, Texas         52.228471
14        Guadalupe County, Texas         48.119747
15           Parker County, Texas         45.745366
16          Bastrop County, Texas         44.911528
17          Andrews County, Texas         43.889028
18          Midland County, Texas         43.053371
19           Martin County, Texas         41.507720
20         McMullen County, Texas         40.201005
21           Collin County, Texas         39.704254
22           Denton County, Texas         36.586312
23          Kendall County, Texas         36.485977
24            Ellis County, Texas         35.578084
25           Oldham County, Texas         31.562974
26           Brazos County, Texas         30.945351
27             Bell County, Texas         30.689562
28            Ector County, Texas         29.677737
29             Hunt County, Texas         29.405201
30           Dallam County, Texas         28.825431
31           Reagan County, Texas         23.717218
32         Brazoria County, Texas         22.982954
33             Hood County, Texas         22.762078
34          Johnson County, Texas         22.639760
35          Randall County, Texas         22.524901
36             Wise County, Texas         21.541306
37           Wilson County, Texas         18.646501
38          Grayson County, Texas         18.506415
39           Grimes County, Texas         17.488714
40             Knox County, Texas         16.553596
41        Van Zandt County, Texas         16.147263
42            Llano County, Texas         16.124707
43           Travis County, Texas         15.949061
44     Throckmorton County, Texas         15.666667
45          Lubbock County, Texas         15.549528
46        Galveston County, Texas         15.224165
47            Bexar County, Texas         14.874324
48            Smith County, Texas         14.461015
49          Tarrant County, Texas         13.970012
50             Polk County, Texas         13.693694
51         Caldwell County, Texas         13.663406
52          Winkler County, Texas         13.364535
53            Crane County, Texas         13.205980
54           Taylor County, Texas         13.124841
55           Walker County, Texas         12.059191
56          Madison County, Texas         11.245421
57            Erath County, Texas         11.011868
58           Harris County, Texas         10.804067
59        Gillespie County, Texas         10.560033
60          Navarro County, Texas         10.345610
61        Tom Green County, Texas         10.015110
62          Coryell County, Texas          9.952114
63         Lipscomb County, Texas          9.622412
64           Burnet County, Texas          9.557702
65           Lavaca County, Texas          9.383500
66           Reeves County, Texas          8.333333
67          Hidalgo County, Texas          8.265988
68         McLennan County, Texas          8.208689
69           Austin County, Texas          8.081705
70           Upshur County, Texas          7.690673
71      San Jacinto County, Texas          6.731775
72           Fannin County, Texas          6.281237
73         Atascosa County, Texas          6.187265
74             Ward County, Texas          5.750487
75         Montague County, Texas          5.695364
76         Mitchell County, Texas          5.482581
77          Hopkins County, Texas          5.473781
78         Burleson County, Texas          5.132114
79            Delta County, Texas          5.060241
80         Cherokee County, Texas          4.970643
81             Real County, Texas          4.806202
82           Hardin County, Texas          4.782545
83             Frio County, Texas          4.727107
84         Hamilton County, Texas          4.595792
85          Jackson County, Texas          4.280918
86       Washington County, Texas          4.009118
87        Jefferson County, Texas          3.939313
88           Scurry County, Texas          3.668580
89           Blanco County, Texas          3.559563
90         Harrison County, Texas          3.477086
91           Orange County, Texas          3.082567
92            Gregg County, Texas          3.078594
93             Rusk County, Texas          2.765096
94        Freestone County, Texas          2.604167
95      Nacogdoches County, Texas          2.105051
96           Medina County, Texas          1.976487
97            Rains County, Texas          1.782014
98           Baylor County, Texas          1.749664
99         Jim Hogg County, Texas          1.732179
100            Jack County, Texas          1.675978
101        Colorado County, Texas          1.639004
102          Yoakum County, Texas          1.223491
103            Coke County, Texas          0.848656
104          DeWitt County, Texas          0.404222
105           Terry County, Texas          0.280549
106        Comanche County, Texas          0.220195
107         Fayette County, Texas          0.198334
108            Wood County, Texas          0.068603
109            King County, Texas          0.000000
110           Lamar County, Texas         -0.220931
111        Live Oak County, Texas         -0.353669
112           Cooke County, Texas         -0.468407
113       Ochiltree County, Texas         -1.004352
114       Henderson County, Texas         -1.153679
115        Angelina County, Texas         -1.164353
116            Leon County, Texas         -1.201923
117         Roberts County, Texas         -1.310044
118         El Paso County, Texas         -1.317278
119       Robertson County, Texas         -1.390221
120           Moore County, Texas         -1.819258
121          Dallas County, Texas         -1.891141
122            Hill County, Texas         -2.085695
123           Bowie County, Texas         -2.100840
124        Anderson County, Texas         -2.175813
125          Menard County, Texas         -2.341920
126        Callahan County, Texas         -2.605965
127           Titus County, Texas         -2.633319
128        Maverick County, Texas         -2.749402
129            Webb County, Texas         -2.785187
130      Palo Pinto County, Texas         -2.853474
131         Hartley County, Texas         -3.010033
132            Gray County, Texas         -3.031994
133      Deaf Smith County, Texas         -3.175134
134          Nueces County, Texas         -3.344242
135            Camp County, Texas         -3.532453
136          Castro County, Texas         -3.655235
137        Victoria County, Texas         -3.660433
138           Young County, Texas         -3.961084
139           Nolan County, Texas         -4.005236
140            Cass County, Texas         -4.497394
141         Kleberg County, Texas         -4.710754
142            Lynn County, Texas         -4.821429
143          Howard County, Texas         -5.085848
144          Zapata County, Texas         -5.134315
145         Hockley County, Texas         -5.295587
146         Wichita County, Texas         -5.402387
147        Gonzales County, Texas         -5.618817
148            Kerr County, Texas         -5.766047
149          Bosque County, Texas         -5.822416
150         Wharton County, Texas         -5.916740
151           Starr County, Texas         -6.096388
152       Stonewall County, Texas         -6.666667
153       Val Verde County, Texas         -6.998880
154         Wheeler County, Texas         -7.030016
155           Upton County, Texas         -7.169345
156        La Salle County, Texas         -7.288450
157          Parmer County, Texas         -7.462173
158             Bee County, Texas         -7.599643
159        Eastland County, Texas         -7.645631
160          Fisher County, Texas         -7.888889
161       Limestone County, Texas         -7.937973
162          Potter County, Texas         -7.981695
163        Lampasas County, Texas         -8.141526
164          Panola County, Texas         -8.321678
165         Cameron County, Texas         -8.439767
166         Houston County, Texas         -9.018891
167        Franklin County, Texas         -9.320092
168       Matagorda County, Texas         -9.521489
169    San Patricio County, Texas         -9.747798
170          Kimble County, Texas         -9.903382
171           Pecos County, Texas        -10.382102
172         Trinity County, Texas        -10.441370
173       Somervell County, Texas        -10.567010
174           Mills County, Texas        -10.576923
175        Hansford County, Texas        -10.742787
176          Sabine County, Texas        -11.199602
177          Shelby County, Texas        -11.362032
178             Lee County, Texas        -11.542910
179          Morris County, Texas        -11.560510
180          Jasper County, Texas        -11.594708
181            Lamb County, Texas        -11.603750
182        Brewster County, Texas        -12.070875
183      Hutchinson County, Texas        -12.275501
184          Archer County, Texas        -12.355040
185           Jones County, Texas        -12.807507
186          Dawson County, Texas        -13.229228
187           Tyler County, Texas        -13.339282
188       Jim Wells County, Texas        -13.367630
189         Runnels County, Texas        -13.447889
190         Haskell County, Texas        -13.492063
191           Milam County, Texas        -13.966647
192        Hemphill County, Texas        -14.230272
193          Goliad County, Texas        -14.527845
194         Bandera County, Texas        -14.536517
195         Refugio County, Texas        -14.845120
196          Carson County, Texas        -15.166772
197           Falls County, Texas        -15.237205
198           Brown County, Texas        -15.442846
199          Bailey County, Texas        -15.942029
200       McCulloch County, Texas        -15.969388
201       Childress County, Texas        -16.009852
202        Stephens County, Texas        -16.480207
203          Uvalde County, Texas        -17.085743
204         Coleman County, Texas        -17.595908
205           Mason County, Texas        -17.608696
206         Calhoun County, Texas        -17.695398
207       Red River County, Texas        -17.696335
208   San Augustine County, Texas        -18.412863
209            Hale County, Texas        -18.553520
210            Clay County, Texas        -18.577707
211            Kent County, Texas        -19.090909
212     Shackelford County, Texas        -19.211823
213         Swisher County, Texas        -19.378339
214          Marion County, Texas        -21.288783
215         Aransas County, Texas        -22.307837
216       Armstrong County, Texas        -22.516556
217         Cochran County, Texas        -22.643554
218         Willacy County, Texas        -23.017158
219           Irion County, Texas        -23.076923
220   Collingsworth County, Texas        -23.216187
221          Newton County, Texas        -23.885976
222         Dickens County, Texas        -23.975410
223      Schleicher County, Texas        -24.828532
224          Zavala County, Texas        -26.636509
225       Wilbarger County, Texas        -27.086699
226       Culberson County, Texas        -27.183272
227         Terrell County, Texas        -27.638191
228          Donley County, Texas        -27.651515
229           Duval County, Texas        -27.971823
230          Concho County, Texas        -28.308824
231        Presidio County, Texas        -28.792135
232           Floyd County, Texas        -29.804129
233          Dimmit County, Texas        -30.012853
234          Crosby County, Texas        -30.394808
235        San Saba County, Texas        -30.440332
236           Garza County, Texas        -31.486146
237        Hudspeth County, Texas        -33.444075
238        Hardeman County, Texas        -33.865248
239         Edwards County, Texas        -33.928571
240            Hall County, Texas        -34.392114
241         Briscoe County, Texas        -34.939759
242          Brooks County, Texas        -35.178571
243        Crockett County, Texas        -35.299219
244          Sutton County, Texas        -36.498761
245      Jeff Davis County, Texas        -38.007380
246       Glasscock County, Texas        -38.480392
247          Motley County, Texas        -42.801556
248          Cottle County, Texas        -43.566591
249           Foard County, Texas        -54.268293
250         Sherman County, Texas        -57.598300
251          Kinney County, Texas        -68.275862
252          Kenedy County, Texas        -78.494624
253          Loving County, Texas       -100.000000
year                         name  pct_change_14_24
0          McMullen County, Texas        224.418605
1           Kaufman County, Texas         64.466013
2           Liberty County, Texas         60.775145
3             Comal County, Texas         51.111689
4              Hays County, Texas         46.649133
5           Bastrop County, Texas         41.692260
6          Chambers County, Texas         37.693732
7            Parker County, Texas         37.165757
8          Rockwall County, Texas         37.004350
9            Waller County, Texas         35.553906
10       Montgomery County, Texas         33.734976
11         Sterling County, Texas         33.246073
12        Fort Bend County, Texas         31.296489
13            Ellis County, Texas         30.249275
14           Borden County, Texas         28.061224
15       Williamson County, Texas         27.090233
16          Midland County, Texas         26.807101
17          Kendall County, Texas         26.465447
18           Oldham County, Texas         25.834543
19             Hunt County, Texas         25.762648
20           Gaines County, Texas         23.925903
21           Collin County, Texas         23.318639
22             Hood County, Texas         22.918949
23          Johnson County, Texas         22.320386
24          Andrews County, Texas         21.404471
25           Denton County, Texas         20.775946
26             Wise County, Texas         19.910092
27        Guadalupe County, Texas         18.235278
28          Grayson County, Texas         18.197413
29           Brazos County, Texas         17.992067
30           Grimes County, Texas         17.784110
31         Jim Hogg County, Texas         17.733231
32             Bell County, Texas         17.722403
33            Ector County, Texas         17.678336
34        Van Zandt County, Texas         16.278694
35         Caldwell County, Texas         15.503638
36          Terrell County, Texas         15.200000
37          Navarro County, Texas         14.242092
38          Randall County, Texas         13.168845
39         Brazoria County, Texas         12.850296
40             Polk County, Texas         12.832650
41        Galveston County, Texas         12.219233
42            Llano County, Texas         11.741935
43           Burnet County, Texas         10.762747
44           Dallam County, Texas         10.745716
45            Delta County, Texas         10.286678
46           Wilson County, Texas          9.982254
47             Coke County, Texas          9.523810
48        Culberson County, Texas          9.225092
49           Taylor County, Texas          9.210607
50          Madison County, Texas          9.048474
51        Gillespie County, Texas          8.651503
52           Fannin County, Texas          8.374656
53          Lubbock County, Texas          7.874933
54            Smith County, Texas          7.715117
55         Hamilton County, Texas          7.329545
56            Bexar County, Texas          7.227371
57            Rains County, Texas          7.202095
58           Reagan County, Texas          7.107601
59            Erath County, Texas          7.093957
60        Tom Green County, Texas          6.997249
61           Lavaca County, Texas          6.935520
62         Montague County, Texas          6.708268
63           Harris County, Texas          6.618480
64             Ward County, Texas          6.372549
65          Tarrant County, Texas          6.251449
66         McLennan County, Texas          6.184193
67             Frio County, Texas          5.741296
68           Walker County, Texas          5.653198
69           Orange County, Texas          5.567212
70       Washington County, Texas          5.122645
71            Cooke County, Texas          4.795383
72           Travis County, Texas          4.585345
73        Jefferson County, Texas          4.098634
74            Starr County, Texas          4.056215
75           Upshur County, Texas          3.830397
76         Burleson County, Texas          3.475869
77             Wood County, Texas          3.402647
78            Lamar County, Texas          3.356501
79         Atascosa County, Texas          3.295446
80     Throckmorton County, Texas          3.273810
81           Reeves County, Texas          3.116147
82             Real County, Texas          3.048780
83        Henderson County, Texas          2.888864
84             Hill County, Texas          2.784388
85            Gregg County, Texas          2.668745
86           Austin County, Texas          2.484211
87           Medina County, Texas          2.368939
88           Fisher County, Texas          2.345679
89         Mitchell County, Texas          2.326870
90           Hardin County, Texas          2.236399
91             Camp County, Texas          1.911408
92          Hopkins County, Texas          1.730257
93           Kimble County, Texas          1.358696
94             Lynn County, Texas          1.266624
95             Jack County, Texas          1.213347
96         Colorado County, Texas          1.177200
97          Hidalgo County, Texas          0.525837
98           Martin County, Texas          0.516129
99           Blanco County, Texas          0.506679
100           Mason County, Texas          0.397351
101         Jackson County, Texas          0.188172
102        Harrison County, Texas          0.000000
103           Crane County, Texas         -0.073314
104        Callahan County, Texas         -0.128783
105    San Patricio County, Texas         -0.149477
106      Palo Pinto County, Texas         -0.190560
107        Cherokee County, Texas         -0.419655
108       Robertson County, Texas         -0.579990
109        Anderson County, Texas         -0.665484
110     Nacogdoches County, Texas         -0.699850
111       Matagorda County, Texas         -0.727117
112       Freestone County, Texas         -0.896763
113       Somervell County, Texas         -0.904331
114          Dallas County, Texas         -1.082839
115          DeWitt County, Texas         -1.084071
116            Kerr County, Texas         -1.526718
117         Wichita County, Texas         -1.626016
118        Victoria County, Texas         -1.660160
119        Maverick County, Texas         -1.788850
120         Winkler County, Texas         -1.801802
121     San Jacinto County, Texas         -1.812931
122        Comanche County, Texas         -1.908867
123         Wharton County, Texas         -1.983944
124           Bowie County, Texas         -2.043920
125         Houston County, Texas         -2.119755
126        Lampasas County, Texas         -2.266748
127          Baylor County, Texas         -2.325581

{'pct_change_09_24': year                    name  pct_change_09_24
 0       Karnes County, Texas        134.894992
 1       Borden County, Texas        107.438017
 2     Sterling County, Texas         81.138790
 3      Kaufman County, Texas         78.644934
 4         Hays County, Texas         75.548041
 ..                       ...               ...
 249      Foard County, Texas        -54.268293
 250    Sherman County, Texas        -57.598300
 251     Kinney County, Texas        -68.275862
 252     Kenedy County, Texas        -78.494624
 253     Loving County, Texas       -100.000000

 [254 rows x 2 columns],
 'pct_change_14_24': year                    name  pct_change_14_24
 0     McMullen County, Texas        224.418605
 1      Kaufman County, Texas         64.466013
 2      Liberty County, Texas         60.775145
 3        Comal County, Texas         51.111689
 4         Hays County, Texas         46.649133
 ..                       ...               ...
 249    Sherman County, Texas        -52.836879
 250       Kent County, Texas        -53.645833
 251     Kinney County, Texas        -71.357410
 252     Kenedy County, Texas        -87.341772
 253     Loving County, Texas       -100.000000

 [254 rows x 2 columns],
 'pct_change_19_24': year                        name  pct_change_19_24
 0           Menard County, Texas         56.766917
 1     Throckmorton County, Texas         50.869565
 2          Kaufman County, Texas         44.601718
 3          Liberty County, Texas         41.603368
 4           Borden County, Texas         40.223464
 ..                           ...               ...
 249         Cottle County, Texas        -51.267057
 250         Motley County, Texas        -53.918495
 251           King County, Texas        -55.714286
 252         Kenedy County, Texas        -88.095238
 253         Loving County, Texas       -100.000000

 [254 rows x 2 columns]}

### Migration to the county (ACS5)

In [53]:
# ACS 5-year migration change - only non-overlapping periods are valid
tx_counties_migration_acs5['pct_chg_migration_09_24'] = ((tx_counties_migration_acs5['total_in_migration_2024'] - tx_counties_migration_acs5['total_in_migration_2009']) / tx_counties_migration_acs5['total_in_migration_2009'] * 100)
tx_counties_migration_acs5['pct_chg_migration_14_24'] = ((tx_counties_migration_acs5['total_in_migration_2024'] - tx_counties_migration_acs5['total_in_migration_2014']) / tx_counties_migration_acs5['total_in_migration_2014'] * 100)
tx_counties_migration_acs5['pct_chg_migration_19_24'] = ((tx_counties_migration_acs5['total_in_migration_2024'] - tx_counties_migration_acs5['total_in_migration_2019']) / tx_counties_migration_acs5['total_in_migration_2019'] * 100)

# Replace inf values with NaN (for counties that had zero migration in the base year)
tx_counties_migration_acs5.replace([float('inf'), float('-inf')], float('nan'), inplace=True)

# Print ranked results
print_rankings(
    df=tx_counties_migration_acs5,
    variable_names=['pct_chg_migration_09_24', 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

                            name  pct_chg_migration_09_24
0     Throckmorton County, Texas               411.111111
1           Oldham County, Texas               367.924528
2         Chambers County, Texas               187.765293
3         Hudspeth County, Texas               185.897436
4         Crockett County, Texas               178.160920
5            Mason County, Texas               148.333333
6          Runnels County, Texas               139.847716
7          Haskell County, Texas               124.844720
8          Coleman County, Texas               105.415162
9           Waller County, Texas               102.640374
10        Hansford County, Texas               102.040816
11          Martin County, Texas                98.175182
12          Kinney County, Texas                95.019157
13         Bastrop County, Texas                88.162064
14            Polk County, Texas                86.237685
15          Brooks County, Texas                83.216783
16            Hall County, Texas                80.676329
17         Andrews County, Texas                80.529595
18         Kaufman County, Texas                78.221674
19        Cherokee County, Texas                76.741071
20            Knox County, Texas                73.500000
21          Borden County, Texas                71.794872
22            Lynn County, Texas                71.703297
23           Llano County, Texas                69.990319
24            Hunt County, Texas                69.654605
25          Archer County, Texas                69.637883
26         Houston County, Texas                65.659882
27           Milam County, Texas                64.450355
28       Glasscock County, Texas                62.500000
29           Delta County, Texas                60.927152
30           Comal County, Texas                59.935837
31         Midland County, Texas                59.310802
32         Grayson County, Texas                58.253558
33           Erath County, Texas                53.927987
34          Blanco County, Texas                52.962963
35         Jackson County, Texas                50.506757
36          Gaines County, Texas                49.944506
37           Garza County, Texas                48.995984
38      Williamson County, Texas                48.555178
39          Bailey County, Texas                47.676768
40           Ector County, Texas                47.248085
41       Guadalupe County, Texas                46.764856
42      Washington County, Texas                46.729958
43        Montague County, Texas                42.441390
44            Hays County, Texas                41.339738
45       Fort Bend County, Texas                38.312264
46         Briscoe County, Texas                36.363636
47         Wharton County, Texas                36.303030
48          Collin County, Texas                35.253389
49          Burnet County, Texas                34.800638
50          Yoakum County, Texas                32.500000
51          Lavaca County, Texas                31.376975
52          Parker County, Texas                30.278201
53          Baylor County, Texas                29.473684
54           Brown County, Texas                28.429818
55          Travis County, Texas                27.990537
56           Bexar County, Texas                27.178311
57       Robertson County, Texas                24.894515
58       Val Verde County, Texas                23.654749
59         Lubbock County, Texas                22.554458
60        Rockwall County, Texas                22.485863
61          Denton County, Texas                22.269079
62          Dallam County, Texas                21.921922
63          Brazos County, Texas                21.721357
64            Hill County, Texas                21.662178
65       Van Zandt County, Texas                21.599792
66           Ellis County, Texas                20.153518
67           Crane County, Texas                18.518519
68         Madison County, Texas                17.352415
69          Austin County, Texas                16.975309
70            Hood County, Texas                16.753279
71         Coryell County, Texas                16.015902
72           Lamar County, Texas                15.135699
73         El Paso County, Texas                14.838876
74      Montgomery County, Texas                13.564541
75          Menard County, Texas                11.811024
76        San Saba County, Texas                11.451943
77           Starr County, Texas                11.310905
78          Dawson County, Texas                11.290323
79           Floyd County, Texas                11.000000
80      Palo Pinto County, Texas                10.825295
81   San Augustine County, Texas                10.743802
82          Harris County, Texas                10.122543
83         Trinity County, Texas                 9.969088
84          Medina County, Texas                 9.712105
85        Maverick County, Texas                 8.752475
86          Zapata County, Texas                 8.388521
87         Hartley County, Texas                 8.156425
88       Matagorda County, Texas                 8.143608
89            Frio County, Texas                 7.796014
90          Fannin County, Texas                 6.729356
91           Tyler County, Texas                 5.839002
92          Dallas County, Texas                 5.558678
93          Dimmit County, Texas                 5.475504
94           Irion County, Texas                 5.263158
95           Jones County, Texas                 4.841105
96           Falls County, Texas                 4.799040
97         Kendall County, Texas                 4.775522
98        McLennan County, Texas                 4.169439
99       Galveston County, Texas                 3.958434
100        Tarrant County, Texas                 3.933858
101       Eastland County, Texas                 2.510986
102         Wilson County, Texas                 2.379379
103        Willacy County, Texas                 2.362869
104           Kerr County, Texas                 1.853123
105       Angelina County, Texas                 1.601557
106       Sterling County, Texas                 0.000000
107     Jeff Davis County, Texas                -0.874636
108         Jasper County, Texas                -1.667313
109          Terry County, Texas                -1.738473
110          Foard County, Texas                -2.000000
111           Bell County, Texas                -2.104525
112      Jefferson County, Texas                -2.519005
113        Bandera County, Texas                -2.538462
114         Orange County, Texas                -2.580937
115        Liberty County, Texas                -3.070496
116         Walker County, Texas                -4.000310
117      Gillespie County, Texas                -4.195323
118           Wise County, Texas                -4.564543
119        Cameron County, Texas                -4.858693
120       Brazoria County, Texas                -5.096467
121          Mills County, Texas                -5.204461
122       Jim Hogg County, Texas                -5.966587
123        Wichita County, Texas                -7.048552
124           Jack County, Texas                -7.574537
125        Johnson County, Texas                -7.692308
126      McCulloch County, Texas                -8.193669
127      Henderson County, Texas                -8.485026
128        Randall County, Texas                -8.503369
129           Gray County, Texas                -8.659491
130       Franklin County, Texas                -8.685626
131       Live Oak County, Texas                -9.128289
132       Harrison County, Texas                -9.258852
133         Panola County, Texas                -9.925926
134         Scurry County, Texas               -10.058542
135          Smith County, Texas               -10.179132
136           Rusk County, Texas               -10.836537
137       Burleson County, Texas               -11.164581
138         Carson County, Texas               -11.578947
139       Anderson County, Texas               -12.395437
140        Hopkins County, Texas               -13.330530
141    Shackelford County, Texas               -13.551402
142          Gregg County, Texas               -14.206239
143       Victoria County, Texas               -14.295235
144       Comanche County, Texas               -14.460784
145         DeWitt County, Texas               -14.654616
146       Callahan County, Texas               -14.770642
147       Caldwell County, Texas               -14.815637
148         Reeves County, Texas               -15.186916
149        Kleberg County, Texas               -15.584804
150        Refugio County, Texas               -15.721232
151           Real County, Texas               -16.149068
152      Stonewall County, Texas               -16.176471
153         Hardin County, Texas               -16.382668
154         Shelby County, Texas               -16.395978
155       Hamilton County, Texas               -16.808511
156          Duval County, Texas               -16.924477
157           Hale County, Texas               -17.057674
158        Hidalgo County, Texas               -18.093505
159    San Jacinto County, Texas               -18.495822
160    Nacogdoches County, Texas               -18.723404
161          Rains County, Texas               -18.755718
162      Childress County, Texas               -18.818819
163        Fayette County, Texas               -19.074675
164           Lamb County, Texas               -19.490446
165       Atascosa County, Texas               -19.534282
166      Tom Green County, Texas               -20.234852
167            Bee County, Texas               -20.410407
168         Nueces County, Texas               -20.803906
169           Cass County, Texas               -20.830450
170           Camp County, Texas               -22.106632
171          Titus County, Texas               -22.384543
172         Concho County, Texas               -22.591743
173           Wood County, Texas               -22.742833
174        Navarro County, Texas               -23.807339
175          Nolan County, Texas               -23.954704
176      Somervell County, Texas               -24.394966
177       Colorado County, Texas               -25.643024
178         Taylor County, Texas               -26.184967
179        Cochran County, Texas               -27.397260
180          Pecos County, Texas               -27.418182
181           Clay County, Texas               -27.669346
182         Grimes County, Texas               -28.174084
183       Presidio County, Texas               -28.318584
184        Aransas County, Texas               -28.343313
185     Hutchinson County, Texas               -29.453441
186         Uvalde County, Texas               -29.904441
187         Castro County, Texas               -30.150754
188         Fisher County, Texas               -30.201342
189       La Salle County, Texas               -30.258718
190          Young County, Texas               -30.839975
191         Potter County, Texas               -31.395001
192       Brewster County, Texas               -31.724138
193         Donley County, Texas               -31.884058
194       Stephens County, Texas               -32.002956
195         Sabine County, Texas               -32.909091
196         Bosque County, Texas               -33.626245
197           King County, Texas               -34.000000
198      Jim Wells County, Texas               -34.411877
199         Marion County, Texas               -34.709193
200           Coke County, Texas               -34.883721
201          Bowie County, Texas               -35.927152
202       Lampasas County, Texas               -36.127660
203   San Patricio County, Texas               -36.233865
204          Cooke County, Texas               -36.324664
205            Lee County, Texas               -37.136205
206         Upshur County, Texas               -38.155401
207         Cottle County, Texas               -39.622642
208       Lipscomb County, Texas               -39.655172
209         Reagan County, Texas               -41.361257
210       Gonzales County, Texas               -43.156059
211           Leon County, Texas               -43.183898
212           Ward County, Texas               -43.283582
213         Howard County, Texas               -43.367474
214        Hockley County, Texas               -44.551551
215           Webb County, Texas               -45.106875
216      Freestone County, Texas               -45.325953
217         Motley County, Texas               -46.969697
218        Calhoun County, Texas               -47.980501
219      Red River County, Texas               -48.030496
220         Crosby County, Texas               -49.317739
221        Swisher County, Texas               -49.919614
222       Hemphill County, Texas               -50.312500
223       Mitchell County, Texas               -50.524309
224      Culberson County, Texas               -51.200000
225          Moore County, Texas               -51.355579
226         Newton County, Texas               -53.010949
227      Ochiltree County, Texas               -54.068241
228      Limestone County, Texas               -54.232996
229           Kent County, Texas               -54.464286
230        Edwards County, Texas               -55.319149
231         Sutton County, Texas               -56.071429
232         Morris County, Texas               -56.255468
233         Parmer County, Texas               -56.623377
234      Wilbarger County, Texas               -57.344633
235       Hardeman County, Texas               -57.941176
236        Wheeler County, Texas               -59.170306
237         Karnes County, Texas               -63.827434
238         Goliad County, Texas               -69.124424
239        Winkler County, Texas               -71.177267
240         Kimble County, Texas               -71.681416
241  Collingsworth County, Texas               -74.257426
242     Deaf Smith County, Texas               -74.340021
243      Armstrong County, Texas               -78.965517
244        Terrell County, Texas               -79.775281
245        Dickens County, Texas               -80.492813
246          Upton County, Texas               -84.210526
247         Zavala County, Texas               -84.726522
248     Schleicher County, Texas               -86.567164
249        Roberts County, Texas               -87.037037
250        Sherman County, Texas               -87.601078
251       McMullen County, Texas               -97.191011
252         Loving County, Texas              -100.000000
253         Kenedy County, Texas                      NaN
                            name  pct_chg_migration_14_24
0             King County, Texas              3200.000000
1           Kenedy County, Texas               800.000000
2          Runnels County, Texas               327.601810
3        Glasscock County, Texas               237.037037
4         Chambers County, Texas               193.132683
5        Stonewall County, Texas               192.307692
6         Jim Hogg County, Texas               173.611111
7          Coleman County, Texas               138.075314
8           Archer County, Texas               130.681818
9           Cottle County, Texas               128.571429
10        Franklin County, Texas               122.056075
11         Kaufman County, Texas               115.650477
12         Wharton County, Texas               111.372180
13      Washington County, Texas               108.754377
14          Oldham County, Texas               104.115226
15    Throckmorton County, Texas                89.041096
16          Jasper County, Texas                87.158672
17      Jeff Davis County, Texas                81.818182
18           Brown County, Texas                77.382256
19       Matagorda County, Texas                75.550817
20       Van Zandt County, Texas                74.076837
21        Rockwall County, Texas                69.953846
22            Polk County, Texas                68.308292
23        Colorado County, Texas                67.368421
24          Blanco County, Texas                66.532258
25           Falls County, Texas                66.222645
26         Grayson County, Texas                65.713899
27        Hudspeth County, Texas                62.773723
28       Guadalupe County, Texas                58.826239
29         Houston County, Texas                56.708075
30           Comal County, Texas                55.533125
31          Collin County, Texas                52.822986
32           Ellis County, Texas                52.765127
33       Culberson County, Texas                52.500000
34        Live Oak County, Texas                52.203857
35           Erath County, Texas                50.319659
36            Hill County, Texas                48.520432
37        Montague County, Texas                47.818792
38           Mason County, Texas                47.524752
39            Lynn County, Texas                47.058824
40            Hall County, Texas                44.961240
41          Fisher County, Texas                43.448276
42          Waller County, Texas                43.367226
43         Bastrop County, Texas                41.329480
44            Hays County, Texas                41.094978
45           Llano County, Texas                40.367706
46       Fort Bend County, Texas                39.332707
47     Shackelford County, Texas                39.097744
48         Trinity County, Texas                38.964844
49        Angelina County, Texas                38.728796
50          Bailey County, Texas                37.664783
51            Hunt County, Texas                34.432425
52          Parker County, Texas                33.378853
53           Mills County, Texas                32.812500
54         Cochran County, Texas                32.500000
55          Walker County, Texas                32.226375
56         Coryell County, Texas                31.092572
57       Somervell County, Texas                29.519071
58      Williamson County, Texas                28.332838
59         Navarro County, Texas                28.163580
60       Robertson County, Texas                27.175081
61            Hood County, Texas                25.779792
62        Cherokee County, Texas                25.722452
63           Rains County, Texas                25.601132
64        Eastland County, Texas                25.326170
65         Midland County, Texas                24.839882
66          Denton County, Texas                24.827209
67         Hartley County, Texas                24.421594
68          Austin County, Texas                24.343832
69            Wise County, Texas                23.482164
70          Burnet County, Texas                23.350846
71           Bexar County, Texas                22.509225
72          Travis County, Texas                22.162856
73          Wilson County, Texas                20.310680
74        Brazoria County, Texas                19.944378
75         Jackson County, Texas                18.958611
76          Hardin County, Texas                18.899273
77          Dawson County, Texas                18.201285
78      Montgomery County, Texas                17.670772
79           Irion County, Texas                17.647059
80            Kerr County, Texas                17.343173
81        Crockett County, Texas                16.908213
82         Kleberg County, Texas                16.708023
83           Tyler County, Texas                16.251557
84           Ector County, Texas                15.322134
85       Henderson County, Texas                15.316315
86        McLennan County, Texas                15.101391
87          Dallas County, Texas                15.037818

{'pct_chg_migration_09_24':                            name  pct_chg_migration_09_24
 0    Throckmorton County, Texas               411.111111
 1          Oldham County, Texas               367.924528
 2        Chambers County, Texas               187.765293
 3        Hudspeth County, Texas               185.897436
 4        Crockett County, Texas               178.160920
 ..                          ...                      ...
 249       Roberts County, Texas               -87.037037
 250       Sherman County, Texas               -87.601078
 251      McMullen County, Texas               -97.191011
 252        Loving County, Texas              -100.000000
 253        Kenedy County, Texas                      NaN

 [254 rows x 2 columns],
 'pct_chg_migration_14_24':                          name  pct_chg_migration_14_24
 0          King County, Texas              3200.000000
 1        Kenedy County, Texas               800.000000
 2       Runnels County, Texas               327.601810
 3     Glasscock County, Texas               237.037037
 4      Chambers County, Texas               193.132683
 ..                        ...                      ...
 249  Deaf Smith County, Texas               -79.716194
 250      Zavala County, Texas               -82.359952
 251    McMullen County, Texas               -88.636364
 252     Roberts County, Texas               -94.308943
 253      Loving County, Texas              -100.000000

 [254 rows x 2 columns],
 'pct_chg_migration_19_24':                        name  pct_chg_migration_19_24
 0    Crockett County, Texas               490.243902
 1        King County, Texas               312.500000
 2      Borden County, Texas               204.545455
 3     Runnels County, Texas               158.196721
 4    Chambers County, Texas               150.180897
 ..                      ...                      ...
 249    Zavala County, Texas               -74.394464
 250    Motley County, Texas               -79.411765
 251  McMullen County, Texas               -85.294118
 252   Roberts County, Texas               -91.358025
 253    Loving County, Texas                      NaN

 [254 rows x 2 columns]}

## ACS5 margins of error

In [54]:
smith_estimates_acs5 = tx_counties_acs5[tx_counties_acs5['name'] == 'Smith County, Texas'].copy()
smith_estimates_acs5

,name,population,total_families,family_households_with_child,median_age,population_under_18,lived_in_same_house,moved_within_county,moved_from_diff_county_same_state,moved_from_diff_state,...,population_under_18_moe,lived_in_same_house_moe,moved_within_county_moe,moved_from_diff_county_same_state_moe,moved_from_diff_state_moe,moved_from_abroad_moe,state,county_code,year,total_in_migration
185,"Smith County, Texas",197631,48076,23912,35.7,51096,155721,23260,10612,3891,...,0,2186,1915,1195,848,322,48,423,2009,15296
299,"Smith County, Texas",214735,53927,26596,36.0,54296,172408,23577,10885,4206,...,-555555555,1791,1568,1188,762,304,48,423,2014,15839
629,"Smith County, Texas",227449,53919,25385,36.6,56012,195995,14368,10144,3540,...,-555555555,2119,1645,1281,809,352,48,423,2019,14649
973,"Smith County, Texas",241740,57522,27097,37.5,58485,210107,14964,9982,3187,...,-555555555,2237,1753,1160,737,222,48,423,2024,13739

In [55]:
# Create migration confidence intervals dataframe for Smith County
migration_data_smith_acs5 = []

for year in smith_estimates_acs5['year'].unique():
    row = smith_estimates_acs5[smith_estimates_acs5['year'] == year].iloc[0]
    
    # Calculate total MOE
    total_moe = np.sqrt(
        row["moved_from_diff_county_same_state_moe"]**2 +
        row["moved_from_diff_state_moe"]**2 +
        row["moved_from_abroad_moe"]**2
    )
    
    migration_data_smith_acs5.append({
        'year': year,
        'total_in_migration': row['total_in_migration'],
        'moe': total_moe,
        'lower_bound': row['total_in_migration'] - total_moe,
        'upper_bound': row['total_in_migration'] + total_moe
    })

smith_migration_moes_acs5 = pd.DataFrame(migration_data_smith_acs5)
smith_migration_moes_acs5

   year  total_in_migration          moe   lower_bound   upper_bound
0  2009               15296  1500.270976  13795.729024  16796.270976
1  2014               15839  1443.746515  14395.253485  17282.746515
2  2019               14649  1555.424701  13093.575299  16204.424701
3  2024               13739  1392.139720  12346.860280  15131.139720

# Filter only to similarly-sized jurisdictions
We're going with MSAs and counties that had between 200K and 300K people in 2024. The Tyler metro area/Smith County had about 250K-ish people.

## ACS1

### Similarly sized MSAs

In [56]:
# filter msas
msa_pop_filtered = msa_tx_pop[(msa_tx_pop[2024] >= 200000) & (msa_tx_pop[2024] <= 300000)]
filtered_msa_codes = msa_pop_filtered['msa_code'].tolist()

# filter all msas dfs
msa_tx_pop_filtered = msa_tx_pop[msa_tx_pop['msa_code'].isin(filtered_msa_codes)].copy()
msa_tx_families_filtered = msa_tx_families[msa_tx_families['msa_code'].isin(filtered_msa_codes)].copy()
msa_tx_under18_filtered = msa_tx_under18[msa_tx_under18['msa_code'].isin(filtered_msa_codes)].copy()
msa_tx_family_households_with_child_filtered = msa_tx_family_households_with_child[msa_tx_family_households_with_child['msa_code'].isin(filtered_msa_codes)].copy()
msa_tx_migration_filtered = msa_tx_migration[msa_tx_migration['msa_code_'].isin(filtered_msa_codes)].copy()

In [57]:
print("Filtered MSAs - population change")
print_rankings(
    df=msa_tx_pop_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs - change in number of families")
print_rankings(
    df=msa_tx_families_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs - change in total population under 18")
print_rankings(
    df=msa_tx_under18_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs - change in family households with children under 18")
print_rankings(
    df=msa_tx_family_households_with_child_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs - migration change")
print_rankings(
    df=msa_tx_migration_filtered,
    name_col='name_',
    variable_names=['pct_chg_migration_05_24', 'pct_chg_migration_09_24',
                 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

Filtered MSAs - population change
year                                  name  pct_change_05_24
0     College Station-Bryan, TX Metro Area         58.756102
1                  Longview, TX Metro Area         48.176936
2                     Tyler, TX Metro Area         34.306203
3                    Laredo, TX Metro Area         23.182889
4                  Amarillo, TX Metro Area         22.182275
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         42.835736
1     College Station-Bryan, TX Metro Area         35.191783
2                     Tyler, TX Metro Area         21.706691
3                  Amarillo, TX Metro Area         13.274891
4                    Laredo, TX Metro Area         12.999196
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         35.869340
1     College Station-Bryan, TX Metro Area         20.344818
2                     Tyler, TX Metro Area         13.822301
3                  Amarillo, TX Metro Area          6.333476
4                    Laredo, TX Metro Area          2.306195
year                                  name  pct_change_19_24
0     College Station-Bryan, TX Metro Area          7.709781
1                     Tyler, TX Metro Area          7.020378
2                  Amarillo, TX Metro Area          3.296752
3                  Longview, TX Metro Area          3.081383
4                    Laredo, TX Metro Area         -1.384049
Filtered MSAs - change in number of families
year                                  name  pct_change_05_24
0     College Station-Bryan, TX Metro Area         56.355436
1                  Longview, TX Metro Area         52.803703
2                     Tyler, TX Metro Area         32.100432
3                    Laredo, TX Metro Area         31.302993
4                  Amarillo, TX Metro Area         11.129005
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         48.151307
1     College Station-Bryan, TX Metro Area         44.251271
2                     Tyler, TX Metro Area         33.865774
3                    Laredo, TX Metro Area         18.480782
4                  Amarillo, TX Metro Area         10.719071
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         46.833535
1     College Station-Bryan, TX Metro Area         30.766408
2                     Tyler, TX Metro Area         19.478202
3                    Laredo, TX Metro Area         12.207100
4                  Amarillo, TX Metro Area          2.694202
year                                  name  pct_change_19_24
0                     Tyler, TX Metro Area         18.175231
1                  Longview, TX Metro Area         13.480194
2     College Station-Bryan, TX Metro Area         12.137425
3                  Amarillo, TX Metro Area          4.335017
4                    Laredo, TX Metro Area          2.840207
Filtered MSAs - change in total population under 18
year                                  name  pct_change_05_24
0     College Station-Bryan, TX Metro Area         38.554790
1                  Longview, TX Metro Area         36.361208
2                     Tyler, TX Metro Area         20.767435
3                  Amarillo, TX Metro Area          9.797127
4                    Laredo, TX Metro Area          0.703160
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         33.192322
1     College Station-Bryan, TX Metro Area         21.772374
2                     Tyler, TX Metro Area         12.716730
3                  Amarillo, TX Metro Area          6.556199
4                    Laredo, TX Metro Area         -8.572684
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         31.957830
1     College Station-Bryan, TX Metro Area         18.401007
2                     Tyler, TX Metro Area          8.971000
3                  Amarillo, TX Metro Area          2.045059
4                    Laredo, TX Metro Area         -8.186302
year                                  name  pct_change_19_24
0                     Tyler, TX Metro Area          5.113978
1     College Station-Bryan, TX Metro Area          3.757632
2                  Longview, TX Metro Area          1.607904
3                  Amarillo, TX Metro Area          0.260331
4                    Laredo, TX Metro Area         -6.587633
Filtered MSAs - change in family households with children under 18
year                                  name  pct_change_05_24
0     College Station-Bryan, TX Metro Area         41.657448
1                  Longview, TX Metro Area         39.013238
2                     Tyler, TX Metro Area         14.977330
3                    Laredo, TX Metro Area          5.834744
4                  Amarillo, TX Metro Area          1.769111
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         44.712295
1                     Tyler, TX Metro Area         36.645509
2     College Station-Bryan, TX Metro Area         25.214911
3                    Laredo, TX Metro Area          4.193038
4                  Amarillo, TX Metro Area          3.385210
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         41.015187
1     College Station-Bryan, TX Metro Area         20.369718
2                     Tyler, TX Metro Area         19.696000
3                    Laredo, TX Metro Area         -4.369700
4                  Amarillo, TX Metro Area         -5.499058
year                                  name  pct_change_19_24
0                  Longview, TX Metro Area         13.537526
1                     Tyler, TX Metro Area         10.637039
2                  Amarillo, TX Metro Area          3.352451
3     College Station-Bryan, TX Metro Area          2.272803
4                    Laredo, TX Metro Area         -4.458896
Filtered MSAs - migration change
                                  name_  pct_chg_migration_05_24
0  College Station-Bryan, TX Metro Area                79.185659
1               Amarillo, TX Metro Area                53.519363
2               Longview, TX Metro Area                20.921128
3                  Tyler, TX Metro Area                 5.376472
4                 Laredo, TX Metro Area               -49.005236
                                  name_  pct_chg_migration_09_24
0  College Station-Bryan, TX Metro Area                20.908211
1                  Tyler, TX Metro Area                11.042868
2               Amarillo, TX Metro Area                 5.767439
3               Longview, TX Metro Area                -8.985212
4                 Laredo, TX Metro Area               -51.628923
                                  name_  pct_chg_migration_14_24
0                  Tyler, TX Metro Area                44.956230
1               Amarillo, TX Metro Area                32.188767
2  College Station-Bryan, TX Metro Area                -8.197324
3               Longview, TX Metro Area               -16.229411
4                 Laredo, TX Metro Area               -45.033860
                                  name_  pct_chg_migration_19_24
0                  Tyler, TX Metro Area                38.303021
1               Amarillo, TX Metro Area                37.924206
2  College Station-Bryan, TX Metro Area                 2.415035
3               Longview, TX Metro Area               -44.705576
4                 Laredo, TX Metro Area               -45.256295

{'pct_chg_migration_05_24':                                   name_  pct_chg_migration_05_24
 0  College Station-Bryan, TX Metro Area                79.185659
 1               Amarillo, TX Metro Area                53.519363
 2               Longview, TX Metro Area                20.921128
 3                  Tyler, TX Metro Area                 5.376472
 4                 Laredo, TX Metro Area               -49.005236,
 'pct_chg_migration_09_24':                                   name_  pct_chg_migration_09_24
 0  College Station-Bryan, TX Metro Area                20.908211
 1                  Tyler, TX Metro Area                11.042868
 2               Amarillo, TX Metro Area                 5.767439
 3               Longview, TX Metro Area                -8.985212
 4                 Laredo, TX Metro Area               -51.628923,
 'pct_chg_migration_14_24':                                   name_  pct_chg_migration_14_24
 0                  Tyler, TX Metro Area                44.956230
 1               Amarillo, TX Metro Area                32.188767
 2  College Station-Bryan, TX Metro Area                -8.197324
 3               Longview, TX Metro Area               -16.229411
 4                 Laredo, TX Metro Area               -45.033860,
 'pct_chg_migration_19_24':                                   name_  pct_chg_migration_19_24
 0                  Tyler, TX Metro Area                38.303021
 1               Amarillo, TX Metro Area                37.924206
 2  College Station-Bryan, TX Metro Area                 2.415035
 3               Longview, TX Metro Area               -44.705576
 4                 Laredo, TX Metro Area               -45.256295}

### Similarly sized counties

In [58]:
# Filter counties with population between 200K-300K in 2024
county_pop_filtered = county_tx_pop[(county_tx_pop[2024] >= 200000) & (county_tx_pop[2024] <= 300000)]
filtered_county_codes = county_pop_filtered['county_code'].tolist()

# Filter all county dataframes
county_tx_pop_filtered = county_tx_pop[county_tx_pop['county_code'].isin(filtered_county_codes)].copy()
county_tx_families_filtered = county_tx_families[county_tx_families['county_code'].isin(filtered_county_codes)].copy()
county_tx_under18_filtered = county_tx_under18[county_tx_under18['county_code'].isin(filtered_county_codes)].copy()
county_tx_family_households_with_child_filtered = county_tx_family_households_with_child[county_tx_family_households_with_child['county_code'].isin(filtered_county_codes)].copy()
tx_counties_migration_filtered = tx_counties_migration[tx_counties_migration['county_code'].isin(filtered_county_codes)].copy()

In [59]:
print("Filtered counties - population change")
print_rankings(
    df=county_tx_pop_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties - change in number of families")
print_rankings(
    df=county_tx_families_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties - change in total population under 18")
print_rankings(
    df=county_tx_under18_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties - change in family households with children under 18")
print_rankings(
    df=county_tx_family_households_with_child_filtered,
    variable_names=['pct_change_05_24', 'pct_change_09_24', 
                 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties - migration change")
print_rankings(
    df=tx_counties_migration_filtered,
    name_col='name',
    variable_names=['pct_chg_migration_05_24', 'pct_chg_migration_09_24',
                 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

Filtered counties - population change
year                     name  pct_change_05_24
0          Hays County, Texas        153.872033
1         Comal County, Texas        112.701226
2         Ellis County, Texas         76.747034
3        Brazos County, Texas         73.951583
4       Johnson County, Texas         46.460346
5         Smith County, Texas         34.306203
6      McLennan County, Texas         25.992861
7          Webb County, Texas         23.182889
8     Jefferson County, Texas          9.786391
year                     name  pct_change_09_24
0          Hays County, Texas         87.745668
1         Comal County, Texas         76.055883
2         Ellis County, Texas         53.151176
3        Brazos County, Texas         38.686164
4       Johnson County, Texas         34.108932
5         Smith County, Texas         21.706691
6      McLennan County, Texas         15.845538
7          Webb County, Texas         12.999196
8     Jefferson County, Texas          4.403524
year                     name  pct_change_14_24
0         Comal County, Texas         63.005481
1          Hays County, Texas         57.832185
2         Ellis County, Texas         45.864534
3       Johnson County, Texas         33.717991
4        Brazos County, Texas         19.350520
5         Smith County, Texas         13.822301
6      McLennan County, Texas         11.056889
7          Webb County, Texas          2.306195
8     Jefferson County, Texas          0.679129
year                     name  pct_change_19_24
0         Comal County, Texas         29.075789
1          Hays County, Texas         26.863778
2         Ellis County, Texas         25.732851
3       Johnson County, Texas         19.753494
4        Brazos County, Texas          8.905768
5         Smith County, Texas          7.020378
6      McLennan County, Texas          5.352209
7     Jefferson County, Texas          0.947270
8          Webb County, Texas         -1.384049
Filtered counties - change in number of families
year                     name  pct_change_05_24
0          Hays County, Texas        159.685109
1         Comal County, Texas        115.406545
2         Ellis County, Texas         81.301542
3        Brazos County, Texas         73.852683
4       Johnson County, Texas         49.156446
5         Smith County, Texas         32.100432
6          Webb County, Texas         31.302993
7      McLennan County, Texas         27.839561
8     Jefferson County, Texas          0.117878
year                     name  pct_change_09_24
0          Hays County, Texas        135.861027
1         Comal County, Texas         73.804947
2         Ellis County, Texas         59.889759
3        Brazos County, Texas         43.693069
4       Johnson County, Texas         36.304559
5         Smith County, Texas         33.865774
6      McLennan County, Texas         24.313860
7          Webb County, Texas         18.480782
8     Jefferson County, Texas         -4.763183
year                     name  pct_change_14_24
0          Hays County, Texas         72.708502
1         Comal County, Texas         72.597553
2         Ellis County, Texas         53.478346
3        Brazos County, Texas         28.968176
4       Johnson County, Texas         21.123138
5         Smith County, Texas         19.478202
6      McLennan County, Texas         13.130489
7          Webb County, Texas         12.207100
8     Jefferson County, Texas          0.242698
year                     name  pct_change_19_24
0          Hays County, Texas         34.484937
1         Ellis County, Texas         29.366341
2         Comal County, Texas         26.434384
3         Smith County, Texas         18.175231
4       Johnson County, Texas         15.976808
5        Brazos County, Texas         13.574038
6      McLennan County, Texas          5.310864
7     Jefferson County, Texas          4.525757
8          Webb County, Texas          2.840207
Filtered counties - change in total population under 18
year                     name  pct_change_05_24
0          Hays County, Texas        130.239327
1         Ellis County, Texas         65.072005
2        Brazos County, Texas         52.918013
3       Johnson County, Texas         36.922998
4         Smith County, Texas         20.767435
5      McLennan County, Texas         11.102002
6          Webb County, Texas          0.703160
7     Jefferson County, Texas          0.293051
8         Comal County, Texas               NaN
year                     name  pct_change_09_24
0          Hays County, Texas         67.514641
1         Comal County, Texas         59.941723
2         Ellis County, Texas         37.847626
3        Brazos County, Texas         25.191416
4       Johnson County, Texas         24.572216
5         Smith County, Texas         12.716730
6      McLennan County, Texas          6.713017
7     Jefferson County, Texas          3.374330
8          Webb County, Texas         -8.572684
year                     name  pct_change_14_24
0         Comal County, Texas         51.253789
1          Hays County, Texas         47.462542
2         Ellis County, Texas         40.445084
3       Johnson County, Texas         29.295891
4        Brazos County, Texas         15.436959
5         Smith County, Texas          8.971000
6      McLennan County, Texas          5.775586
7     Jefferson County, Texas          3.663230
8          Webb County, Texas         -8.186302
year                     name  pct_change_19_24
0         Comal County, Texas         25.505888
1         Ellis County, Texas         24.295572
2          Hays County, Texas         21.119492
3       Johnson County, Texas         17.191172
4        Brazos County, Texas          5.120017
5         Smith County, Texas          5.113978
6     Jefferson County, Texas          2.546063
7      McLennan County, Texas          1.263871
8          Webb County, Texas         -6.587633
Filtered counties - change in family households with children under 18
year                     name  pct_change_05_24
0          Hays County, Texas        151.499036
1         Comal County, Texas        103.687858
2        Brazos County, Texas         58.810600
3         Ellis County, Texas         51.729156
4       Johnson County, Texas         32.198356
5         Smith County, Texas         14.977330
6          Webb County, Texas          5.834744
7      McLennan County, Texas          0.855956
8     Jefferson County, Texas         -5.580447
year                     name  pct_change_09_24
0          Hays County, Texas        148.917692
1         Comal County, Texas         49.322544
2         Ellis County, Texas         45.599255
3         Smith County, Texas         36.645509
4       Johnson County, Texas         26.811152
5        Brazos County, Texas         24.939956
6          Webb County, Texas          4.193038
7      McLennan County, Texas          4.130306
8     Jefferson County, Texas        -14.484283
year                     name  pct_change_14_24
0         Comal County, Texas         77.596240
1          Hays County, Texas         74.982656
2         Ellis County, Texas         50.887517
3         Smith County, Texas         19.696000
4        Brazos County, Texas         13.660199
5       Johnson County, Texas         12.553057
6      McLennan County, Texas          2.582690
7          Webb County, Texas         -4.369700
8     Jefferson County, Texas        -12.667388
year                     name  pct_change_19_24
0          Hays County, Texas         51.471354
1         Ellis County, Texas         31.591789
2         Comal County, Texas         25.243331
3         Smith County, Texas         10.637039
4       Johnson County, Texas          5.744103
5        Brazos County, Texas          2.490346
6     Jefferson County, Texas          1.433190
7          Webb County, Texas         -4.458896
8      McLennan County, Texas         -6.407657
Filtered counties - migration change
                      name  pct_chg_migration_05_24
0       Hays County, Texas               124.803569
1     Brazos County, Texas                93.648208
2      Comal County, Texas                51.468564
3    Johnson County, Texas                50.633302
4      Ellis County, Texas                48.392984
5   McLennan County, Texas                21.644052
6      Smith County, Texas                 5.376472
7  Jefferson County, Texas               -12.765957
8       Webb County, Texas               -49.005236
                      name  pct_chg_migration_09_24
0       Hays County, Texas                61.698357
1      Comal County, Texas                42.401035
2     Brazos County, Texas                27.029915
3    Johnson County, Texas                15.737005
4      Smith County, Texas                11.042868
5      Ellis County, Texas                10.685926
6   McLennan County, Texas                -1.771182
7  Jefferson County, Texas                -5.649680
8       Webb County, Texas               -51.628923
                      name  pct_chg_migration_14_24
0    Johnson County, Texas                49.113150
1      Smith County, Texas                44.956230
2       Hays County, Texas                31.806824
3      Ellis County, Texas                30.480521
4   McLennan County, Texas                12.967947
5      Comal County, Texas                10.504729
6     Brazos County, Texas                -1.750037
7  Jefferson County, Texas               -25.427035
8       Webb County, Texas               -45.033860
                      name  pct_chg_migration_19_24
0       Hays County, Texas                67.241294
1      Smith County, Texas                38.303021
2    Johnson County, Texas                20.059094
3      Ellis County, Texas                10.227444
4     Brazos County, Texas                 3.568207
5      Comal County, Texas                 2.317291
6   McLennan County, Texas                -0.975871
7  Jefferson County, Texas               -13.258110
8       Webb County, Texas               -45.256295

{'pct_chg_migration_05_24':                       name  pct_chg_migration_05_24
 0       Hays County, Texas               124.803569
 1     Brazos County, Texas                93.648208
 2      Comal County, Texas                51.468564
 3    Johnson County, Texas                50.633302
 4      Ellis County, Texas                48.392984
 5   McLennan County, Texas                21.644052
 6      Smith County, Texas                 5.376472
 7  Jefferson County, Texas               -12.765957
 8       Webb County, Texas               -49.005236,
 'pct_chg_migration_09_24':                       name  pct_chg_migration_09_24
 0       Hays County, Texas                61.698357
 1      Comal County, Texas                42.401035
 2     Brazos County, Texas                27.029915
 3    Johnson County, Texas                15.737005
 4      Smith County, Texas                11.042868
 5      Ellis County, Texas                10.685926
 6   McLennan County, Texas                -1.771182
 7  Jefferson County, Texas                -5.649680
 8       Webb County, Texas               -51.628923,
 'pct_chg_migration_14_24':                       name  pct_chg_migration_14_24
 0    Johnson County, Texas                49.113150
 1      Smith County, Texas                44.956230
 2       Hays County, Texas                31.806824
 3      Ellis County, Texas                30.480521
 4   McLennan County, Texas                12.967947
 5      Comal County, Texas                10.504729
 6     Brazos County, Texas                -1.750037
 7  Jefferson County, Texas               -25.427035
 8       Webb County, Texas               -45.033860,
 'pct_chg_migration_19_24':                       name  pct_chg_migration_19_24
 0       Hays County, Texas                67.241294
 1      Smith County, Texas                38.303021
 2    Johnson County, Texas                20.059094
 3      Ellis County, Texas                10.227444
 4     Brazos County, Texas                 3.568207
 5      Comal County, Texas                 2.317291
 6   McLennan County, Texas                -0.975871
 7  Jefferson County, Texas               -13.258110
 8       Webb County, Texas               -45.256295}

## ACS5

### Similarly sized MSAs

In [60]:
# filter msas
msa_pop_filtered_acs5 = msa_tx_pop_acs5[(msa_tx_pop_acs5[2024] >= 200000) & (msa_tx_pop_acs5[2024] <= 300000)]
filtered_msa_codes_acs5 = msa_pop_filtered_acs5['msa_code'].tolist()

# filter all msas dfs
msa_tx_pop_filtered_acs5 = msa_tx_pop_acs5[msa_tx_pop_acs5['msa_code'].isin(filtered_msa_codes_acs5)].copy()
msa_tx_families_filtered_acs5 = msa_tx_families_acs5[msa_tx_families_acs5['msa_code'].isin(filtered_msa_codes_acs5)].copy()
msa_tx_under18_filtered_acs5 = msa_tx_under18_acs5[msa_tx_under18_acs5['msa_code'].isin(filtered_msa_codes_acs5)].copy()
msa_tx_family_households_with_child_filtered_acs5 = msa_tx_family_households_with_child_acs5[msa_tx_family_households_with_child_acs5['msa_code'].isin(filtered_msa_codes_acs5)].copy()
msa_tx_migration_filtered_acs5 = msa_tx_migration_acs5[msa_tx_migration_acs5['msa_code_'].isin(filtered_msa_codes_acs5)].copy()

In [61]:
print("Filtered MSAs (ACS5) - population change")
print_rankings(
    df=msa_tx_pop_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs (ACS5) - change in number of families")
print_rankings(
    df=msa_tx_families_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs (ACS5) - change in total population under 18")
print_rankings(
    df=msa_tx_under18_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs (ACS5) - change in family households with children under 18")
print_rankings(
    df=msa_tx_family_households_with_child_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered MSAs (ACS5) - migration change")
print_rankings(
    df=msa_tx_migration_filtered_acs5,
    name_col='name_',
    variable_names=['pct_chg_migration_09_24', 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

Filtered MSAs (ACS5) - population change
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         43.385555
1     College Station-Bryan, TX Metro Area         36.541801
2                     Tyler, TX Metro Area         22.318867
3                    Laredo, TX Metro Area         16.559829
4                  Amarillo, TX Metro Area         12.427902
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         34.278833
1     College Station-Bryan, TX Metro Area         18.281375
2                     Tyler, TX Metro Area         12.575966
3                  Amarillo, TX Metro Area          5.788638
4                    Laredo, TX Metro Area          3.785780
year                                  name  pct_change_19_24
0     College Station-Bryan, TX Metro Area          7.869658
1                     Tyler, TX Metro Area          6.283167
2                  Amarillo, TX Metro Area          3.086331
3                  Longview, TX Metro Area          2.193851
4                    Laredo, TX Metro Area         -1.547202
Filtered MSAs (ACS5) - change in number of families
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         40.776027
1     College Station-Bryan, TX Metro Area         37.811315
2                    Laredo, TX Metro Area         23.705895
3                     Tyler, TX Metro Area         19.648057
4                  Amarillo, TX Metro Area         11.325042
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         40.154296
1     College Station-Bryan, TX Metro Area         22.474580
2                    Laredo, TX Metro Area         14.404221
3                     Tyler, TX Metro Area          6.666419
4                  Amarillo, TX Metro Area          3.813799
year                                  name  pct_change_19_24
0     College Station-Bryan, TX Metro Area          9.507003
1                  Longview, TX Metro Area          7.749062
2                    Laredo, TX Metro Area          7.456287
3                     Tyler, TX Metro Area          6.682246
4                  Amarillo, TX Metro Area          1.935583
Filtered MSAs (ACS5) - change in total population under 18
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         36.023005
1     College Station-Bryan, TX Metro Area         25.731858
2                     Tyler, TX Metro Area         14.461015
3                  Amarillo, TX Metro Area          6.610823
4                    Laredo, TX Metro Area         -2.785187
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         33.016312
1     College Station-Bryan, TX Metro Area         15.265849
2                     Tyler, TX Metro Area          7.715117
3                  Amarillo, TX Metro Area          1.632787
4                    Laredo, TX Metro Area         -6.088324
year                                  name  pct_change_19_24
0     College Station-Bryan, TX Metro Area          5.818074
1                     Tyler, TX Metro Area          4.415125
2                  Amarillo, TX Metro Area          0.796401
3                  Longview, TX Metro Area          0.552275
4                    Laredo, TX Metro Area         -7.396082
Filtered MSAs (ACS5) - change in family households with children under 18
year                                  name  pct_change_09_24
0                  Longview, TX Metro Area         36.012646
1     College Station-Bryan, TX Metro Area         27.649065
2                     Tyler, TX Metro Area         13.319672
3                    Laredo, TX Metro Area          9.736029
4                  Amarillo, TX Metro Area          2.772389
year                                  name  pct_change_14_24
0                  Longview, TX Metro Area         38.118980
1     College Station-Bryan, TX Metro Area         17.736473
2                    Laredo, TX Metro Area          3.969669
3                     Tyler, TX Metro Area          1.883742
4                  Amarillo, TX Metro Area          1.279719
year                                  name  pct_change_19_24
0                  Longview, TX Metro Area          8.820641
1                     Tyler, TX Metro Area          6.744140
2     College Station-Bryan, TX Metro Area          5.919692
3                    Laredo, TX Metro Area          2.132720
4                  Amarillo, TX Metro Area         -0.342871
Filtered MSAs (ACS5) - migration change
                                  name_  pct_chg_migration_09_24
0  College Station-Bryan, TX Metro Area                20.642996
1               Longview, TX Metro Area                 4.792725
2                  Tyler, TX Metro Area               -10.179132
3               Amarillo, TX Metro Area               -19.750394
4                 Laredo, TX Metro Area               -45.106875
                                  name_  pct_chg_migration_14_24
0  College Station-Bryan, TX Metro Area                10.096640
1               Longview, TX Metro Area                -1.902759
2                  Tyler, TX Metro Area               -13.258413
3               Amarillo, TX Metro Area               -14.276469
4                 Laredo, TX Metro Area               -45.484796
                                  name_  pct_chg_migration_19_24
0  College Station-Bryan, TX Metro Area                 5.234401
1                  Tyler, TX Metro Area                -6.212028
2               Amarillo, TX Metro Area               -11.180152
3               Longview, TX Metro Area               -16.334985
4                 Laredo, TX Metro Area               -25.286995

{'pct_chg_migration_09_24':                                   name_  pct_chg_migration_09_24
 0  College Station-Bryan, TX Metro Area                20.642996
 1               Longview, TX Metro Area                 4.792725
 2                  Tyler, TX Metro Area               -10.179132
 3               Amarillo, TX Metro Area               -19.750394
 4                 Laredo, TX Metro Area               -45.106875,
 'pct_chg_migration_14_24':                                   name_  pct_chg_migration_14_24
 0  College Station-Bryan, TX Metro Area                10.096640
 1               Longview, TX Metro Area                -1.902759
 2                  Tyler, TX Metro Area               -13.258413
 3               Amarillo, TX Metro Area               -14.276469
 4                 Laredo, TX Metro Area               -45.484796,
 'pct_chg_migration_19_24':                                   name_  pct_chg_migration_19_24
 0  College Station-Bryan, TX Metro Area                 5.234401
 1                  Tyler, TX Metro Area                -6.212028
 2               Amarillo, TX Metro Area               -11.180152
 3               Longview, TX Metro Area               -16.334985
 4                 Laredo, TX Metro Area               -25.286995}

### Similarly-sized coutnies (ACS5)

In [62]:
# Filter counties with population between 200K-300K in 2024 (ACS5)
county_pop_filtered_acs5 = county_tx_pop_acs5[(county_tx_pop_acs5[2024] >= 200000) & (county_tx_pop_acs5[2024] <= 300000)]
filtered_county_codes_acs5 = county_pop_filtered_acs5['county_code'].tolist()

# Filter all county dfs
county_tx_pop_filtered_acs5 = county_tx_pop_acs5[county_tx_pop_acs5['county_code'].isin(filtered_county_codes_acs5)].copy()
county_tx_families_filtered_acs5 = county_tx_families_acs5[county_tx_families_acs5['county_code'].isin(filtered_county_codes_acs5)].copy()
county_tx_under18_filtered_acs5 = county_tx_under18_acs5[county_tx_under18_acs5['county_code'].isin(filtered_county_codes_acs5)].copy()
county_tx_family_households_with_child_filtered_acs5 = county_tx_family_households_with_child_acs5[county_tx_family_households_with_child_acs5['county_code'].isin(filtered_county_codes_acs5)].copy()
tx_counties_migration_filtered_acs5 = tx_counties_migration_acs5[tx_counties_migration_acs5['county_code'].isin(filtered_county_codes_acs5)].copy()

In [63]:
print("Filtered counties (ACS5) - population change")
print_rankings(
    df=county_tx_pop_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties (ACS5) - change in number of families")
print_rankings(
    df=county_tx_families_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties (ACS5) - change in total population under 18")
print_rankings(
    df=county_tx_under18_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties (ACS5) - change in family households with children under 18")
print_rankings(
    df=county_tx_family_households_with_child_filtered_acs5,
    variable_names=['pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']
)

print("Filtered counties (ACS5) - migration change")
print_rankings(
    df=tx_counties_migration_filtered_acs5,
    name_col='name',
    variable_names=['pct_chg_migration_09_24', 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']
)

Filtered counties (ACS5) - population change
year                     name  pct_change_09_24
0          Hays County, Texas         90.023414
1         Ellis County, Texas         49.745694
2        Brazos County, Texas         41.386493
3         Smith County, Texas         22.318867
4          Webb County, Texas         16.559829
5      McLennan County, Texas         16.507494
6     Jefferson County, Texas          4.616031
year                     name  pct_change_14_24
0          Hays County, Texas         57.642157
1         Ellis County, Texas         38.014982
2        Brazos County, Texas         20.233311
3         Smith County, Texas         12.575966
4      McLennan County, Texas         10.992128
5          Webb County, Texas          3.785780
6     Jefferson County, Texas          0.559283
year                     name  pct_change_19_24
0          Hays County, Texas         25.904783
1         Ellis County, Texas         22.666483
2        Brazos County, Texas          8.668900
3         Smith County, Texas          6.283167
4      McLennan County, Texas          5.965216
5     Jefferson County, Texas         -0.181647
6          Webb County, Texas         -1.547202
Filtered counties (ACS5) - change in number of families
year                     name  pct_change_09_24
0          Hays County, Texas        123.573773
1         Ellis County, Texas         53.368553
2        Brazos County, Texas         46.944823
3          Webb County, Texas         23.705895
4         Smith County, Texas         19.648057
5      McLennan County, Texas         18.531338
6     Jefferson County, Texas         -0.466170
year                     name  pct_change_14_24
0          Hays County, Texas         69.179150
1         Ellis County, Texas         38.702130
2        Brazos County, Texas         24.768519
3          Webb County, Texas         14.404221
4      McLennan County, Texas         10.980624
5         Smith County, Texas          6.666419
6     Jefferson County, Texas          3.612590
year                     name  pct_change_19_24
0          Hays County, Texas         32.563243
1         Ellis County, Texas         24.563188
2        Brazos County, Texas         10.704798
3          Webb County, Texas          7.456287
4         Smith County, Texas          6.682246
5      McLennan County, Texas          6.452961
6     Jefferson County, Texas          2.762412
Filtered counties (ACS5) - change in total population under 18
year                     name  pct_change_09_24
0          Hays County, Texas         75.548041
1         Ellis County, Texas         35.578084
2        Brazos County, Texas         30.945351
3         Smith County, Texas         14.461015
4      McLennan County, Texas          8.208689
5     Jefferson County, Texas          3.939313
6          Webb County, Texas         -2.785187
year                     name  pct_change_14_24
0          Hays County, Texas         46.649133
1         Ellis County, Texas         30.249275
2        Brazos County, Texas         17.992067
3         Smith County, Texas          7.715117
4      McLennan County, Texas          6.184193
5     Jefferson County, Texas          4.098634
6          Webb County, Texas         -6.088324
year                     name  pct_change_19_24
0          Hays County, Texas         21.979380
1         Ellis County, Texas         20.645217
2        Brazos County, Texas          6.412913
3         Smith County, Texas          4.415125
4      McLennan County, Texas          2.601417
5     Jefferson County, Texas          2.557368
6          Webb County, Texas         -7.396082
Filtered counties (ACS5) - change in family households with children under 18
year                     name  pct_change_09_24
0          Hays County, Texas        110.952226
1        Brazos County, Texas         37.018783
2         Ellis County, Texas         36.404689
3         Smith County, Texas         13.319672
4          Webb County, Texas          9.736029
5      McLennan County, Texas          9.655148
6     Jefferson County, Texas         -5.810472
year                     name  pct_change_14_24
0          Hays County, Texas         56.341828
1         Ellis County, Texas         29.269292
2        Brazos County, Texas         18.196419
3      McLennan County, Texas          5.741446
4          Webb County, Texas          3.969669
5         Smith County, Texas          1.883742
6     Jefferson County, Texas          0.335188
year                     name  pct_change_19_24
0          Hays County, Texas         33.373058
1         Ellis County, Texas         23.387798
2         Smith County, Texas          6.744140
3        Brazos County, Texas          6.332073
4     Jefferson County, Texas          3.372896
5          Webb County, Texas          2.132720
6      McLennan County, Texas          2.046764
Filtered counties (ACS5) - migration change
                      name  pct_chg_migration_09_24
0       Hays County, Texas                41.339738
1     Brazos County, Texas                21.721357
2      Ellis County, Texas                20.153518
3   McLennan County, Texas                 4.169439
4  Jefferson County, Texas                -2.519005
5      Smith County, Texas               -10.179132
6       Webb County, Texas               -45.106875
                      name  pct_chg_migration_14_24
0      Ellis County, Texas                52.765127
1       Hays County, Texas                41.094978
2   McLennan County, Texas                15.101391
3     Brazos County, Texas                10.936494
4  Jefferson County, Texas                -8.407990
5      Smith County, Texas               -13.258413
6       Webb County, Texas               -45.484796
                      name  pct_chg_migration_19_24
0      Ellis County, Texas                50.031949
1       Hays County, Texas                39.939226
2     Brazos County, Texas                 6.569058
3   McLennan County, Texas                 2.225366
4  Jefferson County, Texas                -4.027654
5      Smith County, Texas                -6.212028
6       Webb County, Texas               -25.286995

{'pct_chg_migration_09_24':                       name  pct_chg_migration_09_24
 0       Hays County, Texas                41.339738
 1     Brazos County, Texas                21.721357
 2      Ellis County, Texas                20.153518
 3   McLennan County, Texas                 4.169439
 4  Jefferson County, Texas                -2.519005
 5      Smith County, Texas               -10.179132
 6       Webb County, Texas               -45.106875,
 'pct_chg_migration_14_24':                       name  pct_chg_migration_14_24
 0      Ellis County, Texas                52.765127
 1       Hays County, Texas                41.094978
 2   McLennan County, Texas                15.101391
 3     Brazos County, Texas                10.936494
 4  Jefferson County, Texas                -8.407990
 5      Smith County, Texas               -13.258413
 6       Webb County, Texas               -45.484796,
 'pct_chg_migration_19_24':                       name  pct_chg_migration_19_24
 0      Ellis County, Texas                50.031949
 1       Hays County, Texas                39.939226
 2     Brazos County, Texas                 6.569058
 3   McLennan County, Texas                 2.225366
 4  Jefferson County, Texas                -4.027654
 5      Smith County, Texas                -6.212028
 6       Webb County, Texas               -25.286995}

# Export for graphics

In [64]:
# Create output csvs for graphics 
# Population change - ACS5

# population change -- want county code, county name, percentage change, and true/false for whether the county is between 200k to 300k in population
county_pop_export = county_tx_pop_acs5[['county_code', 'name', 'pct_change_09_24', 'pct_change_14_24', 'pct_change_19_24']].copy()
county_pop_export['name'] = county_pop_export['name'].str.replace(' County, Texas', '', regex=False)

# create a column for whether the county is between 200k to 300k in population in 2024
county_pop_export['pop_200k_300k'] = county_tx_pop_acs5[2024].between(200000, 300000)

# create output directory if it doesn't exist
import os
os.makedirs('output', exist_ok=True)
county_pop_export.to_csv('output/county_population_change.csv', index=False)

print("Exported to output/county_population_change.csv")

Exported to output/county_population_change.csv

In [65]:
# Create output csvs for graphics
# Change in migration - ACS5

# migration -- want county code, county name, percentage change, and true/false for whether the county is between 200k to 300k in population
county_migration_export = tx_counties_migration_acs5[['county_code', 'name', 'pct_chg_migration_09_24', 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']].copy()
county_migration_export['name'] = county_migration_export['name'].str.replace(' County, Texas', '', regex=False)

# create a column for whether the county is between 200k to 300k in population in 2024
county_migration_export['pop_200k_300k'] = tx_counties_migration_acs5[2024].between(200000, 300000)

county_migration_export.to_csv('output/county_migration_change.csv', index=False)

print("Exported to output/county_migration_change.csv")

KeyError: 2024

In [ ]:
# Create output csvs for graphics
# Change in # of families - ACS5

# migration -- want county code, county name, percentage change, and true/false for whether the county is between 200k to 300k in population
county_family_export = county_tx_families_acs5[['county_code', 'name', 'pct_chg_migration_09_24', 'pct_chg_migration_14_24', 'pct_chg_migration_19_24']].copy()
county_family_export['name'] = county_family_export['name'].str.replace(' County, Texas', '', regex=False)

# create a column for whether the county is between 200k to 300k in population in 2024
county_family_export['pop_200k_300k'] = county_tx_families_acs5[2024].between(200000, 300000)
county_family_export.to_csv('output/county_families_change.csv', index=False)

print("Exported to output/county_families_change.csv")

In [ ]:
# i want to output a spreadsheet of moes for migration estimates for acs5 and acs1